begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * System call switch table.  *  * DO NOT EDIT-- this file is automatically generated.  * created from	@(#)syscalls.master	8.1 (Berkeley) 6/14/93  */
end_comment

begin_include
include|#
directive|include
file|<sys/param.h>
end_include

begin_include
include|#
directive|include
file|<sys/systm.h>
end_include

begin_decl_stmt
name|int
name|nosys
argument_list|()
decl_stmt|,
name|notimp
argument_list|()
decl_stmt|;
end_decl_stmt

begin_function_decl
name|int
name|exit
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|fork
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxread
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxwrite
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxopen
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|close
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxwait
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxcreat
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|link
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|unlink
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxexecv
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|chdir
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|mknod
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|chmod
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|chown
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|obreak
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|olseek
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|getpid
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|setuid
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|getuid
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxptrace
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|access
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|sync
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxkill
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxstat
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxlstat
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxdup
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|pipe
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|profil
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|setgid
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|getgid
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxioctl
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|symlink
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxutssys
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|readlink
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|execve
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|umask
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|chroot
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxfcntl
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxulimit
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|vfork
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxread
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxwrite
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxmmap
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|getgroups
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|setgroups
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxgetpgrp2
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxsetpgrp2
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|setitimer
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxwait3
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|getitimer
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|dup2
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxfstat
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|select
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|fsync
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|sigreturn
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxsigvec
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxsigblock
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxsigsetmask
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxsigpause
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|osigstack
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|gettimeofday
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxreadv
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxwritev
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|settimeofday
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|fchown
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|fchmod
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxsetresuid
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxsetresgid
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|rename
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxsysconf
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|mkdir
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|rmdir
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxrtprio
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxnetioctl
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxlockf
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxsemget
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxsemctl
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxsemop
parameter_list|()
function_decl|;
end_function_decl

begin_ifdef
ifdef|#
directive|ifdef
name|SYSVSHM
end_ifdef

begin_function_decl
name|int
name|hpuxshmget
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxshmctl
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxshmat
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxshmdt
parameter_list|()
function_decl|;
end_function_decl

begin_else
else|#
directive|else
end_else

begin_endif
endif|#
directive|endif
end_endif

begin_function_decl
name|int
name|hpuxadvise
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxgetcontext
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxgetaccess
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxwaitpid
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|getdirentries
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxgetdomainname
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxsetdomainname
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxsigaction
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxsigprocmask
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxsigpending
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxsigsuspend
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|getdtablesize
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|bind
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|connect
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|getsockopt
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|listen
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|sendto
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|hpuxsetsockopt2
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|shutdown
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|socket
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|socketpair
parameter_list|()
function_decl|;
end_function_decl

begin_ifdef
ifdef|#
directive|ifdef
name|COMPAT_OHPUX
end_ifdef

begin_define
define|#
directive|define
name|compat
parameter_list|(
name|n
parameter_list|,
name|name
parameter_list|)
value|n, __CONCAT(o,name)
end_define

begin_function_decl
name|int
name|ohpuxtime
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|ohpuxstat
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|ohpuxstime
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|ohpuxalarm
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|ohpuxfstat
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|ohpuxpause
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|ohpuxutime
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|ohpuxstty
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|ohpuxgtty
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|ohpuxnice
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|ohpuxftime
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|ohpuxsetpgrp
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|ohpuxtimes
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|ohpuxssig
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|otruncate
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|oftruncate
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|ogetrlimit
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|osetrlimit
parameter_list|()
function_decl|;
end_function_decl

begin_ifdef
ifdef|#
directive|ifdef
name|SYSVSHM
end_ifdef

begin_else
else|#
directive|else
end_else

begin_endif
endif|#
directive|endif
end_endif

begin_function_decl
name|int
name|oaccept
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|ogetpeername
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|ogetsockname
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|orecv
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|orecvfrom
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|orecvmsg
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|osend
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|int
name|osendmsg
parameter_list|()
function_decl|;
end_function_decl

begin_else
else|#
directive|else
end_else

begin_comment
comment|/* COMPAT_OHPUX */
end_comment

begin_define
define|#
directive|define
name|compat
parameter_list|(
name|n
parameter_list|,
name|name
parameter_list|)
value|0, nosys
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_comment
comment|/* COMPAT_OHPUX */
end_comment

begin_decl_stmt
name|struct
name|sysent
name|hpuxsysent
index|[]
init|=
block|{
literal|0
block|,
name|nosys
block|,
comment|/* 0 = indir or out-of-range */
literal|1
block|,
name|exit
block|,
comment|/* 1 = exit */
literal|0
block|,
name|fork
block|,
comment|/* 2 = fork */
literal|3
block|,
name|hpuxread
block|,
comment|/* 3 = read */
literal|3
block|,
name|hpuxwrite
block|,
comment|/* 4 = write */
literal|3
block|,
name|hpuxopen
block|,
comment|/* 5 = open */
literal|1
block|,
name|close
block|,
comment|/* 6 = close */
literal|1
block|,
name|hpuxwait
block|,
comment|/* 7 = owait */
literal|2
block|,
name|hpuxcreat
block|,
comment|/* 8 = ocreat */
literal|2
block|,
name|link
block|,
comment|/* 9 = link */
literal|1
block|,
name|unlink
block|,
comment|/* 10 = unlink */
literal|2
block|,
name|hpuxexecv
block|,
comment|/* 11 = execv */
literal|1
block|,
name|chdir
block|,
comment|/* 12 = chdir */
name|compat
argument_list|(
literal|1
argument_list|,
name|hpuxtime
argument_list|)
block|,
comment|/* 13 = old time */
literal|3
block|,
name|mknod
block|,
comment|/* 14 = mknod */
literal|2
block|,
name|chmod
block|,
comment|/* 15 = chmod */
literal|3
block|,
name|chown
block|,
comment|/* 16 = chown */
literal|1
block|,
name|obreak
block|,
comment|/* 17 = break */
name|compat
argument_list|(
literal|2
argument_list|,
name|hpuxstat
argument_list|)
block|,
comment|/* 18 = old stat */
literal|3
block|,
name|olseek
block|,
comment|/* 19 = olseek */
literal|0
block|,
name|getpid
block|,
comment|/* 20 = getpid */
literal|3
block|,
name|notimp
block|,
comment|/* 21 = mount (unimplemented) */
literal|1
block|,
name|notimp
block|,
comment|/* 22 = umount (unimplemented) */
literal|1
block|,
name|setuid
block|,
comment|/* 23 = setuid */
literal|0
block|,
name|getuid
block|,
comment|/* 24 = getuid */
name|compat
argument_list|(
literal|1
argument_list|,
name|hpuxstime
argument_list|)
block|,
comment|/* 25 = old stime */
literal|4
block|,
name|hpuxptrace
block|,
comment|/* 26 = ptrace */
name|compat
argument_list|(
literal|1
argument_list|,
name|hpuxalarm
argument_list|)
block|,
comment|/* 27 = old alarm */
name|compat
argument_list|(
literal|2
argument_list|,
name|hpuxfstat
argument_list|)
block|,
comment|/* 28 = old fstat */
name|compat
argument_list|(
literal|0
argument_list|,
name|hpuxpause
argument_list|)
block|,
comment|/* 29 = old pause */
name|compat
argument_list|(
literal|2
argument_list|,
name|hpuxutime
argument_list|)
block|,
comment|/* 30 = old utime */
name|compat
argument_list|(
literal|2
argument_list|,
name|hpuxstty
argument_list|)
block|,
comment|/* 31 = old stty */
name|compat
argument_list|(
literal|2
argument_list|,
name|hpuxgtty
argument_list|)
block|,
comment|/* 32 = old gtty */
literal|2
block|,
name|access
block|,
comment|/* 33 = access */
name|compat
argument_list|(
literal|1
argument_list|,
name|hpuxnice
argument_list|)
block|,
comment|/* 34 = old nice */
name|compat
argument_list|(
literal|1
argument_list|,
name|hpuxftime
argument_list|)
block|,
comment|/* 35 = old ftime */
literal|0
block|,
name|sync
block|,
comment|/* 36 = sync */
literal|2
block|,
name|hpuxkill
block|,
comment|/* 37 = kill */
literal|2
block|,
name|hpuxstat
block|,
comment|/* 38 = stat */
name|compat
argument_list|(
literal|1
argument_list|,
name|hpuxsetpgrp
argument_list|)
block|,
comment|/* 39 = old setpgrp */
literal|2
block|,
name|hpuxlstat
block|,
comment|/* 40 = lstat */
literal|1
block|,
name|hpuxdup
block|,
comment|/* 41 = dup */
literal|0
block|,
name|pipe
block|,
comment|/* 42 = pipe */
name|compat
argument_list|(
literal|1
argument_list|,
name|hpuxtimes
argument_list|)
block|,
comment|/* 43 = old times */
literal|4
block|,
name|profil
block|,
comment|/* 44 = profil */
literal|4
block|,
name|notimp
block|,
comment|/* 45 = ki_syscall (unimplemented) */
literal|1
block|,
name|setgid
block|,
comment|/* 46 = setgid */
literal|0
block|,
name|getgid
block|,
comment|/* 47 = getgid */
name|compat
argument_list|(
literal|2
argument_list|,
name|hpuxssig
argument_list|)
block|,
comment|/* 48 = old ssig */
literal|0
block|,
name|nosys
block|,
comment|/* 49 = reserved for USG */
literal|0
block|,
name|nosys
block|,
comment|/* 50 = reserved for USG */
literal|1
block|,
name|notimp
block|,
comment|/* 51 = acct (unimplemented) */
literal|0
block|,
name|nosys
block|,
comment|/* 52 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 53 = nosys */
literal|3
block|,
name|hpuxioctl
block|,
comment|/* 54 = ioctl */
literal|4
block|,
name|notimp
block|,
comment|/* 55 = reboot (unimplemented) */
literal|2
block|,
name|symlink
block|,
comment|/* 56 = symlink */
literal|3
block|,
name|hpuxutssys
block|,
comment|/* 57 = utssys */
literal|3
block|,
name|readlink
block|,
comment|/* 58 = readlink */
literal|3
block|,
name|execve
block|,
comment|/* 59 = execve */
literal|1
block|,
name|umask
block|,
comment|/* 60 = umask */
literal|1
block|,
name|chroot
block|,
comment|/* 61 = chroot */
literal|3
block|,
name|hpuxfcntl
block|,
comment|/* 62 = fcntl */
literal|2
block|,
name|hpuxulimit
block|,
comment|/* 63 = ulimit */
literal|0
block|,
name|nosys
block|,
comment|/* 64 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 65 = nosys */
literal|0
block|,
name|vfork
block|,
comment|/* 66 = vfork */
literal|0
block|,
name|hpuxread
block|,
comment|/* 67 = vread */
literal|0
block|,
name|hpuxwrite
block|,
comment|/* 68 = vwrite */
literal|0
block|,
name|nosys
block|,
comment|/* 69 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 70 = nosys */
literal|6
block|,
name|hpuxmmap
block|,
comment|/* 71 = mmap */
literal|0
block|,
name|nosys
block|,
comment|/* 72 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 73 = nosys */
literal|3
block|,
name|notimp
block|,
comment|/* 74 = mprotect (unimplemented) */
literal|0
block|,
name|nosys
block|,
comment|/* 75 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 76 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 77 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 78 = nosys */
literal|2
block|,
name|getgroups
block|,
comment|/* 79 = getgroups */
literal|2
block|,
name|setgroups
block|,
comment|/* 80 = setgroups */
literal|1
block|,
name|hpuxgetpgrp2
block|,
comment|/* 81 = getpgrp2 */
literal|2
block|,
name|hpuxsetpgrp2
block|,
comment|/* 82 = setpgrp2 */
literal|3
block|,
name|setitimer
block|,
comment|/* 83 = setitimer */
literal|3
block|,
name|hpuxwait3
block|,
comment|/* 84 = wait3 */
literal|5
block|,
name|notimp
block|,
comment|/* 85 = swapon (unimplemented) */
literal|2
block|,
name|getitimer
block|,
comment|/* 86 = getitimer */
literal|0
block|,
name|nosys
block|,
comment|/* 87 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 88 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 89 = nosys */
literal|2
block|,
name|dup2
block|,
comment|/* 90 = dup2 */
literal|0
block|,
name|nosys
block|,
comment|/* 91 = nosys */
literal|2
block|,
name|hpuxfstat
block|,
comment|/* 92 = fstat */
literal|5
block|,
name|select
block|,
comment|/* 93 = select */
literal|0
block|,
name|nosys
block|,
comment|/* 94 = nosys */
literal|1
block|,
name|fsync
block|,
comment|/* 95 = fsync */
literal|0
block|,
name|nosys
block|,
comment|/* 96 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 97 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 98 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 99 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 100 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 101 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 102 = nosys */
literal|1
block|,
name|sigreturn
block|,
comment|/* 103 = sigreturn */
literal|0
block|,
name|nosys
block|,
comment|/* 104 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 105 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 106 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 107 = nosys */
literal|3
block|,
name|hpuxsigvec
block|,
comment|/* 108 = sigvec */
literal|1
block|,
name|hpuxsigblock
block|,
comment|/* 109 = sigblock */
literal|1
block|,
name|hpuxsigsetmask
block|,
comment|/* 110 = sigsetmask */
literal|1
block|,
name|hpuxsigpause
block|,
comment|/* 111 = sigpause */
literal|2
block|,
name|osigstack
block|,
comment|/* 112 = osigstack */
literal|0
block|,
name|nosys
block|,
comment|/* 113 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 114 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 115 = nosys */
literal|2
block|,
name|gettimeofday
block|,
comment|/* 116 = gettimeofday */
literal|0
block|,
name|nosys
block|,
comment|/* 117 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 118 = nosys */
literal|3
block|,
name|notimp
block|,
comment|/* 119 = hpib_io_stub (unimplemented) */
literal|3
block|,
name|hpuxreadv
block|,
comment|/* 120 = readv */
literal|3
block|,
name|hpuxwritev
block|,
comment|/* 121 = writev */
literal|2
block|,
name|settimeofday
block|,
comment|/* 122 = settimeofday */
literal|3
block|,
name|fchown
block|,
comment|/* 123 = fchown */
literal|2
block|,
name|fchmod
block|,
comment|/* 124 = fchmod */
literal|0
block|,
name|nosys
block|,
comment|/* 125 = nosys */
literal|3
block|,
name|hpuxsetresuid
block|,
comment|/* 126 = setresuid */
literal|3
block|,
name|hpuxsetresgid
block|,
comment|/* 127 = setresgid */
literal|2
block|,
name|rename
block|,
comment|/* 128 = rename */
name|compat
argument_list|(
literal|2
argument_list|,
name|truncate
argument_list|)
block|,
comment|/* 129 = old truncate */
name|compat
argument_list|(
literal|2
argument_list|,
name|ftruncate
argument_list|)
block|,
comment|/* 130 = old ftruncate */
literal|0
block|,
name|nosys
block|,
comment|/* 131 = nosys */
literal|1
block|,
name|hpuxsysconf
block|,
comment|/* 132 = sysconf */
literal|0
block|,
name|nosys
block|,
comment|/* 133 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 134 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 135 = nosys */
literal|2
block|,
name|mkdir
block|,
comment|/* 136 = mkdir */
literal|1
block|,
name|rmdir
block|,
comment|/* 137 = rmdir */
literal|0
block|,
name|nosys
block|,
comment|/* 138 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 139 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 140 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 141 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 142 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 143 = nosys */
name|compat
argument_list|(
literal|2
argument_list|,
name|getrlimit
argument_list|)
block|,
comment|/* 144 = old getrlimit */
name|compat
argument_list|(
literal|2
argument_list|,
name|setrlimit
argument_list|)
block|,
comment|/* 145 = old setrlimit */
literal|0
block|,
name|nosys
block|,
comment|/* 146 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 147 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 148 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 149 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 150 = nosys */
literal|3
block|,
name|notimp
block|,
comment|/* 151 = privgrp (unimplemented) */
literal|2
block|,
name|hpuxrtprio
block|,
comment|/* 152 = rtprio */
literal|1
block|,
name|notimp
block|,
comment|/* 153 = plock (unimplemented) */
literal|2
block|,
name|hpuxnetioctl
block|,
comment|/* 154 = netioctl */
literal|4
block|,
name|hpuxlockf
block|,
comment|/* 155 = lockf */
literal|3
block|,
name|hpuxsemget
block|,
comment|/* 156 = semget */
literal|4
block|,
name|hpuxsemctl
block|,
comment|/* 157 = semctl */
literal|3
block|,
name|hpuxsemop
block|,
comment|/* 158 = semop */
literal|2
block|,
name|notimp
block|,
comment|/* 159 = msgget (unimplemented) */
literal|3
block|,
name|notimp
block|,
comment|/* 160 = msgctl (unimplemented) */
literal|4
block|,
name|notimp
block|,
comment|/* 161 = msgsnd (unimplemented) */
literal|5
block|,
name|notimp
block|,
comment|/* 162 = msgrcv (unimplemented) */
ifdef|#
directive|ifdef
name|SYSVSHM
literal|3
block|,
name|hpuxshmget
block|,
comment|/* 163 = shmget */
literal|3
block|,
name|hpuxshmctl
block|,
comment|/* 164 = shmctl */
literal|3
block|,
name|hpuxshmat
block|,
comment|/* 165 = shmat */
literal|1
block|,
name|hpuxshmdt
block|,
comment|/* 166 = shmdt */
else|#
directive|else
literal|3
block|,
name|notimp
block|,
comment|/* 163 = shmget (unimplemented) */
literal|3
block|,
name|notimp
block|,
comment|/* 164 = shmctl (unimplemented) */
literal|3
block|,
name|notimp
block|,
comment|/* 165 = shmat (unimplemented) */
literal|1
block|,
name|notimp
block|,
comment|/* 166 = shmdt (unimplemented) */
endif|#
directive|endif
literal|1
block|,
name|hpuxadvise
block|,
comment|/* 167 = m68020_advise */
literal|2
block|,
name|notimp
block|,
comment|/* 168 = nsp_init (unimplemented) */
literal|3
block|,
name|notimp
block|,
comment|/* 169 = cluster (unimplemented) */
literal|4
block|,
name|notimp
block|,
comment|/* 170 = mkrnod (unimplemented) */
literal|0
block|,
name|nosys
block|,
comment|/* 171 = nosys */
literal|0
block|,
name|notimp
block|,
comment|/* 172 = unsp_open (unimplemented) */
literal|0
block|,
name|nosys
block|,
comment|/* 173 = nosys */
literal|3
block|,
name|hpuxgetcontext
block|,
comment|/* 174 = getcontext */
literal|0
block|,
name|nosys
block|,
comment|/* 175 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 176 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 177 = nosys */
literal|0
block|,
name|notimp
block|,
comment|/* 178 = lsync (unimplemented) */
literal|0
block|,
name|nosys
block|,
comment|/* 179 = nosys */
literal|0
block|,
name|notimp
block|,
comment|/* 180 = mysite (unimplemented) */
literal|1
block|,
name|notimp
block|,
comment|/* 181 = sitels (unimplemented) */
literal|0
block|,
name|nosys
block|,
comment|/* 182 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 183 = nosys */
literal|4
block|,
name|notimp
block|,
comment|/* 184 = dskless_stats (unimplemented) */
literal|0
block|,
name|nosys
block|,
comment|/* 185 = nosys */
literal|3
block|,
name|notimp
block|,
comment|/* 186 = setacl (unimplemented) */
literal|3
block|,
name|notimp
block|,
comment|/* 187 = fsetacl (unimplemented) */
literal|3
block|,
name|notimp
block|,
comment|/* 188 = getacl (unimplemented) */
literal|3
block|,
name|notimp
block|,
comment|/* 189 = fgetacl (unimplemented) */
literal|6
block|,
name|hpuxgetaccess
block|,
comment|/* 190 = getaccess */
literal|0
block|,
name|notimp
block|,
comment|/* 191 = getaudid (unimplemented) */
literal|1
block|,
name|notimp
block|,
comment|/* 192 = setaudid (unimplemented) */
literal|0
block|,
name|notimp
block|,
comment|/* 193 = getaudproc (unimplemented) */
literal|1
block|,
name|notimp
block|,
comment|/* 194 = setaudproc (unimplemented) */
literal|2
block|,
name|notimp
block|,
comment|/* 195 = getevent (unimplemented) */
literal|2
block|,
name|notimp
block|,
comment|/* 196 = setevent (unimplemented) */
literal|1
block|,
name|notimp
block|,
comment|/* 197 = audwrite (unimplemented) */
literal|1
block|,
name|notimp
block|,
comment|/* 198 = audswitch (unimplemented) */
literal|4
block|,
name|notimp
block|,
comment|/* 199 = audctl (unimplemented) */
literal|3
block|,
name|hpuxwaitpid
block|,
comment|/* 200 = waitpid */
literal|0
block|,
name|nosys
block|,
comment|/* 201 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 202 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 203 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 204 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 205 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 206 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 207 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 208 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 209 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 210 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 211 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 212 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 213 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 214 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 215 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 216 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 217 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 218 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 219 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 220 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 221 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 222 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 223 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 224 = nosys */
literal|2
block|,
name|notimp
block|,
comment|/* 225 = pathconf (unimplemented) */
literal|2
block|,
name|notimp
block|,
comment|/* 226 = fpathconf (unimplemented) */
literal|0
block|,
name|nosys
block|,
comment|/* 227 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 228 = nosys */
literal|0
block|,
name|notimp
block|,
comment|/* 229 = async_daemon (unimplemented) */
literal|3
block|,
name|notimp
block|,
comment|/* 230 = nfs_fcntl (unimplemented) */
literal|4
block|,
name|getdirentries
block|,
comment|/* 231 = getdirentries */
literal|2
block|,
name|hpuxgetdomainname
block|,
comment|/* 232 = getdomainname */
literal|2
block|,
name|notimp
block|,
comment|/* 233 = nfs_getfh (unimplemented) */
literal|4
block|,
name|notimp
block|,
comment|/* 234 = vfsmount (unimplemented) */
literal|1
block|,
name|notimp
block|,
comment|/* 235 = nfs_svc (unimplemented) */
literal|2
block|,
name|hpuxsetdomainname
block|,
comment|/* 236 = setdomainname */
literal|2
block|,
name|notimp
block|,
comment|/* 237 = statfs (unimplemented) */
literal|2
block|,
name|notimp
block|,
comment|/* 238 = fstatfs (unimplemented) */
literal|3
block|,
name|hpuxsigaction
block|,
comment|/* 239 = sigaction */
literal|3
block|,
name|hpuxsigprocmask
block|,
comment|/* 240 = sigprocmask */
literal|1
block|,
name|hpuxsigpending
block|,
comment|/* 241 = sigpending */
literal|1
block|,
name|hpuxsigsuspend
block|,
comment|/* 242 = sigsuspend */
literal|4
block|,
name|notimp
block|,
comment|/* 243 = fsctl (unimplemented) */
literal|0
block|,
name|nosys
block|,
comment|/* 244 = nosys */
literal|3
block|,
name|notimp
block|,
comment|/* 245 = pstat (unimplemented) */
literal|0
block|,
name|nosys
block|,
comment|/* 246 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 247 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 248 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 249 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 250 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 251 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 252 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 253 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 254 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 255 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 256 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 257 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 258 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 259 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 260 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 261 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 262 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 263 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 264 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 265 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 266 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 267 = nosys */
literal|0
block|,
name|getdtablesize
block|,
comment|/* 268 = getnumfds */
literal|0
block|,
name|nosys
block|,
comment|/* 269 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 270 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 271 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 272 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 273 = nosys */
literal|0
block|,
name|nosys
block|,
comment|/* 274 = nosys */
name|compat
argument_list|(
literal|3
argument_list|,
name|accept
argument_list|)
block|,
comment|/* 275 = old accept */
literal|3
block|,
name|bind
block|,
comment|/* 276 = bind */
literal|3
block|,
name|connect
block|,
comment|/* 277 = connect */
name|compat
argument_list|(
literal|3
argument_list|,
name|getpeername
argument_list|)
block|,
comment|/* 278 = old getpeername */
name|compat
argument_list|(
literal|3
argument_list|,
name|getsockname
argument_list|)
block|,
comment|/* 279 = old getsockname */
literal|5
block|,
name|getsockopt
block|,
comment|/* 280 = getsockopt */
literal|2
block|,
name|listen
block|,
comment|/* 281 = listen */
name|compat
argument_list|(
literal|4
argument_list|,
name|recv
argument_list|)
block|,
comment|/* 282 = old recv */
name|compat
argument_list|(
literal|6
argument_list|,
name|recvfrom
argument_list|)
block|,
comment|/* 283 = old recvfrom */
name|compat
argument_list|(
literal|3
argument_list|,
name|recvmsg
argument_list|)
block|,
comment|/* 284 = old recvmsg */
name|compat
argument_list|(
literal|4
argument_list|,
name|send
argument_list|)
block|,
comment|/* 285 = old send */
name|compat
argument_list|(
literal|3
argument_list|,
name|sendmsg
argument_list|)
block|,
comment|/* 286 = old sendmsg */
literal|6
block|,
name|sendto
block|,
comment|/* 287 = sendto */
literal|5
block|,
name|hpuxsetsockopt2
block|,
comment|/* 288 = setsockopt2 */
literal|2
block|,
name|shutdown
block|,
comment|/* 289 = shutdown */
literal|3
block|,
name|socket
block|,
comment|/* 290 = socket */
literal|4
block|,
name|socketpair
block|,
comment|/* 291 = socketpair */
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
name|int
name|hpuxnsysent
init|=
sizeof|sizeof
argument_list|(
name|hpuxsysent
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|hpuxsysent
index|[
literal|0
index|]
argument_list|)
decl_stmt|;
end_decl_stmt

end_unit

