begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* intl-compat.c - Stub functions to call gettext functions from GNU gettext    Library.    Copyright (C) 1995, 2000-2003 Software Foundation, Inc.     This program is free software; you can redistribute it and/or modify it    under the terms of the GNU Library General Public License as published    by the Free Software Foundation; either version 2, or (at your option)    any later version.     This program is distributed in the hope that it will be useful,    but WITHOUT ANY WARRANTY; without even the implied warranty of    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU    Library General Public License for more details.     You should have received a copy of the GNU Library General Public    License along with this program; if not, write to the Free Software    Foundation, Inc., 51 Franklin Street - Fifth Floor, Boston, MA 02110-1301,    USA.  */
end_comment

begin_ifdef
ifdef|#
directive|ifdef
name|HAVE_CONFIG_H
end_ifdef

begin_include
include|#
directive|include
file|<config.h>
end_include

begin_endif
endif|#
directive|endif
end_endif

begin_include
include|#
directive|include
file|"gettextP.h"
end_include

begin_comment
comment|/* @@ end of prolog @@ */
end_comment

begin_comment
comment|/* This file redirects the gettext functions (without prefix) to those    defined in the included GNU libintl library (with "libintl_" prefix).    It is compiled into libintl in order to make the AM_GNU_GETTEXT test    of gettext<= 0.11.2 work with the libintl library>= 0.11.3 which    has the redirections primarily in the<libintl.h> include file.    It is also compiled into libgnuintl so that libgnuintl.so can be used    as LD_PRELOADable library on glibc systems, to provide the extra    features that the functions in the libc don't have (namely, logging).  */
end_comment

begin_undef
undef|#
directive|undef
name|gettext
end_undef

begin_undef
undef|#
directive|undef
name|dgettext
end_undef

begin_undef
undef|#
directive|undef
name|dcgettext
end_undef

begin_undef
undef|#
directive|undef
name|ngettext
end_undef

begin_undef
undef|#
directive|undef
name|dngettext
end_undef

begin_undef
undef|#
directive|undef
name|dcngettext
end_undef

begin_undef
undef|#
directive|undef
name|textdomain
end_undef

begin_undef
undef|#
directive|undef
name|bindtextdomain
end_undef

begin_undef
undef|#
directive|undef
name|bind_textdomain_codeset
end_undef

begin_comment
comment|/* When building a DLL, we must export some functions.  Note that because    the functions are only defined for binary backward compatibility, we    don't need to use __declspec(dllimport) in any case.  */
end_comment

begin_if
if|#
directive|if
name|defined
name|_MSC_VER
operator|&&
name|BUILDING_DLL
end_if

begin_define
define|#
directive|define
name|DLL_EXPORTED
value|__declspec(dllexport)
end_define

begin_else
else|#
directive|else
end_else

begin_define
define|#
directive|define
name|DLL_EXPORTED
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_function
name|DLL_EXPORTED
name|char
modifier|*
name|gettext
parameter_list|(
name|msgid
parameter_list|)
specifier|const
name|char
modifier|*
name|msgid
decl_stmt|;
block|{
return|return
name|libintl_gettext
argument_list|(
name|msgid
argument_list|)
return|;
block|}
end_function

begin_function
name|DLL_EXPORTED
name|char
modifier|*
name|dgettext
parameter_list|(
name|domainname
parameter_list|,
name|msgid
parameter_list|)
specifier|const
name|char
modifier|*
name|domainname
decl_stmt|;
specifier|const
name|char
modifier|*
name|msgid
decl_stmt|;
block|{
return|return
name|libintl_dgettext
argument_list|(
name|domainname
argument_list|,
name|msgid
argument_list|)
return|;
block|}
end_function

begin_function
name|DLL_EXPORTED
name|char
modifier|*
name|dcgettext
parameter_list|(
name|domainname
parameter_list|,
name|msgid
parameter_list|,
name|category
parameter_list|)
specifier|const
name|char
modifier|*
name|domainname
decl_stmt|;
specifier|const
name|char
modifier|*
name|msgid
decl_stmt|;
name|int
name|category
decl_stmt|;
block|{
return|return
name|libintl_dcgettext
argument_list|(
name|domainname
argument_list|,
name|msgid
argument_list|,
name|category
argument_list|)
return|;
block|}
end_function

begin_function
name|DLL_EXPORTED
name|char
modifier|*
name|ngettext
parameter_list|(
name|msgid1
parameter_list|,
name|msgid2
parameter_list|,
name|n
parameter_list|)
specifier|const
name|char
modifier|*
name|msgid1
decl_stmt|;
specifier|const
name|char
modifier|*
name|msgid2
decl_stmt|;
name|unsigned
name|long
name|int
name|n
decl_stmt|;
block|{
return|return
name|libintl_ngettext
argument_list|(
name|msgid1
argument_list|,
name|msgid2
argument_list|,
name|n
argument_list|)
return|;
block|}
end_function

begin_function
name|DLL_EXPORTED
name|char
modifier|*
name|dngettext
parameter_list|(
name|domainname
parameter_list|,
name|msgid1
parameter_list|,
name|msgid2
parameter_list|,
name|n
parameter_list|)
specifier|const
name|char
modifier|*
name|domainname
decl_stmt|;
specifier|const
name|char
modifier|*
name|msgid1
decl_stmt|;
specifier|const
name|char
modifier|*
name|msgid2
decl_stmt|;
name|unsigned
name|long
name|int
name|n
decl_stmt|;
block|{
return|return
name|libintl_dngettext
argument_list|(
name|domainname
argument_list|,
name|msgid1
argument_list|,
name|msgid2
argument_list|,
name|n
argument_list|)
return|;
block|}
end_function

begin_function
name|DLL_EXPORTED
name|char
modifier|*
name|dcngettext
parameter_list|(
name|domainname
parameter_list|,
name|msgid1
parameter_list|,
name|msgid2
parameter_list|,
name|n
parameter_list|,
name|category
parameter_list|)
specifier|const
name|char
modifier|*
name|domainname
decl_stmt|;
specifier|const
name|char
modifier|*
name|msgid1
decl_stmt|;
specifier|const
name|char
modifier|*
name|msgid2
decl_stmt|;
name|unsigned
name|long
name|int
name|n
decl_stmt|;
name|int
name|category
decl_stmt|;
block|{
return|return
name|libintl_dcngettext
argument_list|(
name|domainname
argument_list|,
name|msgid1
argument_list|,
name|msgid2
argument_list|,
name|n
argument_list|,
name|category
argument_list|)
return|;
block|}
end_function

begin_function
name|DLL_EXPORTED
name|char
modifier|*
name|textdomain
parameter_list|(
name|domainname
parameter_list|)
specifier|const
name|char
modifier|*
name|domainname
decl_stmt|;
block|{
return|return
name|libintl_textdomain
argument_list|(
name|domainname
argument_list|)
return|;
block|}
end_function

begin_function
name|DLL_EXPORTED
name|char
modifier|*
name|bindtextdomain
parameter_list|(
name|domainname
parameter_list|,
name|dirname
parameter_list|)
specifier|const
name|char
modifier|*
name|domainname
decl_stmt|;
specifier|const
name|char
modifier|*
name|dirname
decl_stmt|;
block|{
return|return
name|libintl_bindtextdomain
argument_list|(
name|domainname
argument_list|,
name|dirname
argument_list|)
return|;
block|}
end_function

begin_function
name|DLL_EXPORTED
name|char
modifier|*
name|bind_textdomain_codeset
parameter_list|(
name|domainname
parameter_list|,
name|codeset
parameter_list|)
specifier|const
name|char
modifier|*
name|domainname
decl_stmt|;
specifier|const
name|char
modifier|*
name|codeset
decl_stmt|;
block|{
return|return
name|libintl_bind_textdomain_codeset
argument_list|(
name|domainname
argument_list|,
name|codeset
argument_list|)
return|;
block|}
end_function

end_unit

