begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/****************************************************************************  * Copyright (c) 2002-2012,2013 Free Software Foundation, Inc.              *  *                                                                          *  * Permission is hereby granted, free of charge, to any person obtaining a  *  * copy of this software and associated documentation files (the            *  * "Software"), to deal in the Software without restriction, including      *  * without limitation the rights to use, copy, modify, merge, publish,      *  * distribute, distribute with modifications, sublicense, and/or sell       *  * copies of the Software, and to permit persons to whom the Software is    *  * furnished to do so, subject to the following conditions:                 *  *                                                                          *  * The above copyright notice and this permission notice shall be included  *  * in all copies or substantial portions of the Software.                   *  *                                                                          *  * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS  *  * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF               *  * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.   *  * IN NO EVENT SHALL THE ABOVE COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,   *  * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR    *  * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR    *  * THE USE OR OTHER DEALINGS IN THE SOFTWARE.                               *  *                                                                          *  * Except as contained in this notice, the name(s) of the above copyright   *  * holders shall not be used in advertising or otherwise to promote the     *  * sale, use or other dealings in this Software without prior written       *  * authorization.                                                           *  ****************************************************************************/
end_comment

begin_comment
comment|/*  * $Id: demo_defkey.c,v 1.22 2013/09/28 22:02:17 tom Exp $  *  * Demonstrate the define_key() function.  * Thomas Dickey - 2002/11/23  */
end_comment

begin_include
include|#
directive|include
file|<test.priv.h>
end_include

begin_if
if|#
directive|if
name|defined
argument_list|(
name|NCURSES_VERSION
argument_list|)
operator|&&
name|NCURSES_EXT_FUNCS
end_if

begin_define
define|#
directive|define
name|MY_LOGFILE
value|"demo_defkey.log"
end_define

begin_comment
comment|/*  * Log the most recently-written line to our logfile  */
end_comment

begin_function
specifier|static
name|void
name|log_last_line
parameter_list|(
name|WINDOW
modifier|*
name|win
parameter_list|)
block|{
name|FILE
modifier|*
name|fp
decl_stmt|;
name|int
name|y
decl_stmt|,
name|x
decl_stmt|,
name|n
decl_stmt|;
name|char
name|temp
index|[
literal|256
index|]
decl_stmt|;
if|if
condition|(
operator|(
name|fp
operator|=
name|fopen
argument_list|(
name|MY_LOGFILE
argument_list|,
literal|"a"
argument_list|)
operator|)
operator|!=
literal|0
condition|)
block|{
name|int
name|need
init|=
sizeof|sizeof
argument_list|(
name|temp
argument_list|)
operator|-
literal|1
decl_stmt|;
if|if
condition|(
name|need
operator|>
name|COLS
condition|)
name|need
operator|=
name|COLS
expr_stmt|;
name|getyx
argument_list|(
name|win
argument_list|,
name|y
argument_list|,
name|x
argument_list|)
expr_stmt|;
name|wmove
argument_list|(
name|win
argument_list|,
name|y
operator|-
literal|1
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|n
operator|=
name|winnstr
argument_list|(
name|win
argument_list|,
name|temp
argument_list|,
name|need
argument_list|)
expr_stmt|;
while|while
condition|(
name|n
operator|--
operator|>
literal|0
condition|)
block|{
if|if
condition|(
name|isspace
argument_list|(
name|UChar
argument_list|(
name|temp
index|[
name|n
index|]
argument_list|)
argument_list|)
condition|)
name|temp
index|[
name|n
index|]
operator|=
literal|'\0'
expr_stmt|;
else|else
break|break;
block|}
name|wmove
argument_list|(
name|win
argument_list|,
name|y
argument_list|,
name|x
argument_list|)
expr_stmt|;
name|fprintf
argument_list|(
name|fp
argument_list|,
literal|"%s\n"
argument_list|,
name|temp
argument_list|)
expr_stmt|;
name|fclose
argument_list|(
name|fp
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_comment
comment|/*  * Convert a character to visible form.  */
end_comment

begin_function
specifier|static
name|char
modifier|*
name|visichar
parameter_list|(
name|int
name|ch
parameter_list|)
block|{
specifier|static
name|char
name|temp
index|[
literal|10
index|]
decl_stmt|;
name|ch
operator|=
name|UChar
argument_list|(
name|ch
argument_list|)
expr_stmt|;
name|assert
argument_list|(
name|ch
operator|>=
literal|0
operator|&&
name|ch
operator|<
literal|256
argument_list|)
expr_stmt|;
if|if
condition|(
name|ch
operator|==
literal|'\\'
condition|)
block|{
name|strcpy
argument_list|(
name|temp
argument_list|,
literal|"\\\\"
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|ch
operator|==
literal|'\033'
condition|)
block|{
name|strcpy
argument_list|(
name|temp
argument_list|,
literal|"\\E"
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|ch
operator|<
literal|' '
condition|)
block|{
name|sprintf
argument_list|(
name|temp
argument_list|,
literal|"\\%03o"
argument_list|,
name|ch
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|ch
operator|>=
literal|127
condition|)
block|{
name|sprintf
argument_list|(
name|temp
argument_list|,
literal|"\\%03o"
argument_list|,
name|ch
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|sprintf
argument_list|(
name|temp
argument_list|,
literal|"%c"
argument_list|,
name|ch
argument_list|)
expr_stmt|;
block|}
return|return
name|temp
return|;
block|}
end_function

begin_comment
comment|/*  * Convert a string to visible form.  */
end_comment

begin_function
specifier|static
name|char
modifier|*
name|visible
parameter_list|(
specifier|const
name|char
modifier|*
name|string
parameter_list|)
block|{
name|char
modifier|*
name|result
init|=
literal|0
decl_stmt|;
name|size_t
name|need
init|=
literal|1
decl_stmt|;
name|int
name|pass
decl_stmt|;
name|int
name|n
decl_stmt|;
if|if
condition|(
name|string
operator|!=
literal|0
operator|&&
operator|*
name|string
operator|!=
literal|'\0'
condition|)
block|{
for|for
control|(
name|pass
operator|=
literal|0
init|;
name|pass
operator|<
literal|2
condition|;
operator|++
name|pass
control|)
block|{
for|for
control|(
name|n
operator|=
literal|0
init|;
name|string
index|[
name|n
index|]
operator|!=
literal|'\0'
condition|;
operator|++
name|n
control|)
block|{
name|char
name|temp
index|[
literal|80
index|]
decl_stmt|;
name|strncpy
argument_list|(
name|temp
argument_list|,
name|visichar
argument_list|(
name|string
index|[
name|n
index|]
argument_list|)
argument_list|,
sizeof|sizeof
argument_list|(
name|temp
argument_list|)
operator|-
literal|2
argument_list|)
expr_stmt|;
if|if
condition|(
name|pass
condition|)
name|strcat
argument_list|(
name|result
argument_list|,
name|temp
argument_list|)
expr_stmt|;
else|else
name|need
operator|+=
name|strlen
argument_list|(
name|temp
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
operator|!
name|pass
condition|)
name|result
operator|=
name|typeCalloc
argument_list|(
name|char
argument_list|,
name|need
argument_list|)
expr_stmt|;
block|}
block|}
else|else
block|{
name|result
operator|=
name|typeCalloc
argument_list|(
name|char
argument_list|,
operator|(
name|size_t
operator|)
literal|1
argument_list|)
expr_stmt|;
block|}
return|return
name|result
return|;
block|}
end_function

begin_function
specifier|static
name|void
name|really_define_key
parameter_list|(
name|WINDOW
modifier|*
name|win
parameter_list|,
specifier|const
name|char
modifier|*
name|new_string
parameter_list|,
name|int
name|code
parameter_list|)
block|{
name|int
name|rc
decl_stmt|;
specifier|const
name|char
modifier|*
name|code_name
init|=
name|keyname
argument_list|(
name|code
argument_list|)
decl_stmt|;
name|char
modifier|*
name|old_string
decl_stmt|;
name|char
modifier|*
name|vis_string
init|=
literal|0
decl_stmt|;
name|char
name|temp
index|[
literal|80
index|]
decl_stmt|;
if|if
condition|(
name|code_name
operator|==
literal|0
condition|)
block|{
name|sprintf
argument_list|(
name|temp
argument_list|,
literal|"Keycode %d"
argument_list|,
name|code
argument_list|)
expr_stmt|;
name|code_name
operator|=
name|temp
expr_stmt|;
block|}
if|if
condition|(
operator|(
name|old_string
operator|=
name|keybound
argument_list|(
name|code
argument_list|,
literal|0
argument_list|)
operator|)
operator|!=
literal|0
condition|)
block|{
name|wprintw
argument_list|(
name|win
argument_list|,
literal|"%s is %s\n"
argument_list|,
name|code_name
argument_list|,
name|vis_string
operator|=
name|visible
argument_list|(
name|old_string
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|wprintw
argument_list|(
name|win
argument_list|,
literal|"%s is not bound\n"
argument_list|,
name|code_name
argument_list|)
expr_stmt|;
block|}
name|log_last_line
argument_list|(
name|win
argument_list|)
expr_stmt|;
if|if
condition|(
name|vis_string
operator|!=
literal|0
condition|)
block|{
name|free
argument_list|(
name|vis_string
argument_list|)
expr_stmt|;
name|vis_string
operator|=
literal|0
expr_stmt|;
block|}
name|vis_string
operator|=
name|visible
argument_list|(
name|new_string
argument_list|)
expr_stmt|;
if|if
condition|(
operator|(
name|rc
operator|=
name|key_defined
argument_list|(
name|new_string
argument_list|)
operator|)
operator|>
literal|0
condition|)
block|{
name|wprintw
argument_list|(
name|win
argument_list|,
literal|"%s was bound to %s\n"
argument_list|,
name|vis_string
argument_list|,
name|keyname
argument_list|(
name|rc
argument_list|)
argument_list|)
expr_stmt|;
name|log_last_line
argument_list|(
name|win
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|new_string
operator|!=
literal|0
operator|&&
name|rc
operator|<
literal|0
condition|)
block|{
name|wprintw
argument_list|(
name|win
argument_list|,
literal|"%s conflicts with longer strings\n"
argument_list|,
name|vis_string
argument_list|)
expr_stmt|;
name|log_last_line
argument_list|(
name|win
argument_list|)
expr_stmt|;
block|}
name|rc
operator|=
name|define_key
argument_list|(
name|new_string
argument_list|,
name|code
argument_list|)
expr_stmt|;
if|if
condition|(
name|rc
operator|==
name|ERR
condition|)
block|{
name|wprintw
argument_list|(
name|win
argument_list|,
literal|"%s unchanged\n"
argument_list|,
name|code_name
argument_list|)
expr_stmt|;
name|log_last_line
argument_list|(
name|win
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|new_string
operator|!=
literal|0
condition|)
block|{
name|wprintw
argument_list|(
name|win
argument_list|,
literal|"%s is now bound to %s\n"
argument_list|,
name|vis_string
argument_list|,
name|code_name
argument_list|)
expr_stmt|;
name|log_last_line
argument_list|(
name|win
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|old_string
operator|!=
literal|0
condition|)
block|{
name|wprintw
argument_list|(
name|win
argument_list|,
literal|"%s deleted\n"
argument_list|,
name|code_name
argument_list|)
expr_stmt|;
name|log_last_line
argument_list|(
name|win
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|vis_string
operator|!=
literal|0
condition|)
name|free
argument_list|(
name|vis_string
argument_list|)
expr_stmt|;
if|if
condition|(
name|old_string
operator|!=
literal|0
condition|)
name|free
argument_list|(
name|old_string
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
name|duplicate
parameter_list|(
name|WINDOW
modifier|*
name|win
parameter_list|,
name|NCURSES_CONST
name|char
modifier|*
name|name
parameter_list|,
name|int
name|code
parameter_list|)
block|{
name|char
modifier|*
name|value
init|=
name|tigetstr
argument_list|(
name|name
argument_list|)
decl_stmt|;
if|if
condition|(
name|value
operator|!=
literal|0
condition|)
block|{
specifier|const
name|char
modifier|*
name|prefix
init|=
literal|0
decl_stmt|;
name|char
name|temp
index|[
name|BUFSIZ
index|]
decl_stmt|;
if|if
condition|(
operator|!
name|strncmp
argument_list|(
name|value
argument_list|,
literal|"\033["
argument_list|,
operator|(
name|size_t
operator|)
literal|2
argument_list|)
condition|)
block|{
name|prefix
operator|=
literal|"\033O"
expr_stmt|;
block|}
elseif|else
if|if
condition|(
operator|!
name|strncmp
argument_list|(
name|value
argument_list|,
literal|"\033O"
argument_list|,
operator|(
name|size_t
operator|)
literal|2
argument_list|)
condition|)
block|{
name|prefix
operator|=
literal|"\033["
expr_stmt|;
block|}
if|if
condition|(
name|prefix
operator|!=
literal|0
condition|)
block|{
name|sprintf
argument_list|(
name|temp
argument_list|,
literal|"%s%s"
argument_list|,
name|prefix
argument_list|,
name|value
operator|+
literal|2
argument_list|)
expr_stmt|;
name|really_define_key
argument_list|(
name|win
argument_list|,
name|temp
argument_list|,
name|code
argument_list|)
expr_stmt|;
block|}
block|}
block|}
end_function

begin_function
specifier|static
name|void
name|redefine
parameter_list|(
name|WINDOW
modifier|*
name|win
parameter_list|,
name|char
modifier|*
name|string
parameter_list|,
name|int
name|code
parameter_list|)
block|{
name|really_define_key
argument_list|(
name|win
argument_list|,
name|string
argument_list|,
name|code
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
name|remove_definition
parameter_list|(
name|WINDOW
modifier|*
name|win
parameter_list|,
name|int
name|code
parameter_list|)
block|{
name|really_define_key
argument_list|(
name|win
argument_list|,
literal|0
argument_list|,
name|code
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|int
name|main
parameter_list|(
name|int
name|argc
name|GCC_UNUSED
parameter_list|,
name|char
modifier|*
name|argv
index|[]
name|GCC_UNUSED
parameter_list|)
block|{
name|char
modifier|*
name|fkeys
index|[
literal|12
index|]
decl_stmt|;
name|int
name|n
decl_stmt|;
name|int
name|ch
decl_stmt|;
name|WINDOW
modifier|*
name|win
decl_stmt|;
name|unlink
argument_list|(
name|MY_LOGFILE
argument_list|)
expr_stmt|;
name|initscr
argument_list|()
expr_stmt|;
operator|(
name|void
operator|)
name|cbreak
argument_list|()
expr_stmt|;
comment|/* take input chars one at a time, no wait for \n */
operator|(
name|void
operator|)
name|noecho
argument_list|()
expr_stmt|;
comment|/* don't echo input */
name|printw
argument_list|(
literal|"This demo is best on xterm: it reverses the definitions for f1-f12,\n"
argument_list|)
expr_stmt|;
name|printw
argument_list|(
literal|"adds duplicate definitions for cursor application and normal modes,\n"
argument_list|)
expr_stmt|;
name|printw
argument_list|(
literal|"and removes any definitions for the mini keypad.  Type any of those:\n"
argument_list|)
expr_stmt|;
name|refresh
argument_list|()
expr_stmt|;
name|win
operator|=
name|newwin
argument_list|(
name|LINES
operator|-
literal|3
argument_list|,
name|COLS
argument_list|,
literal|3
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|scrollok
argument_list|(
name|win
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
name|keypad
argument_list|(
name|win
argument_list|,
name|TRUE
argument_list|)
expr_stmt|;
name|wmove
argument_list|(
name|win
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
expr_stmt|;
comment|/* we do the define_key() calls after keypad(), since the first call to      * keypad() initializes the corresponding data.      */
for|for
control|(
name|n
operator|=
literal|0
init|;
name|n
operator|<
literal|12
condition|;
operator|++
name|n
control|)
block|{
name|char
name|name
index|[
literal|10
index|]
decl_stmt|;
name|sprintf
argument_list|(
name|name
argument_list|,
literal|"kf%d"
argument_list|,
name|n
operator|+
literal|1
argument_list|)
expr_stmt|;
name|fkeys
index|[
name|n
index|]
operator|=
name|tigetstr
argument_list|(
name|name
argument_list|)
expr_stmt|;
block|}
for|for
control|(
name|n
operator|=
literal|0
init|;
name|n
operator|<
literal|12
condition|;
operator|++
name|n
control|)
block|{
name|redefine
argument_list|(
name|win
argument_list|,
name|fkeys
index|[
literal|11
operator|-
name|n
index|]
argument_list|,
name|KEY_F
argument_list|(
name|n
operator|+
literal|1
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|duplicate
argument_list|(
name|win
argument_list|,
literal|"kcub1"
argument_list|,
name|KEY_LEFT
argument_list|)
expr_stmt|;
name|duplicate
argument_list|(
name|win
argument_list|,
literal|"kcuu1"
argument_list|,
name|KEY_UP
argument_list|)
expr_stmt|;
name|duplicate
argument_list|(
name|win
argument_list|,
literal|"kcud1"
argument_list|,
name|KEY_DOWN
argument_list|)
expr_stmt|;
name|duplicate
argument_list|(
name|win
argument_list|,
literal|"kcuf1"
argument_list|,
name|KEY_RIGHT
argument_list|)
expr_stmt|;
name|remove_definition
argument_list|(
name|win
argument_list|,
name|KEY_A1
argument_list|)
expr_stmt|;
name|remove_definition
argument_list|(
name|win
argument_list|,
name|KEY_A3
argument_list|)
expr_stmt|;
name|remove_definition
argument_list|(
name|win
argument_list|,
name|KEY_B2
argument_list|)
expr_stmt|;
name|remove_definition
argument_list|(
name|win
argument_list|,
name|KEY_C1
argument_list|)
expr_stmt|;
name|remove_definition
argument_list|(
name|win
argument_list|,
name|KEY_C3
argument_list|)
expr_stmt|;
name|really_define_key
argument_list|(
name|win
argument_list|,
literal|"\033O"
argument_list|,
literal|1023
argument_list|)
expr_stmt|;
while|while
condition|(
operator|(
name|ch
operator|=
name|wgetch
argument_list|(
name|win
argument_list|)
operator|)
operator|!=
name|ERR
condition|)
block|{
specifier|const
name|char
modifier|*
name|name
init|=
name|keyname
argument_list|(
name|ch
argument_list|)
decl_stmt|;
name|wprintw
argument_list|(
name|win
argument_list|,
literal|"Keycode %d, name %s\n"
argument_list|,
name|ch
argument_list|,
name|name
operator|!=
literal|0
condition|?
name|name
else|:
literal|"<null>"
argument_list|)
expr_stmt|;
name|log_last_line
argument_list|(
name|win
argument_list|)
expr_stmt|;
name|wclrtoeol
argument_list|(
name|win
argument_list|)
expr_stmt|;
if|if
condition|(
name|ch
operator|==
literal|'q'
condition|)
break|break;
block|}
name|endwin
argument_list|()
expr_stmt|;
name|ExitProgram
argument_list|(
name|EXIT_FAILURE
argument_list|)
expr_stmt|;
block|}
end_function

begin_else
else|#
directive|else
end_else

begin_function
name|int
name|main
parameter_list|(
name|void
parameter_list|)
block|{
name|printf
argument_list|(
literal|"This program requires the ncurses library\n"
argument_list|)
expr_stmt|;
name|ExitProgram
argument_list|(
name|EXIT_FAILURE
argument_list|)
expr_stmt|;
block|}
end_function

begin_endif
endif|#
directive|endif
end_endif

end_unit

