begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/****************************************************************************  * Copyright (c) 2002-2003,2004 Free Software Foundation, Inc.              *  *                                                                          *  * Permission is hereby granted, free of charge, to any person obtaining a  *  * copy of this software and associated documentation files (the            *  * "Software"), to deal in the Software without restriction, including      *  * without limitation the rights to use, copy, modify, merge, publish,      *  * distribute, distribute with modifications, sublicense, and/or sell       *  * copies of the Software, and to permit persons to whom the Software is    *  * furnished to do so, subject to the following conditions:                 *  *                                                                          *  * The above copyright notice and this permission notice shall be included  *  * in all copies or substantial portions of the Software.                   *  *                                                                          *  * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS  *  * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF               *  * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.   *  * IN NO EVENT SHALL THE ABOVE COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,   *  * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR    *  * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR    *  * THE USE OR OTHER DEALINGS IN THE SOFTWARE.                               *  *                                                                          *  * Except as contained in this notice, the name(s) of the above copyright   *  * holders shall not be used in advertising or otherwise to promote the     *  * sale, use or other dealings in this Software without prior written       *  * authorization.                                                           *  ****************************************************************************/
end_comment

begin_comment
comment|/****************************************************************************  *  Author: Thomas E. Dickey 2002                                           *  ****************************************************************************/
end_comment

begin_comment
comment|/* **	lib_unget_wch.c ** **	The routine unget_wch(). ** */
end_comment

begin_include
include|#
directive|include
file|<curses.priv.h>
end_include

begin_macro
name|MODULE_ID
argument_list|(
literal|"$Id: lib_unget_wch.c,v 1.7 2004/12/05 01:21:31 tom Exp $"
argument_list|)
end_macro

begin_ifdef
ifdef|#
directive|ifdef
name|linux
end_ifdef

begin_comment
comment|/*  * glibc's wcrtomb() function is broken - does not return the proper value  * when target is null (noted for glibc 2.3.2).  This is a workaround.  */
end_comment

begin_macro
name|NCURSES_EXPORT
argument_list|(
argument|size_t
argument_list|)
end_macro

begin_macro
name|_nc_wcrtomb
argument_list|(
argument|char *target
argument_list|,
argument|wchar_t source
argument_list|,
argument|mbstate_t * state
argument_list|)
end_macro

begin_block
block|{
if|if
condition|(
name|target
operator|==
literal|0
condition|)
block|{
name|wchar_t
name|temp
index|[
literal|2
index|]
decl_stmt|;
specifier|const
name|wchar_t
modifier|*
name|tempp
init|=
name|temp
decl_stmt|;
name|temp
index|[
literal|0
index|]
operator|=
name|source
expr_stmt|;
name|temp
index|[
literal|1
index|]
operator|=
literal|0
expr_stmt|;
return|return
name|wcsrtombs
argument_list|(
name|NULL
argument_list|,
operator|&
name|tempp
argument_list|,
literal|0
argument_list|,
name|state
argument_list|)
return|;
block|}
return|return
name|wcrtomb
argument_list|(
name|target
argument_list|,
name|source
argument_list|,
name|state
argument_list|)
return|;
block|}
end_block

begin_endif
endif|#
directive|endif
end_endif

begin_macro
name|NCURSES_EXPORT
argument_list|(
argument|int
argument_list|)
end_macro

begin_macro
name|unget_wch
argument_list|(
argument|const wchar_t wch
argument_list|)
end_macro

begin_block
block|{
name|int
name|result
init|=
name|OK
decl_stmt|;
name|mbstate_t
name|state
decl_stmt|;
name|size_t
name|length
decl_stmt|;
name|int
name|n
decl_stmt|;
name|T
argument_list|(
operator|(
name|T_CALLED
argument_list|(
literal|"unget_wch(%#lx)"
argument_list|)
operator|,
operator|(
name|unsigned
name|long
operator|)
name|wch
operator|)
argument_list|)
expr_stmt|;
name|init_mb
argument_list|(
name|state
argument_list|)
expr_stmt|;
name|length
operator|=
name|_nc_wcrtomb
argument_list|(
literal|0
argument_list|,
name|wch
argument_list|,
operator|&
name|state
argument_list|)
expr_stmt|;
if|if
condition|(
name|length
operator|!=
call|(
name|size_t
call|)
argument_list|(
operator|-
literal|1
argument_list|)
operator|&&
name|length
operator|!=
literal|0
condition|)
block|{
name|char
modifier|*
name|string
decl_stmt|;
if|if
condition|(
operator|(
name|string
operator|=
operator|(
name|char
operator|*
operator|)
name|malloc
argument_list|(
name|length
argument_list|)
operator|)
operator|!=
literal|0
condition|)
block|{
name|init_mb
argument_list|(
name|state
argument_list|)
expr_stmt|;
name|wcrtomb
argument_list|(
name|string
argument_list|,
name|wch
argument_list|,
operator|&
name|state
argument_list|)
expr_stmt|;
for|for
control|(
name|n
operator|=
call|(
name|int
call|)
argument_list|(
name|length
operator|-
literal|1
argument_list|)
init|;
name|n
operator|>=
literal|0
condition|;
operator|--
name|n
control|)
block|{
if|if
condition|(
name|ungetch
argument_list|(
name|string
index|[
name|n
index|]
argument_list|)
operator|!=
name|OK
condition|)
block|{
name|result
operator|=
name|ERR
expr_stmt|;
break|break;
block|}
block|}
name|free
argument_list|(
name|string
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|result
operator|=
name|ERR
expr_stmt|;
block|}
block|}
else|else
block|{
name|result
operator|=
name|ERR
expr_stmt|;
block|}
name|returnCode
argument_list|(
name|result
argument_list|)
expr_stmt|;
block|}
end_block

end_unit

