begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* $FreeBSD$ */
end_comment

begin_comment
comment|/* This is an edited copy of the config.h generated by configure. */
end_comment

begin_comment
comment|/* config.h.  Generated from config.h.in by configure.  */
end_comment

begin_comment
comment|/* config.h.in.  Generated from configure.in by autoheader.  */
end_comment

begin_comment
comment|/* define if you have the addrinfo function */
end_comment

begin_define
define|#
directive|define
name|HAVE_ADDRINFO
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `alarm' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_ALARM
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `bpf_dump' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_BPF_DUMP
value|1
end_define

begin_comment
comment|/* capsicum support available */
end_comment

begin_comment
comment|/* See Makefile */
end_comment

begin_comment
comment|/* #undef HAVE_CAPSICUM */
end_comment

begin_comment
comment|/* Define to 1 if you have the `cap_enter' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_CAP_ENTER
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `cap_ioctls_limit' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_CAP_IOCTLS_LIMIT
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `cap_rights_init' function. */
end_comment

begin_comment
comment|/* #undef HAVE_CAP_RIGHTS_INIT */
end_comment

begin_comment
comment|/* Define to 1 if you have the `cap_rights_limit' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_CAP_RIGHTS_LIMIT
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the declaration of `ether_ntohost', and to 0 if you    don't. */
end_comment

begin_define
define|#
directive|define
name|HAVE_DECL_ETHER_NTOHOST
value|1
end_define

begin_comment
comment|/* define if you have the dnet_htoa function */
end_comment

begin_comment
comment|/* #undef HAVE_DNET_HTOA */
end_comment

begin_comment
comment|/* Define to 1 if you have the `ether_ntohost' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_ETHER_NTOHOST
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the<fcntl.h> header file. */
end_comment

begin_define
define|#
directive|define
name|HAVE_FCNTL_H
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `fork' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_FORK
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `getnameinfo' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_GETNAMEINFO
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `getopt_long' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_GETOPT_LONG
value|1
end_define

begin_comment
comment|/* define if you have getrpcbynumber() */
end_comment

begin_define
define|#
directive|define
name|HAVE_GETRPCBYNUMBER
value|1
end_define

begin_comment
comment|/* define if you have the h_errno variable */
end_comment

begin_define
define|#
directive|define
name|HAVE_H_ERRNO
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the<inttypes.h> header file. */
end_comment

begin_define
define|#
directive|define
name|HAVE_INTTYPES_H
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `crypto' library (-lcrypto). */
end_comment

begin_comment
comment|/* See Makefile */
end_comment

begin_comment
comment|/* #undef HAVE_LIBCRYPTO */
end_comment

begin_comment
comment|/* Define to 1 if you have the `rpc' library (-lrpc). */
end_comment

begin_comment
comment|/* #undef HAVE_LIBRPC */
end_comment

begin_comment
comment|/* Define to 1 if you have the<memory.h> header file. */
end_comment

begin_define
define|#
directive|define
name|HAVE_MEMORY_H
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the<netdnet/dnetdb.h> header file. */
end_comment

begin_comment
comment|/* #undef HAVE_NETDNET_DNETDB_H */
end_comment

begin_comment
comment|/* define if you have a dnet_htoa declaration in<netdnet/dnetdb.h> */
end_comment

begin_comment
comment|/* #undef HAVE_NETDNET_DNETDB_H_DNET_HTOA */
end_comment

begin_comment
comment|/* Define to 1 if you have the<netinet/ether.h> header file. */
end_comment

begin_comment
comment|/* #undef HAVE_NETINET_ETHER_H */
end_comment

begin_comment
comment|/* Define to 1 if you have the<netinet/if_ether.h> header file. */
end_comment

begin_define
define|#
directive|define
name|HAVE_NETINET_IF_ETHER_H
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the<net/pfvar.h> header file. */
end_comment

begin_comment
comment|/* See Makefile */
end_comment

begin_comment
comment|/* #undef HAVE_NET_PFVAR_H */
end_comment

begin_comment
comment|/* Define to 1 if you have the `openat' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_OPENAT
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the<openssl/evp.h> header file. */
end_comment

begin_comment
comment|/* See Makefile */
end_comment

begin_comment
comment|/* #undef HAVE_OPENSSL_EVP_H 1 */
end_comment

begin_comment
comment|/* if there's an os_proto.h for this platform, to use additional prototypes */
end_comment

begin_comment
comment|/* #undef HAVE_OS_PROTO_H */
end_comment

begin_comment
comment|/* Define to 1 if you have the<pcap/bluetooth.h> header file. */
end_comment

begin_comment
comment|/* #undef HAVE_PCAP_BLUETOOTH_H */
end_comment

begin_comment
comment|/* Define to 1 if you have the `pcap_breakloop' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_PCAP_BREAKLOOP
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `pcap_create' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_PCAP_CREATE
value|1
end_define

begin_comment
comment|/* define if libpcap has pcap_datalink_name_to_val() */
end_comment

begin_define
define|#
directive|define
name|HAVE_PCAP_DATALINK_NAME_TO_VAL
value|1
end_define

begin_comment
comment|/* define if libpcap has pcap_datalink_val_to_description() */
end_comment

begin_define
define|#
directive|define
name|HAVE_PCAP_DATALINK_VAL_TO_DESCRIPTION
value|1
end_define

begin_comment
comment|/* define if libpcap has pcap_debug */
end_comment

begin_comment
comment|/* #undef HAVE_PCAP_DEBUG */
end_comment

begin_comment
comment|/* Define to 1 if you have the `pcap_dump_flush' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_PCAP_DUMP_FLUSH
value|1
end_define

begin_comment
comment|/* define if libpcap has pcap_dump_ftell() */
end_comment

begin_define
define|#
directive|define
name|HAVE_PCAP_DUMP_FTELL
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `pcap_findalldevs' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_PCAP_FINDALLDEVS
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `pcap_free_datalinks' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_PCAP_FREE_DATALINKS
value|1
end_define

begin_comment
comment|/* Define to 1 if the system has the type `pcap_if_t'. */
end_comment

begin_define
define|#
directive|define
name|HAVE_PCAP_IF_T
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `pcap_lib_version' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_PCAP_LIB_VERSION
value|1
end_define

begin_comment
comment|/* define if libpcap has pcap_list_datalinks() */
end_comment

begin_define
define|#
directive|define
name|HAVE_PCAP_LIST_DATALINKS
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the<pcap/nflog.h> header file. */
end_comment

begin_comment
comment|/* #undef HAVE_PCAP_NFLOG_H */
end_comment

begin_comment
comment|/* Define to 1 if you have the `pcap_setdirection' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_PCAP_SETDIRECTION
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `pcap_set_datalink' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_PCAP_SET_DATALINK
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `pcap_set_tstamp_precision' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_PCAP_SET_TSTAMP_PRECISION
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `pcap_set_tstamp_type' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_PCAP_SET_TSTAMP_TYPE
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the<pcap/usb.h> header file. */
end_comment

begin_comment
comment|/* #undef HAVE_PCAP_USB_H */
end_comment

begin_comment
comment|/* define if libpcap has pcap_version */
end_comment

begin_comment
comment|/* #undef HAVE_PCAP_VERSION */
end_comment

begin_comment
comment|/* Define to 1 if you have the `pfopen' function. */
end_comment

begin_comment
comment|/* #undef HAVE_PFOPEN */
end_comment

begin_comment
comment|/* Define to 1 if you have the<rpc/rpcent.h> header file. */
end_comment

begin_define
define|#
directive|define
name|HAVE_RPC_RPCENT_H
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the<rpc/rpc.h> header file. */
end_comment

begin_define
define|#
directive|define
name|HAVE_RPC_RPC_H
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `setlinebuf' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_SETLINEBUF
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `sigaction' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_SIGACTION
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `sigset' function. */
end_comment

begin_comment
comment|/* #undef HAVE_SIGSET */
end_comment

begin_comment
comment|/* Define to 1 if you have the `snprintf' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_SNPRINTF
value|1
end_define

begin_comment
comment|/* if struct sockaddr has the sa_len member */
end_comment

begin_define
define|#
directive|define
name|HAVE_SOCKADDR_SA_LEN
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the<stdint.h> header file. */
end_comment

begin_define
define|#
directive|define
name|HAVE_STDINT_H
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the<stdlib.h> header file. */
end_comment

begin_define
define|#
directive|define
name|HAVE_STDLIB_H
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `strcasecmp' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_STRCASECMP
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `strdup' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_STRDUP
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `strftime' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_STRFTIME
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the<strings.h> header file. */
end_comment

begin_define
define|#
directive|define
name|HAVE_STRINGS_H
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the<string.h> header file. */
end_comment

begin_define
define|#
directive|define
name|HAVE_STRING_H
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `strlcat' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_STRLCAT
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `strlcpy' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_STRLCPY
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `strsep' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_STRSEP
value|1
end_define

begin_comment
comment|/* Define to 1 if the system has the type `struct ether_addr'. */
end_comment

begin_comment
comment|/* #undef HAVE_STRUCT_ETHER_ADDR */
end_comment

begin_comment
comment|/* Define to 1 if you have the<sys/stat.h> header file. */
end_comment

begin_define
define|#
directive|define
name|HAVE_SYS_STAT_H
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the<sys/types.h> header file. */
end_comment

begin_define
define|#
directive|define
name|HAVE_SYS_TYPES_H
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the<unistd.h> header file. */
end_comment

begin_define
define|#
directive|define
name|HAVE_UNISTD_H
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `vfork' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_VFORK
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `vfprintf' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_VFPRINTF
value|1
end_define

begin_comment
comment|/* Define to 1 if you have the `vsnprintf' function. */
end_comment

begin_define
define|#
directive|define
name|HAVE_VSNPRINTF
value|1
end_define

begin_comment
comment|/* define if libpcap has yydebug */
end_comment

begin_comment
comment|/* #undef HAVE_YYDEBUG */
end_comment

begin_comment
comment|/* define if your compiler has __attribute__ */
end_comment

begin_define
define|#
directive|define
name|HAVE___ATTRIBUTE__
value|1
end_define

begin_comment
comment|/* Define if you enable IPv6 support */
end_comment

begin_comment
comment|/* See Makefile */
end_comment

begin_comment
comment|/* #undef INET6 */
end_comment

begin_comment
comment|/* if unaligned access fails */
end_comment

begin_comment
comment|/* #undef LBL_ALIGN */
end_comment

begin_comment
comment|/* define if you need to include missing/addrinfo.h */
end_comment

begin_comment
comment|/* #undef NEED_ADDRINFO_H */
end_comment

begin_comment
comment|/* Define to 1 if netinet/ether.h declares `ether_ntohost' */
end_comment

begin_comment
comment|/* #undef NETINET_ETHER_H_DECLARES_ETHER_NTOHOST */
end_comment

begin_comment
comment|/* Define to 1 if netinet/if_ether.h declares `ether_ntohost' */
end_comment

begin_define
define|#
directive|define
name|NETINET_IF_ETHER_H_DECLARES_ETHER_NTOHOST
end_define

begin_comment
comment|/**/
end_comment

begin_comment
comment|/* Define to the address where bug reports for this package should be sent. */
end_comment

begin_define
define|#
directive|define
name|PACKAGE_BUGREPORT
value|""
end_define

begin_comment
comment|/* Define to the full name of this package. */
end_comment

begin_define
define|#
directive|define
name|PACKAGE_NAME
value|""
end_define

begin_comment
comment|/* Define to the full name and version of this package. */
end_comment

begin_define
define|#
directive|define
name|PACKAGE_STRING
value|""
end_define

begin_comment
comment|/* Define to the one symbol short name of this package. */
end_comment

begin_define
define|#
directive|define
name|PACKAGE_TARNAME
value|""
end_define

begin_comment
comment|/* Define to the home page for this package. */
end_comment

begin_define
define|#
directive|define
name|PACKAGE_URL
value|""
end_define

begin_comment
comment|/* Define to the version of this package. */
end_comment

begin_define
define|#
directive|define
name|PACKAGE_VERSION
value|""
end_define

begin_comment
comment|/* define if the platform doesn't define PRId64 */
end_comment

begin_comment
comment|/* #undef PRId64 */
end_comment

begin_comment
comment|/* define if the platform doesn't define PRIo64 */
end_comment

begin_comment
comment|/* #undef PRIo64 */
end_comment

begin_comment
comment|/* define if the platform doesn't define PRIx64 */
end_comment

begin_comment
comment|/* #undef PRIu64 */
end_comment

begin_comment
comment|/* define if the platform doesn't define PRIu64 */
end_comment

begin_comment
comment|/* #undef PRIx64 */
end_comment

begin_comment
comment|/* Define as the return type of signal handlers (`int' or `void'). */
end_comment

begin_define
define|#
directive|define
name|RETSIGTYPE
value|void
end_define

begin_comment
comment|/* return value of signal handlers */
end_comment

begin_define
define|#
directive|define
name|RETSIGVAL
end_define

begin_comment
comment|/**/
end_comment

begin_comment
comment|/* Define to 1 if you have the ANSI C header files. */
end_comment

begin_define
define|#
directive|define
name|STDC_HEADERS
value|1
end_define

begin_comment
comment|/* define if you want to build the possibly-buggy SMB printer */
end_comment

begin_define
define|#
directive|define
name|TCPDUMP_DO_SMB
value|1
end_define

begin_comment
comment|/* Define to 1 if you can safely include both<sys/time.h> and<time.h>. */
end_comment

begin_define
define|#
directive|define
name|TIME_WITH_SYS_TIME
value|1
end_define

begin_comment
comment|/* define if you have ether_ntohost() and it works */
end_comment

begin_define
define|#
directive|define
name|USE_ETHER_NTOHOST
value|1
end_define

begin_comment
comment|/* Define if you enable support for libsmi */
end_comment

begin_comment
comment|/* #undef USE_LIBSMI */
end_comment

begin_comment
comment|/* define if should chroot when dropping privileges */
end_comment

begin_comment
comment|/* #undef WITH_CHROOT */
end_comment

begin_comment
comment|/* define if should drop privileges by default */
end_comment

begin_comment
comment|/* #undef WITH_USER */
end_comment

begin_comment
comment|/* get BSD semantics on Irix */
end_comment

begin_comment
comment|/* #undef _BSD_SIGNALS */
end_comment

begin_comment
comment|/* define on AIX to get certain functions */
end_comment

begin_comment
comment|/* #undef _SUN */
end_comment

begin_comment
comment|/* Define for Solaris 2.5.1 so the uint32_t typedef from<sys/synch.h>,<pthread.h>, or<semaphore.h> is not used. If the typedef were allowed, the    #define below would cause a syntax error. */
end_comment

begin_comment
comment|/* #undef _UINT32_T */
end_comment

begin_comment
comment|/* Define for Solaris 2.5.1 so the uint64_t typedef from<sys/synch.h>,<pthread.h>, or<semaphore.h> is not used. If the typedef were allowed, the    #define below would cause a syntax error. */
end_comment

begin_comment
comment|/* #undef _UINT64_T */
end_comment

begin_comment
comment|/* Define for Solaris 2.5.1 so the uint8_t typedef from<sys/synch.h>,<pthread.h>, or<semaphore.h> is not used. If the typedef were allowed, the    #define below would cause a syntax error. */
end_comment

begin_comment
comment|/* #undef _UINT8_T */
end_comment

begin_comment
comment|/* define if your compiler allows __attribute__((format)) without a warning */
end_comment

begin_define
define|#
directive|define
name|__ATTRIBUTE___FORMAT_OK
value|1
end_define

begin_comment
comment|/* define if your compiler allows __attribute__((format)) to be applied to    function pointers */
end_comment

begin_define
define|#
directive|define
name|__ATTRIBUTE___FORMAT_OK_FOR_FUNCTION_POINTERS
value|1
end_define

begin_comment
comment|/* define if your compiler allows __attribute__((noreturn)) to be applied to    function pointers */
end_comment

begin_define
define|#
directive|define
name|__ATTRIBUTE___NORETURN_OK_FOR_FUNCTION_POINTERS
value|1
end_define

begin_comment
comment|/* to handle Ultrix compilers that don't support const in prototypes */
end_comment

begin_comment
comment|/* #undef const */
end_comment

begin_comment
comment|/* Define as token for inline if inlining supported */
end_comment

begin_define
define|#
directive|define
name|inline
value|inline
end_define

begin_comment
comment|/* Define to the type of a signed integer type of width exactly 16 bits if    such a type exists and the standard includes do not define it. */
end_comment

begin_comment
comment|/* #undef int16_t */
end_comment

begin_comment
comment|/* Define to the type of a signed integer type of width exactly 32 bits if    such a type exists and the standard includes do not define it. */
end_comment

begin_comment
comment|/* #undef int32_t */
end_comment

begin_comment
comment|/* Define to the type of a signed integer type of width exactly 64 bits if    such a type exists and the standard includes do not define it. */
end_comment

begin_comment
comment|/* #undef int64_t */
end_comment

begin_comment
comment|/* Define to the type of a signed integer type of width exactly 8 bits if such    a type exists and the standard includes do not define it. */
end_comment

begin_comment
comment|/* #undef int8_t */
end_comment

begin_comment
comment|/* Define to `uint16_t' if u_int16_t not defined. */
end_comment

begin_comment
comment|/* #undef u_int16_t */
end_comment

begin_comment
comment|/* Define to `uint32_t' if u_int32_t not defined. */
end_comment

begin_comment
comment|/* #undef u_int32_t */
end_comment

begin_comment
comment|/* Define to `uint64_t' if u_int64_t not defined. */
end_comment

begin_comment
comment|/* #undef u_int64_t */
end_comment

begin_comment
comment|/* Define to `uint8_t' if u_int8_t not defined. */
end_comment

begin_comment
comment|/* #undef u_int8_t */
end_comment

begin_comment
comment|/* Define to the type of an unsigned integer type of width exactly 16 bits if    such a type exists and the standard includes do not define it. */
end_comment

begin_comment
comment|/* #undef uint16_t */
end_comment

begin_comment
comment|/* Define to the type of an unsigned integer type of width exactly 32 bits if    such a type exists and the standard includes do not define it. */
end_comment

begin_comment
comment|/* #undef uint32_t */
end_comment

begin_comment
comment|/* Define to the type of an unsigned integer type of width exactly 64 bits if    such a type exists and the standard includes do not define it. */
end_comment

begin_comment
comment|/* #undef uint64_t */
end_comment

begin_comment
comment|/* Define to the type of an unsigned integer type of width exactly 8 bits if    such a type exists and the standard includes do not define it. */
end_comment

begin_comment
comment|/* #undef uint8_t */
end_comment

end_unit

