begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (c) 1995 - 2000 Kungliga Tekniska Högskolan  * (Royal Institute of Technology, Stockholm, Sweden).  * All rights reserved.  *   * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions  * are met:  *   * 1. Redistributions of source code must retain the above copyright  *    notice, this list of conditions and the following disclaimer.  *   * 2. Redistributions in binary form must reproduce the above copyright  *    notice, this list of conditions and the following disclaimer in the  *    documentation and/or other materials provided with the distribution.  *   * 3. Neither the name of the Institute nor the names of its contributors  *    may be used to endorse or promote products derived from this software  *    without specific prior written permission.  *   * THIS SOFTWARE IS PROVIDED BY THE INSTITUTE AND CONTRIBUTORS ``AS IS'' AND  * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE  * ARE DISCLAIMED.  IN NO EVENT SHALL THE INSTITUTE OR CONTRIBUTORS BE LIABLE  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS  * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)  * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT  * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY  * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF  * SUCH DAMAGE.  */
end_comment

begin_include
include|#
directive|include
file|"krb_locl.h"
end_include

begin_expr_stmt
name|RCSID
argument_list|(
literal|"$Id: rd_safe.c,v 1.26.2.1 2000/10/10 13:20:36 assar Exp $"
argument_list|)
expr_stmt|;
end_expr_stmt

begin_comment
comment|/* application include files */
end_comment

begin_include
include|#
directive|include
file|"krb-archaeology.h"
end_include

begin_ifndef
ifndef|#
directive|ifndef
name|DES_QUAD_GUESS
end_ifndef

begin_comment
comment|/* Temporary fixes for krb_{rd,mk}_safe */
end_comment

begin_define
define|#
directive|define
name|DES_QUAD_GUESS
value|0
end_define

begin_define
define|#
directive|define
name|DES_QUAD_NEW
value|1
end_define

begin_define
define|#
directive|define
name|DES_QUAD_OLD
value|2
end_define

begin_define
define|#
directive|define
name|DES_QUAD_DEFAULT
value|DES_QUAD_GUESS
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_comment
comment|/* DES_QUAD_GUESS */
end_comment

begin_comment
comment|/* Generate two checksums in the given byteorder of the data, one  * new-form and one old-form. It has to be done this way to be  * compatible with the old version of des_quad_cksum.  */
end_comment

begin_comment
comment|/* des_quad_chsum-type; 0 == unknown, 1 == new PL10++, 2 == old */
end_comment

begin_decl_stmt
name|int
name|dqc_type
init|=
name|DES_QUAD_DEFAULT
decl_stmt|;
end_decl_stmt

begin_function
name|void
name|fixup_quad_cksum
parameter_list|(
name|void
modifier|*
name|start
parameter_list|,
name|size_t
name|len
parameter_list|,
name|des_cblock
modifier|*
name|key
parameter_list|,
name|void
modifier|*
name|new_checksum
parameter_list|,
name|void
modifier|*
name|old_checksum
parameter_list|,
name|int
name|little
parameter_list|)
block|{
name|des_quad_cksum
argument_list|(
operator|(
name|des_cblock
operator|*
operator|)
name|start
argument_list|,
operator|(
name|des_cblock
operator|*
operator|)
name|new_checksum
argument_list|,
name|len
argument_list|,
literal|2
argument_list|,
name|key
argument_list|)
expr_stmt|;
if|if
condition|(
name|HOST_BYTE_ORDER
condition|)
block|{
if|if
condition|(
name|little
condition|)
block|{
name|memcpy
argument_list|(
name|old_checksum
argument_list|,
name|new_checksum
argument_list|,
literal|16
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|u_int32_t
modifier|*
name|tmp
init|=
operator|(
name|u_int32_t
operator|*
operator|)
name|new_checksum
decl_stmt|;
name|memcpy
argument_list|(
name|old_checksum
argument_list|,
name|new_checksum
argument_list|,
literal|16
argument_list|)
expr_stmt|;
name|swap_u_16
argument_list|(
name|old_checksum
argument_list|)
expr_stmt|;
name|swap_u_long
argument_list|(
name|tmp
index|[
literal|0
index|]
argument_list|)
expr_stmt|;
name|swap_u_long
argument_list|(
name|tmp
index|[
literal|1
index|]
argument_list|)
expr_stmt|;
name|swap_u_long
argument_list|(
name|tmp
index|[
literal|2
index|]
argument_list|)
expr_stmt|;
name|swap_u_long
argument_list|(
name|tmp
index|[
literal|3
index|]
argument_list|)
expr_stmt|;
block|}
block|}
else|else
block|{
if|if
condition|(
name|little
condition|)
block|{
name|u_int32_t
modifier|*
name|tmp
init|=
operator|(
name|u_int32_t
operator|*
operator|)
name|new_checksum
decl_stmt|;
name|swap_u_long
argument_list|(
name|tmp
index|[
literal|0
index|]
argument_list|)
expr_stmt|;
name|swap_u_long
argument_list|(
name|tmp
index|[
literal|1
index|]
argument_list|)
expr_stmt|;
name|swap_u_long
argument_list|(
name|tmp
index|[
literal|2
index|]
argument_list|)
expr_stmt|;
name|swap_u_long
argument_list|(
name|tmp
index|[
literal|3
index|]
argument_list|)
expr_stmt|;
name|memcpy
argument_list|(
name|old_checksum
argument_list|,
name|new_checksum
argument_list|,
literal|16
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|u_int32_t
name|tmp
index|[
literal|4
index|]
decl_stmt|;
name|tmp
index|[
literal|0
index|]
operator|=
operator|(
operator|(
name|u_int32_t
operator|*
operator|)
name|new_checksum
operator|)
index|[
literal|3
index|]
expr_stmt|;
name|tmp
index|[
literal|1
index|]
operator|=
operator|(
operator|(
name|u_int32_t
operator|*
operator|)
name|new_checksum
operator|)
index|[
literal|2
index|]
expr_stmt|;
name|tmp
index|[
literal|2
index|]
operator|=
operator|(
operator|(
name|u_int32_t
operator|*
operator|)
name|new_checksum
operator|)
index|[
literal|1
index|]
expr_stmt|;
name|tmp
index|[
literal|3
index|]
operator|=
operator|(
operator|(
name|u_int32_t
operator|*
operator|)
name|new_checksum
operator|)
index|[
literal|0
index|]
expr_stmt|;
name|memcpy
argument_list|(
name|old_checksum
argument_list|,
name|tmp
argument_list|,
literal|16
argument_list|)
expr_stmt|;
block|}
block|}
block|}
end_function

begin_comment
comment|/*  * krb_rd_safe() checks the integrity of an AUTH_MSG_SAFE message.  * Given the message received, "in", the length of that message,  * "in_length", the "key" to compute the checksum with, and the  * network addresses of the "sender" and "receiver" of the message,  * krb_rd_safe() returns RD_AP_OK if message is okay, otherwise  * some error code.  *  * The message data retrieved from "in" is returned in the structure  * "m_data".  The pointer to the application data (m_data->app_data)  * refers back to the appropriate place in "in".  *  * See the file "mk_safe.c" for the format of the AUTH_MSG_SAFE  * message.  The structure containing the extracted message  * information, MSG_DAT, is defined in "krb.h".  */
end_comment

begin_function
name|int32_t
name|krb_rd_safe
parameter_list|(
name|void
modifier|*
name|in
parameter_list|,
name|u_int32_t
name|in_length
parameter_list|,
name|des_cblock
modifier|*
name|key
parameter_list|,
name|struct
name|sockaddr_in
modifier|*
name|sender
parameter_list|,
name|struct
name|sockaddr_in
modifier|*
name|receiver
parameter_list|,
name|MSG_DAT
modifier|*
name|m_data
parameter_list|)
block|{
name|unsigned
name|char
modifier|*
name|p
init|=
operator|(
name|unsigned
name|char
operator|*
operator|)
name|in
decl_stmt|,
modifier|*
name|start
decl_stmt|;
name|unsigned
name|char
name|pvno
decl_stmt|,
name|type
decl_stmt|;
name|int
name|little_endian
decl_stmt|;
name|struct
name|timeval
name|tv
decl_stmt|;
name|u_int32_t
name|src_addr
decl_stmt|;
name|int
name|delta_t
decl_stmt|;
name|pvno
operator|=
operator|*
name|p
operator|++
expr_stmt|;
if|if
condition|(
name|pvno
operator|!=
name|KRB_PROT_VERSION
condition|)
return|return
name|RD_AP_VERSION
return|;
name|type
operator|=
operator|*
name|p
operator|++
expr_stmt|;
name|little_endian
operator|=
name|type
operator|&
literal|1
expr_stmt|;
name|type
operator|&=
operator|~
literal|1
expr_stmt|;
if|if
condition|(
name|type
operator|!=
name|AUTH_MSG_SAFE
condition|)
return|return
name|RD_AP_MSG_TYPE
return|;
name|start
operator|=
name|p
expr_stmt|;
name|p
operator|+=
name|krb_get_int
argument_list|(
name|p
argument_list|,
operator|&
name|m_data
operator|->
name|app_length
argument_list|,
literal|4
argument_list|,
name|little_endian
argument_list|)
expr_stmt|;
if|if
condition|(
name|m_data
operator|->
name|app_length
operator|+
literal|31
operator|>
name|in_length
condition|)
return|return
name|RD_AP_MODIFIED
return|;
name|m_data
operator|->
name|app_data
operator|=
name|p
expr_stmt|;
name|p
operator|+=
name|m_data
operator|->
name|app_length
expr_stmt|;
name|m_data
operator|->
name|time_5ms
operator|=
operator|*
name|p
operator|++
expr_stmt|;
name|p
operator|+=
name|krb_get_address
argument_list|(
name|p
argument_list|,
operator|&
name|src_addr
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|krb_equiv
argument_list|(
name|src_addr
argument_list|,
name|sender
operator|->
name|sin_addr
operator|.
name|s_addr
argument_list|)
condition|)
return|return
name|RD_AP_BADD
return|;
name|p
operator|+=
name|krb_get_int
argument_list|(
name|p
argument_list|,
operator|(
name|u_int32_t
operator|*
operator|)
operator|&
name|m_data
operator|->
name|time_sec
argument_list|,
literal|4
argument_list|,
name|little_endian
argument_list|)
expr_stmt|;
name|m_data
operator|->
name|time_sec
operator|=
name|lsb_time
argument_list|(
name|m_data
operator|->
name|time_sec
argument_list|,
name|sender
argument_list|,
name|receiver
argument_list|)
expr_stmt|;
name|gettimeofday
argument_list|(
operator|&
name|tv
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|delta_t
operator|=
name|abs
argument_list|(
call|(
name|int
call|)
argument_list|(
operator|(
name|long
operator|)
name|tv
operator|.
name|tv_sec
operator|-
name|m_data
operator|->
name|time_sec
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|delta_t
operator|>
name|CLOCK_SKEW
condition|)
return|return
name|RD_AP_TIME
return|;
comment|/*      * caller must check timestamps for proper order and replays, since      * server might have multiple clients each with its own timestamps      * and we don't assume tightly synchronized clocks.      */
block|{
name|unsigned
name|char
name|new_checksum
index|[
literal|16
index|]
decl_stmt|;
name|unsigned
name|char
name|old_checksum
index|[
literal|16
index|]
decl_stmt|;
name|fixup_quad_cksum
argument_list|(
name|start
argument_list|,
name|p
operator|-
name|start
argument_list|,
name|key
argument_list|,
name|new_checksum
argument_list|,
name|old_checksum
argument_list|,
name|little_endian
argument_list|)
expr_stmt|;
if|if
condition|(
operator|(
name|dqc_type
operator|==
name|DES_QUAD_GUESS
operator|||
name|dqc_type
operator|==
name|DES_QUAD_NEW
operator|)
operator|&&
name|memcmp
argument_list|(
name|new_checksum
argument_list|,
name|p
argument_list|,
literal|16
argument_list|)
operator|==
literal|0
condition|)
name|dqc_type
operator|=
name|DES_QUAD_NEW
expr_stmt|;
elseif|else
if|if
condition|(
operator|(
name|dqc_type
operator|==
name|DES_QUAD_GUESS
operator|||
name|dqc_type
operator|==
name|DES_QUAD_OLD
operator|)
operator|&&
name|memcmp
argument_list|(
name|old_checksum
argument_list|,
name|p
argument_list|,
literal|16
argument_list|)
operator|==
literal|0
condition|)
name|dqc_type
operator|=
name|DES_QUAD_OLD
expr_stmt|;
else|else
return|return
name|RD_AP_MODIFIED
return|;
block|}
return|return
name|KSUCCESS
return|;
block|}
end_function

end_unit

