begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*-  * Copyright (c) 2003-2012 Broadcom Corporation  * All Rights Reserved  *  * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions  * are met:  *  * 1. Redistributions of source code must retain the above copyright  *    notice, this list of conditions and the following disclaimer.  * 2. Redistributions in binary form must reproduce the above copyright  *    notice, this list of conditions and the following disclaimer in  *    the documentation and/or other materials provided with the  *    distribution.  *   * THIS SOFTWARE IS PROVIDED BY BROADCOM ``AS IS'' AND ANY EXPRESS OR  * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED  * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE  * ARE DISCLAIMED. IN NO EVENT SHALL BROADCOM OR CONTRIBUTORS BE LIABLE  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR  * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF  * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR  * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,  * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE  * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN  * IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.  *  * $FreeBSD$  */
end_comment

begin_include
include|#
directive|include
file|"ucore.h"
end_include

begin_function
name|int
name|main
parameter_list|(
name|void
parameter_list|)
block|{
if|#
directive|if
literal|0
block|volatile unsigned int *pkt =  	    (volatile unsigned int *) (PACKET_MEMORY + PACKET_DATA_OFFSET); 	int intf, hw_parser_error, context;
endif|#
directive|endif
name|unsigned
name|int
name|pktrdy
decl_stmt|;
name|int
name|num_cachelines
init|=
literal|1518
operator|/
literal|64
decl_stmt|;
comment|/* pktsize / L3 cacheline size */
comment|/* Spray packets to using distribution vector */
while|while
condition|(
literal|1
condition|)
block|{
name|pktrdy
operator|=
name|nlm_read_ucore_rxpktrdy
argument_list|()
expr_stmt|;
if|#
directive|if
literal|0
block|intf = pktrdy& 0x1f; 		context = (pktrdy>> 13)& 0x3ff; 		hw_parser_error = (pktrdy>> 23)& 0x1;
endif|#
directive|endif
name|nlm_ucore_setup_poepktdistr
argument_list|(
name|FWD_DIST_VEC
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|nlm_ucore_pkt_done
argument_list|(
name|num_cachelines
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

end_unit

