begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (c) 2005, PADL Software Pty Ltd.  * All rights reserved.  *  * Portions Copyright (c) 2009 Apple Inc. All rights reserved.  *  * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions  * are met:  *  * 1. Redistributions of source code must retain the above copyright  *    notice, this list of conditions and the following disclaimer.  *  * 2. Redistributions in binary form must reproduce the above copyright  *    notice, this list of conditions and the following disclaimer in the  *    documentation and/or other materials provided with the distribution.  *  * 3. Neither the name of PADL Software nor the names of its contributors  *    may be used to endorse or promote products derived from this software  *    without specific prior written permission.  *  * THIS SOFTWARE IS PROVIDED BY PADL SOFTWARE AND CONTRIBUTORS ``AS IS'' AND  * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE  * ARE DISCLAIMED.  IN NO EVENT SHALL PADL SOFTWARE OR CONTRIBUTORS BE LIABLE  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS  * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)  * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT  * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY  * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF  * SUCH DAMAGE.  */
end_comment

begin_include
include|#
directive|include
file|"kcm_locl.h"
end_include

begin_include
include|#
directive|include
file|<pwd.h>
end_include

begin_function
name|krb5_error_code
name|kcm_ccache_resolve_client
parameter_list|(
name|krb5_context
name|context
parameter_list|,
name|kcm_client
modifier|*
name|client
parameter_list|,
name|kcm_operation
name|opcode
parameter_list|,
specifier|const
name|char
modifier|*
name|name
parameter_list|,
name|kcm_ccache
modifier|*
name|ccache
parameter_list|)
block|{
name|krb5_error_code
name|ret
decl_stmt|;
name|ret
operator|=
name|kcm_ccache_resolve
argument_list|(
name|context
argument_list|,
name|name
argument_list|,
name|ccache
argument_list|)
expr_stmt|;
if|if
condition|(
name|ret
condition|)
block|{
name|kcm_log
argument_list|(
literal|1
argument_list|,
literal|"Failed to resolve cache %s: %s"
argument_list|,
name|name
argument_list|,
name|krb5_get_err_text
argument_list|(
name|context
argument_list|,
name|ret
argument_list|)
argument_list|)
expr_stmt|;
return|return
name|ret
return|;
block|}
name|ret
operator|=
name|kcm_access
argument_list|(
name|context
argument_list|,
name|client
argument_list|,
name|opcode
argument_list|,
operator|*
name|ccache
argument_list|)
expr_stmt|;
if|if
condition|(
name|ret
condition|)
block|{
name|ret
operator|=
name|KRB5_FCC_NOFILE
expr_stmt|;
comment|/* don't disclose */
name|kcm_release_ccache
argument_list|(
name|context
argument_list|,
operator|*
name|ccache
argument_list|)
expr_stmt|;
block|}
return|return
name|ret
return|;
block|}
end_function

begin_function
name|krb5_error_code
name|kcm_ccache_destroy_client
parameter_list|(
name|krb5_context
name|context
parameter_list|,
name|kcm_client
modifier|*
name|client
parameter_list|,
specifier|const
name|char
modifier|*
name|name
parameter_list|)
block|{
name|krb5_error_code
name|ret
decl_stmt|;
name|kcm_ccache
name|ccache
decl_stmt|;
name|ret
operator|=
name|kcm_ccache_resolve
argument_list|(
name|context
argument_list|,
name|name
argument_list|,
operator|&
name|ccache
argument_list|)
expr_stmt|;
if|if
condition|(
name|ret
condition|)
block|{
name|kcm_log
argument_list|(
literal|1
argument_list|,
literal|"Failed to resolve cache %s: %s"
argument_list|,
name|name
argument_list|,
name|krb5_get_err_text
argument_list|(
name|context
argument_list|,
name|ret
argument_list|)
argument_list|)
expr_stmt|;
return|return
name|ret
return|;
block|}
name|ret
operator|=
name|kcm_access
argument_list|(
name|context
argument_list|,
name|client
argument_list|,
name|KCM_OP_DESTROY
argument_list|,
name|ccache
argument_list|)
expr_stmt|;
name|kcm_cleanup_events
argument_list|(
name|context
argument_list|,
name|ccache
argument_list|)
expr_stmt|;
name|kcm_release_ccache
argument_list|(
name|context
argument_list|,
name|ccache
argument_list|)
expr_stmt|;
if|if
condition|(
name|ret
condition|)
return|return
name|ret
return|;
return|return
name|kcm_ccache_destroy
argument_list|(
name|context
argument_list|,
name|name
argument_list|)
return|;
block|}
end_function

begin_function
name|krb5_error_code
name|kcm_ccache_new_client
parameter_list|(
name|krb5_context
name|context
parameter_list|,
name|kcm_client
modifier|*
name|client
parameter_list|,
specifier|const
name|char
modifier|*
name|name
parameter_list|,
name|kcm_ccache
modifier|*
name|ccache_p
parameter_list|)
block|{
name|krb5_error_code
name|ret
decl_stmt|;
name|kcm_ccache
name|ccache
decl_stmt|;
comment|/* We insist the ccache name starts with UID or UID: */
if|if
condition|(
name|name_constraints
operator|!=
literal|0
condition|)
block|{
name|char
name|prefix
index|[
literal|64
index|]
decl_stmt|;
name|size_t
name|prefix_len
decl_stmt|;
name|int
name|bad
init|=
literal|1
decl_stmt|;
name|snprintf
argument_list|(
name|prefix
argument_list|,
sizeof|sizeof
argument_list|(
name|prefix
argument_list|)
argument_list|,
literal|"%ld:"
argument_list|,
operator|(
name|long
operator|)
name|client
operator|->
name|uid
argument_list|)
expr_stmt|;
name|prefix_len
operator|=
name|strlen
argument_list|(
name|prefix
argument_list|)
expr_stmt|;
if|if
condition|(
name|strncmp
argument_list|(
name|name
argument_list|,
name|prefix
argument_list|,
name|prefix_len
argument_list|)
operator|==
literal|0
condition|)
name|bad
operator|=
literal|0
expr_stmt|;
else|else
block|{
name|prefix
index|[
name|prefix_len
operator|-
literal|1
index|]
operator|=
literal|'\0'
expr_stmt|;
if|if
condition|(
name|strcmp
argument_list|(
name|name
argument_list|,
name|prefix
argument_list|)
operator|==
literal|0
condition|)
name|bad
operator|=
literal|0
expr_stmt|;
block|}
comment|/* Allow root to create badly-named ccaches */
if|if
condition|(
name|bad
operator|&&
operator|!
name|CLIENT_IS_ROOT
argument_list|(
name|client
argument_list|)
condition|)
return|return
name|KRB5_CC_BADNAME
return|;
block|}
name|ret
operator|=
name|kcm_ccache_resolve
argument_list|(
name|context
argument_list|,
name|name
argument_list|,
operator|&
name|ccache
argument_list|)
expr_stmt|;
if|if
condition|(
name|ret
operator|==
literal|0
condition|)
block|{
if|if
condition|(
operator|(
name|ccache
operator|->
name|uid
operator|!=
name|client
operator|->
name|uid
operator|||
name|ccache
operator|->
name|gid
operator|!=
name|client
operator|->
name|gid
operator|)
operator|&&
operator|!
name|CLIENT_IS_ROOT
argument_list|(
name|client
argument_list|)
condition|)
return|return
name|KRB5_FCC_PERM
return|;
block|}
elseif|else
if|if
condition|(
name|ret
operator|!=
name|KRB5_FCC_NOFILE
operator|&&
operator|!
operator|(
name|CLIENT_IS_ROOT
argument_list|(
name|client
argument_list|)
operator|&&
name|ret
operator|==
name|KRB5_FCC_PERM
operator|)
condition|)
block|{
return|return
name|ret
return|;
block|}
if|if
condition|(
name|ret
operator|==
name|KRB5_FCC_NOFILE
condition|)
block|{
name|ret
operator|=
name|kcm_ccache_new
argument_list|(
name|context
argument_list|,
name|name
argument_list|,
operator|&
name|ccache
argument_list|)
expr_stmt|;
if|if
condition|(
name|ret
condition|)
block|{
name|kcm_log
argument_list|(
literal|1
argument_list|,
literal|"Failed to initialize cache %s: %s"
argument_list|,
name|name
argument_list|,
name|krb5_get_err_text
argument_list|(
name|context
argument_list|,
name|ret
argument_list|)
argument_list|)
expr_stmt|;
return|return
name|ret
return|;
block|}
comment|/* bind to current client */
name|ccache
operator|->
name|uid
operator|=
name|client
operator|->
name|uid
expr_stmt|;
name|ccache
operator|->
name|gid
operator|=
name|client
operator|->
name|gid
expr_stmt|;
name|ccache
operator|->
name|session
operator|=
name|client
operator|->
name|session
expr_stmt|;
block|}
else|else
block|{
name|ret
operator|=
name|kcm_zero_ccache_data
argument_list|(
name|context
argument_list|,
name|ccache
argument_list|)
expr_stmt|;
if|if
condition|(
name|ret
condition|)
block|{
name|kcm_log
argument_list|(
literal|1
argument_list|,
literal|"Failed to empty cache %s: %s"
argument_list|,
name|name
argument_list|,
name|krb5_get_err_text
argument_list|(
name|context
argument_list|,
name|ret
argument_list|)
argument_list|)
expr_stmt|;
name|kcm_release_ccache
argument_list|(
name|context
argument_list|,
name|ccache
argument_list|)
expr_stmt|;
return|return
name|ret
return|;
block|}
name|kcm_cleanup_events
argument_list|(
name|context
argument_list|,
name|ccache
argument_list|)
expr_stmt|;
block|}
name|ret
operator|=
name|kcm_access
argument_list|(
name|context
argument_list|,
name|client
argument_list|,
name|KCM_OP_INITIALIZE
argument_list|,
name|ccache
argument_list|)
expr_stmt|;
if|if
condition|(
name|ret
condition|)
block|{
name|kcm_release_ccache
argument_list|(
name|context
argument_list|,
name|ccache
argument_list|)
expr_stmt|;
name|kcm_ccache_destroy
argument_list|(
name|context
argument_list|,
name|name
argument_list|)
expr_stmt|;
return|return
name|ret
return|;
block|}
comment|/*      * Finally, if the user is root and the cache was created under      * another user's name, chown the cache to that user and their      * default gid.      */
if|if
condition|(
name|CLIENT_IS_ROOT
argument_list|(
name|client
argument_list|)
condition|)
block|{
name|unsigned
name|long
name|uid
decl_stmt|;
name|int
name|matches
init|=
name|sscanf
argument_list|(
name|name
argument_list|,
literal|"%ld:"
argument_list|,
operator|&
name|uid
argument_list|)
decl_stmt|;
if|if
condition|(
name|matches
operator|==
literal|0
condition|)
name|matches
operator|=
name|sscanf
argument_list|(
name|name
argument_list|,
literal|"%ld"
argument_list|,
operator|&
name|uid
argument_list|)
expr_stmt|;
if|if
condition|(
name|matches
operator|==
literal|1
condition|)
block|{
name|struct
name|passwd
modifier|*
name|pwd
init|=
name|getpwuid
argument_list|(
name|uid
argument_list|)
decl_stmt|;
if|if
condition|(
name|pwd
operator|!=
name|NULL
condition|)
block|{
name|gid_t
name|gid
init|=
name|pwd
operator|->
name|pw_gid
decl_stmt|;
name|kcm_chown
argument_list|(
name|context
argument_list|,
name|client
argument_list|,
name|ccache
argument_list|,
name|uid
argument_list|,
name|gid
argument_list|)
expr_stmt|;
block|}
block|}
block|}
operator|*
name|ccache_p
operator|=
name|ccache
expr_stmt|;
return|return
literal|0
return|;
block|}
end_function

end_unit

