begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/******************************************************************************  *  * Module Name: exconvrt - Object conversion routines  *              $Revision: 1.74 $  *  *****************************************************************************/
end_comment

begin_comment
comment|/******************************************************************************  *  * 1. Copyright Notice  *  * Some or all of this work - Copyright (c) 1999 - 2007, Intel Corp.  * All rights reserved.  *  * 2. License  *  * 2.1. This is your license from Intel Corp. under its intellectual property  * rights.  You may have additional license terms from the party that provided  * you this software, covering your right to use that party's intellectual  * property rights.  *  * 2.2. Intel grants, free of charge, to any person ("Licensee") obtaining a  * copy of the source code appearing in this file ("Covered Code") an  * irrevocable, perpetual, worldwide license under Intel's copyrights in the  * base code distributed originally by Intel ("Original Intel Code") to copy,  * make derivatives, distribute, use and display any portion of the Covered  * Code in any form, with the right to sublicense such rights; and  *  * 2.3. Intel grants Licensee a non-exclusive and non-transferable patent  * license (with the right to sublicense), under only those claims of Intel  * patents that are infringed by the Original Intel Code, to make, use, sell,  * offer to sell, and import the Covered Code and derivative works thereof  * solely to the minimum extent necessary to exercise the above copyright  * license, and in no event shall the patent license extend to any additions  * to or modifications of the Original Intel Code.  No other license or right  * is granted directly or by implication, estoppel or otherwise;  *  * The above copyright and patent license is granted only if the following  * conditions are met:  *  * 3. Conditions  *  * 3.1. Redistribution of Source with Rights to Further Distribute Source.  * Redistribution of source code of any substantial portion of the Covered  * Code or modification with rights to further distribute source must include  * the above Copyright Notice, the above License, this list of Conditions,  * and the following Disclaimer and Export Compliance provision.  In addition,  * Licensee must cause all Covered Code to which Licensee contributes to  * contain a file documenting the changes Licensee made to create that Covered  * Code and the date of any change.  Licensee must include in that file the  * documentation of any changes made by any predecessor Licensee.  Licensee  * must include a prominent statement that the modification is derived,  * directly or indirectly, from Original Intel Code.  *  * 3.2. Redistribution of Source with no Rights to Further Distribute Source.  * Redistribution of source code of any substantial portion of the Covered  * Code or modification without rights to further distribute source must  * include the following Disclaimer and Export Compliance provision in the  * documentation and/or other materials provided with distribution.  In  * addition, Licensee may not authorize further sublicense of source of any  * portion of the Covered Code, and must include terms to the effect that the  * license from Licensee to its licensee is limited to the intellectual  * property embodied in the software Licensee provides to its licensee, and  * not to intellectual property embodied in modifications its licensee may  * make.  *  * 3.3. Redistribution of Executable. Redistribution in executable form of any  * substantial portion of the Covered Code or modification must reproduce the  * above Copyright Notice, and the following Disclaimer and Export Compliance  * provision in the documentation and/or other materials provided with the  * distribution.  *  * 3.4. Intel retains all right, title, and interest in and to the Original  * Intel Code.  *  * 3.5. Neither the name Intel nor any other trademark owned or controlled by  * Intel shall be used in advertising or otherwise to promote the sale, use or  * other dealings in products derived from or relating to the Covered Code  * without prior written authorization from Intel.  *  * 4. Disclaimer and Export Compliance  *  * 4.1. INTEL MAKES NO WARRANTY OF ANY KIND REGARDING ANY SOFTWARE PROVIDED  * HERE.  ANY SOFTWARE ORIGINATING FROM INTEL OR DERIVED FROM INTEL SOFTWARE  * IS PROVIDED "AS IS," AND INTEL WILL NOT PROVIDE ANY SUPPORT,  ASSISTANCE,  * INSTALLATION, TRAINING OR OTHER SERVICES.  INTEL WILL NOT PROVIDE ANY  * UPDATES, ENHANCEMENTS OR EXTENSIONS.  INTEL SPECIFICALLY DISCLAIMS ANY  * IMPLIED WARRANTIES OF MERCHANTABILITY, NONINFRINGEMENT AND FITNESS FOR A  * PARTICULAR PURPOSE.  *  * 4.2. IN NO EVENT SHALL INTEL HAVE ANY LIABILITY TO LICENSEE, ITS LICENSEES  * OR ANY OTHER THIRD PARTY, FOR ANY LOST PROFITS, LOST DATA, LOSS OF USE OR  * COSTS OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, OR FOR ANY INDIRECT,  * SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THIS AGREEMENT, UNDER ANY  * CAUSE OF ACTION OR THEORY OF LIABILITY, AND IRRESPECTIVE OF WHETHER INTEL  * HAS ADVANCE NOTICE OF THE POSSIBILITY OF SUCH DAMAGES.  THESE LIMITATIONS  * SHALL APPLY NOTWITHSTANDING THE FAILURE OF THE ESSENTIAL PURPOSE OF ANY  * LIMITED REMEDY.  *  * 4.3. Licensee shall not export, either directly or indirectly, any of this  * software or system incorporating such software without first obtaining any  * required license or other approval from the U. S. Department of Commerce or  * any other agency or department of the United States Government.  In the  * event Licensee exports any such software from the United States or  * re-exports any such software from a foreign destination, Licensee shall  * ensure that the distribution and export/re-export of the software is in  * compliance with all laws, regulations, orders, or other restrictions of the  * U.S. Export Administration Regulations. Licensee agrees that neither it nor  * any of its subsidiaries will export/re-export any technical data, process,  * software, or service, directly or indirectly, to any country for which the  * United States government or any agency thereof requires an export license,  * other governmental approval, or letter of assurance, without first obtaining  * such license, approval or letter.  *  *****************************************************************************/
end_comment

begin_define
define|#
directive|define
name|__EXCONVRT_C__
end_define

begin_include
include|#
directive|include
file|<contrib/dev/acpica/acpi.h>
end_include

begin_include
include|#
directive|include
file|<contrib/dev/acpica/acinterp.h>
end_include

begin_include
include|#
directive|include
file|<contrib/dev/acpica/amlcode.h>
end_include

begin_define
define|#
directive|define
name|_COMPONENT
value|ACPI_EXECUTER
end_define

begin_macro
name|ACPI_MODULE_NAME
argument_list|(
literal|"exconvrt"
argument_list|)
end_macro

begin_comment
comment|/* Local prototypes */
end_comment

begin_function_decl
specifier|static
name|UINT32
name|AcpiExConvertToAscii
parameter_list|(
name|ACPI_INTEGER
name|Integer
parameter_list|,
name|UINT16
name|Base
parameter_list|,
name|UINT8
modifier|*
name|String
parameter_list|,
name|UINT8
name|MaxLength
parameter_list|)
function_decl|;
end_function_decl

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    AcpiExConvertToInteger  *  * PARAMETERS:  ObjDesc         - Object to be converted.  Must be an  *                                Integer, Buffer, or String  *              ResultDesc      - Where the new Integer object is returned  *              Flags           - Used for string conversion  *  * RETURN:      Status  *  * DESCRIPTION: Convert an ACPI Object to an integer.  *  ******************************************************************************/
end_comment

begin_function
name|ACPI_STATUS
name|AcpiExConvertToInteger
parameter_list|(
name|ACPI_OPERAND_OBJECT
modifier|*
name|ObjDesc
parameter_list|,
name|ACPI_OPERAND_OBJECT
modifier|*
modifier|*
name|ResultDesc
parameter_list|,
name|UINT32
name|Flags
parameter_list|)
block|{
name|ACPI_OPERAND_OBJECT
modifier|*
name|ReturnDesc
decl_stmt|;
name|UINT8
modifier|*
name|Pointer
decl_stmt|;
name|ACPI_INTEGER
name|Result
decl_stmt|;
name|UINT32
name|i
decl_stmt|;
name|UINT32
name|Count
decl_stmt|;
name|ACPI_STATUS
name|Status
decl_stmt|;
name|ACPI_FUNCTION_TRACE_PTR
argument_list|(
name|ExConvertToInteger
argument_list|,
name|ObjDesc
argument_list|)
expr_stmt|;
switch|switch
condition|(
name|ACPI_GET_OBJECT_TYPE
argument_list|(
name|ObjDesc
argument_list|)
condition|)
block|{
case|case
name|ACPI_TYPE_INTEGER
case|:
comment|/* No conversion necessary */
operator|*
name|ResultDesc
operator|=
name|ObjDesc
expr_stmt|;
name|return_ACPI_STATUS
argument_list|(
name|AE_OK
argument_list|)
expr_stmt|;
case|case
name|ACPI_TYPE_BUFFER
case|:
case|case
name|ACPI_TYPE_STRING
case|:
comment|/* Note: Takes advantage of common buffer/string fields */
name|Pointer
operator|=
name|ObjDesc
operator|->
name|Buffer
operator|.
name|Pointer
expr_stmt|;
name|Count
operator|=
name|ObjDesc
operator|->
name|Buffer
operator|.
name|Length
expr_stmt|;
break|break;
default|default:
name|return_ACPI_STATUS
argument_list|(
name|AE_TYPE
argument_list|)
expr_stmt|;
block|}
comment|/*      * Convert the buffer/string to an integer.  Note that both buffers and      * strings are treated as raw data - we don't convert ascii to hex for      * strings.      *      * There are two terminating conditions for the loop:      * 1) The size of an integer has been reached, or      * 2) The end of the buffer or string has been reached      */
name|Result
operator|=
literal|0
expr_stmt|;
comment|/* String conversion is different than Buffer conversion */
switch|switch
condition|(
name|ACPI_GET_OBJECT_TYPE
argument_list|(
name|ObjDesc
argument_list|)
condition|)
block|{
case|case
name|ACPI_TYPE_STRING
case|:
comment|/*          * Convert string to an integer - for most cases, the string must be          * hexadecimal as per the ACPI specification.  The only exception (as          * of ACPI 3.0) is that the ToInteger() operator allows both decimal          * and hexadecimal strings (hex prefixed with "0x").          */
name|Status
operator|=
name|AcpiUtStrtoul64
argument_list|(
operator|(
name|char
operator|*
operator|)
name|Pointer
argument_list|,
name|Flags
argument_list|,
operator|&
name|Result
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
break|break;
case|case
name|ACPI_TYPE_BUFFER
case|:
comment|/* Check for zero-length buffer */
if|if
condition|(
operator|!
name|Count
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|AE_AML_BUFFER_LIMIT
argument_list|)
expr_stmt|;
block|}
comment|/* Transfer no more than an integer's worth of data */
if|if
condition|(
name|Count
operator|>
name|AcpiGbl_IntegerByteWidth
condition|)
block|{
name|Count
operator|=
name|AcpiGbl_IntegerByteWidth
expr_stmt|;
block|}
comment|/*          * Convert buffer to an integer - we simply grab enough raw data          * from the buffer to fill an integer          */
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
name|Count
condition|;
name|i
operator|++
control|)
block|{
comment|/*              * Get next byte and shift it into the Result.              * Little endian is used, meaning that the first byte of the buffer              * is the LSB of the integer              */
name|Result
operator||=
operator|(
operator|(
operator|(
name|ACPI_INTEGER
operator|)
name|Pointer
index|[
name|i
index|]
operator|)
operator|<<
operator|(
name|i
operator|*
literal|8
operator|)
operator|)
expr_stmt|;
block|}
break|break;
default|default:
comment|/* No other types can get here */
break|break;
block|}
comment|/* Create a new integer */
name|ReturnDesc
operator|=
name|AcpiUtCreateInternalObject
argument_list|(
name|ACPI_TYPE_INTEGER
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|ReturnDesc
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|AE_NO_MEMORY
argument_list|)
expr_stmt|;
block|}
name|ACPI_DEBUG_PRINT
argument_list|(
operator|(
name|ACPI_DB_EXEC
operator|,
literal|"Converted value: %8.8X%8.8X\n"
operator|,
name|ACPI_FORMAT_UINT64
argument_list|(
name|Result
argument_list|)
operator|)
argument_list|)
expr_stmt|;
comment|/* Save the Result */
name|ReturnDesc
operator|->
name|Integer
operator|.
name|Value
operator|=
name|Result
expr_stmt|;
name|AcpiExTruncateFor32bitTable
argument_list|(
name|ReturnDesc
argument_list|)
expr_stmt|;
operator|*
name|ResultDesc
operator|=
name|ReturnDesc
expr_stmt|;
name|return_ACPI_STATUS
argument_list|(
name|AE_OK
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    AcpiExConvertToBuffer  *  * PARAMETERS:  ObjDesc         - Object to be converted.  Must be an  *                                Integer, Buffer, or String  *              ResultDesc      - Where the new buffer object is returned  *  * RETURN:      Status  *  * DESCRIPTION: Convert an ACPI Object to a Buffer  *  ******************************************************************************/
end_comment

begin_function
name|ACPI_STATUS
name|AcpiExConvertToBuffer
parameter_list|(
name|ACPI_OPERAND_OBJECT
modifier|*
name|ObjDesc
parameter_list|,
name|ACPI_OPERAND_OBJECT
modifier|*
modifier|*
name|ResultDesc
parameter_list|)
block|{
name|ACPI_OPERAND_OBJECT
modifier|*
name|ReturnDesc
decl_stmt|;
name|UINT8
modifier|*
name|NewBuf
decl_stmt|;
name|ACPI_FUNCTION_TRACE_PTR
argument_list|(
name|ExConvertToBuffer
argument_list|,
name|ObjDesc
argument_list|)
expr_stmt|;
switch|switch
condition|(
name|ACPI_GET_OBJECT_TYPE
argument_list|(
name|ObjDesc
argument_list|)
condition|)
block|{
case|case
name|ACPI_TYPE_BUFFER
case|:
comment|/* No conversion necessary */
operator|*
name|ResultDesc
operator|=
name|ObjDesc
expr_stmt|;
name|return_ACPI_STATUS
argument_list|(
name|AE_OK
argument_list|)
expr_stmt|;
case|case
name|ACPI_TYPE_INTEGER
case|:
comment|/*          * Create a new Buffer object.          * Need enough space for one integer          */
name|ReturnDesc
operator|=
name|AcpiUtCreateBufferObject
argument_list|(
name|AcpiGbl_IntegerByteWidth
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|ReturnDesc
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|AE_NO_MEMORY
argument_list|)
expr_stmt|;
block|}
comment|/* Copy the integer to the buffer, LSB first */
name|NewBuf
operator|=
name|ReturnDesc
operator|->
name|Buffer
operator|.
name|Pointer
expr_stmt|;
name|ACPI_MEMCPY
argument_list|(
name|NewBuf
argument_list|,
operator|&
name|ObjDesc
operator|->
name|Integer
operator|.
name|Value
argument_list|,
name|AcpiGbl_IntegerByteWidth
argument_list|)
expr_stmt|;
break|break;
case|case
name|ACPI_TYPE_STRING
case|:
comment|/*          * Create a new Buffer object          * Size will be the string length          *          * NOTE: Add one to the string length to include the null terminator.          * The ACPI spec is unclear on this subject, but there is existing          * ASL/AML code that depends on the null being transferred to the new          * buffer.          */
name|ReturnDesc
operator|=
name|AcpiUtCreateBufferObject
argument_list|(
operator|(
name|ACPI_SIZE
operator|)
name|ObjDesc
operator|->
name|String
operator|.
name|Length
operator|+
literal|1
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|ReturnDesc
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|AE_NO_MEMORY
argument_list|)
expr_stmt|;
block|}
comment|/* Copy the string to the buffer */
name|NewBuf
operator|=
name|ReturnDesc
operator|->
name|Buffer
operator|.
name|Pointer
expr_stmt|;
name|ACPI_STRNCPY
argument_list|(
operator|(
name|char
operator|*
operator|)
name|NewBuf
argument_list|,
operator|(
name|char
operator|*
operator|)
name|ObjDesc
operator|->
name|String
operator|.
name|Pointer
argument_list|,
name|ObjDesc
operator|->
name|String
operator|.
name|Length
argument_list|)
expr_stmt|;
break|break;
default|default:
name|return_ACPI_STATUS
argument_list|(
name|AE_TYPE
argument_list|)
expr_stmt|;
block|}
comment|/* Mark buffer initialized */
name|ReturnDesc
operator|->
name|Common
operator|.
name|Flags
operator||=
name|AOPOBJ_DATA_VALID
expr_stmt|;
operator|*
name|ResultDesc
operator|=
name|ReturnDesc
expr_stmt|;
name|return_ACPI_STATUS
argument_list|(
name|AE_OK
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    AcpiExConvertToAscii  *  * PARAMETERS:  Integer         - Value to be converted  *              Base            - ACPI_STRING_DECIMAL or ACPI_STRING_HEX  *              String          - Where the string is returned  *              DataWidth       - Size of data item to be converted, in bytes  *  * RETURN:      Actual string length  *  * DESCRIPTION: Convert an ACPI Integer to a hex or decimal string  *  ******************************************************************************/
end_comment

begin_function
specifier|static
name|UINT32
name|AcpiExConvertToAscii
parameter_list|(
name|ACPI_INTEGER
name|Integer
parameter_list|,
name|UINT16
name|Base
parameter_list|,
name|UINT8
modifier|*
name|String
parameter_list|,
name|UINT8
name|DataWidth
parameter_list|)
block|{
name|ACPI_INTEGER
name|Digit
decl_stmt|;
name|ACPI_NATIVE_UINT
name|i
decl_stmt|;
name|ACPI_NATIVE_UINT
name|j
decl_stmt|;
name|ACPI_NATIVE_UINT
name|k
init|=
literal|0
decl_stmt|;
name|ACPI_NATIVE_UINT
name|HexLength
decl_stmt|;
name|ACPI_NATIVE_UINT
name|DecimalLength
decl_stmt|;
name|UINT32
name|Remainder
decl_stmt|;
name|BOOLEAN
name|SupressZeros
decl_stmt|;
name|ACPI_FUNCTION_ENTRY
argument_list|()
expr_stmt|;
switch|switch
condition|(
name|Base
condition|)
block|{
case|case
literal|10
case|:
comment|/* Setup max length for the decimal number */
switch|switch
condition|(
name|DataWidth
condition|)
block|{
case|case
literal|1
case|:
name|DecimalLength
operator|=
name|ACPI_MAX8_DECIMAL_DIGITS
expr_stmt|;
break|break;
case|case
literal|4
case|:
name|DecimalLength
operator|=
name|ACPI_MAX32_DECIMAL_DIGITS
expr_stmt|;
break|break;
case|case
literal|8
case|:
default|default:
name|DecimalLength
operator|=
name|ACPI_MAX64_DECIMAL_DIGITS
expr_stmt|;
break|break;
block|}
name|SupressZeros
operator|=
name|TRUE
expr_stmt|;
comment|/* No leading zeros */
name|Remainder
operator|=
literal|0
expr_stmt|;
for|for
control|(
name|i
operator|=
name|DecimalLength
init|;
name|i
operator|>
literal|0
condition|;
name|i
operator|--
control|)
block|{
comment|/* Divide by nth factor of 10 */
name|Digit
operator|=
name|Integer
expr_stmt|;
for|for
control|(
name|j
operator|=
literal|0
init|;
name|j
operator|<
name|i
condition|;
name|j
operator|++
control|)
block|{
operator|(
name|void
operator|)
name|AcpiUtShortDivide
argument_list|(
name|Digit
argument_list|,
literal|10
argument_list|,
operator|&
name|Digit
argument_list|,
operator|&
name|Remainder
argument_list|)
expr_stmt|;
block|}
comment|/* Handle leading zeros */
if|if
condition|(
name|Remainder
operator|!=
literal|0
condition|)
block|{
name|SupressZeros
operator|=
name|FALSE
expr_stmt|;
block|}
if|if
condition|(
operator|!
name|SupressZeros
condition|)
block|{
name|String
index|[
name|k
index|]
operator|=
call|(
name|UINT8
call|)
argument_list|(
name|ACPI_ASCII_ZERO
operator|+
name|Remainder
argument_list|)
expr_stmt|;
name|k
operator|++
expr_stmt|;
block|}
block|}
break|break;
case|case
literal|16
case|:
comment|/* HexLength: 2 ascii hex chars per data byte */
name|HexLength
operator|=
operator|(
name|ACPI_NATIVE_UINT
operator|)
name|ACPI_MUL_2
argument_list|(
name|DataWidth
argument_list|)
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
operator|,
name|j
operator|=
operator|(
name|HexLength
operator|-
literal|1
operator|)
init|;
name|i
operator|<
name|HexLength
condition|;
name|i
operator|++
operator|,
name|j
operator|--
control|)
block|{
comment|/* Get one hex digit, most significant digits first */
name|String
index|[
name|k
index|]
operator|=
operator|(
name|UINT8
operator|)
name|AcpiUtHexToAsciiChar
argument_list|(
name|Integer
argument_list|,
name|ACPI_MUL_4
argument_list|(
name|j
argument_list|)
argument_list|)
expr_stmt|;
name|k
operator|++
expr_stmt|;
block|}
break|break;
default|default:
return|return
operator|(
literal|0
operator|)
return|;
block|}
comment|/*      * Since leading zeros are supressed, we must check for the case where      * the integer equals 0      *      * Finally, null terminate the string and return the length      */
if|if
condition|(
operator|!
name|k
condition|)
block|{
name|String
index|[
literal|0
index|]
operator|=
name|ACPI_ASCII_ZERO
expr_stmt|;
name|k
operator|=
literal|1
expr_stmt|;
block|}
name|String
index|[
name|k
index|]
operator|=
literal|0
expr_stmt|;
return|return
operator|(
operator|(
name|UINT32
operator|)
name|k
operator|)
return|;
block|}
end_function

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    AcpiExConvertToString  *  * PARAMETERS:  ObjDesc         - Object to be converted.  Must be an  *                                Integer, Buffer, or String  *              ResultDesc      - Where the string object is returned  *              Type            - String flags (base and conversion type)  *  * RETURN:      Status  *  * DESCRIPTION: Convert an ACPI Object to a string  *  ******************************************************************************/
end_comment

begin_function
name|ACPI_STATUS
name|AcpiExConvertToString
parameter_list|(
name|ACPI_OPERAND_OBJECT
modifier|*
name|ObjDesc
parameter_list|,
name|ACPI_OPERAND_OBJECT
modifier|*
modifier|*
name|ResultDesc
parameter_list|,
name|UINT32
name|Type
parameter_list|)
block|{
name|ACPI_OPERAND_OBJECT
modifier|*
name|ReturnDesc
decl_stmt|;
name|UINT8
modifier|*
name|NewBuf
decl_stmt|;
name|UINT32
name|i
decl_stmt|;
name|UINT32
name|StringLength
init|=
literal|0
decl_stmt|;
name|UINT16
name|Base
init|=
literal|16
decl_stmt|;
name|UINT8
name|Separator
init|=
literal|','
decl_stmt|;
name|ACPI_FUNCTION_TRACE_PTR
argument_list|(
name|ExConvertToString
argument_list|,
name|ObjDesc
argument_list|)
expr_stmt|;
switch|switch
condition|(
name|ACPI_GET_OBJECT_TYPE
argument_list|(
name|ObjDesc
argument_list|)
condition|)
block|{
case|case
name|ACPI_TYPE_STRING
case|:
comment|/* No conversion necessary */
operator|*
name|ResultDesc
operator|=
name|ObjDesc
expr_stmt|;
name|return_ACPI_STATUS
argument_list|(
name|AE_OK
argument_list|)
expr_stmt|;
case|case
name|ACPI_TYPE_INTEGER
case|:
switch|switch
condition|(
name|Type
condition|)
block|{
case|case
name|ACPI_EXPLICIT_CONVERT_DECIMAL
case|:
comment|/* Make room for maximum decimal number */
name|StringLength
operator|=
name|ACPI_MAX_DECIMAL_DIGITS
expr_stmt|;
name|Base
operator|=
literal|10
expr_stmt|;
break|break;
default|default:
comment|/* Two hex string characters for each integer byte */
name|StringLength
operator|=
name|ACPI_MUL_2
argument_list|(
name|AcpiGbl_IntegerByteWidth
argument_list|)
expr_stmt|;
break|break;
block|}
comment|/*          * Create a new String          * Need enough space for one ASCII integer (plus null terminator)          */
name|ReturnDesc
operator|=
name|AcpiUtCreateStringObject
argument_list|(
operator|(
name|ACPI_SIZE
operator|)
name|StringLength
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|ReturnDesc
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|AE_NO_MEMORY
argument_list|)
expr_stmt|;
block|}
name|NewBuf
operator|=
name|ReturnDesc
operator|->
name|Buffer
operator|.
name|Pointer
expr_stmt|;
comment|/* Convert integer to string */
name|StringLength
operator|=
name|AcpiExConvertToAscii
argument_list|(
name|ObjDesc
operator|->
name|Integer
operator|.
name|Value
argument_list|,
name|Base
argument_list|,
name|NewBuf
argument_list|,
name|AcpiGbl_IntegerByteWidth
argument_list|)
expr_stmt|;
comment|/* Null terminate at the correct place */
name|ReturnDesc
operator|->
name|String
operator|.
name|Length
operator|=
name|StringLength
expr_stmt|;
name|NewBuf
index|[
name|StringLength
index|]
operator|=
literal|0
expr_stmt|;
break|break;
case|case
name|ACPI_TYPE_BUFFER
case|:
comment|/* Setup string length, base, and separator */
switch|switch
condition|(
name|Type
condition|)
block|{
case|case
name|ACPI_EXPLICIT_CONVERT_DECIMAL
case|:
comment|/* Used by ToDecimalString */
comment|/*              * From ACPI: "If Data is a buffer, it is converted to a string of              * decimal values separated by commas."              */
name|Base
operator|=
literal|10
expr_stmt|;
comment|/*              * Calculate the final string length.  Individual string values              * are variable length (include separator for each)              */
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
name|ObjDesc
operator|->
name|Buffer
operator|.
name|Length
condition|;
name|i
operator|++
control|)
block|{
if|if
condition|(
name|ObjDesc
operator|->
name|Buffer
operator|.
name|Pointer
index|[
name|i
index|]
operator|>=
literal|100
condition|)
block|{
name|StringLength
operator|+=
literal|4
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|ObjDesc
operator|->
name|Buffer
operator|.
name|Pointer
index|[
name|i
index|]
operator|>=
literal|10
condition|)
block|{
name|StringLength
operator|+=
literal|3
expr_stmt|;
block|}
else|else
block|{
name|StringLength
operator|+=
literal|2
expr_stmt|;
block|}
block|}
break|break;
case|case
name|ACPI_IMPLICIT_CONVERT_HEX
case|:
comment|/*              * From the ACPI spec:              *"The entire contents of the buffer are converted to a string of              * two-character hexadecimal numbers, each separated by a space."              */
name|Separator
operator|=
literal|' '
expr_stmt|;
name|StringLength
operator|=
operator|(
name|ObjDesc
operator|->
name|Buffer
operator|.
name|Length
operator|*
literal|3
operator|)
expr_stmt|;
break|break;
case|case
name|ACPI_EXPLICIT_CONVERT_HEX
case|:
comment|/* Used by ToHexString */
comment|/*              * From ACPI: "If Data is a buffer, it is converted to a string of              * hexadecimal values separated by commas."              */
name|StringLength
operator|=
operator|(
name|ObjDesc
operator|->
name|Buffer
operator|.
name|Length
operator|*
literal|3
operator|)
expr_stmt|;
break|break;
default|default:
name|return_ACPI_STATUS
argument_list|(
name|AE_BAD_PARAMETER
argument_list|)
expr_stmt|;
block|}
comment|/*          * Create a new string object and string buffer          * (-1 because of extra separator included in StringLength from above)          */
name|ReturnDesc
operator|=
name|AcpiUtCreateStringObject
argument_list|(
call|(
name|ACPI_SIZE
call|)
argument_list|(
name|StringLength
operator|-
literal|1
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|ReturnDesc
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|AE_NO_MEMORY
argument_list|)
expr_stmt|;
block|}
name|NewBuf
operator|=
name|ReturnDesc
operator|->
name|Buffer
operator|.
name|Pointer
expr_stmt|;
comment|/*          * Convert buffer bytes to hex or decimal values          * (separated by commas or spaces)          */
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
name|ObjDesc
operator|->
name|Buffer
operator|.
name|Length
condition|;
name|i
operator|++
control|)
block|{
name|NewBuf
operator|+=
name|AcpiExConvertToAscii
argument_list|(
operator|(
name|ACPI_INTEGER
operator|)
name|ObjDesc
operator|->
name|Buffer
operator|.
name|Pointer
index|[
name|i
index|]
argument_list|,
name|Base
argument_list|,
name|NewBuf
argument_list|,
literal|1
argument_list|)
expr_stmt|;
operator|*
name|NewBuf
operator|++
operator|=
name|Separator
expr_stmt|;
comment|/* each separated by a comma or space */
block|}
comment|/*          * Null terminate the string          * (overwrites final comma/space from above)          */
name|NewBuf
operator|--
expr_stmt|;
operator|*
name|NewBuf
operator|=
literal|0
expr_stmt|;
break|break;
default|default:
name|return_ACPI_STATUS
argument_list|(
name|AE_TYPE
argument_list|)
expr_stmt|;
block|}
operator|*
name|ResultDesc
operator|=
name|ReturnDesc
expr_stmt|;
name|return_ACPI_STATUS
argument_list|(
name|AE_OK
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    AcpiExConvertToTargetType  *  * PARAMETERS:  DestinationType     - Current type of the destination  *              SourceDesc          - Source object to be converted.  *              ResultDesc          - Where the converted object is returned  *              WalkState           - Current method state  *  * RETURN:      Status  *  * DESCRIPTION: Implements "implicit conversion" rules for storing an object.  *  ******************************************************************************/
end_comment

begin_function
name|ACPI_STATUS
name|AcpiExConvertToTargetType
parameter_list|(
name|ACPI_OBJECT_TYPE
name|DestinationType
parameter_list|,
name|ACPI_OPERAND_OBJECT
modifier|*
name|SourceDesc
parameter_list|,
name|ACPI_OPERAND_OBJECT
modifier|*
modifier|*
name|ResultDesc
parameter_list|,
name|ACPI_WALK_STATE
modifier|*
name|WalkState
parameter_list|)
block|{
name|ACPI_STATUS
name|Status
init|=
name|AE_OK
decl_stmt|;
name|ACPI_FUNCTION_TRACE
argument_list|(
name|ExConvertToTargetType
argument_list|)
expr_stmt|;
comment|/* Default behavior */
operator|*
name|ResultDesc
operator|=
name|SourceDesc
expr_stmt|;
comment|/*      * If required by the target,      * perform implicit conversion on the source before we store it.      */
switch|switch
condition|(
name|GET_CURRENT_ARG_TYPE
argument_list|(
name|WalkState
operator|->
name|OpInfo
operator|->
name|RuntimeArgs
argument_list|)
condition|)
block|{
case|case
name|ARGI_SIMPLE_TARGET
case|:
case|case
name|ARGI_FIXED_TARGET
case|:
case|case
name|ARGI_INTEGER_REF
case|:
comment|/* Handles Increment, Decrement cases */
switch|switch
condition|(
name|DestinationType
condition|)
block|{
case|case
name|ACPI_TYPE_LOCAL_REGION_FIELD
case|:
comment|/*              * Named field can always handle conversions              */
break|break;
default|default:
comment|/* No conversion allowed for these types */
if|if
condition|(
name|DestinationType
operator|!=
name|ACPI_GET_OBJECT_TYPE
argument_list|(
name|SourceDesc
argument_list|)
condition|)
block|{
name|ACPI_DEBUG_PRINT
argument_list|(
operator|(
name|ACPI_DB_INFO
operator|,
literal|"Explicit operator, will store (%s) over existing type (%s)\n"
operator|,
name|AcpiUtGetObjectTypeName
argument_list|(
name|SourceDesc
argument_list|)
operator|,
name|AcpiUtGetTypeName
argument_list|(
name|DestinationType
argument_list|)
operator|)
argument_list|)
expr_stmt|;
name|Status
operator|=
name|AE_TYPE
expr_stmt|;
block|}
block|}
break|break;
case|case
name|ARGI_TARGETREF
case|:
switch|switch
condition|(
name|DestinationType
condition|)
block|{
case|case
name|ACPI_TYPE_INTEGER
case|:
case|case
name|ACPI_TYPE_BUFFER_FIELD
case|:
case|case
name|ACPI_TYPE_LOCAL_BANK_FIELD
case|:
case|case
name|ACPI_TYPE_LOCAL_INDEX_FIELD
case|:
comment|/*              * These types require an Integer operand.  We can convert              * a Buffer or a String to an Integer if necessary.              */
name|Status
operator|=
name|AcpiExConvertToInteger
argument_list|(
name|SourceDesc
argument_list|,
name|ResultDesc
argument_list|,
literal|16
argument_list|)
expr_stmt|;
break|break;
case|case
name|ACPI_TYPE_STRING
case|:
comment|/*              * The operand must be a String.  We can convert an              * Integer or Buffer if necessary              */
name|Status
operator|=
name|AcpiExConvertToString
argument_list|(
name|SourceDesc
argument_list|,
name|ResultDesc
argument_list|,
name|ACPI_IMPLICIT_CONVERT_HEX
argument_list|)
expr_stmt|;
break|break;
case|case
name|ACPI_TYPE_BUFFER
case|:
comment|/*              * The operand must be a Buffer.  We can convert an              * Integer or String if necessary              */
name|Status
operator|=
name|AcpiExConvertToBuffer
argument_list|(
name|SourceDesc
argument_list|,
name|ResultDesc
argument_list|)
expr_stmt|;
break|break;
default|default:
name|ACPI_ERROR
argument_list|(
operator|(
name|AE_INFO
operator|,
literal|"Bad destination type during conversion: %X"
operator|,
name|DestinationType
operator|)
argument_list|)
expr_stmt|;
name|Status
operator|=
name|AE_AML_INTERNAL
expr_stmt|;
break|break;
block|}
break|break;
case|case
name|ARGI_REFERENCE
case|:
comment|/*          * CreateXxxxField cases - we are storing the field object into the name          */
break|break;
default|default:
name|ACPI_ERROR
argument_list|(
operator|(
name|AE_INFO
operator|,
literal|"Unknown Target type ID 0x%X AmlOpcode %X DestType %s"
operator|,
name|GET_CURRENT_ARG_TYPE
argument_list|(
name|WalkState
operator|->
name|OpInfo
operator|->
name|RuntimeArgs
argument_list|)
operator|,
name|WalkState
operator|->
name|Opcode
operator|,
name|AcpiUtGetTypeName
argument_list|(
name|DestinationType
argument_list|)
operator|)
argument_list|)
expr_stmt|;
name|Status
operator|=
name|AE_AML_INTERNAL
expr_stmt|;
block|}
comment|/*      * Source-to-Target conversion semantics:      *      * If conversion to the target type cannot be performed, then simply      * overwrite the target with the new object and type.      */
if|if
condition|(
name|Status
operator|==
name|AE_TYPE
condition|)
block|{
name|Status
operator|=
name|AE_OK
expr_stmt|;
block|}
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
end_function

end_unit

