begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/******************************************************************************  *  * Name: hwsleep.c - ACPI Hardware Sleep/Wake Interface  *              $Revision: 1.87 $  *  *****************************************************************************/
end_comment

begin_comment
comment|/******************************************************************************  *  * 1. Copyright Notice  *  * Some or all of this work - Copyright (c) 1999 - 2007, Intel Corp.  * All rights reserved.  *  * 2. License  *  * 2.1. This is your license from Intel Corp. under its intellectual property  * rights.  You may have additional license terms from the party that provided  * you this software, covering your right to use that party's intellectual  * property rights.  *  * 2.2. Intel grants, free of charge, to any person ("Licensee") obtaining a  * copy of the source code appearing in this file ("Covered Code") an  * irrevocable, perpetual, worldwide license under Intel's copyrights in the  * base code distributed originally by Intel ("Original Intel Code") to copy,  * make derivatives, distribute, use and display any portion of the Covered  * Code in any form, with the right to sublicense such rights; and  *  * 2.3. Intel grants Licensee a non-exclusive and non-transferable patent  * license (with the right to sublicense), under only those claims of Intel  * patents that are infringed by the Original Intel Code, to make, use, sell,  * offer to sell, and import the Covered Code and derivative works thereof  * solely to the minimum extent necessary to exercise the above copyright  * license, and in no event shall the patent license extend to any additions  * to or modifications of the Original Intel Code.  No other license or right  * is granted directly or by implication, estoppel or otherwise;  *  * The above copyright and patent license is granted only if the following  * conditions are met:  *  * 3. Conditions  *  * 3.1. Redistribution of Source with Rights to Further Distribute Source.  * Redistribution of source code of any substantial portion of the Covered  * Code or modification with rights to further distribute source must include  * the above Copyright Notice, the above License, this list of Conditions,  * and the following Disclaimer and Export Compliance provision.  In addition,  * Licensee must cause all Covered Code to which Licensee contributes to  * contain a file documenting the changes Licensee made to create that Covered  * Code and the date of any change.  Licensee must include in that file the  * documentation of any changes made by any predecessor Licensee.  Licensee  * must include a prominent statement that the modification is derived,  * directly or indirectly, from Original Intel Code.  *  * 3.2. Redistribution of Source with no Rights to Further Distribute Source.  * Redistribution of source code of any substantial portion of the Covered  * Code or modification without rights to further distribute source must  * include the following Disclaimer and Export Compliance provision in the  * documentation and/or other materials provided with distribution.  In  * addition, Licensee may not authorize further sublicense of source of any  * portion of the Covered Code, and must include terms to the effect that the  * license from Licensee to its licensee is limited to the intellectual  * property embodied in the software Licensee provides to its licensee, and  * not to intellectual property embodied in modifications its licensee may  * make.  *  * 3.3. Redistribution of Executable. Redistribution in executable form of any  * substantial portion of the Covered Code or modification must reproduce the  * above Copyright Notice, and the following Disclaimer and Export Compliance  * provision in the documentation and/or other materials provided with the  * distribution.  *  * 3.4. Intel retains all right, title, and interest in and to the Original  * Intel Code.  *  * 3.5. Neither the name Intel nor any other trademark owned or controlled by  * Intel shall be used in advertising or otherwise to promote the sale, use or  * other dealings in products derived from or relating to the Covered Code  * without prior written authorization from Intel.  *  * 4. Disclaimer and Export Compliance  *  * 4.1. INTEL MAKES NO WARRANTY OF ANY KIND REGARDING ANY SOFTWARE PROVIDED  * HERE.  ANY SOFTWARE ORIGINATING FROM INTEL OR DERIVED FROM INTEL SOFTWARE  * IS PROVIDED "AS IS," AND INTEL WILL NOT PROVIDE ANY SUPPORT,  ASSISTANCE,  * INSTALLATION, TRAINING OR OTHER SERVICES.  INTEL WILL NOT PROVIDE ANY  * UPDATES, ENHANCEMENTS OR EXTENSIONS.  INTEL SPECIFICALLY DISCLAIMS ANY  * IMPLIED WARRANTIES OF MERCHANTABILITY, NONINFRINGEMENT AND FITNESS FOR A  * PARTICULAR PURPOSE.  *  * 4.2. IN NO EVENT SHALL INTEL HAVE ANY LIABILITY TO LICENSEE, ITS LICENSEES  * OR ANY OTHER THIRD PARTY, FOR ANY LOST PROFITS, LOST DATA, LOSS OF USE OR  * COSTS OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, OR FOR ANY INDIRECT,  * SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THIS AGREEMENT, UNDER ANY  * CAUSE OF ACTION OR THEORY OF LIABILITY, AND IRRESPECTIVE OF WHETHER INTEL  * HAS ADVANCE NOTICE OF THE POSSIBILITY OF SUCH DAMAGES.  THESE LIMITATIONS  * SHALL APPLY NOTWITHSTANDING THE FAILURE OF THE ESSENTIAL PURPOSE OF ANY  * LIMITED REMEDY.  *  * 4.3. Licensee shall not export, either directly or indirectly, any of this  * software or system incorporating such software without first obtaining any  * required license or other approval from the U. S. Department of Commerce or  * any other agency or department of the United States Government.  In the  * event Licensee exports any such software from the United States or  * re-exports any such software from a foreign destination, Licensee shall  * ensure that the distribution and export/re-export of the software is in  * compliance with all laws, regulations, orders, or other restrictions of the  * U.S. Export Administration Regulations. Licensee agrees that neither it nor  * any of its subsidiaries will export/re-export any technical data, process,  * software, or service, directly or indirectly, to any country for which the  * United States government or any agency thereof requires an export license,  * other governmental approval, or letter of assurance, without first obtaining  * such license, approval or letter.  *  *****************************************************************************/
end_comment

begin_include
include|#
directive|include
file|<contrib/dev/acpica/acpi.h>
end_include

begin_include
include|#
directive|include
file|<contrib/dev/acpica/actables.h>
end_include

begin_define
define|#
directive|define
name|_COMPONENT
value|ACPI_HARDWARE
end_define

begin_macro
name|ACPI_MODULE_NAME
argument_list|(
literal|"hwsleep"
argument_list|)
end_macro

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    AcpiSetFirmwareWakingVector  *  * PARAMETERS:  PhysicalAddress     - Physical address of ACPI real mode  *                                    entry point.  *  * RETURN:      Status  *  * DESCRIPTION: Access function for the FirmwareWakingVector field in FACS  *  ******************************************************************************/
end_comment

begin_function
name|ACPI_STATUS
name|AcpiSetFirmwareWakingVector
parameter_list|(
name|ACPI_PHYSICAL_ADDRESS
name|PhysicalAddress
parameter_list|)
block|{
name|ACPI_TABLE_FACS
modifier|*
name|Facs
decl_stmt|;
name|ACPI_STATUS
name|Status
decl_stmt|;
name|ACPI_FUNCTION_TRACE
argument_list|(
name|AcpiSetFirmwareWakingVector
argument_list|)
expr_stmt|;
comment|/* Get the FACS */
name|Status
operator|=
name|AcpiGetTableByIndex
argument_list|(
name|ACPI_TABLE_INDEX_FACS
argument_list|,
operator|(
name|ACPI_TABLE_HEADER
operator|*
operator|*
operator|)
operator|&
name|Facs
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
comment|/* Set the vector */
if|if
condition|(
operator|(
name|Facs
operator|->
name|Length
operator|<
literal|32
operator|)
operator|||
operator|(
operator|!
operator|(
name|Facs
operator|->
name|XFirmwareWakingVector
operator|)
operator|)
condition|)
block|{
comment|/*          * ACPI 1.0 FACS or short table or optional X_ field is zero          */
name|Facs
operator|->
name|FirmwareWakingVector
operator|=
operator|(
name|UINT32
operator|)
name|PhysicalAddress
expr_stmt|;
block|}
else|else
block|{
comment|/*          * ACPI 2.0 FACS with valid X_ field          */
name|Facs
operator|->
name|XFirmwareWakingVector
operator|=
name|PhysicalAddress
expr_stmt|;
block|}
name|return_ACPI_STATUS
argument_list|(
name|AE_OK
argument_list|)
expr_stmt|;
block|}
end_function

begin_macro
name|ACPI_EXPORT_SYMBOL
argument_list|(
argument|AcpiSetFirmwareWakingVector
argument_list|)
end_macro

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    AcpiGetFirmwareWakingVector  *  * PARAMETERS:  *PhysicalAddress    - Where the contents of  *                                    the FirmwareWakingVector field of  *                                    the FACS will be returned.  *  * RETURN:      Status, vector  *  * DESCRIPTION: Access function for the FirmwareWakingVector field in FACS  *  ******************************************************************************/
end_comment

begin_function
name|ACPI_STATUS
name|AcpiGetFirmwareWakingVector
parameter_list|(
name|ACPI_PHYSICAL_ADDRESS
modifier|*
name|PhysicalAddress
parameter_list|)
block|{
name|ACPI_TABLE_FACS
modifier|*
name|Facs
decl_stmt|;
name|ACPI_STATUS
name|Status
decl_stmt|;
name|ACPI_FUNCTION_TRACE
argument_list|(
name|AcpiGetFirmwareWakingVector
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|PhysicalAddress
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|AE_BAD_PARAMETER
argument_list|)
expr_stmt|;
block|}
comment|/* Get the FACS */
name|Status
operator|=
name|AcpiGetTableByIndex
argument_list|(
name|ACPI_TABLE_INDEX_FACS
argument_list|,
operator|(
name|ACPI_TABLE_HEADER
operator|*
operator|*
operator|)
operator|&
name|Facs
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
comment|/* Get the vector */
if|if
condition|(
operator|(
name|Facs
operator|->
name|Length
operator|<
literal|32
operator|)
operator|||
operator|(
operator|!
operator|(
name|Facs
operator|->
name|XFirmwareWakingVector
operator|)
operator|)
condition|)
block|{
comment|/*          * ACPI 1.0 FACS or short table or optional X_ field is zero          */
operator|*
name|PhysicalAddress
operator|=
operator|(
name|ACPI_PHYSICAL_ADDRESS
operator|)
name|Facs
operator|->
name|FirmwareWakingVector
expr_stmt|;
block|}
else|else
block|{
comment|/*          * ACPI 2.0 FACS with valid X_ field          */
operator|*
name|PhysicalAddress
operator|=
operator|(
name|ACPI_PHYSICAL_ADDRESS
operator|)
name|Facs
operator|->
name|XFirmwareWakingVector
expr_stmt|;
block|}
name|return_ACPI_STATUS
argument_list|(
name|AE_OK
argument_list|)
expr_stmt|;
block|}
end_function

begin_macro
name|ACPI_EXPORT_SYMBOL
argument_list|(
argument|AcpiGetFirmwareWakingVector
argument_list|)
end_macro

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    AcpiEnterSleepStatePrep  *  * PARAMETERS:  SleepState          - Which sleep state to enter  *  * RETURN:      Status  *  * DESCRIPTION: Prepare to enter a system sleep state (see ACPI 2.0 spec p 231)  *              This function must execute with interrupts enabled.  *              We break sleeping into 2 stages so that OSPM can handle  *              various OS-specific tasks between the two steps.  *  ******************************************************************************/
end_comment

begin_function
name|ACPI_STATUS
name|AcpiEnterSleepStatePrep
parameter_list|(
name|UINT8
name|SleepState
parameter_list|)
block|{
name|ACPI_STATUS
name|Status
decl_stmt|;
name|ACPI_OBJECT_LIST
name|ArgList
decl_stmt|;
name|ACPI_OBJECT
name|Arg
decl_stmt|;
name|ACPI_FUNCTION_TRACE
argument_list|(
name|AcpiEnterSleepStatePrep
argument_list|)
expr_stmt|;
comment|/*      * _PSW methods could be run here to enable wake-on keyboard, LAN, etc.      */
name|Status
operator|=
name|AcpiGetSleepTypeData
argument_list|(
name|SleepState
argument_list|,
operator|&
name|AcpiGbl_SleepTypeA
argument_list|,
operator|&
name|AcpiGbl_SleepTypeB
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
comment|/* Setup parameter object */
name|ArgList
operator|.
name|Count
operator|=
literal|1
expr_stmt|;
name|ArgList
operator|.
name|Pointer
operator|=
operator|&
name|Arg
expr_stmt|;
name|Arg
operator|.
name|Type
operator|=
name|ACPI_TYPE_INTEGER
expr_stmt|;
name|Arg
operator|.
name|Integer
operator|.
name|Value
operator|=
name|SleepState
expr_stmt|;
comment|/* Run the _PTS and _GTS methods */
name|Status
operator|=
name|AcpiEvaluateObject
argument_list|(
name|NULL
argument_list|,
name|METHOD_NAME__PTS
argument_list|,
operator|&
name|ArgList
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
operator|&&
name|Status
operator|!=
name|AE_NOT_FOUND
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
name|Status
operator|=
name|AcpiEvaluateObject
argument_list|(
name|NULL
argument_list|,
name|METHOD_NAME__GTS
argument_list|,
operator|&
name|ArgList
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
operator|&&
name|Status
operator|!=
name|AE_NOT_FOUND
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
comment|/* Setup the argument to _SST */
switch|switch
condition|(
name|SleepState
condition|)
block|{
case|case
name|ACPI_STATE_S0
case|:
name|Arg
operator|.
name|Integer
operator|.
name|Value
operator|=
name|ACPI_SST_WORKING
expr_stmt|;
break|break;
case|case
name|ACPI_STATE_S1
case|:
case|case
name|ACPI_STATE_S2
case|:
case|case
name|ACPI_STATE_S3
case|:
name|Arg
operator|.
name|Integer
operator|.
name|Value
operator|=
name|ACPI_SST_SLEEPING
expr_stmt|;
break|break;
case|case
name|ACPI_STATE_S4
case|:
name|Arg
operator|.
name|Integer
operator|.
name|Value
operator|=
name|ACPI_SST_SLEEP_CONTEXT
expr_stmt|;
break|break;
default|default:
name|Arg
operator|.
name|Integer
operator|.
name|Value
operator|=
name|ACPI_SST_INDICATOR_OFF
expr_stmt|;
comment|/* Default is off */
break|break;
block|}
comment|/* Set the system indicators to show the desired sleep state. */
name|Status
operator|=
name|AcpiEvaluateObject
argument_list|(
name|NULL
argument_list|,
name|METHOD_NAME__SST
argument_list|,
operator|&
name|ArgList
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
operator|&&
name|Status
operator|!=
name|AE_NOT_FOUND
condition|)
block|{
name|ACPI_EXCEPTION
argument_list|(
operator|(
name|AE_INFO
operator|,
name|Status
operator|,
literal|"While executing method _SST"
operator|)
argument_list|)
expr_stmt|;
block|}
name|return_ACPI_STATUS
argument_list|(
name|AE_OK
argument_list|)
expr_stmt|;
block|}
end_function

begin_macro
name|ACPI_EXPORT_SYMBOL
argument_list|(
argument|AcpiEnterSleepStatePrep
argument_list|)
end_macro

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    AcpiEnterSleepState  *  * PARAMETERS:  SleepState          - Which sleep state to enter  *  * RETURN:      Status  *  * DESCRIPTION: Enter a system sleep state (see ACPI 2.0 spec p 231)  *              THIS FUNCTION MUST BE CALLED WITH INTERRUPTS DISABLED  *  ******************************************************************************/
end_comment

begin_function
name|ACPI_STATUS
name|AcpiEnterSleepState
parameter_list|(
name|UINT8
name|SleepState
parameter_list|)
block|{
name|UINT32
name|PM1AControl
decl_stmt|;
name|UINT32
name|PM1BControl
decl_stmt|;
name|ACPI_BIT_REGISTER_INFO
modifier|*
name|SleepTypeRegInfo
decl_stmt|;
name|ACPI_BIT_REGISTER_INFO
modifier|*
name|SleepEnableRegInfo
decl_stmt|;
name|UINT32
name|InValue
decl_stmt|;
name|ACPI_STATUS
name|Status
decl_stmt|;
name|ACPI_FUNCTION_TRACE
argument_list|(
name|AcpiEnterSleepState
argument_list|)
expr_stmt|;
if|if
condition|(
operator|(
name|AcpiGbl_SleepTypeA
operator|>
name|ACPI_SLEEP_TYPE_MAX
operator|)
operator|||
operator|(
name|AcpiGbl_SleepTypeB
operator|>
name|ACPI_SLEEP_TYPE_MAX
operator|)
condition|)
block|{
name|ACPI_ERROR
argument_list|(
operator|(
name|AE_INFO
operator|,
literal|"Sleep values out of range: A=%X B=%X"
operator|,
name|AcpiGbl_SleepTypeA
operator|,
name|AcpiGbl_SleepTypeB
operator|)
argument_list|)
expr_stmt|;
name|return_ACPI_STATUS
argument_list|(
name|AE_AML_OPERAND_VALUE
argument_list|)
expr_stmt|;
block|}
name|SleepTypeRegInfo
operator|=
name|AcpiHwGetBitRegisterInfo
argument_list|(
name|ACPI_BITREG_SLEEP_TYPE_A
argument_list|)
expr_stmt|;
name|SleepEnableRegInfo
operator|=
name|AcpiHwGetBitRegisterInfo
argument_list|(
name|ACPI_BITREG_SLEEP_ENABLE
argument_list|)
expr_stmt|;
comment|/* Clear wake status */
name|Status
operator|=
name|AcpiSetRegister
argument_list|(
name|ACPI_BITREG_WAKE_STATUS
argument_list|,
literal|1
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
comment|/* Clear all fixed and general purpose status bits */
name|Status
operator|=
name|AcpiHwClearAcpiStatus
argument_list|()
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|SleepState
operator|!=
name|ACPI_STATE_S5
condition|)
block|{
comment|/* Disable BM arbitration */
name|Status
operator|=
name|AcpiSetRegister
argument_list|(
name|ACPI_BITREG_ARB_DISABLE
argument_list|,
literal|1
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
block|}
comment|/*      * 1) Disable/Clear all GPEs      * 2) Enable all wakeup GPEs      */
name|Status
operator|=
name|AcpiHwDisableAllGpes
argument_list|()
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
name|AcpiGbl_SystemAwakeAndRunning
operator|=
name|FALSE
expr_stmt|;
name|Status
operator|=
name|AcpiHwEnableAllWakeupGpes
argument_list|()
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
comment|/* Get current value of PM1A control */
name|Status
operator|=
name|AcpiHwRegisterRead
argument_list|(
name|ACPI_MTX_DO_NOT_LOCK
argument_list|,
name|ACPI_REGISTER_PM1_CONTROL
argument_list|,
operator|&
name|PM1AControl
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
name|ACPI_DEBUG_PRINT
argument_list|(
operator|(
name|ACPI_DB_INIT
operator|,
literal|"Entering sleep state [S%d]\n"
operator|,
name|SleepState
operator|)
argument_list|)
expr_stmt|;
comment|/* Clear SLP_EN and SLP_TYP fields */
name|PM1AControl
operator|&=
operator|~
operator|(
name|SleepTypeRegInfo
operator|->
name|AccessBitMask
operator||
name|SleepEnableRegInfo
operator|->
name|AccessBitMask
operator|)
expr_stmt|;
name|PM1BControl
operator|=
name|PM1AControl
expr_stmt|;
comment|/* Insert SLP_TYP bits */
name|PM1AControl
operator||=
operator|(
name|AcpiGbl_SleepTypeA
operator|<<
name|SleepTypeRegInfo
operator|->
name|BitPosition
operator|)
expr_stmt|;
name|PM1BControl
operator||=
operator|(
name|AcpiGbl_SleepTypeB
operator|<<
name|SleepTypeRegInfo
operator|->
name|BitPosition
operator|)
expr_stmt|;
comment|/*      * We split the writes of SLP_TYP and SLP_EN to workaround      * poorly implemented hardware.      */
comment|/* Write #1: fill in SLP_TYP data */
name|Status
operator|=
name|AcpiHwRegisterWrite
argument_list|(
name|ACPI_MTX_DO_NOT_LOCK
argument_list|,
name|ACPI_REGISTER_PM1A_CONTROL
argument_list|,
name|PM1AControl
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
name|Status
operator|=
name|AcpiHwRegisterWrite
argument_list|(
name|ACPI_MTX_DO_NOT_LOCK
argument_list|,
name|ACPI_REGISTER_PM1B_CONTROL
argument_list|,
name|PM1BControl
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
comment|/* Insert SLP_ENABLE bit */
name|PM1AControl
operator||=
name|SleepEnableRegInfo
operator|->
name|AccessBitMask
expr_stmt|;
name|PM1BControl
operator||=
name|SleepEnableRegInfo
operator|->
name|AccessBitMask
expr_stmt|;
comment|/* Write #2: SLP_TYP + SLP_EN */
name|ACPI_FLUSH_CPU_CACHE
argument_list|()
expr_stmt|;
name|Status
operator|=
name|AcpiHwRegisterWrite
argument_list|(
name|ACPI_MTX_DO_NOT_LOCK
argument_list|,
name|ACPI_REGISTER_PM1A_CONTROL
argument_list|,
name|PM1AControl
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
name|Status
operator|=
name|AcpiHwRegisterWrite
argument_list|(
name|ACPI_MTX_DO_NOT_LOCK
argument_list|,
name|ACPI_REGISTER_PM1B_CONTROL
argument_list|,
name|PM1BControl
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|SleepState
operator|>
name|ACPI_STATE_S3
condition|)
block|{
comment|/*          * We wanted to sleep> S3, but it didn't happen (by virtue of the          * fact that we are still executing!)          *          * Wait ten seconds, then try again. This is to get S4/S5 to work on          * all machines.          *          * We wait so long to allow chipsets that poll this reg very slowly to          * still read the right value. Ideally, this block would go          * away entirely.          */
name|AcpiOsStall
argument_list|(
literal|10000000
argument_list|)
expr_stmt|;
name|Status
operator|=
name|AcpiHwRegisterWrite
argument_list|(
name|ACPI_MTX_DO_NOT_LOCK
argument_list|,
name|ACPI_REGISTER_PM1_CONTROL
argument_list|,
name|SleepEnableRegInfo
operator|->
name|AccessBitMask
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
block|}
comment|/* Wait until we enter sleep state */
do|do
block|{
name|Status
operator|=
name|AcpiGetRegister
argument_list|(
name|ACPI_BITREG_WAKE_STATUS
argument_list|,
operator|&
name|InValue
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
comment|/* Spin until we wake */
block|}
do|while
condition|(
operator|!
name|InValue
condition|)
do|;
name|return_ACPI_STATUS
argument_list|(
name|AE_OK
argument_list|)
expr_stmt|;
block|}
end_function

begin_macro
name|ACPI_EXPORT_SYMBOL
argument_list|(
argument|AcpiEnterSleepState
argument_list|)
end_macro

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    AcpiEnterSleepStateS4bios  *  * PARAMETERS:  None  *  * RETURN:      Status  *  * DESCRIPTION: Perform a S4 bios request.  *              THIS FUNCTION MUST BE CALLED WITH INTERRUPTS DISABLED  *  ******************************************************************************/
end_comment

begin_function
name|ACPI_STATUS
name|AcpiEnterSleepStateS4bios
parameter_list|(
name|void
parameter_list|)
block|{
name|UINT32
name|InValue
decl_stmt|;
name|ACPI_STATUS
name|Status
decl_stmt|;
name|ACPI_FUNCTION_TRACE
argument_list|(
name|AcpiEnterSleepStateS4bios
argument_list|)
expr_stmt|;
name|Status
operator|=
name|AcpiSetRegister
argument_list|(
name|ACPI_BITREG_WAKE_STATUS
argument_list|,
literal|1
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
name|Status
operator|=
name|AcpiHwClearAcpiStatus
argument_list|()
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
comment|/*      * 1) Disable/Clear all GPEs      * 2) Enable all wakeup GPEs      */
name|Status
operator|=
name|AcpiHwDisableAllGpes
argument_list|()
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
name|AcpiGbl_SystemAwakeAndRunning
operator|=
name|FALSE
expr_stmt|;
name|Status
operator|=
name|AcpiHwEnableAllWakeupGpes
argument_list|()
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
name|ACPI_FLUSH_CPU_CACHE
argument_list|()
expr_stmt|;
name|Status
operator|=
name|AcpiOsWritePort
argument_list|(
name|AcpiGbl_FADT
operator|.
name|SmiCommand
argument_list|,
operator|(
name|UINT32
operator|)
name|AcpiGbl_FADT
operator|.
name|S4BiosRequest
argument_list|,
literal|8
argument_list|)
expr_stmt|;
do|do
block|{
name|AcpiOsStall
argument_list|(
literal|1000
argument_list|)
expr_stmt|;
name|Status
operator|=
name|AcpiGetRegister
argument_list|(
name|ACPI_BITREG_WAKE_STATUS
argument_list|,
operator|&
name|InValue
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
block|}
do|while
condition|(
operator|!
name|InValue
condition|)
do|;
name|return_ACPI_STATUS
argument_list|(
name|AE_OK
argument_list|)
expr_stmt|;
block|}
end_function

begin_macro
name|ACPI_EXPORT_SYMBOL
argument_list|(
argument|AcpiEnterSleepStateS4bios
argument_list|)
end_macro

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    AcpiLeaveSleepState  *  * PARAMETERS:  SleepState          - Which sleep state we just exited  *  * RETURN:      Status  *  * DESCRIPTION: Perform OS-independent ACPI cleanup after a sleep  *              Called with interrupts ENABLED.  *  ******************************************************************************/
end_comment

begin_function
name|ACPI_STATUS
name|AcpiLeaveSleepState
parameter_list|(
name|UINT8
name|SleepState
parameter_list|)
block|{
name|ACPI_OBJECT_LIST
name|ArgList
decl_stmt|;
name|ACPI_OBJECT
name|Arg
decl_stmt|;
name|ACPI_STATUS
name|Status
decl_stmt|;
name|ACPI_BIT_REGISTER_INFO
modifier|*
name|SleepTypeRegInfo
decl_stmt|;
name|ACPI_BIT_REGISTER_INFO
modifier|*
name|SleepEnableRegInfo
decl_stmt|;
name|UINT32
name|PM1AControl
decl_stmt|;
name|UINT32
name|PM1BControl
decl_stmt|;
name|ACPI_FUNCTION_TRACE
argument_list|(
name|AcpiLeaveSleepState
argument_list|)
expr_stmt|;
comment|/*      * Set SLP_TYPE and SLP_EN to state S0.      * This is unclear from the ACPI Spec, but it is required      * by some machines.      */
name|Status
operator|=
name|AcpiGetSleepTypeData
argument_list|(
name|ACPI_STATE_S0
argument_list|,
operator|&
name|AcpiGbl_SleepTypeA
argument_list|,
operator|&
name|AcpiGbl_SleepTypeB
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_SUCCESS
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|SleepTypeRegInfo
operator|=
name|AcpiHwGetBitRegisterInfo
argument_list|(
name|ACPI_BITREG_SLEEP_TYPE_A
argument_list|)
expr_stmt|;
name|SleepEnableRegInfo
operator|=
name|AcpiHwGetBitRegisterInfo
argument_list|(
name|ACPI_BITREG_SLEEP_ENABLE
argument_list|)
expr_stmt|;
comment|/* Get current value of PM1A control */
name|Status
operator|=
name|AcpiHwRegisterRead
argument_list|(
name|ACPI_MTX_DO_NOT_LOCK
argument_list|,
name|ACPI_REGISTER_PM1_CONTROL
argument_list|,
operator|&
name|PM1AControl
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_SUCCESS
argument_list|(
name|Status
argument_list|)
condition|)
block|{
comment|/* Clear SLP_EN and SLP_TYP fields */
name|PM1AControl
operator|&=
operator|~
operator|(
name|SleepTypeRegInfo
operator|->
name|AccessBitMask
operator||
name|SleepEnableRegInfo
operator|->
name|AccessBitMask
operator|)
expr_stmt|;
name|PM1BControl
operator|=
name|PM1AControl
expr_stmt|;
comment|/* Insert SLP_TYP bits */
name|PM1AControl
operator||=
operator|(
name|AcpiGbl_SleepTypeA
operator|<<
name|SleepTypeRegInfo
operator|->
name|BitPosition
operator|)
expr_stmt|;
name|PM1BControl
operator||=
operator|(
name|AcpiGbl_SleepTypeB
operator|<<
name|SleepTypeRegInfo
operator|->
name|BitPosition
operator|)
expr_stmt|;
comment|/* Just ignore any errors */
operator|(
name|void
operator|)
name|AcpiHwRegisterWrite
argument_list|(
name|ACPI_MTX_DO_NOT_LOCK
argument_list|,
name|ACPI_REGISTER_PM1A_CONTROL
argument_list|,
name|PM1AControl
argument_list|)
expr_stmt|;
operator|(
name|void
operator|)
name|AcpiHwRegisterWrite
argument_list|(
name|ACPI_MTX_DO_NOT_LOCK
argument_list|,
name|ACPI_REGISTER_PM1B_CONTROL
argument_list|,
name|PM1BControl
argument_list|)
expr_stmt|;
block|}
block|}
comment|/* Ensure EnterSleepStatePrep -> EnterSleepState ordering */
name|AcpiGbl_SleepTypeA
operator|=
name|ACPI_SLEEP_TYPE_INVALID
expr_stmt|;
comment|/* Setup parameter object */
name|ArgList
operator|.
name|Count
operator|=
literal|1
expr_stmt|;
name|ArgList
operator|.
name|Pointer
operator|=
operator|&
name|Arg
expr_stmt|;
name|Arg
operator|.
name|Type
operator|=
name|ACPI_TYPE_INTEGER
expr_stmt|;
comment|/* Ignore any errors from these methods */
name|Arg
operator|.
name|Integer
operator|.
name|Value
operator|=
name|ACPI_SST_WAKING
expr_stmt|;
name|Status
operator|=
name|AcpiEvaluateObject
argument_list|(
name|NULL
argument_list|,
name|METHOD_NAME__SST
argument_list|,
operator|&
name|ArgList
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
operator|&&
name|Status
operator|!=
name|AE_NOT_FOUND
condition|)
block|{
name|ACPI_EXCEPTION
argument_list|(
operator|(
name|AE_INFO
operator|,
name|Status
operator|,
literal|"During Method _SST"
operator|)
argument_list|)
expr_stmt|;
block|}
name|Arg
operator|.
name|Integer
operator|.
name|Value
operator|=
name|SleepState
expr_stmt|;
name|Status
operator|=
name|AcpiEvaluateObject
argument_list|(
name|NULL
argument_list|,
name|METHOD_NAME__BFS
argument_list|,
operator|&
name|ArgList
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
operator|&&
name|Status
operator|!=
name|AE_NOT_FOUND
condition|)
block|{
name|ACPI_EXCEPTION
argument_list|(
operator|(
name|AE_INFO
operator|,
name|Status
operator|,
literal|"During Method _BFS"
operator|)
argument_list|)
expr_stmt|;
block|}
name|Status
operator|=
name|AcpiEvaluateObject
argument_list|(
name|NULL
argument_list|,
name|METHOD_NAME__WAK
argument_list|,
operator|&
name|ArgList
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
operator|&&
name|Status
operator|!=
name|AE_NOT_FOUND
condition|)
block|{
name|ACPI_EXCEPTION
argument_list|(
operator|(
name|AE_INFO
operator|,
name|Status
operator|,
literal|"During Method _WAK"
operator|)
argument_list|)
expr_stmt|;
block|}
comment|/* TBD: _WAK "sometimes" returns stuff - do we want to look at it? */
comment|/*      * Restore the GPEs:      * 1) Disable/Clear all GPEs      * 2) Enable all runtime GPEs      */
name|Status
operator|=
name|AcpiHwDisableAllGpes
argument_list|()
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
name|AcpiGbl_SystemAwakeAndRunning
operator|=
name|TRUE
expr_stmt|;
name|Status
operator|=
name|AcpiHwEnableAllRuntimeGpes
argument_list|()
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
comment|/* Enable power button */
operator|(
name|void
operator|)
name|AcpiSetRegister
argument_list|(
name|AcpiGbl_FixedEventInfo
index|[
name|ACPI_EVENT_POWER_BUTTON
index|]
operator|.
name|EnableRegisterId
argument_list|,
literal|1
argument_list|)
expr_stmt|;
operator|(
name|void
operator|)
name|AcpiSetRegister
argument_list|(
name|AcpiGbl_FixedEventInfo
index|[
name|ACPI_EVENT_POWER_BUTTON
index|]
operator|.
name|StatusRegisterId
argument_list|,
literal|1
argument_list|)
expr_stmt|;
comment|/* Enable BM arbitration */
name|Status
operator|=
name|AcpiSetRegister
argument_list|(
name|ACPI_BITREG_ARB_DISABLE
argument_list|,
literal|0
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
condition|)
block|{
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
name|Arg
operator|.
name|Integer
operator|.
name|Value
operator|=
name|ACPI_SST_WORKING
expr_stmt|;
name|Status
operator|=
name|AcpiEvaluateObject
argument_list|(
name|NULL
argument_list|,
name|METHOD_NAME__SST
argument_list|,
operator|&
name|ArgList
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|ACPI_FAILURE
argument_list|(
name|Status
argument_list|)
operator|&&
name|Status
operator|!=
name|AE_NOT_FOUND
condition|)
block|{
name|ACPI_EXCEPTION
argument_list|(
operator|(
name|AE_INFO
operator|,
name|Status
operator|,
literal|"During Method _SST"
operator|)
argument_list|)
expr_stmt|;
block|}
name|return_ACPI_STATUS
argument_list|(
name|Status
argument_list|)
expr_stmt|;
block|}
end_function

begin_macro
name|ACPI_EXPORT_SYMBOL
argument_list|(
argument|AcpiLeaveSleepState
argument_list|)
end_macro

end_unit

