begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * IEEE 802.11 Common routines  * Copyright (c) 2002-2008, Jouni Malinen<j@w1.fi>  *  * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License version 2 as  * published by the Free Software Foundation.  *  * Alternatively, this software may be distributed under the terms of BSD  * license.  *  * See README and COPYING for more details.  */
end_comment

begin_include
include|#
directive|include
file|"includes.h"
end_include

begin_include
include|#
directive|include
file|"common.h"
end_include

begin_include
include|#
directive|include
file|"ieee802_11_defs.h"
end_include

begin_include
include|#
directive|include
file|"ieee802_11_common.h"
end_include

begin_function
specifier|static
name|int
name|ieee802_11_parse_vendor_specific
parameter_list|(
name|u8
modifier|*
name|pos
parameter_list|,
name|size_t
name|elen
parameter_list|,
name|struct
name|ieee802_11_elems
modifier|*
name|elems
parameter_list|,
name|int
name|show_errors
parameter_list|)
block|{
name|unsigned
name|int
name|oui
decl_stmt|;
comment|/* first 3 bytes in vendor specific information element are the IEEE 	 * OUI of the vendor. The following byte is used a vendor specific 	 * sub-type. */
if|if
condition|(
name|elen
operator|<
literal|4
condition|)
block|{
if|if
condition|(
name|show_errors
condition|)
block|{
name|wpa_printf
argument_list|(
name|MSG_MSGDUMP
argument_list|,
literal|"short vendor specific "
literal|"information element ignored (len=%lu)"
argument_list|,
operator|(
name|unsigned
name|long
operator|)
name|elen
argument_list|)
expr_stmt|;
block|}
return|return
operator|-
literal|1
return|;
block|}
name|oui
operator|=
name|WPA_GET_BE24
argument_list|(
name|pos
argument_list|)
expr_stmt|;
switch|switch
condition|(
name|oui
condition|)
block|{
case|case
name|OUI_MICROSOFT
case|:
comment|/* Microsoft/Wi-Fi information elements are further typed and 		 * subtyped */
switch|switch
condition|(
name|pos
index|[
literal|3
index|]
condition|)
block|{
case|case
literal|1
case|:
comment|/* Microsoft OUI (00:50:F2) with OUI Type 1: 			 * real WPA information element */
name|elems
operator|->
name|wpa_ie
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|wpa_ie_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WME_OUI_TYPE
case|:
comment|/* this is a Wi-Fi WME info. element */
if|if
condition|(
name|elen
operator|<
literal|5
condition|)
block|{
name|wpa_printf
argument_list|(
name|MSG_MSGDUMP
argument_list|,
literal|"short WME "
literal|"information element ignored "
literal|"(len=%lu)"
argument_list|,
operator|(
name|unsigned
name|long
operator|)
name|elen
argument_list|)
expr_stmt|;
return|return
operator|-
literal|1
return|;
block|}
switch|switch
condition|(
name|pos
index|[
literal|4
index|]
condition|)
block|{
case|case
name|WME_OUI_SUBTYPE_INFORMATION_ELEMENT
case|:
case|case
name|WME_OUI_SUBTYPE_PARAMETER_ELEMENT
case|:
name|elems
operator|->
name|wme
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|wme_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WME_OUI_SUBTYPE_TSPEC_ELEMENT
case|:
name|elems
operator|->
name|wme_tspec
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|wme_tspec_len
operator|=
name|elen
expr_stmt|;
break|break;
default|default:
name|wpa_printf
argument_list|(
name|MSG_MSGDUMP
argument_list|,
literal|"unknown WME "
literal|"information element ignored "
literal|"(subtype=%d len=%lu)"
argument_list|,
name|pos
index|[
literal|4
index|]
argument_list|,
operator|(
name|unsigned
name|long
operator|)
name|elen
argument_list|)
expr_stmt|;
return|return
operator|-
literal|1
return|;
block|}
break|break;
case|case
literal|4
case|:
comment|/* Wi-Fi Protected Setup (WPS) IE */
name|elems
operator|->
name|wps_ie
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|wps_ie_len
operator|=
name|elen
expr_stmt|;
break|break;
default|default:
name|wpa_printf
argument_list|(
name|MSG_MSGDUMP
argument_list|,
literal|"Unknown Microsoft "
literal|"information element ignored "
literal|"(type=%d len=%lu)\n"
argument_list|,
name|pos
index|[
literal|3
index|]
argument_list|,
operator|(
name|unsigned
name|long
operator|)
name|elen
argument_list|)
expr_stmt|;
return|return
operator|-
literal|1
return|;
block|}
break|break;
case|case
name|OUI_BROADCOM
case|:
switch|switch
condition|(
name|pos
index|[
literal|3
index|]
condition|)
block|{
case|case
name|VENDOR_HT_CAPAB_OUI_TYPE
case|:
name|elems
operator|->
name|vendor_ht_cap
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|vendor_ht_cap_len
operator|=
name|elen
expr_stmt|;
break|break;
default|default:
name|wpa_printf
argument_list|(
name|MSG_MSGDUMP
argument_list|,
literal|"Unknown Broadcom "
literal|"information element ignored "
literal|"(type=%d len=%lu)\n"
argument_list|,
name|pos
index|[
literal|3
index|]
argument_list|,
operator|(
name|unsigned
name|long
operator|)
name|elen
argument_list|)
expr_stmt|;
return|return
operator|-
literal|1
return|;
block|}
break|break;
default|default:
name|wpa_printf
argument_list|(
name|MSG_MSGDUMP
argument_list|,
literal|"unknown vendor specific information "
literal|"element ignored (vendor OUI %02x:%02x:%02x "
literal|"len=%lu)"
argument_list|,
name|pos
index|[
literal|0
index|]
argument_list|,
name|pos
index|[
literal|1
index|]
argument_list|,
name|pos
index|[
literal|2
index|]
argument_list|,
operator|(
name|unsigned
name|long
operator|)
name|elen
argument_list|)
expr_stmt|;
return|return
operator|-
literal|1
return|;
block|}
return|return
literal|0
return|;
block|}
end_function

begin_comment
comment|/**  * ieee802_11_parse_elems - Parse information elements in management frames  * @start: Pointer to the start of IEs  * @len: Length of IE buffer in octets  * @elems: Data structure for parsed elements  * @show_errors: Whether to show parsing errors in debug log  * Returns: Parsing result  */
end_comment

begin_function
name|ParseRes
name|ieee802_11_parse_elems
parameter_list|(
name|u8
modifier|*
name|start
parameter_list|,
name|size_t
name|len
parameter_list|,
name|struct
name|ieee802_11_elems
modifier|*
name|elems
parameter_list|,
name|int
name|show_errors
parameter_list|)
block|{
name|size_t
name|left
init|=
name|len
decl_stmt|;
name|u8
modifier|*
name|pos
init|=
name|start
decl_stmt|;
name|int
name|unknown
init|=
literal|0
decl_stmt|;
name|os_memset
argument_list|(
name|elems
argument_list|,
literal|0
argument_list|,
sizeof|sizeof
argument_list|(
operator|*
name|elems
argument_list|)
argument_list|)
expr_stmt|;
while|while
condition|(
name|left
operator|>=
literal|2
condition|)
block|{
name|u8
name|id
decl_stmt|,
name|elen
decl_stmt|;
name|id
operator|=
operator|*
name|pos
operator|++
expr_stmt|;
name|elen
operator|=
operator|*
name|pos
operator|++
expr_stmt|;
name|left
operator|-=
literal|2
expr_stmt|;
if|if
condition|(
name|elen
operator|>
name|left
condition|)
block|{
if|if
condition|(
name|show_errors
condition|)
block|{
name|wpa_printf
argument_list|(
name|MSG_DEBUG
argument_list|,
literal|"IEEE 802.11 element "
literal|"parse failed (id=%d elen=%d "
literal|"left=%lu)"
argument_list|,
name|id
argument_list|,
name|elen
argument_list|,
operator|(
name|unsigned
name|long
operator|)
name|left
argument_list|)
expr_stmt|;
name|wpa_hexdump
argument_list|(
name|MSG_MSGDUMP
argument_list|,
literal|"IEs"
argument_list|,
name|start
argument_list|,
name|len
argument_list|)
expr_stmt|;
block|}
return|return
name|ParseFailed
return|;
block|}
switch|switch
condition|(
name|id
condition|)
block|{
case|case
name|WLAN_EID_SSID
case|:
name|elems
operator|->
name|ssid
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|ssid_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WLAN_EID_SUPP_RATES
case|:
name|elems
operator|->
name|supp_rates
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|supp_rates_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WLAN_EID_FH_PARAMS
case|:
name|elems
operator|->
name|fh_params
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|fh_params_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WLAN_EID_DS_PARAMS
case|:
name|elems
operator|->
name|ds_params
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|ds_params_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WLAN_EID_CF_PARAMS
case|:
name|elems
operator|->
name|cf_params
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|cf_params_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WLAN_EID_TIM
case|:
name|elems
operator|->
name|tim
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|tim_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WLAN_EID_IBSS_PARAMS
case|:
name|elems
operator|->
name|ibss_params
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|ibss_params_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WLAN_EID_CHALLENGE
case|:
name|elems
operator|->
name|challenge
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|challenge_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WLAN_EID_ERP_INFO
case|:
name|elems
operator|->
name|erp_info
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|erp_info_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WLAN_EID_EXT_SUPP_RATES
case|:
name|elems
operator|->
name|ext_supp_rates
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|ext_supp_rates_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WLAN_EID_VENDOR_SPECIFIC
case|:
if|if
condition|(
name|ieee802_11_parse_vendor_specific
argument_list|(
name|pos
argument_list|,
name|elen
argument_list|,
name|elems
argument_list|,
name|show_errors
argument_list|)
condition|)
name|unknown
operator|++
expr_stmt|;
break|break;
case|case
name|WLAN_EID_RSN
case|:
name|elems
operator|->
name|rsn_ie
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|rsn_ie_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WLAN_EID_PWR_CAPABILITY
case|:
name|elems
operator|->
name|power_cap
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|power_cap_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WLAN_EID_SUPPORTED_CHANNELS
case|:
name|elems
operator|->
name|supp_channels
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|supp_channels_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WLAN_EID_MOBILITY_DOMAIN
case|:
name|elems
operator|->
name|mdie
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|mdie_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WLAN_EID_FAST_BSS_TRANSITION
case|:
name|elems
operator|->
name|ftie
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|ftie_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WLAN_EID_TIMEOUT_INTERVAL
case|:
name|elems
operator|->
name|timeout_int
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|timeout_int_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WLAN_EID_HT_CAP
case|:
name|elems
operator|->
name|ht_capabilities
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|ht_capabilities_len
operator|=
name|elen
expr_stmt|;
break|break;
case|case
name|WLAN_EID_HT_OPERATION
case|:
name|elems
operator|->
name|ht_operation
operator|=
name|pos
expr_stmt|;
name|elems
operator|->
name|ht_operation_len
operator|=
name|elen
expr_stmt|;
break|break;
default|default:
name|unknown
operator|++
expr_stmt|;
if|if
condition|(
operator|!
name|show_errors
condition|)
break|break;
name|wpa_printf
argument_list|(
name|MSG_MSGDUMP
argument_list|,
literal|"IEEE 802.11 element parse "
literal|"ignored unknown element (id=%d elen=%d)"
argument_list|,
name|id
argument_list|,
name|elen
argument_list|)
expr_stmt|;
break|break;
block|}
name|left
operator|-=
name|elen
expr_stmt|;
name|pos
operator|+=
name|elen
expr_stmt|;
block|}
if|if
condition|(
name|left
condition|)
return|return
name|ParseFailed
return|;
return|return
name|unknown
condition|?
name|ParseUnknown
else|:
name|ParseOK
return|;
block|}
end_function

end_unit

