begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * ng_btsocket_hci_raw.c  *  * Copyright (c) 2001-2002 Maksim Yevmenkin<m_evmenkin@yahoo.com>  * All rights reserved.  *  * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions  * are met:  * 1. Redistributions of source code must retain the above copyright  *    notice, this list of conditions and the following disclaimer.  * 2. Redistributions in binary form must reproduce the above copyright  *    notice, this list of conditions and the following disclaimer in the  *    documentation and/or other materials provided with the distribution.  *  * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND  * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE  * ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS  * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)  * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT  * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY  * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF  * SUCH DAMAGE.  *  * $Id: ng_btsocket_hci_raw.c,v 1.3 2002/11/12 22:31:39 max Exp $  * $FreeBSD$  */
end_comment

begin_include
include|#
directive|include
file|<sys/param.h>
end_include

begin_include
include|#
directive|include
file|<sys/systm.h>
end_include

begin_include
include|#
directive|include
file|<sys/domain.h>
end_include

begin_include
include|#
directive|include
file|<sys/errno.h>
end_include

begin_include
include|#
directive|include
file|<sys/filedesc.h>
end_include

begin_include
include|#
directive|include
file|<sys/ioccom.h>
end_include

begin_include
include|#
directive|include
file|<sys/kernel.h>
end_include

begin_include
include|#
directive|include
file|<sys/lock.h>
end_include

begin_include
include|#
directive|include
file|<sys/malloc.h>
end_include

begin_include
include|#
directive|include
file|<sys/mbuf.h>
end_include

begin_include
include|#
directive|include
file|<sys/mutex.h>
end_include

begin_include
include|#
directive|include
file|<sys/protosw.h>
end_include

begin_include
include|#
directive|include
file|<sys/queue.h>
end_include

begin_include
include|#
directive|include
file|<sys/socket.h>
end_include

begin_include
include|#
directive|include
file|<sys/socketvar.h>
end_include

begin_include
include|#
directive|include
file|<sys/sysctl.h>
end_include

begin_include
include|#
directive|include
file|<sys/taskqueue.h>
end_include

begin_include
include|#
directive|include
file|<netgraph/ng_message.h>
end_include

begin_include
include|#
directive|include
file|<netgraph/netgraph.h>
end_include

begin_include
include|#
directive|include
file|<bitstring.h>
end_include

begin_include
include|#
directive|include
file|"ng_bluetooth.h"
end_include

begin_include
include|#
directive|include
file|"ng_hci.h"
end_include

begin_include
include|#
directive|include
file|"ng_l2cap.h"
end_include

begin_include
include|#
directive|include
file|"ng_btsocket.h"
end_include

begin_include
include|#
directive|include
file|"ng_btsocket_hci_raw.h"
end_include

begin_comment
comment|/* MALLOC define */
end_comment

begin_ifdef
ifdef|#
directive|ifdef
name|NG_SEPARATE_MALLOC
end_ifdef

begin_expr_stmt
name|MALLOC_DEFINE
argument_list|(
name|M_NETGRAPH_BTSOCKET_HCI_RAW
argument_list|,
literal|"netgraph_btsocks_hci_raw"
argument_list|,
literal|"Netgraph Bluetooth raw HCI sockets"
argument_list|)
expr_stmt|;
end_expr_stmt

begin_else
else|#
directive|else
end_else

begin_define
define|#
directive|define
name|M_NETGRAPH_BTSOCKET_HCI_RAW
value|M_NETGRAPH
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_comment
comment|/* NG_SEPARATE_MALLOC */
end_comment

begin_comment
comment|/* Netgraph node methods */
end_comment

begin_decl_stmt
specifier|static
name|ng_constructor_t
name|ng_btsocket_hci_raw_node_constructor
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|ng_rcvmsg_t
name|ng_btsocket_hci_raw_node_rcvmsg
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|ng_shutdown_t
name|ng_btsocket_hci_raw_node_shutdown
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|ng_newhook_t
name|ng_btsocket_hci_raw_node_newhook
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|ng_connect_t
name|ng_btsocket_hci_raw_node_connect
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|ng_rcvdata_t
name|ng_btsocket_hci_raw_node_rcvdata
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|ng_disconnect_t
name|ng_btsocket_hci_raw_node_disconnect
decl_stmt|;
end_decl_stmt

begin_function_decl
specifier|static
name|void
name|ng_btsocket_hci_raw_input
parameter_list|(
name|void
modifier|*
parameter_list|,
name|int
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|ng_btsocket_hci_raw_output
parameter_list|(
name|node_p
parameter_list|,
name|hook_p
parameter_list|,
name|void
modifier|*
parameter_list|,
name|int
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|ng_btsocket_hci_raw_savctl
parameter_list|(
name|ng_btsocket_hci_raw_pcb_p
parameter_list|,
name|struct
name|mbuf
modifier|*
modifier|*
parameter_list|,
name|struct
name|mbuf
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_comment
comment|/* Netgraph type descriptor */
end_comment

begin_decl_stmt
specifier|static
name|struct
name|ng_type
name|typestruct
init|=
block|{
name|NG_ABI_VERSION
block|,
name|NG_BTSOCKET_HCI_RAW_NODE_TYPE
block|,
comment|/* typename */
name|NULL
block|,
comment|/* modevent */
name|ng_btsocket_hci_raw_node_constructor
block|,
comment|/* constructor */
name|ng_btsocket_hci_raw_node_rcvmsg
block|,
comment|/* control message */
name|ng_btsocket_hci_raw_node_shutdown
block|,
comment|/* destructor */
name|ng_btsocket_hci_raw_node_newhook
block|,
comment|/* new hook */
name|NULL
block|,
comment|/* find hook */
name|ng_btsocket_hci_raw_node_connect
block|,
comment|/* connect hook */
name|ng_btsocket_hci_raw_node_rcvdata
block|,
comment|/* data */
name|ng_btsocket_hci_raw_node_disconnect
block|,
comment|/* disconnect hook */
name|NULL
comment|/* node command list */
block|}
decl_stmt|;
end_decl_stmt

begin_comment
comment|/* Globals */
end_comment

begin_decl_stmt
specifier|extern
name|int
name|ifqmaxlen
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|u_int32_t
name|ng_btsocket_hci_raw_debug_level
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|u_int32_t
name|ng_btsocket_hci_raw_ioctl_timeout
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|node_p
name|ng_btsocket_hci_raw_node
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|struct
name|ng_bt_itemq
name|ng_btsocket_hci_raw_queue
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|struct
name|mtx
name|ng_btsocket_hci_raw_queue_mtx
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|struct
name|task
name|ng_btsocket_hci_raw_task
decl_stmt|;
end_decl_stmt

begin_expr_stmt
specifier|static
name|LIST_HEAD
argument_list|(
argument_list|,
argument|ng_btsocket_hci_raw_pcb
argument_list|)
name|ng_btsocket_hci_raw_sockets
expr_stmt|;
end_expr_stmt

begin_decl_stmt
specifier|static
name|struct
name|mtx
name|ng_btsocket_hci_raw_sockets_mtx
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|u_int32_t
name|ng_btsocket_hci_raw_token
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|struct
name|mtx
name|ng_btsocket_hci_raw_token_mtx
decl_stmt|;
end_decl_stmt

begin_comment
comment|/* Sysctl tree */
end_comment

begin_expr_stmt
name|SYSCTL_DECL
argument_list|(
name|_net_bluetooth_hci_sockets
argument_list|)
expr_stmt|;
end_expr_stmt

begin_expr_stmt
name|SYSCTL_NODE
argument_list|(
name|_net_bluetooth_hci_sockets
argument_list|,
name|OID_AUTO
argument_list|,
name|raw
argument_list|,
name|CTLFLAG_RW
argument_list|,
literal|0
argument_list|,
literal|"Bluetooth raw HCI sockets family"
argument_list|)
expr_stmt|;
end_expr_stmt

begin_expr_stmt
name|SYSCTL_INT
argument_list|(
name|_net_bluetooth_hci_sockets_raw
argument_list|,
name|OID_AUTO
argument_list|,
name|debug_level
argument_list|,
name|CTLFLAG_RW
argument_list|,
operator|&
name|ng_btsocket_hci_raw_debug_level
argument_list|,
name|NG_BTSOCKET_WARN_LEVEL
argument_list|,
literal|"Bluetooth raw HCI sockets debug level"
argument_list|)
expr_stmt|;
end_expr_stmt

begin_expr_stmt
name|SYSCTL_INT
argument_list|(
name|_net_bluetooth_hci_sockets_raw
argument_list|,
name|OID_AUTO
argument_list|,
name|ioctl_timeout
argument_list|,
name|CTLFLAG_RW
argument_list|,
operator|&
name|ng_btsocket_hci_raw_ioctl_timeout
argument_list|,
literal|5
argument_list|,
literal|"Bluetooth raw HCI sockets ioctl timeout"
argument_list|)
expr_stmt|;
end_expr_stmt

begin_expr_stmt
name|SYSCTL_INT
argument_list|(
name|_net_bluetooth_hci_sockets_raw
argument_list|,
name|OID_AUTO
argument_list|,
name|queue_len
argument_list|,
name|CTLFLAG_RD
argument_list|,
operator|&
name|ng_btsocket_hci_raw_queue
operator|.
name|len
argument_list|,
literal|0
argument_list|,
literal|"Bluetooth raw HCI sockets input queue length"
argument_list|)
expr_stmt|;
end_expr_stmt

begin_expr_stmt
name|SYSCTL_INT
argument_list|(
name|_net_bluetooth_hci_sockets_raw
argument_list|,
name|OID_AUTO
argument_list|,
name|queue_maxlen
argument_list|,
name|CTLFLAG_RD
argument_list|,
operator|&
name|ng_btsocket_hci_raw_queue
operator|.
name|maxlen
argument_list|,
literal|0
argument_list|,
literal|"Bluetooth raw HCI sockets input queue max. length"
argument_list|)
expr_stmt|;
end_expr_stmt

begin_expr_stmt
name|SYSCTL_INT
argument_list|(
name|_net_bluetooth_hci_sockets_raw
argument_list|,
name|OID_AUTO
argument_list|,
name|queue_drops
argument_list|,
name|CTLFLAG_RD
argument_list|,
operator|&
name|ng_btsocket_hci_raw_queue
operator|.
name|drops
argument_list|,
literal|0
argument_list|,
literal|"Bluetooth raw HCI sockets input queue drops"
argument_list|)
expr_stmt|;
end_expr_stmt

begin_comment
comment|/* Debug */
end_comment

begin_define
define|#
directive|define
name|NG_BTSOCKET_HCI_RAW_INFO
define|\
value|if (ng_btsocket_hci_raw_debug_level>= NG_BTSOCKET_INFO_LEVEL) \ 		printf
end_define

begin_define
define|#
directive|define
name|NG_BTSOCKET_HCI_RAW_WARN
define|\
value|if (ng_btsocket_hci_raw_debug_level>= NG_BTSOCKET_WARN_LEVEL) \ 		printf
end_define

begin_define
define|#
directive|define
name|NG_BTSOCKET_HCI_RAW_ERR
define|\
value|if (ng_btsocket_hci_raw_debug_level>= NG_BTSOCKET_ERR_LEVEL) \ 		printf
end_define

begin_define
define|#
directive|define
name|NG_BTSOCKET_HCI_RAW_ALERT
define|\
value|if (ng_btsocket_hci_raw_debug_level>= NG_BTSOCKET_ALERT_LEVEL) \ 		printf
end_define

begin_comment
comment|/****************************************************************************  ****************************************************************************  **                          Netgraph specific  ****************************************************************************  ****************************************************************************/
end_comment

begin_comment
comment|/*  * Netgraph node constructor. Do not allow to create node of this type.  */
end_comment

begin_function
specifier|static
name|int
name|ng_btsocket_hci_raw_node_constructor
parameter_list|(
name|node_p
name|node
parameter_list|)
block|{
return|return
operator|(
name|EINVAL
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_node_constructor */
end_comment

begin_comment
comment|/*  * Netgraph node destructor. Just let old node go and create new fresh one.  */
end_comment

begin_function
specifier|static
name|int
name|ng_btsocket_hci_raw_node_shutdown
parameter_list|(
name|node_p
name|node
parameter_list|)
block|{
name|int
name|error
init|=
literal|0
decl_stmt|;
name|NG_NODE_UNREF
argument_list|(
name|node
argument_list|)
expr_stmt|;
name|error
operator|=
name|ng_make_node_common
argument_list|(
operator|&
name|typestruct
argument_list|,
operator|&
name|ng_btsocket_hci_raw_node
argument_list|)
expr_stmt|;
if|if
condition|(
name|error
operator|!=
literal|0
condition|)
block|{
name|NG_BTSOCKET_HCI_RAW_ALERT
argument_list|(
literal|"%s: Could not create Netgraph node, error=%d\n"
argument_list|,
name|__func__
argument_list|,
name|error
argument_list|)
expr_stmt|;
name|ng_btsocket_hci_raw_node
operator|=
name|NULL
expr_stmt|;
return|return
operator|(
name|ENOMEM
operator|)
return|;
block|}
name|error
operator|=
name|ng_name_node
argument_list|(
name|ng_btsocket_hci_raw_node
argument_list|,
name|NG_BTSOCKET_HCI_RAW_NODE_TYPE
argument_list|)
expr_stmt|;
if|if
condition|(
name|error
operator|!=
literal|0
condition|)
block|{
name|NG_BTSOCKET_HCI_RAW_ALERT
argument_list|(
literal|"%s: Could not name Netgraph node, error=%d\n"
argument_list|,
name|__func__
argument_list|,
name|error
argument_list|)
expr_stmt|;
name|NG_NODE_UNREF
argument_list|(
name|ng_btsocket_hci_raw_node
argument_list|)
expr_stmt|;
name|ng_btsocket_hci_raw_node
operator|=
name|NULL
expr_stmt|;
return|return
operator|(
name|EINVAL
operator|)
return|;
block|}
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_node_shutdown */
end_comment

begin_comment
comment|/*  * Create new hook. Just say "yes"  */
end_comment

begin_function
specifier|static
name|int
name|ng_btsocket_hci_raw_node_newhook
parameter_list|(
name|node_p
name|node
parameter_list|,
name|hook_p
name|hook
parameter_list|,
name|char
specifier|const
modifier|*
name|name
parameter_list|)
block|{
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_node_newhook */
end_comment

begin_comment
comment|/*  * Connect hook. Just say "yes"  */
end_comment

begin_function
specifier|static
name|int
name|ng_btsocket_hci_raw_node_connect
parameter_list|(
name|hook_p
name|hook
parameter_list|)
block|{
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_node_connect */
end_comment

begin_comment
comment|/*  * Disconnect hook  */
end_comment

begin_function
specifier|static
name|int
name|ng_btsocket_hci_raw_node_disconnect
parameter_list|(
name|hook_p
name|hook
parameter_list|)
block|{
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_node_disconnect */
end_comment

begin_comment
comment|/*  * Receive control message.  * Make sure it is a message from HCI node and it is a response.  * Enqueue item and schedule input task.  */
end_comment

begin_function
specifier|static
name|int
name|ng_btsocket_hci_raw_node_rcvmsg
parameter_list|(
name|node_p
name|node
parameter_list|,
name|item_p
name|item
parameter_list|,
name|hook_p
name|lasthook
parameter_list|)
block|{
name|struct
name|ng_mesg
modifier|*
name|msg
init|=
name|NGI_MSG
argument_list|(
name|item
argument_list|)
decl_stmt|;
comment|/* item still has message */
name|int
name|error
init|=
literal|0
decl_stmt|;
if|if
condition|(
name|msg
operator|!=
name|NULL
operator|&&
name|msg
operator|->
name|header
operator|.
name|typecookie
operator|==
name|NGM_HCI_COOKIE
operator|&&
name|msg
operator|->
name|header
operator|.
name|flags
operator|&
name|NGF_RESP
condition|)
block|{
name|mtx_lock
argument_list|(
operator|&
name|ng_btsocket_hci_raw_queue_mtx
argument_list|)
expr_stmt|;
if|if
condition|(
name|NG_BT_ITEMQ_FULL
argument_list|(
operator|&
name|ng_btsocket_hci_raw_queue
argument_list|)
condition|)
block|{
name|NG_BTSOCKET_HCI_RAW_ERR
argument_list|(
literal|"%s: Input queue is full\n"
argument_list|,
name|__func__
argument_list|)
expr_stmt|;
name|NG_BT_ITEMQ_DROP
argument_list|(
operator|&
name|ng_btsocket_hci_raw_queue
argument_list|)
expr_stmt|;
name|NG_FREE_ITEM
argument_list|(
name|item
argument_list|)
expr_stmt|;
name|error
operator|=
name|ENOBUFS
expr_stmt|;
block|}
else|else
block|{
name|NG_BT_ITEMQ_ENQUEUE
argument_list|(
operator|&
name|ng_btsocket_hci_raw_queue
argument_list|,
name|item
argument_list|)
expr_stmt|;
name|error
operator|=
name|taskqueue_enqueue
argument_list|(
name|taskqueue_swi
argument_list|,
operator|&
name|ng_btsocket_hci_raw_task
argument_list|)
expr_stmt|;
block|}
name|mtx_unlock
argument_list|(
operator|&
name|ng_btsocket_hci_raw_queue_mtx
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|NG_FREE_ITEM
argument_list|(
name|item
argument_list|)
expr_stmt|;
name|error
operator|=
name|EINVAL
expr_stmt|;
block|}
return|return
operator|(
name|error
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_node_rcvmsg */
end_comment

begin_comment
comment|/*  * Receive packet from the one of our hook.  * Prepend every packet with sockaddr_hci and record sender's node name.  * Enqueue item and schedule input task.  */
end_comment

begin_function
specifier|static
name|int
name|ng_btsocket_hci_raw_node_rcvdata
parameter_list|(
name|hook_p
name|hook
parameter_list|,
name|item_p
name|item
parameter_list|)
block|{
name|struct
name|mbuf
modifier|*
name|nam
init|=
name|NULL
decl_stmt|;
name|int
name|error
decl_stmt|;
name|MGET
argument_list|(
name|nam
argument_list|,
name|M_DONTWAIT
argument_list|,
name|MT_SONAME
argument_list|)
expr_stmt|;
if|if
condition|(
name|nam
operator|!=
name|NULL
condition|)
block|{
name|struct
name|sockaddr_hci
modifier|*
name|sa
init|=
name|mtod
argument_list|(
name|nam
argument_list|,
expr|struct
name|sockaddr_hci
operator|*
argument_list|)
decl_stmt|;
name|nam
operator|->
name|m_len
operator|=
sizeof|sizeof
argument_list|(
expr|struct
name|sockaddr_hci
argument_list|)
expr_stmt|;
name|sa
operator|->
name|hci_len
operator|=
sizeof|sizeof
argument_list|(
operator|*
name|sa
argument_list|)
expr_stmt|;
name|sa
operator|->
name|hci_family
operator|=
name|AF_BLUETOOTH
expr_stmt|;
name|strncpy
argument_list|(
name|sa
operator|->
name|hci_node
argument_list|,
name|NG_PEER_NODE_NAME
argument_list|(
name|hook
argument_list|)
argument_list|,
sizeof|sizeof
argument_list|(
name|sa
operator|->
name|hci_node
argument_list|)
argument_list|)
expr_stmt|;
name|sa
operator|->
name|hci_node
index|[
sizeof|sizeof
argument_list|(
name|sa
operator|->
name|hci_node
argument_list|)
operator|-
literal|1
index|]
operator|=
literal|0
expr_stmt|;
comment|/* sanity */
name|NGI_GET_M
argument_list|(
name|item
argument_list|,
name|nam
operator|->
name|m_next
argument_list|)
expr_stmt|;
name|NGI_M
argument_list|(
name|item
argument_list|)
operator|=
name|nam
expr_stmt|;
name|mtx_lock
argument_list|(
operator|&
name|ng_btsocket_hci_raw_queue_mtx
argument_list|)
expr_stmt|;
if|if
condition|(
name|NG_BT_ITEMQ_FULL
argument_list|(
operator|&
name|ng_btsocket_hci_raw_queue
argument_list|)
condition|)
block|{
name|NG_BTSOCKET_HCI_RAW_ERR
argument_list|(
literal|"%s: Input queue is full\n"
argument_list|,
name|__func__
argument_list|)
expr_stmt|;
name|NG_BT_ITEMQ_DROP
argument_list|(
operator|&
name|ng_btsocket_hci_raw_queue
argument_list|)
expr_stmt|;
name|NG_FREE_ITEM
argument_list|(
name|item
argument_list|)
expr_stmt|;
name|error
operator|=
name|ENOBUFS
expr_stmt|;
block|}
else|else
block|{
name|NG_BT_ITEMQ_ENQUEUE
argument_list|(
operator|&
name|ng_btsocket_hci_raw_queue
argument_list|,
name|item
argument_list|)
expr_stmt|;
name|error
operator|=
name|taskqueue_enqueue
argument_list|(
name|taskqueue_swi
argument_list|,
operator|&
name|ng_btsocket_hci_raw_task
argument_list|)
expr_stmt|;
block|}
name|mtx_unlock
argument_list|(
operator|&
name|ng_btsocket_hci_raw_queue_mtx
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|NG_BTSOCKET_HCI_RAW_ERR
argument_list|(
literal|"%s: Failed to allocate address mbuf\n"
argument_list|,
name|__func__
argument_list|)
expr_stmt|;
name|NG_FREE_ITEM
argument_list|(
name|item
argument_list|)
expr_stmt|;
name|error
operator|=
name|ENOBUFS
expr_stmt|;
block|}
return|return
operator|(
name|error
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_node_rcvdata */
end_comment

begin_comment
comment|/****************************************************************************  ****************************************************************************  **                              Sockets specific  ****************************************************************************  ****************************************************************************/
end_comment

begin_comment
comment|/*  * Get next token  */
end_comment

begin_function
specifier|static
name|void
name|ng_btsocket_hci_raw_get_token
parameter_list|(
name|u_int32_t
modifier|*
name|token
parameter_list|)
block|{
name|mtx_lock
argument_list|(
operator|&
name|ng_btsocket_hci_raw_token_mtx
argument_list|)
expr_stmt|;
if|if
condition|(
operator|++
name|ng_btsocket_hci_raw_token
operator|==
literal|0
condition|)
name|ng_btsocket_hci_raw_token
operator|=
literal|1
expr_stmt|;
operator|*
name|token
operator|=
name|ng_btsocket_hci_raw_token
expr_stmt|;
name|mtx_unlock
argument_list|(
operator|&
name|ng_btsocket_hci_raw_token_mtx
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_token */
end_comment

begin_comment
comment|/*  * Send Netgraph message to the node - do not expect reply  */
end_comment

begin_function
specifier|static
name|int
name|ng_btsocket_raw_send_ngmsg
parameter_list|(
name|char
modifier|*
name|path
parameter_list|,
name|int
name|cmd
parameter_list|,
name|void
modifier|*
name|arg
parameter_list|,
name|int
name|arglen
parameter_list|)
block|{
name|struct
name|ng_mesg
modifier|*
name|msg
init|=
name|NULL
decl_stmt|;
name|int
name|error
init|=
literal|0
decl_stmt|;
name|NG_MKMESSAGE
argument_list|(
name|msg
argument_list|,
name|NGM_HCI_COOKIE
argument_list|,
name|cmd
argument_list|,
name|arglen
argument_list|,
name|M_WAITOK
argument_list|)
expr_stmt|;
if|if
condition|(
name|msg
operator|==
name|NULL
condition|)
return|return
operator|(
name|ENOMEM
operator|)
return|;
if|if
condition|(
name|arg
operator|!=
name|NULL
operator|&&
name|arglen
operator|>
literal|0
condition|)
name|bcopy
argument_list|(
name|arg
argument_list|,
name|msg
operator|->
name|data
argument_list|,
name|arglen
argument_list|)
expr_stmt|;
name|NG_SEND_MSG_PATH
argument_list|(
name|error
argument_list|,
name|ng_btsocket_hci_raw_node
argument_list|,
name|msg
argument_list|,
name|path
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
return|return
operator|(
name|error
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_raw_send_ngmsg */
end_comment

begin_comment
comment|/*  * Send Netgraph message to the node (no data) and wait for reply   */
end_comment

begin_function
specifier|static
name|int
name|ng_btsocket_raw_send_sync_ngmsg
parameter_list|(
name|ng_btsocket_hci_raw_pcb_p
name|pcb
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|int
name|cmd
parameter_list|,
name|void
modifier|*
name|rsp
parameter_list|,
name|int
name|rsplen
parameter_list|)
block|{
name|struct
name|ng_mesg
modifier|*
name|msg
init|=
name|NULL
decl_stmt|;
name|int
name|error
init|=
literal|0
decl_stmt|;
name|ng_btsocket_hci_raw_get_token
argument_list|(
operator|&
name|pcb
operator|->
name|token
argument_list|)
expr_stmt|;
name|pcb
operator|->
name|msg
operator|=
name|NULL
expr_stmt|;
name|NG_MKMESSAGE
argument_list|(
name|msg
argument_list|,
name|NGM_HCI_COOKIE
argument_list|,
name|cmd
argument_list|,
literal|0
argument_list|,
name|M_WAITOK
argument_list|)
expr_stmt|;
if|if
condition|(
name|msg
operator|==
name|NULL
condition|)
block|{
name|pcb
operator|->
name|token
operator|=
literal|0
expr_stmt|;
return|return
operator|(
name|ENOMEM
operator|)
return|;
block|}
name|msg
operator|->
name|header
operator|.
name|token
operator|=
name|pcb
operator|->
name|token
expr_stmt|;
name|NG_SEND_MSG_PATH
argument_list|(
name|error
argument_list|,
name|ng_btsocket_hci_raw_node
argument_list|,
name|msg
argument_list|,
name|path
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|error
operator|!=
literal|0
condition|)
block|{
name|pcb
operator|->
name|token
operator|=
literal|0
expr_stmt|;
return|return
operator|(
name|error
operator|)
return|;
block|}
name|error
operator|=
name|tsleep
argument_list|(
operator|&
name|pcb
operator|->
name|msg
argument_list|,
name|PZERO
operator||
name|PCATCH
argument_list|,
literal|"hcictl"
argument_list|,
name|ng_btsocket_hci_raw_ioctl_timeout
operator|*
name|hz
argument_list|)
expr_stmt|;
if|if
condition|(
name|error
operator|!=
literal|0
condition|)
block|{
name|pcb
operator|->
name|token
operator|=
literal|0
expr_stmt|;
return|return
operator|(
name|error
operator|)
return|;
block|}
if|if
condition|(
name|pcb
operator|->
name|msg
operator|!=
name|NULL
operator|&&
name|pcb
operator|->
name|msg
operator|->
name|header
operator|.
name|cmd
operator|==
name|cmd
condition|)
name|bcopy
argument_list|(
name|pcb
operator|->
name|msg
operator|->
name|data
argument_list|,
name|rsp
argument_list|,
name|rsplen
argument_list|)
expr_stmt|;
else|else
name|error
operator|=
name|EINVAL
expr_stmt|;
name|NG_FREE_MSG
argument_list|(
name|pcb
operator|->
name|msg
argument_list|)
expr_stmt|;
comment|/* checks for != NULL */
name|pcb
operator|->
name|token
operator|=
literal|0
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_raw_send_sync_ngmsg */
end_comment

begin_comment
comment|/*  * Create control information for the packet  */
end_comment

begin_function
specifier|static
name|void
name|ng_btsocket_hci_raw_savctl
parameter_list|(
name|ng_btsocket_hci_raw_pcb_p
name|pcb
parameter_list|,
name|struct
name|mbuf
modifier|*
modifier|*
name|ctl
parameter_list|,
name|struct
name|mbuf
modifier|*
name|m
parameter_list|)
block|{
name|int
name|dir
decl_stmt|;
name|struct
name|timeval
name|tv
decl_stmt|;
if|if
condition|(
name|pcb
operator|->
name|flags
operator|&
name|NG_BTSOCKET_HCI_RAW_DIRECTION
condition|)
block|{
name|dir
operator|=
operator|(
name|m
operator|->
name|m_flags
operator|&
name|M_PROTO1
operator|)
condition|?
literal|1
else|:
literal|0
expr_stmt|;
operator|*
name|ctl
operator|=
name|sbcreatecontrol
argument_list|(
operator|(
name|caddr_t
operator|)
operator|&
name|dir
argument_list|,
sizeof|sizeof
argument_list|(
name|dir
argument_list|)
argument_list|,
name|SCM_HCI_RAW_DIRECTION
argument_list|,
name|SOL_HCI_RAW
argument_list|)
expr_stmt|;
if|if
condition|(
operator|*
name|ctl
operator|!=
name|NULL
condition|)
name|ctl
operator|=
operator|&
operator|(
operator|(
operator|*
name|ctl
operator|)
operator|->
name|m_next
operator|)
expr_stmt|;
block|}
if|if
condition|(
name|pcb
operator|->
name|so
operator|->
name|so_options
operator|&
name|SO_TIMESTAMP
condition|)
block|{
name|microtime
argument_list|(
operator|&
name|tv
argument_list|)
expr_stmt|;
operator|*
name|ctl
operator|=
name|sbcreatecontrol
argument_list|(
operator|(
name|caddr_t
operator|)
operator|&
name|tv
argument_list|,
sizeof|sizeof
argument_list|(
name|tv
argument_list|)
argument_list|,
name|SCM_TIMESTAMP
argument_list|,
name|SOL_SOCKET
argument_list|)
expr_stmt|;
if|if
condition|(
operator|*
name|ctl
operator|!=
name|NULL
condition|)
name|ctl
operator|=
operator|&
operator|(
operator|(
operator|*
name|ctl
operator|)
operator|->
name|m_next
operator|)
expr_stmt|;
block|}
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_savctl */
end_comment

begin_comment
comment|/*  * Raw HCI sockets data input routine  */
end_comment

begin_function
specifier|static
name|void
name|ng_btsocket_hci_raw_data_input
parameter_list|(
name|struct
name|mbuf
modifier|*
name|nam
parameter_list|)
block|{
name|ng_btsocket_hci_raw_pcb_p
name|pcb
init|=
name|NULL
decl_stmt|;
name|struct
name|mbuf
modifier|*
name|m0
init|=
name|NULL
decl_stmt|,
modifier|*
name|m
init|=
name|NULL
decl_stmt|;
name|struct
name|sockaddr_hci
modifier|*
name|sa
init|=
name|NULL
decl_stmt|;
name|bitstr_t
modifier|*
name|mask
init|=
name|NULL
decl_stmt|;
name|int
name|bit
decl_stmt|;
name|m0
operator|=
name|nam
operator|->
name|m_next
expr_stmt|;
name|nam
operator|->
name|m_next
operator|=
name|NULL
expr_stmt|;
name|KASSERT
argument_list|(
operator|(
name|nam
operator|->
name|m_type
operator|==
name|MT_SONAME
operator|)
argument_list|,
operator|(
literal|"%s: m_type=%d\n"
operator|,
name|__func__
operator|,
name|nam
operator|->
name|m_type
operator|)
argument_list|)
expr_stmt|;
name|KASSERT
argument_list|(
operator|(
name|m0
operator|->
name|m_flags
operator|&
name|M_PKTHDR
operator|)
argument_list|,
operator|(
literal|"%s: m_flags=%#x\n"
operator|,
name|__func__
operator|,
name|m0
operator|->
name|m_flags
operator|)
argument_list|)
expr_stmt|;
name|sa
operator|=
name|mtod
argument_list|(
name|nam
argument_list|,
expr|struct
name|sockaddr_hci
operator|*
argument_list|)
expr_stmt|;
name|mtx_lock
argument_list|(
operator|&
name|ng_btsocket_hci_raw_sockets_mtx
argument_list|)
expr_stmt|;
name|LIST_FOREACH
argument_list|(
argument|pcb
argument_list|,
argument|&ng_btsocket_hci_raw_sockets
argument_list|,
argument|next
argument_list|)
block|{
comment|/* 		 * If socket was bound then check address and 		 *  make sure it matches. 		 */
if|if
condition|(
name|pcb
operator|->
name|addr
operator|.
name|hci_node
index|[
literal|0
index|]
operator|!=
literal|0
operator|&&
name|strcmp
argument_list|(
name|sa
operator|->
name|hci_node
argument_list|,
name|pcb
operator|->
name|addr
operator|.
name|hci_node
argument_list|)
operator|!=
literal|0
condition|)
continue|continue;
comment|/* 		 * Check packet agains socket filter 		 * XXX do we have to call m_pullup() here? 		 */
switch|switch
condition|(
operator|*
name|mtod
argument_list|(
name|m0
argument_list|,
name|u_int8_t
operator|*
argument_list|)
condition|)
block|{
case|case
name|NG_HCI_CMD_PKT
case|:
case|case
name|NG_HCI_ACL_DATA_PKT
case|:
case|case
name|NG_HCI_SCO_DATA_PKT
case|:
name|mask
operator|=
name|pcb
operator|->
name|filter
operator|.
name|packet_mask
expr_stmt|;
name|bit
operator|=
operator|*
name|mtod
argument_list|(
name|m0
argument_list|,
name|u_int8_t
operator|*
argument_list|)
operator|-
literal|1
expr_stmt|;
break|break;
case|case
name|NG_HCI_EVENT_PKT
case|:
name|mask
operator|=
name|pcb
operator|->
name|filter
operator|.
name|event_mask
expr_stmt|;
name|bit
operator|=
name|mtod
argument_list|(
name|m0
argument_list|,
name|ng_hci_event_pkt_t
operator|*
argument_list|)
operator|->
name|event
operator|-
literal|1
expr_stmt|;
break|break;
default|default:
name|KASSERT
argument_list|(
literal|0
argument_list|,
operator|(
literal|"%s: invalid packet type=%#x\n"
operator|,
name|__func__
operator|,
operator|*
name|mtod
argument_list|(
name|m0
argument_list|,
name|u_int8_t
operator|*
argument_list|)
operator|)
argument_list|)
expr_stmt|;
name|mask
operator|=
name|NULL
expr_stmt|;
name|bit
operator|=
literal|0
expr_stmt|;
break|break;
block|}
if|if
condition|(
name|mask
operator|==
name|NULL
operator|||
operator|!
name|bit_test
argument_list|(
name|mask
argument_list|,
name|bit
argument_list|)
condition|)
continue|continue;
comment|/* 		 * Make a copy of the packet, append to the socket's 		 * receive queue and wakeup socket. sbappendaddr() 		 * will check if socket has enough buffer space. 		 */
name|m
operator|=
name|m_dup
argument_list|(
name|m0
argument_list|,
name|M_DONTWAIT
argument_list|)
expr_stmt|;
if|if
condition|(
name|m
operator|!=
name|NULL
condition|)
block|{
name|struct
name|mbuf
modifier|*
name|ctl
init|=
name|NULL
decl_stmt|;
name|ng_btsocket_hci_raw_savctl
argument_list|(
name|pcb
argument_list|,
operator|&
name|ctl
argument_list|,
name|m
argument_list|)
expr_stmt|;
if|if
condition|(
name|sbappendaddr
argument_list|(
operator|&
name|pcb
operator|->
name|so
operator|->
name|so_rcv
argument_list|,
operator|(
expr|struct
name|sockaddr
operator|*
operator|)
name|sa
argument_list|,
name|m
argument_list|,
name|ctl
argument_list|)
condition|)
name|sorwakeup
argument_list|(
name|pcb
operator|->
name|so
argument_list|)
expr_stmt|;
else|else
block|{
name|NG_BTSOCKET_HCI_RAW_WARN
argument_list|(
literal|"%s: sbappendadd() failed\n"
argument_list|,
name|__func__
argument_list|)
expr_stmt|;
name|NG_FREE_M
argument_list|(
name|m
argument_list|)
expr_stmt|;
name|NG_FREE_M
argument_list|(
name|ctl
argument_list|)
expr_stmt|;
block|}
block|}
block|}
name|mtx_unlock
argument_list|(
operator|&
name|ng_btsocket_hci_raw_sockets_mtx
argument_list|)
expr_stmt|;
name|NG_FREE_M
argument_list|(
name|nam
argument_list|)
expr_stmt|;
name|NG_FREE_M
argument_list|(
name|m0
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_data_input */
end_comment

begin_comment
comment|/*  * Raw HCI sockets message input routine  */
end_comment

begin_function
specifier|static
name|void
name|ng_btsocket_hci_raw_msg_input
parameter_list|(
name|struct
name|ng_mesg
modifier|*
name|msg
parameter_list|)
block|{
name|ng_btsocket_hci_raw_pcb_p
name|pcb
init|=
name|NULL
decl_stmt|;
if|if
condition|(
name|msg
operator|->
name|header
operator|.
name|token
operator|!=
literal|0
condition|)
block|{
name|mtx_lock
argument_list|(
operator|&
name|ng_btsocket_hci_raw_sockets_mtx
argument_list|)
expr_stmt|;
name|LIST_FOREACH
argument_list|(
argument|pcb
argument_list|,
argument|&ng_btsocket_hci_raw_sockets
argument_list|,
argument|next
argument_list|)
block|{
if|if
condition|(
name|msg
operator|->
name|header
operator|.
name|token
operator|==
name|pcb
operator|->
name|token
condition|)
block|{
name|pcb
operator|->
name|msg
operator|=
name|msg
expr_stmt|;
name|msg
operator|=
name|NULL
expr_stmt|;
name|wakeup
argument_list|(
operator|&
name|pcb
operator|->
name|msg
argument_list|)
expr_stmt|;
break|break;
block|}
block|}
name|mtx_unlock
argument_list|(
operator|&
name|ng_btsocket_hci_raw_sockets_mtx
argument_list|)
expr_stmt|;
block|}
name|NG_FREE_MSG
argument_list|(
name|msg
argument_list|)
expr_stmt|;
comment|/* checks for != NULL */
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_msg_input */
end_comment

begin_comment
comment|/*  * Raw HCI sockets input routines  */
end_comment

begin_function
specifier|static
name|void
name|ng_btsocket_hci_raw_input
parameter_list|(
name|void
modifier|*
name|context
parameter_list|,
name|int
name|pending
parameter_list|)
block|{
name|item_p
name|item
init|=
name|NULL
decl_stmt|;
for|for
control|(
init|;
condition|;
control|)
block|{
name|mtx_lock
argument_list|(
operator|&
name|ng_btsocket_hci_raw_queue_mtx
argument_list|)
expr_stmt|;
name|NG_BT_ITEMQ_DEQUEUE
argument_list|(
operator|&
name|ng_btsocket_hci_raw_queue
argument_list|,
name|item
argument_list|)
expr_stmt|;
name|mtx_unlock
argument_list|(
operator|&
name|ng_btsocket_hci_raw_queue_mtx
argument_list|)
expr_stmt|;
if|if
condition|(
name|item
operator|==
name|NULL
condition|)
break|break;
switch|switch
condition|(
name|item
operator|->
name|el_flags
operator|&
name|NGQF_TYPE
condition|)
block|{
case|case
name|NGQF_DATA
case|:
block|{
name|struct
name|mbuf
modifier|*
name|m
init|=
name|NULL
decl_stmt|;
name|NGI_GET_M
argument_list|(
name|item
argument_list|,
name|m
argument_list|)
expr_stmt|;
name|ng_btsocket_hci_raw_data_input
argument_list|(
name|m
argument_list|)
expr_stmt|;
block|}
break|break;
case|case
name|NGQF_MESG
case|:
block|{
name|struct
name|ng_mesg
modifier|*
name|msg
init|=
name|NULL
decl_stmt|;
name|NGI_GET_MSG
argument_list|(
name|item
argument_list|,
name|msg
argument_list|)
expr_stmt|;
name|ng_btsocket_hci_raw_msg_input
argument_list|(
name|msg
argument_list|)
expr_stmt|;
block|}
break|break;
default|default:
name|KASSERT
argument_list|(
literal|0
argument_list|,
operator|(
literal|"%s: invalid item type=%ld\n"
operator|,
name|__func__
operator|,
operator|(
name|item
operator|->
name|el_flags
operator|&
name|NGQF_TYPE
operator|)
operator|)
argument_list|)
expr_stmt|;
break|break;
block|}
name|NG_FREE_ITEM
argument_list|(
name|item
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_input */
end_comment

begin_comment
comment|/*  * Raw HCI sockets output routine  */
end_comment

begin_function
specifier|static
name|void
name|ng_btsocket_hci_raw_output
parameter_list|(
name|node_p
name|node
parameter_list|,
name|hook_p
name|hook
parameter_list|,
name|void
modifier|*
name|arg1
parameter_list|,
name|int
name|arg2
parameter_list|)
block|{
name|struct
name|mbuf
modifier|*
name|nam
init|=
operator|(
expr|struct
name|mbuf
operator|*
operator|)
name|arg1
decl_stmt|,
modifier|*
name|m
init|=
name|NULL
decl_stmt|;
name|struct
name|sockaddr_hci
modifier|*
name|sa
init|=
name|NULL
decl_stmt|;
name|int
name|error
decl_stmt|;
name|m
operator|=
name|nam
operator|->
name|m_next
expr_stmt|;
name|nam
operator|->
name|m_next
operator|=
name|NULL
expr_stmt|;
name|KASSERT
argument_list|(
operator|(
name|nam
operator|->
name|m_type
operator|==
name|MT_SONAME
operator|)
argument_list|,
operator|(
literal|"%s: m_type=%d\n"
operator|,
name|__func__
operator|,
name|nam
operator|->
name|m_type
operator|)
argument_list|)
expr_stmt|;
name|KASSERT
argument_list|(
operator|(
name|m
operator|->
name|m_flags
operator|&
name|M_PKTHDR
operator|)
argument_list|,
operator|(
literal|"%s: m_flags=%#x\n"
operator|,
name|__func__
operator|,
name|m
operator|->
name|m_flags
operator|)
argument_list|)
expr_stmt|;
name|sa
operator|=
name|mtod
argument_list|(
name|nam
argument_list|,
expr|struct
name|sockaddr_hci
operator|*
argument_list|)
expr_stmt|;
comment|/* 	 * Find downstream hook 	 * XXX For now access node hook list directly. Should be safe because 	 * we used ng_send_fn() and we should have exclusive lock on the node. 	 */
name|LIST_FOREACH
argument_list|(
argument|hook
argument_list|,
argument|&node->nd_hooks
argument_list|,
argument|hk_hooks
argument_list|)
block|{
if|if
condition|(
name|hook
operator|==
name|NULL
operator|||
name|NG_HOOK_NOT_VALID
argument_list|(
name|hook
argument_list|)
operator|||
name|NG_NODE_NOT_VALID
argument_list|(
name|NG_PEER_NODE
argument_list|(
name|hook
argument_list|)
argument_list|)
condition|)
continue|continue;
if|if
condition|(
name|strcmp
argument_list|(
name|sa
operator|->
name|hci_node
argument_list|,
name|NG_PEER_NODE_NAME
argument_list|(
name|hook
argument_list|)
argument_list|)
operator|==
literal|0
condition|)
block|{
name|NG_SEND_DATA_ONLY
argument_list|(
name|error
argument_list|,
name|hook
argument_list|,
name|m
argument_list|)
expr_stmt|;
comment|/* sets m to NULL */
break|break;
block|}
block|}
name|NG_FREE_M
argument_list|(
name|nam
argument_list|)
expr_stmt|;
comment|/* check for != NULL */
name|NG_FREE_M
argument_list|(
name|m
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_output */
end_comment

begin_comment
comment|/*  * Initialize everything  */
end_comment

begin_function
name|void
name|ng_btsocket_hci_raw_init
parameter_list|(
name|void
parameter_list|)
block|{
name|int
name|error
init|=
literal|0
decl_stmt|;
name|ng_btsocket_hci_raw_node
operator|=
name|NULL
expr_stmt|;
name|ng_btsocket_hci_raw_debug_level
operator|=
name|NG_BTSOCKET_WARN_LEVEL
expr_stmt|;
name|ng_btsocket_hci_raw_ioctl_timeout
operator|=
literal|5
expr_stmt|;
comment|/* Register Netgraph node type */
name|error
operator|=
name|ng_newtype
argument_list|(
operator|&
name|typestruct
argument_list|)
expr_stmt|;
if|if
condition|(
name|error
operator|!=
literal|0
condition|)
block|{
name|NG_BTSOCKET_HCI_RAW_ALERT
argument_list|(
literal|"%s: Could not register Netgraph node type, error=%d\n"
argument_list|,
name|__func__
argument_list|,
name|error
argument_list|)
expr_stmt|;
return|return;
block|}
comment|/* Create Netgrapg node */
name|error
operator|=
name|ng_make_node_common
argument_list|(
operator|&
name|typestruct
argument_list|,
operator|&
name|ng_btsocket_hci_raw_node
argument_list|)
expr_stmt|;
if|if
condition|(
name|error
operator|!=
literal|0
condition|)
block|{
name|NG_BTSOCKET_HCI_RAW_ALERT
argument_list|(
literal|"%s: Could not create Netgraph node, error=%d\n"
argument_list|,
name|__func__
argument_list|,
name|error
argument_list|)
expr_stmt|;
name|ng_btsocket_hci_raw_node
operator|=
name|NULL
expr_stmt|;
return|return;
block|}
name|error
operator|=
name|ng_name_node
argument_list|(
name|ng_btsocket_hci_raw_node
argument_list|,
name|NG_BTSOCKET_HCI_RAW_NODE_TYPE
argument_list|)
expr_stmt|;
if|if
condition|(
name|error
operator|!=
literal|0
condition|)
block|{
name|NG_BTSOCKET_HCI_RAW_ALERT
argument_list|(
literal|"%s: Could not name Netgraph node, error=%d\n"
argument_list|,
name|__func__
argument_list|,
name|error
argument_list|)
expr_stmt|;
name|NG_NODE_UNREF
argument_list|(
name|ng_btsocket_hci_raw_node
argument_list|)
expr_stmt|;
name|ng_btsocket_hci_raw_node
operator|=
name|NULL
expr_stmt|;
return|return;
block|}
comment|/* Create input queue */
name|NG_BT_ITEMQ_INIT
argument_list|(
operator|&
name|ng_btsocket_hci_raw_queue
argument_list|,
name|ifqmaxlen
argument_list|)
expr_stmt|;
name|mtx_init
argument_list|(
operator|&
name|ng_btsocket_hci_raw_queue_mtx
argument_list|,
literal|"btsocks_hci_raw_queue_mtx"
argument_list|,
name|NULL
argument_list|,
name|MTX_DEF
argument_list|)
expr_stmt|;
name|TASK_INIT
argument_list|(
operator|&
name|ng_btsocket_hci_raw_task
argument_list|,
literal|0
argument_list|,
name|ng_btsocket_hci_raw_input
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
comment|/* Create list of sockets */
name|LIST_INIT
argument_list|(
operator|&
name|ng_btsocket_hci_raw_sockets
argument_list|)
expr_stmt|;
name|mtx_init
argument_list|(
operator|&
name|ng_btsocket_hci_raw_sockets_mtx
argument_list|,
literal|"btsocks_hci_raw_sockets_mtx"
argument_list|,
name|NULL
argument_list|,
name|MTX_DEF
argument_list|)
expr_stmt|;
comment|/* Tokens */
name|ng_btsocket_hci_raw_token
operator|=
literal|0
expr_stmt|;
name|mtx_init
argument_list|(
operator|&
name|ng_btsocket_hci_raw_token_mtx
argument_list|,
literal|"btsocks_hci_raw_token_mtx"
argument_list|,
name|NULL
argument_list|,
name|MTX_DEF
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_init */
end_comment

begin_comment
comment|/*  * Abort connection on socket  */
end_comment

begin_function
name|int
name|ng_btsocket_hci_raw_abort
parameter_list|(
name|struct
name|socket
modifier|*
name|so
parameter_list|)
block|{
name|soisdisconnected
argument_list|(
name|so
argument_list|)
expr_stmt|;
return|return
operator|(
name|ng_btsocket_hci_raw_detach
argument_list|(
name|so
argument_list|)
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_abort */
end_comment

begin_comment
comment|/*  * Create new raw HCI socket  */
end_comment

begin_function
name|int
name|ng_btsocket_hci_raw_attach
parameter_list|(
name|struct
name|socket
modifier|*
name|so
parameter_list|,
name|int
name|proto
parameter_list|,
name|struct
name|thread
modifier|*
name|td
parameter_list|)
block|{
name|ng_btsocket_hci_raw_pcb_p
name|pcb
init|=
name|so2hci_raw_pcb
argument_list|(
name|so
argument_list|)
decl_stmt|;
name|int
name|error
init|=
literal|0
decl_stmt|;
if|if
condition|(
name|pcb
operator|!=
name|NULL
condition|)
return|return
operator|(
name|EISCONN
operator|)
return|;
if|if
condition|(
name|ng_btsocket_hci_raw_node
operator|==
name|NULL
condition|)
return|return
operator|(
name|EPROTONOSUPPORT
operator|)
return|;
if|if
condition|(
name|proto
operator|!=
name|BLUETOOTH_PROTO_HCI
condition|)
return|return
operator|(
name|EPROTONOSUPPORT
operator|)
return|;
if|if
condition|(
name|so
operator|->
name|so_type
operator|!=
name|SOCK_RAW
condition|)
return|return
operator|(
name|ESOCKTNOSUPPORT
operator|)
return|;
if|if
condition|(
operator|(
name|error
operator|=
name|suser
argument_list|(
name|td
argument_list|)
operator|)
operator|!=
literal|0
condition|)
return|return
operator|(
name|error
operator|)
return|;
name|error
operator|=
name|soreserve
argument_list|(
name|so
argument_list|,
name|NG_BTSOCKET_HCI_RAW_SENDSPACE
argument_list|,
name|NG_BTSOCKET_HCI_RAW_RECVSPACE
argument_list|)
expr_stmt|;
if|if
condition|(
name|error
operator|!=
literal|0
condition|)
return|return
operator|(
name|error
operator|)
return|;
name|MALLOC
argument_list|(
name|pcb
argument_list|,
name|ng_btsocket_hci_raw_pcb_p
argument_list|,
sizeof|sizeof
argument_list|(
operator|*
name|pcb
argument_list|)
argument_list|,
name|M_NETGRAPH_BTSOCKET_HCI_RAW
argument_list|,
name|M_WAITOK
operator||
name|M_ZERO
argument_list|)
expr_stmt|;
if|if
condition|(
name|pcb
operator|==
name|NULL
condition|)
return|return
operator|(
name|ENOMEM
operator|)
return|;
name|so
operator|->
name|so_pcb
operator|=
operator|(
name|caddr_t
operator|)
name|pcb
expr_stmt|;
name|pcb
operator|->
name|so
operator|=
name|so
expr_stmt|;
comment|/* 	 * Set default socket filter. By default socket only accepts HCI 	 * Command_Complete and Command_Status event packets. 	 */
name|bit_set
argument_list|(
name|pcb
operator|->
name|filter
operator|.
name|event_mask
argument_list|,
name|NG_HCI_EVENT_COMMAND_COMPL
operator|-
literal|1
argument_list|)
expr_stmt|;
name|bit_set
argument_list|(
name|pcb
operator|->
name|filter
operator|.
name|event_mask
argument_list|,
name|NG_HCI_EVENT_COMMAND_STATUS
operator|-
literal|1
argument_list|)
expr_stmt|;
name|mtx_lock
argument_list|(
operator|&
name|ng_btsocket_hci_raw_sockets_mtx
argument_list|)
expr_stmt|;
name|LIST_INSERT_HEAD
argument_list|(
operator|&
name|ng_btsocket_hci_raw_sockets
argument_list|,
name|pcb
argument_list|,
name|next
argument_list|)
expr_stmt|;
name|mtx_unlock
argument_list|(
operator|&
name|ng_btsocket_hci_raw_sockets_mtx
argument_list|)
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_attach */
end_comment

begin_comment
comment|/*  * Bind raw HCI socket  */
end_comment

begin_function
name|int
name|ng_btsocket_hci_raw_bind
parameter_list|(
name|struct
name|socket
modifier|*
name|so
parameter_list|,
name|struct
name|sockaddr
modifier|*
name|nam
parameter_list|,
name|struct
name|thread
modifier|*
name|td
parameter_list|)
block|{
name|ng_btsocket_hci_raw_pcb_p
name|pcb
init|=
name|so2hci_raw_pcb
argument_list|(
name|so
argument_list|)
decl_stmt|;
name|struct
name|sockaddr_hci
modifier|*
name|sa
init|=
operator|(
expr|struct
name|sockaddr_hci
operator|*
operator|)
name|nam
decl_stmt|;
if|if
condition|(
name|pcb
operator|==
name|NULL
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
if|if
condition|(
name|ng_btsocket_hci_raw_node
operator|==
name|NULL
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
if|if
condition|(
name|sa
operator|==
name|NULL
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
if|if
condition|(
name|sa
operator|->
name|hci_family
operator|!=
name|AF_BLUETOOTH
condition|)
return|return
operator|(
name|EAFNOSUPPORT
operator|)
return|;
if|if
condition|(
name|sa
operator|->
name|hci_len
operator|!=
sizeof|sizeof
argument_list|(
operator|*
name|sa
argument_list|)
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
if|if
condition|(
name|sa
operator|->
name|hci_node
index|[
literal|0
index|]
operator|==
literal|0
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
name|bcopy
argument_list|(
name|sa
argument_list|,
operator|&
name|pcb
operator|->
name|addr
argument_list|,
sizeof|sizeof
argument_list|(
name|pcb
operator|->
name|addr
argument_list|)
argument_list|)
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_bind */
end_comment

begin_comment
comment|/*  * Connect raw HCI socket  */
end_comment

begin_function
name|int
name|ng_btsocket_hci_raw_connect
parameter_list|(
name|struct
name|socket
modifier|*
name|so
parameter_list|,
name|struct
name|sockaddr
modifier|*
name|nam
parameter_list|,
name|struct
name|thread
modifier|*
name|td
parameter_list|)
block|{
name|ng_btsocket_hci_raw_pcb_p
name|pcb
init|=
name|so2hci_raw_pcb
argument_list|(
name|so
argument_list|)
decl_stmt|;
name|struct
name|sockaddr_hci
modifier|*
name|sa
init|=
operator|(
expr|struct
name|sockaddr_hci
operator|*
operator|)
name|nam
decl_stmt|;
if|if
condition|(
name|pcb
operator|==
name|NULL
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
if|if
condition|(
name|ng_btsocket_hci_raw_node
operator|==
name|NULL
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
if|if
condition|(
name|sa
operator|==
name|NULL
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
if|if
condition|(
name|sa
operator|->
name|hci_family
operator|!=
name|AF_BLUETOOTH
condition|)
return|return
operator|(
name|EAFNOSUPPORT
operator|)
return|;
if|if
condition|(
name|sa
operator|->
name|hci_len
operator|!=
sizeof|sizeof
argument_list|(
operator|*
name|sa
argument_list|)
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
if|if
condition|(
name|sa
operator|->
name|hci_node
index|[
literal|0
index|]
operator|==
literal|0
condition|)
return|return
operator|(
name|EDESTADDRREQ
operator|)
return|;
if|if
condition|(
name|bcmp
argument_list|(
name|sa
argument_list|,
operator|&
name|pcb
operator|->
name|addr
argument_list|,
sizeof|sizeof
argument_list|(
name|pcb
operator|->
name|addr
argument_list|)
argument_list|)
operator|!=
literal|0
condition|)
return|return
operator|(
name|EADDRNOTAVAIL
operator|)
return|;
name|soisconnected
argument_list|(
name|so
argument_list|)
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_connect */
end_comment

begin_comment
comment|/*  * Process ioctl on socket  */
end_comment

begin_function
name|int
name|ng_btsocket_hci_raw_control
parameter_list|(
name|struct
name|socket
modifier|*
name|so
parameter_list|,
name|u_long
name|cmd
parameter_list|,
name|caddr_t
name|data
parameter_list|,
name|struct
name|ifnet
modifier|*
name|ifp
parameter_list|,
name|struct
name|thread
modifier|*
name|td
parameter_list|)
block|{
name|ng_btsocket_hci_raw_pcb_p
name|pcb
init|=
name|so2hci_raw_pcb
argument_list|(
name|so
argument_list|)
decl_stmt|;
name|char
name|path
index|[
name|NG_NODELEN
operator|+
literal|2
index|]
decl_stmt|,
modifier|*
name|hci_node
init|=
operator|(
name|char
operator|*
operator|)
name|data
decl_stmt|;
name|struct
name|ng_mesg
modifier|*
name|msg
init|=
name|NULL
decl_stmt|;
name|int
name|error
init|=
literal|0
decl_stmt|;
if|if
condition|(
name|pcb
operator|==
name|NULL
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
if|if
condition|(
name|ng_btsocket_hci_raw_node
operator|==
name|NULL
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
comment|/* 	 * Make sure caller has provided HCI node name, if not try to 	 * use addr from socket (if socket was bound) 	 */
if|if
condition|(
name|hci_node
index|[
literal|0
index|]
operator|==
literal|0
condition|)
block|{
if|if
condition|(
name|pcb
operator|->
name|addr
operator|.
name|hci_node
index|[
literal|0
index|]
operator|==
literal|0
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
name|bzero
argument_list|(
name|hci_node
argument_list|,
sizeof|sizeof
argument_list|(
name|pcb
operator|->
name|addr
operator|.
name|hci_node
argument_list|)
argument_list|)
expr_stmt|;
name|strncpy
argument_list|(
name|hci_node
argument_list|,
name|pcb
operator|->
name|addr
operator|.
name|hci_node
argument_list|,
sizeof|sizeof
argument_list|(
name|pcb
operator|->
name|addr
operator|.
name|hci_node
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|snprintf
argument_list|(
name|path
argument_list|,
sizeof|sizeof
argument_list|(
name|path
argument_list|)
argument_list|,
literal|"%s:"
argument_list|,
name|hci_node
argument_list|)
expr_stmt|;
switch|switch
condition|(
name|cmd
condition|)
block|{
case|case
name|SIOC_HCI_RAW_NODE_GET_STATE
case|:
block|{
name|struct
name|ng_btsocket_hci_raw_node_state
modifier|*
name|p
init|=
operator|(
expr|struct
name|ng_btsocket_hci_raw_node_state
operator|*
operator|)
name|data
decl_stmt|;
name|error
operator|=
name|ng_btsocket_raw_send_sync_ngmsg
argument_list|(
name|pcb
argument_list|,
name|path
argument_list|,
name|NGM_HCI_NODE_GET_STATE
argument_list|,
operator|&
name|p
operator|->
name|state
argument_list|,
sizeof|sizeof
argument_list|(
name|p
operator|->
name|state
argument_list|)
argument_list|)
expr_stmt|;
block|}
break|break;
case|case
name|SIOC_HCI_RAW_NODE_INIT
case|:
name|error
operator|=
name|ng_btsocket_raw_send_ngmsg
argument_list|(
name|path
argument_list|,
name|NGM_HCI_NODE_INIT
argument_list|,
name|NULL
argument_list|,
literal|0
argument_list|)
expr_stmt|;
break|break;
case|case
name|SIOC_HCI_RAW_NODE_GET_DEBUG
case|:
block|{
name|struct
name|ng_btsocket_hci_raw_node_debug
modifier|*
name|p
init|=
operator|(
expr|struct
name|ng_btsocket_hci_raw_node_debug
operator|*
operator|)
name|data
decl_stmt|;
name|error
operator|=
name|ng_btsocket_raw_send_sync_ngmsg
argument_list|(
name|pcb
argument_list|,
name|path
argument_list|,
name|NGM_HCI_NODE_GET_DEBUG
argument_list|,
operator|&
name|p
operator|->
name|debug
argument_list|,
sizeof|sizeof
argument_list|(
name|p
operator|->
name|debug
argument_list|)
argument_list|)
expr_stmt|;
block|}
break|break;
case|case
name|SIOC_HCI_RAW_NODE_SET_DEBUG
case|:
block|{
name|struct
name|ng_btsocket_hci_raw_node_debug
modifier|*
name|p
init|=
operator|(
expr|struct
name|ng_btsocket_hci_raw_node_debug
operator|*
operator|)
name|data
decl_stmt|;
name|error
operator|=
name|ng_btsocket_raw_send_ngmsg
argument_list|(
name|path
argument_list|,
name|NGM_HCI_NODE_SET_DEBUG
argument_list|,
operator|&
name|p
operator|->
name|debug
argument_list|,
sizeof|sizeof
argument_list|(
name|p
operator|->
name|debug
argument_list|)
argument_list|)
expr_stmt|;
block|}
break|break;
case|case
name|SIOC_HCI_RAW_NODE_GET_BUFFER
case|:
block|{
name|struct
name|ng_btsocket_hci_raw_node_buffer
modifier|*
name|p
init|=
operator|(
expr|struct
name|ng_btsocket_hci_raw_node_buffer
operator|*
operator|)
name|data
decl_stmt|;
name|error
operator|=
name|ng_btsocket_raw_send_sync_ngmsg
argument_list|(
name|pcb
argument_list|,
name|path
argument_list|,
name|NGM_HCI_NODE_GET_BUFFER
argument_list|,
operator|&
name|p
operator|->
name|buffer
argument_list|,
sizeof|sizeof
argument_list|(
name|p
operator|->
name|buffer
argument_list|)
argument_list|)
expr_stmt|;
block|}
break|break;
case|case
name|SIOC_HCI_RAW_NODE_GET_BDADDR
case|:
block|{
name|struct
name|ng_btsocket_hci_raw_node_bdaddr
modifier|*
name|p
init|=
operator|(
expr|struct
name|ng_btsocket_hci_raw_node_bdaddr
operator|*
operator|)
name|data
decl_stmt|;
name|error
operator|=
name|ng_btsocket_raw_send_sync_ngmsg
argument_list|(
name|pcb
argument_list|,
name|path
argument_list|,
name|NGM_HCI_NODE_GET_BDADDR
argument_list|,
operator|&
name|p
operator|->
name|bdaddr
argument_list|,
sizeof|sizeof
argument_list|(
name|p
operator|->
name|bdaddr
argument_list|)
argument_list|)
expr_stmt|;
block|}
break|break;
case|case
name|SIOC_HCI_RAW_NODE_GET_FEATURES
case|:
block|{
name|struct
name|ng_btsocket_hci_raw_node_features
modifier|*
name|p
init|=
operator|(
expr|struct
name|ng_btsocket_hci_raw_node_features
operator|*
operator|)
name|data
decl_stmt|;
name|error
operator|=
name|ng_btsocket_raw_send_sync_ngmsg
argument_list|(
name|pcb
argument_list|,
name|path
argument_list|,
name|NGM_HCI_NODE_GET_FEATURES
argument_list|,
operator|&
name|p
operator|->
name|features
argument_list|,
sizeof|sizeof
argument_list|(
name|p
operator|->
name|features
argument_list|)
argument_list|)
expr_stmt|;
block|}
break|break;
case|case
name|SIOC_HCI_RAW_NODE_GET_STAT
case|:
block|{
name|struct
name|ng_btsocket_hci_raw_node_stat
modifier|*
name|p
init|=
operator|(
expr|struct
name|ng_btsocket_hci_raw_node_stat
operator|*
operator|)
name|data
decl_stmt|;
name|error
operator|=
name|ng_btsocket_raw_send_sync_ngmsg
argument_list|(
name|pcb
argument_list|,
name|path
argument_list|,
name|NGM_HCI_NODE_GET_STAT
argument_list|,
operator|&
name|p
operator|->
name|stat
argument_list|,
sizeof|sizeof
argument_list|(
name|p
operator|->
name|stat
argument_list|)
argument_list|)
expr_stmt|;
block|}
break|break;
case|case
name|SIOC_HCI_RAW_NODE_RESET_STAT
case|:
name|error
operator|=
name|ng_btsocket_raw_send_ngmsg
argument_list|(
name|path
argument_list|,
name|NGM_HCI_NODE_RESET_STAT
argument_list|,
name|NULL
argument_list|,
literal|0
argument_list|)
expr_stmt|;
break|break;
case|case
name|SIOC_HCI_RAW_NODE_FLUSH_NEIGHBOR_CACHE
case|:
name|error
operator|=
name|ng_btsocket_raw_send_ngmsg
argument_list|(
name|path
argument_list|,
name|NGM_HCI_NODE_FLUSH_NEIGHBOR_CACHE
argument_list|,
name|NULL
argument_list|,
literal|0
argument_list|)
expr_stmt|;
break|break;
case|case
name|SIOC_HCI_RAW_NODE_GET_NEIGHBOR_CACHE
case|:
block|{
name|struct
name|ng_btsocket_hci_raw_node_neighbor_cache
modifier|*
name|p
init|=
operator|(
expr|struct
name|ng_btsocket_hci_raw_node_neighbor_cache
operator|*
operator|)
name|data
decl_stmt|;
name|ng_hci_node_get_neighbor_cache_ep
modifier|*
name|p1
init|=
name|NULL
decl_stmt|;
name|ng_hci_node_neighbor_cache_entry_ep
modifier|*
name|p2
init|=
name|NULL
decl_stmt|;
if|if
condition|(
name|p
operator|->
name|num_entries
operator|<=
literal|0
operator|||
name|p
operator|->
name|num_entries
operator|>
name|NG_HCI_MAX_NEIGHBOR_NUM
operator|||
name|p
operator|->
name|entries
operator|==
name|NULL
condition|)
block|{
name|error
operator|=
name|EINVAL
expr_stmt|;
break|break;
block|}
name|ng_btsocket_hci_raw_get_token
argument_list|(
operator|&
name|pcb
operator|->
name|token
argument_list|)
expr_stmt|;
name|pcb
operator|->
name|msg
operator|=
name|NULL
expr_stmt|;
name|NG_MKMESSAGE
argument_list|(
name|msg
argument_list|,
name|NGM_HCI_COOKIE
argument_list|,
name|NGM_HCI_NODE_GET_NEIGHBOR_CACHE
argument_list|,
literal|0
argument_list|,
name|M_WAITOK
argument_list|)
expr_stmt|;
if|if
condition|(
name|msg
operator|==
name|NULL
condition|)
block|{
name|pcb
operator|->
name|token
operator|=
literal|0
expr_stmt|;
name|error
operator|=
name|ENOMEM
expr_stmt|;
break|break;
block|}
name|msg
operator|->
name|header
operator|.
name|token
operator|=
name|pcb
operator|->
name|token
expr_stmt|;
name|NG_SEND_MSG_PATH
argument_list|(
name|error
argument_list|,
name|ng_btsocket_hci_raw_node
argument_list|,
name|msg
argument_list|,
name|path
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|error
operator|!=
literal|0
condition|)
block|{
name|pcb
operator|->
name|token
operator|=
literal|0
expr_stmt|;
break|break;
block|}
name|error
operator|=
name|tsleep
argument_list|(
operator|&
name|pcb
operator|->
name|msg
argument_list|,
name|PZERO
operator||
name|PCATCH
argument_list|,
literal|"hcictl"
argument_list|,
name|ng_btsocket_hci_raw_ioctl_timeout
operator|*
name|hz
argument_list|)
expr_stmt|;
if|if
condition|(
name|error
operator|!=
literal|0
condition|)
block|{
name|pcb
operator|->
name|token
operator|=
literal|0
expr_stmt|;
break|break;
block|}
if|if
condition|(
name|pcb
operator|->
name|msg
operator|!=
name|NULL
operator|&&
name|pcb
operator|->
name|msg
operator|->
name|header
operator|.
name|cmd
operator|==
name|NGM_HCI_NODE_GET_NEIGHBOR_CACHE
condition|)
block|{
comment|/* Return data back to user space */
name|p1
operator|=
operator|(
name|ng_hci_node_get_neighbor_cache_ep
operator|*
operator|)
operator|(
name|pcb
operator|->
name|msg
operator|->
name|data
operator|)
expr_stmt|;
name|p2
operator|=
operator|(
name|ng_hci_node_neighbor_cache_entry_ep
operator|*
operator|)
operator|(
name|p1
operator|+
literal|1
operator|)
expr_stmt|;
name|p
operator|->
name|num_entries
operator|=
name|min
argument_list|(
name|p
operator|->
name|num_entries
argument_list|,
name|p1
operator|->
name|num_entries
argument_list|)
expr_stmt|;
if|if
condition|(
name|p
operator|->
name|num_entries
operator|>
literal|0
condition|)
name|error
operator|=
name|copyout
argument_list|(
operator|(
name|caddr_t
operator|)
name|p2
argument_list|,
operator|(
name|caddr_t
operator|)
name|p
operator|->
name|entries
argument_list|,
name|p
operator|->
name|num_entries
operator|*
sizeof|sizeof
argument_list|(
operator|*
name|p2
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
name|error
operator|=
name|EINVAL
expr_stmt|;
name|NG_FREE_MSG
argument_list|(
name|pcb
operator|->
name|msg
argument_list|)
expr_stmt|;
comment|/* checks for != NULL */
name|pcb
operator|->
name|token
operator|=
literal|0
expr_stmt|;
block|}
break|break;
case|case
name|SIOC_HCI_RAW_NODE_GET_CON_LIST
case|:
block|{
name|struct
name|ng_btsocket_hci_raw_con_list
modifier|*
name|p
init|=
operator|(
expr|struct
name|ng_btsocket_hci_raw_con_list
operator|*
operator|)
name|data
decl_stmt|;
name|ng_hci_node_con_list_ep
modifier|*
name|p1
init|=
name|NULL
decl_stmt|;
name|ng_hci_node_con_ep
modifier|*
name|p2
init|=
name|NULL
decl_stmt|;
if|if
condition|(
name|p
operator|->
name|num_connections
operator|==
literal|0
operator|||
name|p
operator|->
name|num_connections
operator|>
name|NG_HCI_MAX_CON_NUM
operator|||
name|p
operator|->
name|connections
operator|==
name|NULL
condition|)
block|{
name|error
operator|=
name|EINVAL
expr_stmt|;
break|break;
block|}
name|ng_btsocket_hci_raw_get_token
argument_list|(
operator|&
name|pcb
operator|->
name|token
argument_list|)
expr_stmt|;
name|pcb
operator|->
name|msg
operator|=
name|NULL
expr_stmt|;
name|NG_MKMESSAGE
argument_list|(
name|msg
argument_list|,
name|NGM_HCI_COOKIE
argument_list|,
name|NGM_HCI_NODE_GET_CON_LIST
argument_list|,
literal|0
argument_list|,
name|M_WAITOK
argument_list|)
expr_stmt|;
if|if
condition|(
name|msg
operator|==
name|NULL
condition|)
block|{
name|pcb
operator|->
name|token
operator|=
literal|0
expr_stmt|;
name|error
operator|=
name|ENOMEM
expr_stmt|;
break|break;
block|}
name|msg
operator|->
name|header
operator|.
name|token
operator|=
name|pcb
operator|->
name|token
expr_stmt|;
name|NG_SEND_MSG_PATH
argument_list|(
name|error
argument_list|,
name|ng_btsocket_hci_raw_node
argument_list|,
name|msg
argument_list|,
name|path
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|error
operator|!=
literal|0
condition|)
block|{
name|pcb
operator|->
name|token
operator|=
literal|0
expr_stmt|;
break|break;
block|}
name|error
operator|=
name|tsleep
argument_list|(
operator|&
name|pcb
operator|->
name|msg
argument_list|,
name|PZERO
operator||
name|PCATCH
argument_list|,
literal|"hcictl"
argument_list|,
name|ng_btsocket_hci_raw_ioctl_timeout
operator|*
name|hz
argument_list|)
expr_stmt|;
if|if
condition|(
name|error
operator|!=
literal|0
condition|)
block|{
name|pcb
operator|->
name|token
operator|=
literal|0
expr_stmt|;
break|break;
block|}
if|if
condition|(
name|pcb
operator|->
name|msg
operator|!=
name|NULL
operator|&&
name|pcb
operator|->
name|msg
operator|->
name|header
operator|.
name|cmd
operator|==
name|NGM_HCI_NODE_GET_CON_LIST
condition|)
block|{
comment|/* Return data back to user space */
name|p1
operator|=
operator|(
name|ng_hci_node_con_list_ep
operator|*
operator|)
operator|(
name|pcb
operator|->
name|msg
operator|->
name|data
operator|)
expr_stmt|;
name|p2
operator|=
operator|(
name|ng_hci_node_con_ep
operator|*
operator|)
operator|(
name|p1
operator|+
literal|1
operator|)
expr_stmt|;
name|p
operator|->
name|num_connections
operator|=
name|min
argument_list|(
name|p
operator|->
name|num_connections
argument_list|,
name|p1
operator|->
name|num_connections
argument_list|)
expr_stmt|;
if|if
condition|(
name|p
operator|->
name|num_connections
operator|>
literal|0
condition|)
name|error
operator|=
name|copyout
argument_list|(
operator|(
name|caddr_t
operator|)
name|p2
argument_list|,
operator|(
name|caddr_t
operator|)
name|p
operator|->
name|connections
argument_list|,
name|p
operator|->
name|num_connections
operator|*
sizeof|sizeof
argument_list|(
operator|*
name|p2
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
name|error
operator|=
name|EINVAL
expr_stmt|;
name|NG_FREE_MSG
argument_list|(
name|pcb
operator|->
name|msg
argument_list|)
expr_stmt|;
comment|/* checks for != NULL */
name|pcb
operator|->
name|token
operator|=
literal|0
expr_stmt|;
block|}
break|break;
case|case
name|SIOC_HCI_RAW_NODE_GET_LINK_POLICY_MASK
case|:
block|{
name|struct
name|ng_btsocket_hci_raw_node_link_policy_mask
modifier|*
name|p
init|=
operator|(
expr|struct
name|ng_btsocket_hci_raw_node_link_policy_mask
operator|*
operator|)
name|data
decl_stmt|;
name|error
operator|=
name|ng_btsocket_raw_send_sync_ngmsg
argument_list|(
name|pcb
argument_list|,
name|path
argument_list|,
name|NGM_HCI_NODE_GET_LINK_POLICY_SETTINGS_MASK
argument_list|,
operator|&
name|p
operator|->
name|policy_mask
argument_list|,
sizeof|sizeof
argument_list|(
name|p
operator|->
name|policy_mask
argument_list|)
argument_list|)
expr_stmt|;
block|}
break|break;
case|case
name|SIOC_HCI_RAW_NODE_SET_LINK_POLICY_MASK
case|:
block|{
name|struct
name|ng_btsocket_hci_raw_node_link_policy_mask
modifier|*
name|p
init|=
operator|(
expr|struct
name|ng_btsocket_hci_raw_node_link_policy_mask
operator|*
operator|)
name|data
decl_stmt|;
name|error
operator|=
name|ng_btsocket_raw_send_ngmsg
argument_list|(
name|path
argument_list|,
name|NGM_HCI_NODE_SET_LINK_POLICY_SETTINGS_MASK
argument_list|,
operator|&
name|p
operator|->
name|policy_mask
argument_list|,
sizeof|sizeof
argument_list|(
name|p
operator|->
name|policy_mask
argument_list|)
argument_list|)
expr_stmt|;
block|}
break|break;
case|case
name|SIOC_HCI_RAW_NODE_GET_PACKET_MASK
case|:
block|{
name|struct
name|ng_btsocket_hci_raw_node_packet_mask
modifier|*
name|p
init|=
operator|(
expr|struct
name|ng_btsocket_hci_raw_node_packet_mask
operator|*
operator|)
name|data
decl_stmt|;
name|error
operator|=
name|ng_btsocket_raw_send_sync_ngmsg
argument_list|(
name|pcb
argument_list|,
name|path
argument_list|,
name|NGM_HCI_NODE_GET_PACKET_MASK
argument_list|,
operator|&
name|p
operator|->
name|packet_mask
argument_list|,
sizeof|sizeof
argument_list|(
name|p
operator|->
name|packet_mask
argument_list|)
argument_list|)
expr_stmt|;
block|}
break|break;
case|case
name|SIOC_HCI_RAW_NODE_SET_PACKET_MASK
case|:
block|{
name|struct
name|ng_btsocket_hci_raw_node_packet_mask
modifier|*
name|p
init|=
operator|(
expr|struct
name|ng_btsocket_hci_raw_node_packet_mask
operator|*
operator|)
name|data
decl_stmt|;
name|error
operator|=
name|ng_btsocket_raw_send_ngmsg
argument_list|(
name|path
argument_list|,
name|NGM_HCI_NODE_SET_PACKET_MASK
argument_list|,
operator|&
name|p
operator|->
name|packet_mask
argument_list|,
sizeof|sizeof
argument_list|(
name|p
operator|->
name|packet_mask
argument_list|)
argument_list|)
expr_stmt|;
block|}
break|break;
default|default:
name|error
operator|=
name|EINVAL
expr_stmt|;
break|break;
block|}
return|return
operator|(
name|error
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_control */
end_comment

begin_comment
comment|/*  * Process getsockopt/setsockopt system calls  */
end_comment

begin_function
name|int
name|ng_btsocket_hci_raw_ctloutput
parameter_list|(
name|struct
name|socket
modifier|*
name|so
parameter_list|,
name|struct
name|sockopt
modifier|*
name|sopt
parameter_list|)
block|{
name|ng_btsocket_hci_raw_pcb_p
name|pcb
init|=
name|so2hci_raw_pcb
argument_list|(
name|so
argument_list|)
decl_stmt|;
name|struct
name|ng_btsocket_hci_raw_filter
name|filter
decl_stmt|;
name|int
name|error
init|=
literal|0
decl_stmt|,
name|dir
decl_stmt|;
if|if
condition|(
name|pcb
operator|==
name|NULL
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
if|if
condition|(
name|ng_btsocket_hci_raw_node
operator|==
name|NULL
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
if|if
condition|(
name|sopt
operator|->
name|sopt_level
operator|!=
name|SOL_HCI_RAW
condition|)
return|return
operator|(
literal|0
operator|)
return|;
switch|switch
condition|(
name|sopt
operator|->
name|sopt_dir
condition|)
block|{
case|case
name|SOPT_GET
case|:
switch|switch
condition|(
name|sopt
operator|->
name|sopt_name
condition|)
block|{
case|case
name|SO_HCI_RAW_FILTER
case|:
name|error
operator|=
name|sooptcopyout
argument_list|(
name|sopt
argument_list|,
operator|&
name|pcb
operator|->
name|filter
argument_list|,
sizeof|sizeof
argument_list|(
name|pcb
operator|->
name|filter
argument_list|)
argument_list|)
expr_stmt|;
break|break;
case|case
name|SO_HCI_RAW_DIRECTION
case|:
name|dir
operator|=
operator|(
name|pcb
operator|->
name|flags
operator|&
name|NG_BTSOCKET_HCI_RAW_DIRECTION
operator|)
condition|?
literal|1
else|:
literal|0
expr_stmt|;
name|error
operator|=
name|sooptcopyout
argument_list|(
name|sopt
argument_list|,
operator|&
name|dir
argument_list|,
sizeof|sizeof
argument_list|(
name|dir
argument_list|)
argument_list|)
expr_stmt|;
break|break;
default|default:
name|error
operator|=
name|EINVAL
expr_stmt|;
break|break;
block|}
break|break;
case|case
name|SOPT_SET
case|:
switch|switch
condition|(
name|sopt
operator|->
name|sopt_name
condition|)
block|{
case|case
name|SO_HCI_RAW_FILTER
case|:
name|error
operator|=
name|sooptcopyin
argument_list|(
name|sopt
argument_list|,
operator|&
name|filter
argument_list|,
sizeof|sizeof
argument_list|(
name|filter
argument_list|)
argument_list|,
sizeof|sizeof
argument_list|(
name|filter
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|error
operator|==
literal|0
condition|)
name|bcopy
argument_list|(
operator|&
name|filter
argument_list|,
operator|&
name|pcb
operator|->
name|filter
argument_list|,
sizeof|sizeof
argument_list|(
name|pcb
operator|->
name|filter
argument_list|)
argument_list|)
expr_stmt|;
break|break;
case|case
name|SO_HCI_RAW_DIRECTION
case|:
name|error
operator|=
name|sooptcopyin
argument_list|(
name|sopt
argument_list|,
operator|&
name|dir
argument_list|,
sizeof|sizeof
argument_list|(
name|dir
argument_list|)
argument_list|,
sizeof|sizeof
argument_list|(
name|dir
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|error
operator|!=
literal|0
condition|)
break|break;
if|if
condition|(
name|dir
condition|)
name|pcb
operator|->
name|flags
operator||=
name|NG_BTSOCKET_HCI_RAW_DIRECTION
expr_stmt|;
else|else
name|pcb
operator|->
name|flags
operator|&=
operator|~
name|NG_BTSOCKET_HCI_RAW_DIRECTION
expr_stmt|;
break|break;
default|default:
name|error
operator|=
name|EINVAL
expr_stmt|;
break|break;
block|}
break|break;
default|default:
name|error
operator|=
name|EINVAL
expr_stmt|;
break|break;
block|}
return|return
operator|(
name|error
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_ctloutput */
end_comment

begin_comment
comment|/*  * Detach raw HCI socket  */
end_comment

begin_function
name|int
name|ng_btsocket_hci_raw_detach
parameter_list|(
name|struct
name|socket
modifier|*
name|so
parameter_list|)
block|{
name|ng_btsocket_hci_raw_pcb_p
name|pcb
init|=
name|so2hci_raw_pcb
argument_list|(
name|so
argument_list|)
decl_stmt|;
if|if
condition|(
name|pcb
operator|==
name|NULL
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
if|if
condition|(
name|ng_btsocket_hci_raw_node
operator|==
name|NULL
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
name|so
operator|->
name|so_pcb
operator|=
name|NULL
expr_stmt|;
name|sotryfree
argument_list|(
name|so
argument_list|)
expr_stmt|;
name|mtx_lock
argument_list|(
operator|&
name|ng_btsocket_hci_raw_sockets_mtx
argument_list|)
expr_stmt|;
name|LIST_REMOVE
argument_list|(
name|pcb
argument_list|,
name|next
argument_list|)
expr_stmt|;
name|mtx_unlock
argument_list|(
operator|&
name|ng_btsocket_hci_raw_sockets_mtx
argument_list|)
expr_stmt|;
name|bzero
argument_list|(
name|pcb
argument_list|,
sizeof|sizeof
argument_list|(
operator|*
name|pcb
argument_list|)
argument_list|)
expr_stmt|;
name|FREE
argument_list|(
name|pcb
argument_list|,
name|M_NETGRAPH_BTSOCKET_HCI_RAW
argument_list|)
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_detach */
end_comment

begin_comment
comment|/*  * Disconnect raw HCI socket  */
end_comment

begin_function
name|int
name|ng_btsocket_hci_raw_disconnect
parameter_list|(
name|struct
name|socket
modifier|*
name|so
parameter_list|)
block|{
name|ng_btsocket_hci_raw_pcb_p
name|pcb
init|=
name|so2hci_raw_pcb
argument_list|(
name|so
argument_list|)
decl_stmt|;
if|if
condition|(
name|pcb
operator|==
name|NULL
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
if|if
condition|(
name|ng_btsocket_hci_raw_node
operator|==
name|NULL
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
name|soisdisconnected
argument_list|(
name|so
argument_list|)
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_disconnect */
end_comment

begin_comment
comment|/*  * Get socket peer's address  */
end_comment

begin_function
name|int
name|ng_btsocket_hci_raw_peeraddr
parameter_list|(
name|struct
name|socket
modifier|*
name|so
parameter_list|,
name|struct
name|sockaddr
modifier|*
modifier|*
name|nam
parameter_list|)
block|{
return|return
operator|(
name|EOPNOTSUPP
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_peeraddr */
end_comment

begin_comment
comment|/*  * Send data  */
end_comment

begin_function
name|int
name|ng_btsocket_hci_raw_send
parameter_list|(
name|struct
name|socket
modifier|*
name|so
parameter_list|,
name|int
name|flags
parameter_list|,
name|struct
name|mbuf
modifier|*
name|m
parameter_list|,
name|struct
name|sockaddr
modifier|*
name|sa
parameter_list|,
name|struct
name|mbuf
modifier|*
name|control
parameter_list|,
name|struct
name|thread
modifier|*
name|td
parameter_list|)
block|{
name|ng_btsocket_hci_raw_pcb_p
name|pcb
init|=
name|so2hci_raw_pcb
argument_list|(
name|so
argument_list|)
decl_stmt|;
name|struct
name|mbuf
modifier|*
name|nam
init|=
name|NULL
decl_stmt|;
name|int
name|error
init|=
literal|0
decl_stmt|;
if|if
condition|(
name|ng_btsocket_hci_raw_node
operator|==
name|NULL
condition|)
block|{
name|error
operator|=
name|ENETDOWN
expr_stmt|;
goto|goto
name|drop
goto|;
block|}
if|if
condition|(
name|pcb
operator|==
name|NULL
condition|)
block|{
name|error
operator|=
name|EINVAL
expr_stmt|;
goto|goto
name|drop
goto|;
block|}
if|if
condition|(
name|control
operator|!=
name|NULL
condition|)
block|{
name|error
operator|=
name|EINVAL
expr_stmt|;
goto|goto
name|drop
goto|;
block|}
if|if
condition|(
name|m
operator|->
name|m_pkthdr
operator|.
name|len
operator|<
sizeof|sizeof
argument_list|(
name|ng_hci_cmd_pkt_t
argument_list|)
operator|||
name|m
operator|->
name|m_pkthdr
operator|.
name|len
operator|>
sizeof|sizeof
argument_list|(
name|ng_hci_cmd_pkt_t
argument_list|)
operator|+
name|NG_HCI_CMD_PKT_SIZE
condition|)
block|{
name|error
operator|=
name|EMSGSIZE
expr_stmt|;
goto|goto
name|drop
goto|;
block|}
if|if
condition|(
name|sa
operator|==
name|NULL
condition|)
block|{
if|if
condition|(
name|pcb
operator|->
name|addr
operator|.
name|hci_node
index|[
literal|0
index|]
operator|==
literal|0
condition|)
block|{
name|error
operator|=
name|EDESTADDRREQ
expr_stmt|;
goto|goto
name|drop
goto|;
block|}
name|sa
operator|=
operator|(
expr|struct
name|sockaddr
operator|*
operator|)
operator|&
name|pcb
operator|->
name|addr
expr_stmt|;
block|}
name|MGET
argument_list|(
name|nam
argument_list|,
name|M_TRYWAIT
argument_list|,
name|MT_SONAME
argument_list|)
expr_stmt|;
if|if
condition|(
name|nam
operator|==
name|NULL
condition|)
block|{
name|error
operator|=
name|ENOBUFS
expr_stmt|;
goto|goto
name|drop
goto|;
block|}
name|nam
operator|->
name|m_len
operator|=
sizeof|sizeof
argument_list|(
expr|struct
name|sockaddr_hci
argument_list|)
expr_stmt|;
name|bcopy
argument_list|(
name|sa
argument_list|,
name|mtod
argument_list|(
name|nam
argument_list|,
expr|struct
name|sockaddr_hci
operator|*
argument_list|)
argument_list|,
sizeof|sizeof
argument_list|(
expr|struct
name|sockaddr_hci
argument_list|)
argument_list|)
expr_stmt|;
name|nam
operator|->
name|m_next
operator|=
name|m
expr_stmt|;
name|m
operator|=
name|NULL
expr_stmt|;
return|return
operator|(
name|ng_send_fn
argument_list|(
name|ng_btsocket_hci_raw_node
argument_list|,
name|NULL
argument_list|,
name|ng_btsocket_hci_raw_output
argument_list|,
name|nam
argument_list|,
literal|0
argument_list|)
operator|)
return|;
name|drop
label|:
name|NG_FREE_M
argument_list|(
name|control
argument_list|)
expr_stmt|;
comment|/* NG_FREE_M checks for != NULL */
name|NG_FREE_M
argument_list|(
name|nam
argument_list|)
expr_stmt|;
name|NG_FREE_M
argument_list|(
name|m
argument_list|)
expr_stmt|;
return|return
operator|(
name|error
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_send */
end_comment

begin_comment
comment|/*  * Get socket address  */
end_comment

begin_function
name|int
name|ng_btsocket_hci_raw_sockaddr
parameter_list|(
name|struct
name|socket
modifier|*
name|so
parameter_list|,
name|struct
name|sockaddr
modifier|*
modifier|*
name|nam
parameter_list|)
block|{
name|ng_btsocket_hci_raw_pcb_p
name|pcb
init|=
name|so2hci_raw_pcb
argument_list|(
name|so
argument_list|)
decl_stmt|;
name|struct
name|sockaddr_hci
name|sa
decl_stmt|;
if|if
condition|(
name|pcb
operator|==
name|NULL
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
if|if
condition|(
name|ng_btsocket_hci_raw_node
operator|==
name|NULL
condition|)
return|return
operator|(
name|EINVAL
operator|)
return|;
name|bzero
argument_list|(
operator|&
name|sa
argument_list|,
sizeof|sizeof
argument_list|(
name|sa
argument_list|)
argument_list|)
expr_stmt|;
name|sa
operator|.
name|hci_len
operator|=
sizeof|sizeof
argument_list|(
name|sa
argument_list|)
expr_stmt|;
name|sa
operator|.
name|hci_family
operator|=
name|AF_BLUETOOTH
expr_stmt|;
name|strncpy
argument_list|(
name|sa
operator|.
name|hci_node
argument_list|,
name|pcb
operator|->
name|addr
operator|.
name|hci_node
argument_list|,
sizeof|sizeof
argument_list|(
name|sa
operator|.
name|hci_node
argument_list|)
argument_list|)
expr_stmt|;
operator|*
name|nam
operator|=
name|dup_sockaddr
argument_list|(
operator|(
expr|struct
name|sockaddr
operator|*
operator|)
operator|&
name|sa
argument_list|,
literal|0
argument_list|)
expr_stmt|;
return|return
operator|(
operator|(
operator|*
name|nam
operator|==
name|NULL
operator|)
condition|?
name|ENOMEM
else|:
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/* ng_btsocket_hci_raw_sockaddr */
end_comment

end_unit

