begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*-  * Copyright (c) 2002 Ian Dowse.  All rights reserved.  *  * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions  * are met:  * 1. Redistributions of source code must retain the above copyright  *    notice, this list of conditions and the following disclaimer.  * 2. Redistributions in binary form must reproduce the above copyright  *    notice, this list of conditions and the following disclaimer in the  *    documentation and/or other materials provided with the distribution.  *  * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND  * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE  * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS  * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)  * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT  * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY  * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF  * SUCH DAMAGE.  *  * $FreeBSD$  */
end_comment

begin_ifndef
ifndef|#
directive|ifndef
name|_SYS_SYSCALLSUBR_H_
end_ifndef

begin_define
define|#
directive|define
name|_SYS_SYSCALLSUBR_H_
end_define

begin_include
include|#
directive|include
file|<sys/signal.h>
end_include

begin_include
include|#
directive|include
file|<sys/uio.h>
end_include

begin_include
include|#
directive|include
file|<sys/socket.h>
end_include

begin_struct_decl
struct_decl|struct
name|mbuf
struct_decl|;
end_struct_decl

begin_struct_decl
struct_decl|struct
name|msghdr
struct_decl|;
end_struct_decl

begin_struct_decl
struct_decl|struct
name|sockaddr
struct_decl|;
end_struct_decl

begin_struct_decl
struct_decl|struct
name|kevent
struct_decl|;
end_struct_decl

begin_function_decl
name|int
name|kern___getcwd
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|u_char
modifier|*
name|buf
parameter_list|,
name|enum
name|uio_seg
name|bufseg
parameter_list|,
name|u_int
name|buflen
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_access
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|enum
name|uio_seg
name|pathseg
parameter_list|,
name|int
name|flags
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_adjtime
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|struct
name|timeval
modifier|*
name|delta
parameter_list|,
name|struct
name|timeval
modifier|*
name|olddelta
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_bind
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|int
name|fd
parameter_list|,
name|struct
name|sockaddr
modifier|*
name|sa
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_chdir
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|enum
name|uio_seg
name|pathseg
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_chmod
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|enum
name|uio_seg
name|pathseg
parameter_list|,
name|int
name|mode
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_chown
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|enum
name|uio_seg
name|pathseg
parameter_list|,
name|int
name|uid
parameter_list|,
name|int
name|gid
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_connect
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|int
name|fd
parameter_list|,
name|struct
name|sockaddr
modifier|*
name|sa
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_fcntl
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|int
name|fd
parameter_list|,
name|int
name|cmd
parameter_list|,
name|intptr_t
name|arg
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_futimes
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|int
name|fd
parameter_list|,
name|struct
name|timeval
modifier|*
name|tptr
parameter_list|,
name|enum
name|uio_seg
name|tptrseg
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_getsockopt
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|int
name|s
parameter_list|,
name|int
name|level
parameter_list|,
name|int
name|name
parameter_list|,
name|void
modifier|*
name|optval
parameter_list|,
name|enum
name|uio_seg
name|valseg
parameter_list|,
name|socklen_t
modifier|*
name|valsize
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_kevent
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|int
name|fd
parameter_list|,
name|struct
name|kevent
modifier|*
name|changelist
parameter_list|,
name|int
name|nchanges
parameter_list|,
name|enum
name|uio_seg
name|changeseg
parameter_list|,
name|struct
name|kevent
modifier|*
name|eventlist
parameter_list|,
name|int
name|nevents
parameter_list|,
name|enum
name|uio_seg
name|eventseg
parameter_list|,
specifier|const
name|struct
name|timespec
modifier|*
name|timeout
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_lchown
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|enum
name|uio_seg
name|pathseg
parameter_list|,
name|int
name|uid
parameter_list|,
name|int
name|gid
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_link
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|char
modifier|*
name|link
parameter_list|,
name|enum
name|uio_seg
name|segflg
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_lutimes
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|enum
name|uio_seg
name|pathseg
parameter_list|,
name|struct
name|timeval
modifier|*
name|tptr
parameter_list|,
name|enum
name|uio_seg
name|tptrseg
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_mkdir
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|enum
name|uio_seg
name|segflg
parameter_list|,
name|int
name|mode
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_mkfifo
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|enum
name|uio_seg
name|pathseg
parameter_list|,
name|int
name|mode
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_mknod
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|enum
name|uio_seg
name|pathseg
parameter_list|,
name|int
name|mode
parameter_list|,
name|int
name|dev
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_nanosleep
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|struct
name|timespec
modifier|*
name|rqt
parameter_list|,
name|struct
name|timespec
modifier|*
name|rmt
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_open
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|enum
name|uio_seg
name|pathseg
parameter_list|,
name|int
name|flags
parameter_list|,
name|int
name|mode
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_ptrace
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|int
name|req
parameter_list|,
name|pid_t
name|pid
parameter_list|,
name|void
modifier|*
name|addr
parameter_list|,
name|int
name|data
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_readlink
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|enum
name|uio_seg
name|pathseg
parameter_list|,
name|char
modifier|*
name|buf
parameter_list|,
name|enum
name|uio_seg
name|bufseg
parameter_list|,
name|int
name|count
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_readv
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|int
name|fd
parameter_list|,
name|struct
name|uio
modifier|*
name|auio
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_rename
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|from
parameter_list|,
name|char
modifier|*
name|to
parameter_list|,
name|enum
name|uio_seg
name|pathseg
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_rmdir
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|enum
name|uio_seg
name|pathseg
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_sched_rr_get_interval
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|pid_t
name|pid
parameter_list|,
name|struct
name|timespec
modifier|*
name|ts
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_select
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|int
name|nd
parameter_list|,
name|fd_set
modifier|*
name|fd_in
parameter_list|,
name|fd_set
modifier|*
name|fd_ou
parameter_list|,
name|fd_set
modifier|*
name|fd_ex
parameter_list|,
name|struct
name|timeval
modifier|*
name|tvp
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_sendit
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|int
name|s
parameter_list|,
name|struct
name|msghdr
modifier|*
name|mp
parameter_list|,
name|int
name|flags
parameter_list|,
name|struct
name|mbuf
modifier|*
name|control
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_setsockopt
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|int
name|s
parameter_list|,
name|int
name|level
parameter_list|,
name|int
name|name
parameter_list|,
name|void
modifier|*
name|optval
parameter_list|,
name|enum
name|uio_seg
name|valseg
parameter_list|,
name|socklen_t
name|valsize
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_settimeofday
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|struct
name|timeval
modifier|*
name|tv
parameter_list|,
name|struct
name|timezone
modifier|*
name|tzp
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_shmat
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|int
name|shmid
parameter_list|,
specifier|const
name|void
modifier|*
name|shmaddr
parameter_list|,
name|int
name|shmflg
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_shmctl
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|int
name|shmid
parameter_list|,
name|int
name|cmd
parameter_list|,
name|void
modifier|*
name|buf
parameter_list|,
name|size_t
modifier|*
name|bufsz
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_sigaction
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|int
name|sig
parameter_list|,
name|struct
name|sigaction
modifier|*
name|act
parameter_list|,
name|struct
name|sigaction
modifier|*
name|oact
parameter_list|,
name|int
name|flags
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_sigaltstack
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|stack_t
modifier|*
name|ss
parameter_list|,
name|stack_t
modifier|*
name|oss
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_sigprocmask
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|int
name|how
parameter_list|,
name|sigset_t
modifier|*
name|set
parameter_list|,
name|sigset_t
modifier|*
name|oset
parameter_list|,
name|int
name|old
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_sigsuspend
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|sigset_t
name|mask
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_symlink
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|char
modifier|*
name|link
parameter_list|,
name|enum
name|uio_seg
name|segflg
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_truncate
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|enum
name|uio_seg
name|pathseg
parameter_list|,
name|off_t
name|length
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_unlink
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|enum
name|uio_seg
name|pathseg
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_utimes
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|char
modifier|*
name|path
parameter_list|,
name|enum
name|uio_seg
name|pathseg
parameter_list|,
name|struct
name|timeval
modifier|*
name|tptr
parameter_list|,
name|enum
name|uio_seg
name|tptrseg
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|kern_writev
parameter_list|(
name|struct
name|thread
modifier|*
name|td
parameter_list|,
name|int
name|fd
parameter_list|,
name|struct
name|uio
modifier|*
name|auio
parameter_list|)
function_decl|;
end_function_decl

begin_comment
comment|/* flags for kern_sigaction */
end_comment

begin_define
define|#
directive|define
name|KSA_OSIGSET
value|0x0001
end_define

begin_comment
comment|/* uses osigact_t */
end_comment

begin_define
define|#
directive|define
name|KSA_FREEBSD4
value|0x0002
end_define

begin_comment
comment|/* uses ucontext4 */
end_comment

begin_endif
endif|#
directive|endif
end_endif

begin_comment
comment|/* !_SYS_SYSCALLSUBR_H_ */
end_comment

end_unit

