begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* $XConsortium: StringDefs.h,v 1.52 91/05/04 20:57:56 rws Exp $ */
end_comment

begin_comment
comment|/* This file is automatically generated. */
end_comment

begin_comment
comment|/* Do not edit. */
end_comment

begin_ifndef
ifndef|#
directive|ifndef
name|_XtStringDefs_h_
end_ifndef

begin_define
define|#
directive|define
name|_XtStringDefs_h_
end_define

begin_ifdef
ifdef|#
directive|ifdef
name|XTSTRINGDEFINES
end_ifdef

begin_define
define|#
directive|define
name|XtNaccelerators
value|"accelerators"
end_define

begin_define
define|#
directive|define
name|XtNallowHoriz
value|"allowHoriz"
end_define

begin_define
define|#
directive|define
name|XtNallowVert
value|"allowVert"
end_define

begin_define
define|#
directive|define
name|XtNancestorSensitive
value|"ancestorSensitive"
end_define

begin_define
define|#
directive|define
name|XtNbackground
value|"background"
end_define

begin_define
define|#
directive|define
name|XtNbackgroundPixmap
value|"backgroundPixmap"
end_define

begin_define
define|#
directive|define
name|XtNbitmap
value|"bitmap"
end_define

begin_define
define|#
directive|define
name|XtNborderColor
value|"borderColor"
end_define

begin_define
define|#
directive|define
name|XtNborder
value|"borderColor"
end_define

begin_define
define|#
directive|define
name|XtNborderPixmap
value|"borderPixmap"
end_define

begin_define
define|#
directive|define
name|XtNborderWidth
value|"borderWidth"
end_define

begin_define
define|#
directive|define
name|XtNcallback
value|"callback"
end_define

begin_define
define|#
directive|define
name|XtNchildren
value|"children"
end_define

begin_define
define|#
directive|define
name|XtNcolormap
value|"colormap"
end_define

begin_define
define|#
directive|define
name|XtNdepth
value|"depth"
end_define

begin_define
define|#
directive|define
name|XtNdestroyCallback
value|"destroyCallback"
end_define

begin_define
define|#
directive|define
name|XtNeditType
value|"editType"
end_define

begin_define
define|#
directive|define
name|XtNfile
value|"file"
end_define

begin_define
define|#
directive|define
name|XtNfont
value|"font"
end_define

begin_define
define|#
directive|define
name|XtNforceBars
value|"forceBars"
end_define

begin_define
define|#
directive|define
name|XtNforeground
value|"foreground"
end_define

begin_define
define|#
directive|define
name|XtNfunction
value|"function"
end_define

begin_define
define|#
directive|define
name|XtNheight
value|"height"
end_define

begin_define
define|#
directive|define
name|XtNhighlight
value|"highlight"
end_define

begin_define
define|#
directive|define
name|XtNhSpace
value|"hSpace"
end_define

begin_define
define|#
directive|define
name|XtNindex
value|"index"
end_define

begin_define
define|#
directive|define
name|XtNinitialResourcesPersistent
value|"initialResourcesPersistent"
end_define

begin_define
define|#
directive|define
name|XtNinnerHeight
value|"innerHeight"
end_define

begin_define
define|#
directive|define
name|XtNinnerWidth
value|"innerWidth"
end_define

begin_define
define|#
directive|define
name|XtNinnerWindow
value|"innerWindow"
end_define

begin_define
define|#
directive|define
name|XtNinsertPosition
value|"insertPosition"
end_define

begin_define
define|#
directive|define
name|XtNinternalHeight
value|"internalHeight"
end_define

begin_define
define|#
directive|define
name|XtNinternalWidth
value|"internalWidth"
end_define

begin_define
define|#
directive|define
name|XtNjumpProc
value|"jumpProc"
end_define

begin_define
define|#
directive|define
name|XtNjustify
value|"justify"
end_define

begin_define
define|#
directive|define
name|XtNknobHeight
value|"knobHeight"
end_define

begin_define
define|#
directive|define
name|XtNknobIndent
value|"knobIndent"
end_define

begin_define
define|#
directive|define
name|XtNknobPixel
value|"knobPixel"
end_define

begin_define
define|#
directive|define
name|XtNknobWidth
value|"knobWidth"
end_define

begin_define
define|#
directive|define
name|XtNlabel
value|"label"
end_define

begin_define
define|#
directive|define
name|XtNlength
value|"length"
end_define

begin_define
define|#
directive|define
name|XtNlowerRight
value|"lowerRight"
end_define

begin_define
define|#
directive|define
name|XtNmappedWhenManaged
value|"mappedWhenManaged"
end_define

begin_define
define|#
directive|define
name|XtNmenuEntry
value|"menuEntry"
end_define

begin_define
define|#
directive|define
name|XtNname
value|"name"
end_define

begin_define
define|#
directive|define
name|XtNnotify
value|"notify"
end_define

begin_define
define|#
directive|define
name|XtNnumChildren
value|"numChildren"
end_define

begin_define
define|#
directive|define
name|XtNorientation
value|"orientation"
end_define

begin_define
define|#
directive|define
name|XtNparameter
value|"parameter"
end_define

begin_define
define|#
directive|define
name|XtNpixmap
value|"pixmap"
end_define

begin_define
define|#
directive|define
name|XtNpopupCallback
value|"popupCallback"
end_define

begin_define
define|#
directive|define
name|XtNpopdownCallback
value|"popdownCallback"
end_define

begin_define
define|#
directive|define
name|XtNresize
value|"resize"
end_define

begin_define
define|#
directive|define
name|XtNreverseVideo
value|"reverseVideo"
end_define

begin_define
define|#
directive|define
name|XtNscreen
value|"screen"
end_define

begin_define
define|#
directive|define
name|XtNscrollProc
value|"scrollProc"
end_define

begin_define
define|#
directive|define
name|XtNscrollDCursor
value|"scrollDCursor"
end_define

begin_define
define|#
directive|define
name|XtNscrollHCursor
value|"scrollHCursor"
end_define

begin_define
define|#
directive|define
name|XtNscrollLCursor
value|"scrollLCursor"
end_define

begin_define
define|#
directive|define
name|XtNscrollRCursor
value|"scrollRCursor"
end_define

begin_define
define|#
directive|define
name|XtNscrollUCursor
value|"scrollUCursor"
end_define

begin_define
define|#
directive|define
name|XtNscrollVCursor
value|"scrollVCursor"
end_define

begin_define
define|#
directive|define
name|XtNselection
value|"selection"
end_define

begin_define
define|#
directive|define
name|XtNselectionArray
value|"selectionArray"
end_define

begin_define
define|#
directive|define
name|XtNsensitive
value|"sensitive"
end_define

begin_define
define|#
directive|define
name|XtNshown
value|"shown"
end_define

begin_define
define|#
directive|define
name|XtNspace
value|"space"
end_define

begin_define
define|#
directive|define
name|XtNstring
value|"string"
end_define

begin_define
define|#
directive|define
name|XtNtextOptions
value|"textOptions"
end_define

begin_define
define|#
directive|define
name|XtNtextSink
value|"textSink"
end_define

begin_define
define|#
directive|define
name|XtNtextSource
value|"textSource"
end_define

begin_define
define|#
directive|define
name|XtNthickness
value|"thickness"
end_define

begin_define
define|#
directive|define
name|XtNthumb
value|"thumb"
end_define

begin_define
define|#
directive|define
name|XtNthumbProc
value|"thumbProc"
end_define

begin_define
define|#
directive|define
name|XtNtop
value|"top"
end_define

begin_define
define|#
directive|define
name|XtNtranslations
value|"translations"
end_define

begin_define
define|#
directive|define
name|XtNunrealizeCallback
value|"unrealizeCallback"
end_define

begin_define
define|#
directive|define
name|XtNupdate
value|"update"
end_define

begin_define
define|#
directive|define
name|XtNuseBottom
value|"useBottom"
end_define

begin_define
define|#
directive|define
name|XtNuseRight
value|"useRight"
end_define

begin_define
define|#
directive|define
name|XtNvalue
value|"value"
end_define

begin_define
define|#
directive|define
name|XtNvSpace
value|"vSpace"
end_define

begin_define
define|#
directive|define
name|XtNwidth
value|"width"
end_define

begin_define
define|#
directive|define
name|XtNwindow
value|"window"
end_define

begin_define
define|#
directive|define
name|XtNx
value|"x"
end_define

begin_define
define|#
directive|define
name|XtNy
value|"y"
end_define

begin_define
define|#
directive|define
name|XtCAccelerators
value|"Accelerators"
end_define

begin_define
define|#
directive|define
name|XtCBackground
value|"Background"
end_define

begin_define
define|#
directive|define
name|XtCBitmap
value|"Bitmap"
end_define

begin_define
define|#
directive|define
name|XtCBoolean
value|"Boolean"
end_define

begin_define
define|#
directive|define
name|XtCBorderColor
value|"BorderColor"
end_define

begin_define
define|#
directive|define
name|XtCBorderWidth
value|"BorderWidth"
end_define

begin_define
define|#
directive|define
name|XtCCallback
value|"Callback"
end_define

begin_define
define|#
directive|define
name|XtCColormap
value|"Colormap"
end_define

begin_define
define|#
directive|define
name|XtCColor
value|"Color"
end_define

begin_define
define|#
directive|define
name|XtCCursor
value|"Cursor"
end_define

begin_define
define|#
directive|define
name|XtCDepth
value|"Depth"
end_define

begin_define
define|#
directive|define
name|XtCEditType
value|"EditType"
end_define

begin_define
define|#
directive|define
name|XtCEventBindings
value|"EventBindings"
end_define

begin_define
define|#
directive|define
name|XtCFile
value|"File"
end_define

begin_define
define|#
directive|define
name|XtCFont
value|"Font"
end_define

begin_define
define|#
directive|define
name|XtCForeground
value|"Foreground"
end_define

begin_define
define|#
directive|define
name|XtCFraction
value|"Fraction"
end_define

begin_define
define|#
directive|define
name|XtCFunction
value|"Function"
end_define

begin_define
define|#
directive|define
name|XtCHeight
value|"Height"
end_define

begin_define
define|#
directive|define
name|XtCHSpace
value|"HSpace"
end_define

begin_define
define|#
directive|define
name|XtCIndex
value|"Index"
end_define

begin_define
define|#
directive|define
name|XtCInitialResourcesPersistent
value|"InitialResourcesPersistent"
end_define

begin_define
define|#
directive|define
name|XtCInsertPosition
value|"InsertPosition"
end_define

begin_define
define|#
directive|define
name|XtCInterval
value|"Interval"
end_define

begin_define
define|#
directive|define
name|XtCJustify
value|"Justify"
end_define

begin_define
define|#
directive|define
name|XtCKnobIndent
value|"KnobIndent"
end_define

begin_define
define|#
directive|define
name|XtCKnobPixel
value|"KnobPixel"
end_define

begin_define
define|#
directive|define
name|XtCLabel
value|"Label"
end_define

begin_define
define|#
directive|define
name|XtCLength
value|"Length"
end_define

begin_define
define|#
directive|define
name|XtCMappedWhenManaged
value|"MappedWhenManaged"
end_define

begin_define
define|#
directive|define
name|XtCMargin
value|"Margin"
end_define

begin_define
define|#
directive|define
name|XtCMenuEntry
value|"MenuEntry"
end_define

begin_define
define|#
directive|define
name|XtCNotify
value|"Notify"
end_define

begin_define
define|#
directive|define
name|XtCOrientation
value|"Orientation"
end_define

begin_define
define|#
directive|define
name|XtCParameter
value|"Parameter"
end_define

begin_define
define|#
directive|define
name|XtCPixmap
value|"Pixmap"
end_define

begin_define
define|#
directive|define
name|XtCPosition
value|"Position"
end_define

begin_define
define|#
directive|define
name|XtCReadOnly
value|"ReadOnly"
end_define

begin_define
define|#
directive|define
name|XtCResize
value|"Resize"
end_define

begin_define
define|#
directive|define
name|XtCReverseVideo
value|"ReverseVideo"
end_define

begin_define
define|#
directive|define
name|XtCScreen
value|"Screen"
end_define

begin_define
define|#
directive|define
name|XtCScrollProc
value|"ScrollProc"
end_define

begin_define
define|#
directive|define
name|XtCScrollDCursor
value|"ScrollDCursor"
end_define

begin_define
define|#
directive|define
name|XtCScrollHCursor
value|"ScrollHCursor"
end_define

begin_define
define|#
directive|define
name|XtCScrollLCursor
value|"ScrollLCursor"
end_define

begin_define
define|#
directive|define
name|XtCScrollRCursor
value|"ScrollRCursor"
end_define

begin_define
define|#
directive|define
name|XtCScrollUCursor
value|"ScrollUCursor"
end_define

begin_define
define|#
directive|define
name|XtCScrollVCursor
value|"ScrollVCursor"
end_define

begin_define
define|#
directive|define
name|XtCSelection
value|"Selection"
end_define

begin_define
define|#
directive|define
name|XtCSensitive
value|"Sensitive"
end_define

begin_define
define|#
directive|define
name|XtCSelectionArray
value|"SelectionArray"
end_define

begin_define
define|#
directive|define
name|XtCSpace
value|"Space"
end_define

begin_define
define|#
directive|define
name|XtCString
value|"String"
end_define

begin_define
define|#
directive|define
name|XtCTextOptions
value|"TextOptions"
end_define

begin_define
define|#
directive|define
name|XtCTextPosition
value|"TextPosition"
end_define

begin_define
define|#
directive|define
name|XtCTextSink
value|"TextSink"
end_define

begin_define
define|#
directive|define
name|XtCTextSource
value|"TextSource"
end_define

begin_define
define|#
directive|define
name|XtCThickness
value|"Thickness"
end_define

begin_define
define|#
directive|define
name|XtCThumb
value|"Thumb"
end_define

begin_define
define|#
directive|define
name|XtCTranslations
value|"Translations"
end_define

begin_define
define|#
directive|define
name|XtCValue
value|"Value"
end_define

begin_define
define|#
directive|define
name|XtCVSpace
value|"VSpace"
end_define

begin_define
define|#
directive|define
name|XtCWidth
value|"Width"
end_define

begin_define
define|#
directive|define
name|XtCWindow
value|"Window"
end_define

begin_define
define|#
directive|define
name|XtCX
value|"X"
end_define

begin_define
define|#
directive|define
name|XtCY
value|"Y"
end_define

begin_define
define|#
directive|define
name|XtRAcceleratorTable
value|"AcceleratorTable"
end_define

begin_define
define|#
directive|define
name|XtRAtom
value|"Atom"
end_define

begin_define
define|#
directive|define
name|XtRBitmap
value|"Bitmap"
end_define

begin_define
define|#
directive|define
name|XtRBool
value|"Bool"
end_define

begin_define
define|#
directive|define
name|XtRBoolean
value|"Boolean"
end_define

begin_define
define|#
directive|define
name|XtRCallback
value|"Callback"
end_define

begin_define
define|#
directive|define
name|XtRCallProc
value|"CallProc"
end_define

begin_define
define|#
directive|define
name|XtRCardinal
value|"Cardinal"
end_define

begin_define
define|#
directive|define
name|XtRColor
value|"Color"
end_define

begin_define
define|#
directive|define
name|XtRColormap
value|"Colormap"
end_define

begin_define
define|#
directive|define
name|XtRCursor
value|"Cursor"
end_define

begin_define
define|#
directive|define
name|XtRDimension
value|"Dimension"
end_define

begin_define
define|#
directive|define
name|XtRDisplay
value|"Display"
end_define

begin_define
define|#
directive|define
name|XtREditMode
value|"EditMode"
end_define

begin_define
define|#
directive|define
name|XtREnum
value|"Enum"
end_define

begin_define
define|#
directive|define
name|XtRFile
value|"File"
end_define

begin_define
define|#
directive|define
name|XtRFloat
value|"Float"
end_define

begin_define
define|#
directive|define
name|XtRFont
value|"Font"
end_define

begin_define
define|#
directive|define
name|XtRFontStruct
value|"FontStruct"
end_define

begin_define
define|#
directive|define
name|XtRFunction
value|"Function"
end_define

begin_define
define|#
directive|define
name|XtRGeometry
value|"Geometry"
end_define

begin_define
define|#
directive|define
name|XtRImmediate
value|"Immediate"
end_define

begin_define
define|#
directive|define
name|XtRInitialState
value|"InitialState"
end_define

begin_define
define|#
directive|define
name|XtRInt
value|"Int"
end_define

begin_define
define|#
directive|define
name|XtRJustify
value|"Justify"
end_define

begin_define
define|#
directive|define
name|XtRLongBoolean
value|"Bool"
end_define

begin_define
define|#
directive|define
name|XtRObject
value|"Object"
end_define

begin_define
define|#
directive|define
name|XtROrientation
value|"Orientation"
end_define

begin_define
define|#
directive|define
name|XtRPixel
value|"Pixel"
end_define

begin_define
define|#
directive|define
name|XtRPixmap
value|"Pixmap"
end_define

begin_define
define|#
directive|define
name|XtRPointer
value|"Pointer"
end_define

begin_define
define|#
directive|define
name|XtRPosition
value|"Position"
end_define

begin_define
define|#
directive|define
name|XtRScreen
value|"Screen"
end_define

begin_define
define|#
directive|define
name|XtRShort
value|"Short"
end_define

begin_define
define|#
directive|define
name|XtRString
value|"String"
end_define

begin_define
define|#
directive|define
name|XtRStringArray
value|"StringArray"
end_define

begin_define
define|#
directive|define
name|XtRStringTable
value|"StringTable"
end_define

begin_define
define|#
directive|define
name|XtRUnsignedChar
value|"UnsignedChar"
end_define

begin_define
define|#
directive|define
name|XtRTranslationTable
value|"TranslationTable"
end_define

begin_define
define|#
directive|define
name|XtRVisual
value|"Visual"
end_define

begin_define
define|#
directive|define
name|XtRWidget
value|"Widget"
end_define

begin_define
define|#
directive|define
name|XtRWidgetClass
value|"WidgetClass"
end_define

begin_define
define|#
directive|define
name|XtRWidgetList
value|"WidgetList"
end_define

begin_define
define|#
directive|define
name|XtRWindow
value|"Window"
end_define

begin_define
define|#
directive|define
name|XtEoff
value|"off"
end_define

begin_define
define|#
directive|define
name|XtEfalse
value|"false"
end_define

begin_define
define|#
directive|define
name|XtEno
value|"no"
end_define

begin_define
define|#
directive|define
name|XtEon
value|"on"
end_define

begin_define
define|#
directive|define
name|XtEtrue
value|"true"
end_define

begin_define
define|#
directive|define
name|XtEyes
value|"yes"
end_define

begin_define
define|#
directive|define
name|XtEvertical
value|"vertical"
end_define

begin_define
define|#
directive|define
name|XtEhorizontal
value|"horizontal"
end_define

begin_define
define|#
directive|define
name|XtEtextRead
value|"read"
end_define

begin_define
define|#
directive|define
name|XtEtextAppend
value|"append"
end_define

begin_define
define|#
directive|define
name|XtEtextEdit
value|"edit"
end_define

begin_define
define|#
directive|define
name|XtExtdefaultbackground
value|"xtdefaultbackground"
end_define

begin_define
define|#
directive|define
name|XtExtdefaultforeground
value|"xtdefaultforeground"
end_define

begin_define
define|#
directive|define
name|XtExtdefaultfont
value|"xtdefaultfont"
end_define

begin_define
define|#
directive|define
name|XtNfontSet
value|"fontSet"
end_define

begin_define
define|#
directive|define
name|XtRFontSet
value|"FontSet"
end_define

begin_define
define|#
directive|define
name|XtCFontSet
value|"FontSet"
end_define

begin_else
else|#
directive|else
end_else

begin_if
if|#
directive|if
name|__STDC__
end_if

begin_define
define|#
directive|define
name|_XtConst_
value|const
end_define

begin_else
else|#
directive|else
end_else

begin_define
define|#
directive|define
name|_XtConst_
end_define

begin_comment
comment|/**/
end_comment

begin_endif
endif|#
directive|endif
end_endif

begin_decl_stmt
specifier|extern
name|_XtConst_
name|char
name|XtStrings
index|[]
decl_stmt|;
end_decl_stmt

begin_ifndef
ifndef|#
directive|ifndef
name|XtNaccelerators
end_ifndef

begin_define
define|#
directive|define
name|XtNaccelerators
value|((char*)&XtStrings[0])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNallowHoriz
end_ifndef

begin_define
define|#
directive|define
name|XtNallowHoriz
value|((char*)&XtStrings[13])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNallowVert
end_ifndef

begin_define
define|#
directive|define
name|XtNallowVert
value|((char*)&XtStrings[24])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNancestorSensitive
end_ifndef

begin_define
define|#
directive|define
name|XtNancestorSensitive
value|((char*)&XtStrings[34])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNbackground
end_ifndef

begin_define
define|#
directive|define
name|XtNbackground
value|((char*)&XtStrings[52])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNbackgroundPixmap
end_ifndef

begin_define
define|#
directive|define
name|XtNbackgroundPixmap
value|((char*)&XtStrings[63])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNbitmap
end_ifndef

begin_define
define|#
directive|define
name|XtNbitmap
value|((char*)&XtStrings[80])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNborderColor
end_ifndef

begin_define
define|#
directive|define
name|XtNborderColor
value|((char*)&XtStrings[87])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNborder
end_ifndef

begin_define
define|#
directive|define
name|XtNborder
value|((char*)&XtStrings[99])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNborderPixmap
end_ifndef

begin_define
define|#
directive|define
name|XtNborderPixmap
value|((char*)&XtStrings[111])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNborderWidth
end_ifndef

begin_define
define|#
directive|define
name|XtNborderWidth
value|((char*)&XtStrings[124])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNcallback
end_ifndef

begin_define
define|#
directive|define
name|XtNcallback
value|((char*)&XtStrings[136])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNchildren
end_ifndef

begin_define
define|#
directive|define
name|XtNchildren
value|((char*)&XtStrings[145])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNcolormap
end_ifndef

begin_define
define|#
directive|define
name|XtNcolormap
value|((char*)&XtStrings[154])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNdepth
end_ifndef

begin_define
define|#
directive|define
name|XtNdepth
value|((char*)&XtStrings[163])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNdestroyCallback
end_ifndef

begin_define
define|#
directive|define
name|XtNdestroyCallback
value|((char*)&XtStrings[169])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNeditType
end_ifndef

begin_define
define|#
directive|define
name|XtNeditType
value|((char*)&XtStrings[185])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNfile
end_ifndef

begin_define
define|#
directive|define
name|XtNfile
value|((char*)&XtStrings[194])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNfont
end_ifndef

begin_define
define|#
directive|define
name|XtNfont
value|((char*)&XtStrings[199])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNforceBars
end_ifndef

begin_define
define|#
directive|define
name|XtNforceBars
value|((char*)&XtStrings[204])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNforeground
end_ifndef

begin_define
define|#
directive|define
name|XtNforeground
value|((char*)&XtStrings[214])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNfunction
end_ifndef

begin_define
define|#
directive|define
name|XtNfunction
value|((char*)&XtStrings[225])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNheight
end_ifndef

begin_define
define|#
directive|define
name|XtNheight
value|((char*)&XtStrings[234])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNhighlight
end_ifndef

begin_define
define|#
directive|define
name|XtNhighlight
value|((char*)&XtStrings[241])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNhSpace
end_ifndef

begin_define
define|#
directive|define
name|XtNhSpace
value|((char*)&XtStrings[251])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNindex
end_ifndef

begin_define
define|#
directive|define
name|XtNindex
value|((char*)&XtStrings[258])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNinitialResourcesPersistent
end_ifndef

begin_define
define|#
directive|define
name|XtNinitialResourcesPersistent
value|((char*)&XtStrings[264])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNinnerHeight
end_ifndef

begin_define
define|#
directive|define
name|XtNinnerHeight
value|((char*)&XtStrings[291])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNinnerWidth
end_ifndef

begin_define
define|#
directive|define
name|XtNinnerWidth
value|((char*)&XtStrings[303])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNinnerWindow
end_ifndef

begin_define
define|#
directive|define
name|XtNinnerWindow
value|((char*)&XtStrings[314])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNinsertPosition
end_ifndef

begin_define
define|#
directive|define
name|XtNinsertPosition
value|((char*)&XtStrings[326])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNinternalHeight
end_ifndef

begin_define
define|#
directive|define
name|XtNinternalHeight
value|((char*)&XtStrings[341])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNinternalWidth
end_ifndef

begin_define
define|#
directive|define
name|XtNinternalWidth
value|((char*)&XtStrings[356])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNjumpProc
end_ifndef

begin_define
define|#
directive|define
name|XtNjumpProc
value|((char*)&XtStrings[370])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNjustify
end_ifndef

begin_define
define|#
directive|define
name|XtNjustify
value|((char*)&XtStrings[379])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNknobHeight
end_ifndef

begin_define
define|#
directive|define
name|XtNknobHeight
value|((char*)&XtStrings[387])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNknobIndent
end_ifndef

begin_define
define|#
directive|define
name|XtNknobIndent
value|((char*)&XtStrings[398])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNknobPixel
end_ifndef

begin_define
define|#
directive|define
name|XtNknobPixel
value|((char*)&XtStrings[409])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNknobWidth
end_ifndef

begin_define
define|#
directive|define
name|XtNknobWidth
value|((char*)&XtStrings[419])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNlabel
end_ifndef

begin_define
define|#
directive|define
name|XtNlabel
value|((char*)&XtStrings[429])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNlength
end_ifndef

begin_define
define|#
directive|define
name|XtNlength
value|((char*)&XtStrings[435])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNlowerRight
end_ifndef

begin_define
define|#
directive|define
name|XtNlowerRight
value|((char*)&XtStrings[442])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNmappedWhenManaged
end_ifndef

begin_define
define|#
directive|define
name|XtNmappedWhenManaged
value|((char*)&XtStrings[453])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNmenuEntry
end_ifndef

begin_define
define|#
directive|define
name|XtNmenuEntry
value|((char*)&XtStrings[471])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNname
end_ifndef

begin_define
define|#
directive|define
name|XtNname
value|((char*)&XtStrings[481])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNnotify
end_ifndef

begin_define
define|#
directive|define
name|XtNnotify
value|((char*)&XtStrings[486])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNnumChildren
end_ifndef

begin_define
define|#
directive|define
name|XtNnumChildren
value|((char*)&XtStrings[493])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNorientation
end_ifndef

begin_define
define|#
directive|define
name|XtNorientation
value|((char*)&XtStrings[505])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNparameter
end_ifndef

begin_define
define|#
directive|define
name|XtNparameter
value|((char*)&XtStrings[517])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNpixmap
end_ifndef

begin_define
define|#
directive|define
name|XtNpixmap
value|((char*)&XtStrings[527])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNpopupCallback
end_ifndef

begin_define
define|#
directive|define
name|XtNpopupCallback
value|((char*)&XtStrings[534])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNpopdownCallback
end_ifndef

begin_define
define|#
directive|define
name|XtNpopdownCallback
value|((char*)&XtStrings[548])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNresize
end_ifndef

begin_define
define|#
directive|define
name|XtNresize
value|((char*)&XtStrings[564])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNreverseVideo
end_ifndef

begin_define
define|#
directive|define
name|XtNreverseVideo
value|((char*)&XtStrings[571])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNscreen
end_ifndef

begin_define
define|#
directive|define
name|XtNscreen
value|((char*)&XtStrings[584])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNscrollProc
end_ifndef

begin_define
define|#
directive|define
name|XtNscrollProc
value|((char*)&XtStrings[591])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNscrollDCursor
end_ifndef

begin_define
define|#
directive|define
name|XtNscrollDCursor
value|((char*)&XtStrings[602])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNscrollHCursor
end_ifndef

begin_define
define|#
directive|define
name|XtNscrollHCursor
value|((char*)&XtStrings[616])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNscrollLCursor
end_ifndef

begin_define
define|#
directive|define
name|XtNscrollLCursor
value|((char*)&XtStrings[630])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNscrollRCursor
end_ifndef

begin_define
define|#
directive|define
name|XtNscrollRCursor
value|((char*)&XtStrings[644])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNscrollUCursor
end_ifndef

begin_define
define|#
directive|define
name|XtNscrollUCursor
value|((char*)&XtStrings[658])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNscrollVCursor
end_ifndef

begin_define
define|#
directive|define
name|XtNscrollVCursor
value|((char*)&XtStrings[672])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNselection
end_ifndef

begin_define
define|#
directive|define
name|XtNselection
value|((char*)&XtStrings[686])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNselectionArray
end_ifndef

begin_define
define|#
directive|define
name|XtNselectionArray
value|((char*)&XtStrings[696])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNsensitive
end_ifndef

begin_define
define|#
directive|define
name|XtNsensitive
value|((char*)&XtStrings[711])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNshown
end_ifndef

begin_define
define|#
directive|define
name|XtNshown
value|((char*)&XtStrings[721])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNspace
end_ifndef

begin_define
define|#
directive|define
name|XtNspace
value|((char*)&XtStrings[727])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNstring
end_ifndef

begin_define
define|#
directive|define
name|XtNstring
value|((char*)&XtStrings[733])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNtextOptions
end_ifndef

begin_define
define|#
directive|define
name|XtNtextOptions
value|((char*)&XtStrings[740])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNtextSink
end_ifndef

begin_define
define|#
directive|define
name|XtNtextSink
value|((char*)&XtStrings[752])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNtextSource
end_ifndef

begin_define
define|#
directive|define
name|XtNtextSource
value|((char*)&XtStrings[761])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNthickness
end_ifndef

begin_define
define|#
directive|define
name|XtNthickness
value|((char*)&XtStrings[772])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNthumb
end_ifndef

begin_define
define|#
directive|define
name|XtNthumb
value|((char*)&XtStrings[782])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNthumbProc
end_ifndef

begin_define
define|#
directive|define
name|XtNthumbProc
value|((char*)&XtStrings[788])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNtop
end_ifndef

begin_define
define|#
directive|define
name|XtNtop
value|((char*)&XtStrings[798])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNtranslations
end_ifndef

begin_define
define|#
directive|define
name|XtNtranslations
value|((char*)&XtStrings[802])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNunrealizeCallback
end_ifndef

begin_define
define|#
directive|define
name|XtNunrealizeCallback
value|((char*)&XtStrings[815])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNupdate
end_ifndef

begin_define
define|#
directive|define
name|XtNupdate
value|((char*)&XtStrings[833])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNuseBottom
end_ifndef

begin_define
define|#
directive|define
name|XtNuseBottom
value|((char*)&XtStrings[840])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNuseRight
end_ifndef

begin_define
define|#
directive|define
name|XtNuseRight
value|((char*)&XtStrings[850])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNvalue
end_ifndef

begin_define
define|#
directive|define
name|XtNvalue
value|((char*)&XtStrings[859])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNvSpace
end_ifndef

begin_define
define|#
directive|define
name|XtNvSpace
value|((char*)&XtStrings[865])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNwidth
end_ifndef

begin_define
define|#
directive|define
name|XtNwidth
value|((char*)&XtStrings[872])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNwindow
end_ifndef

begin_define
define|#
directive|define
name|XtNwindow
value|((char*)&XtStrings[878])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNx
end_ifndef

begin_define
define|#
directive|define
name|XtNx
value|((char*)&XtStrings[885])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNy
end_ifndef

begin_define
define|#
directive|define
name|XtNy
value|((char*)&XtStrings[887])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCAccelerators
end_ifndef

begin_define
define|#
directive|define
name|XtCAccelerators
value|((char*)&XtStrings[889])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCBackground
end_ifndef

begin_define
define|#
directive|define
name|XtCBackground
value|((char*)&XtStrings[902])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCBitmap
end_ifndef

begin_define
define|#
directive|define
name|XtCBitmap
value|((char*)&XtStrings[913])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCBoolean
end_ifndef

begin_define
define|#
directive|define
name|XtCBoolean
value|((char*)&XtStrings[920])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCBorderColor
end_ifndef

begin_define
define|#
directive|define
name|XtCBorderColor
value|((char*)&XtStrings[928])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCBorderWidth
end_ifndef

begin_define
define|#
directive|define
name|XtCBorderWidth
value|((char*)&XtStrings[940])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCCallback
end_ifndef

begin_define
define|#
directive|define
name|XtCCallback
value|((char*)&XtStrings[952])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCColormap
end_ifndef

begin_define
define|#
directive|define
name|XtCColormap
value|((char*)&XtStrings[961])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCColor
end_ifndef

begin_define
define|#
directive|define
name|XtCColor
value|((char*)&XtStrings[970])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCCursor
end_ifndef

begin_define
define|#
directive|define
name|XtCCursor
value|((char*)&XtStrings[976])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCDepth
end_ifndef

begin_define
define|#
directive|define
name|XtCDepth
value|((char*)&XtStrings[983])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCEditType
end_ifndef

begin_define
define|#
directive|define
name|XtCEditType
value|((char*)&XtStrings[989])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCEventBindings
end_ifndef

begin_define
define|#
directive|define
name|XtCEventBindings
value|((char*)&XtStrings[998])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCFile
end_ifndef

begin_define
define|#
directive|define
name|XtCFile
value|((char*)&XtStrings[1012])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCFont
end_ifndef

begin_define
define|#
directive|define
name|XtCFont
value|((char*)&XtStrings[1017])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCForeground
end_ifndef

begin_define
define|#
directive|define
name|XtCForeground
value|((char*)&XtStrings[1022])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCFraction
end_ifndef

begin_define
define|#
directive|define
name|XtCFraction
value|((char*)&XtStrings[1033])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCFunction
end_ifndef

begin_define
define|#
directive|define
name|XtCFunction
value|((char*)&XtStrings[1042])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCHeight
end_ifndef

begin_define
define|#
directive|define
name|XtCHeight
value|((char*)&XtStrings[1051])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCHSpace
end_ifndef

begin_define
define|#
directive|define
name|XtCHSpace
value|((char*)&XtStrings[1058])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCIndex
end_ifndef

begin_define
define|#
directive|define
name|XtCIndex
value|((char*)&XtStrings[1065])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCInitialResourcesPersistent
end_ifndef

begin_define
define|#
directive|define
name|XtCInitialResourcesPersistent
value|((char*)&XtStrings[1071])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCInsertPosition
end_ifndef

begin_define
define|#
directive|define
name|XtCInsertPosition
value|((char*)&XtStrings[1098])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCInterval
end_ifndef

begin_define
define|#
directive|define
name|XtCInterval
value|((char*)&XtStrings[1113])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCJustify
end_ifndef

begin_define
define|#
directive|define
name|XtCJustify
value|((char*)&XtStrings[1122])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCKnobIndent
end_ifndef

begin_define
define|#
directive|define
name|XtCKnobIndent
value|((char*)&XtStrings[1130])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCKnobPixel
end_ifndef

begin_define
define|#
directive|define
name|XtCKnobPixel
value|((char*)&XtStrings[1141])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCLabel
end_ifndef

begin_define
define|#
directive|define
name|XtCLabel
value|((char*)&XtStrings[1151])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCLength
end_ifndef

begin_define
define|#
directive|define
name|XtCLength
value|((char*)&XtStrings[1157])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCMappedWhenManaged
end_ifndef

begin_define
define|#
directive|define
name|XtCMappedWhenManaged
value|((char*)&XtStrings[1164])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCMargin
end_ifndef

begin_define
define|#
directive|define
name|XtCMargin
value|((char*)&XtStrings[1182])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCMenuEntry
end_ifndef

begin_define
define|#
directive|define
name|XtCMenuEntry
value|((char*)&XtStrings[1189])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCNotify
end_ifndef

begin_define
define|#
directive|define
name|XtCNotify
value|((char*)&XtStrings[1199])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCOrientation
end_ifndef

begin_define
define|#
directive|define
name|XtCOrientation
value|((char*)&XtStrings[1206])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCParameter
end_ifndef

begin_define
define|#
directive|define
name|XtCParameter
value|((char*)&XtStrings[1218])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCPixmap
end_ifndef

begin_define
define|#
directive|define
name|XtCPixmap
value|((char*)&XtStrings[1228])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCPosition
end_ifndef

begin_define
define|#
directive|define
name|XtCPosition
value|((char*)&XtStrings[1235])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCReadOnly
end_ifndef

begin_define
define|#
directive|define
name|XtCReadOnly
value|((char*)&XtStrings[1244])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCResize
end_ifndef

begin_define
define|#
directive|define
name|XtCResize
value|((char*)&XtStrings[1253])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCReverseVideo
end_ifndef

begin_define
define|#
directive|define
name|XtCReverseVideo
value|((char*)&XtStrings[1260])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCScreen
end_ifndef

begin_define
define|#
directive|define
name|XtCScreen
value|((char*)&XtStrings[1273])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCScrollProc
end_ifndef

begin_define
define|#
directive|define
name|XtCScrollProc
value|((char*)&XtStrings[1280])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCScrollDCursor
end_ifndef

begin_define
define|#
directive|define
name|XtCScrollDCursor
value|((char*)&XtStrings[1291])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCScrollHCursor
end_ifndef

begin_define
define|#
directive|define
name|XtCScrollHCursor
value|((char*)&XtStrings[1305])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCScrollLCursor
end_ifndef

begin_define
define|#
directive|define
name|XtCScrollLCursor
value|((char*)&XtStrings[1319])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCScrollRCursor
end_ifndef

begin_define
define|#
directive|define
name|XtCScrollRCursor
value|((char*)&XtStrings[1333])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCScrollUCursor
end_ifndef

begin_define
define|#
directive|define
name|XtCScrollUCursor
value|((char*)&XtStrings[1347])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCScrollVCursor
end_ifndef

begin_define
define|#
directive|define
name|XtCScrollVCursor
value|((char*)&XtStrings[1361])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCSelection
end_ifndef

begin_define
define|#
directive|define
name|XtCSelection
value|((char*)&XtStrings[1375])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCSensitive
end_ifndef

begin_define
define|#
directive|define
name|XtCSensitive
value|((char*)&XtStrings[1385])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCSelectionArray
end_ifndef

begin_define
define|#
directive|define
name|XtCSelectionArray
value|((char*)&XtStrings[1395])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCSpace
end_ifndef

begin_define
define|#
directive|define
name|XtCSpace
value|((char*)&XtStrings[1410])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCString
end_ifndef

begin_define
define|#
directive|define
name|XtCString
value|((char*)&XtStrings[1416])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCTextOptions
end_ifndef

begin_define
define|#
directive|define
name|XtCTextOptions
value|((char*)&XtStrings[1423])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCTextPosition
end_ifndef

begin_define
define|#
directive|define
name|XtCTextPosition
value|((char*)&XtStrings[1435])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCTextSink
end_ifndef

begin_define
define|#
directive|define
name|XtCTextSink
value|((char*)&XtStrings[1448])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCTextSource
end_ifndef

begin_define
define|#
directive|define
name|XtCTextSource
value|((char*)&XtStrings[1457])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCThickness
end_ifndef

begin_define
define|#
directive|define
name|XtCThickness
value|((char*)&XtStrings[1468])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCThumb
end_ifndef

begin_define
define|#
directive|define
name|XtCThumb
value|((char*)&XtStrings[1478])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCTranslations
end_ifndef

begin_define
define|#
directive|define
name|XtCTranslations
value|((char*)&XtStrings[1484])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCValue
end_ifndef

begin_define
define|#
directive|define
name|XtCValue
value|((char*)&XtStrings[1497])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCVSpace
end_ifndef

begin_define
define|#
directive|define
name|XtCVSpace
value|((char*)&XtStrings[1503])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCWidth
end_ifndef

begin_define
define|#
directive|define
name|XtCWidth
value|((char*)&XtStrings[1510])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCWindow
end_ifndef

begin_define
define|#
directive|define
name|XtCWindow
value|((char*)&XtStrings[1516])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCX
end_ifndef

begin_define
define|#
directive|define
name|XtCX
value|((char*)&XtStrings[1523])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCY
end_ifndef

begin_define
define|#
directive|define
name|XtCY
value|((char*)&XtStrings[1525])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRAcceleratorTable
end_ifndef

begin_define
define|#
directive|define
name|XtRAcceleratorTable
value|((char*)&XtStrings[1527])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRAtom
end_ifndef

begin_define
define|#
directive|define
name|XtRAtom
value|((char*)&XtStrings[1544])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRBitmap
end_ifndef

begin_define
define|#
directive|define
name|XtRBitmap
value|((char*)&XtStrings[1549])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRBool
end_ifndef

begin_define
define|#
directive|define
name|XtRBool
value|((char*)&XtStrings[1556])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRBoolean
end_ifndef

begin_define
define|#
directive|define
name|XtRBoolean
value|((char*)&XtStrings[1561])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRCallback
end_ifndef

begin_define
define|#
directive|define
name|XtRCallback
value|((char*)&XtStrings[1569])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRCallProc
end_ifndef

begin_define
define|#
directive|define
name|XtRCallProc
value|((char*)&XtStrings[1578])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRCardinal
end_ifndef

begin_define
define|#
directive|define
name|XtRCardinal
value|((char*)&XtStrings[1587])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRColor
end_ifndef

begin_define
define|#
directive|define
name|XtRColor
value|((char*)&XtStrings[1596])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRColormap
end_ifndef

begin_define
define|#
directive|define
name|XtRColormap
value|((char*)&XtStrings[1602])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRCursor
end_ifndef

begin_define
define|#
directive|define
name|XtRCursor
value|((char*)&XtStrings[1611])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRDimension
end_ifndef

begin_define
define|#
directive|define
name|XtRDimension
value|((char*)&XtStrings[1618])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRDisplay
end_ifndef

begin_define
define|#
directive|define
name|XtRDisplay
value|((char*)&XtStrings[1628])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtREditMode
end_ifndef

begin_define
define|#
directive|define
name|XtREditMode
value|((char*)&XtStrings[1636])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtREnum
end_ifndef

begin_define
define|#
directive|define
name|XtREnum
value|((char*)&XtStrings[1645])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRFile
end_ifndef

begin_define
define|#
directive|define
name|XtRFile
value|((char*)&XtStrings[1650])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRFloat
end_ifndef

begin_define
define|#
directive|define
name|XtRFloat
value|((char*)&XtStrings[1655])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRFont
end_ifndef

begin_define
define|#
directive|define
name|XtRFont
value|((char*)&XtStrings[1661])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRFontStruct
end_ifndef

begin_define
define|#
directive|define
name|XtRFontStruct
value|((char*)&XtStrings[1666])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRFunction
end_ifndef

begin_define
define|#
directive|define
name|XtRFunction
value|((char*)&XtStrings[1677])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRGeometry
end_ifndef

begin_define
define|#
directive|define
name|XtRGeometry
value|((char*)&XtStrings[1686])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRImmediate
end_ifndef

begin_define
define|#
directive|define
name|XtRImmediate
value|((char*)&XtStrings[1695])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRInitialState
end_ifndef

begin_define
define|#
directive|define
name|XtRInitialState
value|((char*)&XtStrings[1705])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRInt
end_ifndef

begin_define
define|#
directive|define
name|XtRInt
value|((char*)&XtStrings[1718])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRJustify
end_ifndef

begin_define
define|#
directive|define
name|XtRJustify
value|((char*)&XtStrings[1722])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRLongBoolean
end_ifndef

begin_define
define|#
directive|define
name|XtRLongBoolean
value|((char*)&XtStrings[1730])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRObject
end_ifndef

begin_define
define|#
directive|define
name|XtRObject
value|((char*)&XtStrings[1735])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtROrientation
end_ifndef

begin_define
define|#
directive|define
name|XtROrientation
value|((char*)&XtStrings[1742])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRPixel
end_ifndef

begin_define
define|#
directive|define
name|XtRPixel
value|((char*)&XtStrings[1754])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRPixmap
end_ifndef

begin_define
define|#
directive|define
name|XtRPixmap
value|((char*)&XtStrings[1760])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRPointer
end_ifndef

begin_define
define|#
directive|define
name|XtRPointer
value|((char*)&XtStrings[1767])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRPosition
end_ifndef

begin_define
define|#
directive|define
name|XtRPosition
value|((char*)&XtStrings[1775])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRScreen
end_ifndef

begin_define
define|#
directive|define
name|XtRScreen
value|((char*)&XtStrings[1784])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRShort
end_ifndef

begin_define
define|#
directive|define
name|XtRShort
value|((char*)&XtStrings[1791])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRString
end_ifndef

begin_define
define|#
directive|define
name|XtRString
value|((char*)&XtStrings[1797])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRStringArray
end_ifndef

begin_define
define|#
directive|define
name|XtRStringArray
value|((char*)&XtStrings[1804])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRStringTable
end_ifndef

begin_define
define|#
directive|define
name|XtRStringTable
value|((char*)&XtStrings[1816])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRUnsignedChar
end_ifndef

begin_define
define|#
directive|define
name|XtRUnsignedChar
value|((char*)&XtStrings[1828])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRTranslationTable
end_ifndef

begin_define
define|#
directive|define
name|XtRTranslationTable
value|((char*)&XtStrings[1841])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRVisual
end_ifndef

begin_define
define|#
directive|define
name|XtRVisual
value|((char*)&XtStrings[1858])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRWidget
end_ifndef

begin_define
define|#
directive|define
name|XtRWidget
value|((char*)&XtStrings[1865])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRWidgetClass
end_ifndef

begin_define
define|#
directive|define
name|XtRWidgetClass
value|((char*)&XtStrings[1872])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRWidgetList
end_ifndef

begin_define
define|#
directive|define
name|XtRWidgetList
value|((char*)&XtStrings[1884])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRWindow
end_ifndef

begin_define
define|#
directive|define
name|XtRWindow
value|((char*)&XtStrings[1895])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtEoff
end_ifndef

begin_define
define|#
directive|define
name|XtEoff
value|((char*)&XtStrings[1902])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtEfalse
end_ifndef

begin_define
define|#
directive|define
name|XtEfalse
value|((char*)&XtStrings[1906])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtEno
end_ifndef

begin_define
define|#
directive|define
name|XtEno
value|((char*)&XtStrings[1912])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtEon
end_ifndef

begin_define
define|#
directive|define
name|XtEon
value|((char*)&XtStrings[1915])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtEtrue
end_ifndef

begin_define
define|#
directive|define
name|XtEtrue
value|((char*)&XtStrings[1918])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtEyes
end_ifndef

begin_define
define|#
directive|define
name|XtEyes
value|((char*)&XtStrings[1923])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtEvertical
end_ifndef

begin_define
define|#
directive|define
name|XtEvertical
value|((char*)&XtStrings[1927])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtEhorizontal
end_ifndef

begin_define
define|#
directive|define
name|XtEhorizontal
value|((char*)&XtStrings[1936])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtEtextRead
end_ifndef

begin_define
define|#
directive|define
name|XtEtextRead
value|((char*)&XtStrings[1947])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtEtextAppend
end_ifndef

begin_define
define|#
directive|define
name|XtEtextAppend
value|((char*)&XtStrings[1952])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtEtextEdit
end_ifndef

begin_define
define|#
directive|define
name|XtEtextEdit
value|((char*)&XtStrings[1959])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtExtdefaultbackground
end_ifndef

begin_define
define|#
directive|define
name|XtExtdefaultbackground
value|((char*)&XtStrings[1964])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtExtdefaultforeground
end_ifndef

begin_define
define|#
directive|define
name|XtExtdefaultforeground
value|((char*)&XtStrings[1984])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtExtdefaultfont
end_ifndef

begin_define
define|#
directive|define
name|XtExtdefaultfont
value|((char*)&XtStrings[2004])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtNfontSet
end_ifndef

begin_define
define|#
directive|define
name|XtNfontSet
value|((char*)&XtStrings[2018])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtRFontSet
end_ifndef

begin_define
define|#
directive|define
name|XtRFontSet
value|((char*)&XtStrings[2026])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_ifndef
ifndef|#
directive|ifndef
name|XtCFontSet
end_ifndef

begin_define
define|#
directive|define
name|XtCFontSet
value|((char*)&XtStrings[2034])
end_define

begin_endif
endif|#
directive|endif
end_endif

begin_undef
undef|#
directive|undef
name|_XtConst_
end_undef

begin_endif
endif|#
directive|endif
end_endif

begin_endif
endif|#
directive|endif
end_endif

end_unit

