begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * CDDL HEADER START  *  * The contents of this file are subject to the terms of the  * Common Development and Distribution License, Version 1.0 only  * (the "License").  You may not use this file except in compliance  * with the License.  *  * You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE  * or http://www.opensolaris.org/os/licensing.  * See the License for the specific language governing permissions  * and limitations under the License.  *  * When distributing Covered Code, include this CDDL HEADER in each  * file and include the License file at usr/src/OPENSOLARIS.LICENSE.  * If applicable, add the following below this CDDL HEADER, with the  * fields enclosed by brackets "[]" replaced with your own identifying  * information: Portions Copyright [yyyy] [name of copyright owner]  *  * CDDL HEADER END  *  * $FreeBSD$  *  */
end_comment

begin_comment
comment|/*  * Copyright 2005 Sun Microsystems, Inc.  All rights reserved.  * Use is subject to license terms.  */
end_comment

begin_include
include|#
directive|include
file|<sys/cdefs.h>
end_include

begin_expr_stmt
name|__FBSDID
argument_list|(
literal|"$FreeBSD$"
argument_list|)
expr_stmt|;
end_expr_stmt

begin_include
include|#
directive|include
file|<sys/param.h>
end_include

begin_include
include|#
directive|include
file|<sys/systm.h>
end_include

begin_include
include|#
directive|include
file|<sys/types.h>
end_include

begin_include
include|#
directive|include
file|<sys/kernel.h>
end_include

begin_include
include|#
directive|include
file|<sys/malloc.h>
end_include

begin_include
include|#
directive|include
file|<sys/kmem.h>
end_include

begin_include
include|#
directive|include
file|<sys/smp.h>
end_include

begin_include
include|#
directive|include
file|<sys/dtrace_impl.h>
end_include

begin_include
include|#
directive|include
file|<sys/dtrace_bsd.h>
end_include

begin_include
include|#
directive|include
file|<machine/armreg.h>
end_include

begin_include
include|#
directive|include
file|<machine/clock.h>
end_include

begin_include
include|#
directive|include
file|<machine/frame.h>
end_include

begin_include
include|#
directive|include
file|<machine/trap.h>
end_include

begin_include
include|#
directive|include
file|<vm/pmap.h>
end_include

begin_decl_stmt
specifier|extern
name|dtrace_id_t
name|dtrace_probeid_error
decl_stmt|;
end_decl_stmt

begin_function_decl
specifier|extern
name|int
function_decl|(
modifier|*
name|dtrace_invop_jump_addr
function_decl|)
parameter_list|(
name|struct
name|trapframe
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|extern
name|void
name|dtrace_getnanotime
parameter_list|(
name|struct
name|timespec
modifier|*
name|tsp
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|dtrace_invop
parameter_list|(
name|uintptr_t
parameter_list|,
name|struct
name|trapframe
modifier|*
parameter_list|,
name|uintptr_t
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|dtrace_invop_init
parameter_list|(
name|void
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|void
name|dtrace_invop_uninit
parameter_list|(
name|void
parameter_list|)
function_decl|;
end_function_decl

begin_typedef
typedef|typedef
struct|struct
name|dtrace_invop_hdlr
block|{
name|int
function_decl|(
modifier|*
name|dtih_func
function_decl|)
parameter_list|(
name|uintptr_t
parameter_list|,
name|struct
name|trapframe
modifier|*
parameter_list|,
name|uintptr_t
parameter_list|)
function_decl|;
name|struct
name|dtrace_invop_hdlr
modifier|*
name|dtih_next
decl_stmt|;
block|}
name|dtrace_invop_hdlr_t
typedef|;
end_typedef

begin_decl_stmt
name|dtrace_invop_hdlr_t
modifier|*
name|dtrace_invop_hdlr
decl_stmt|;
end_decl_stmt

begin_function
name|int
name|dtrace_invop
parameter_list|(
name|uintptr_t
name|addr
parameter_list|,
name|struct
name|trapframe
modifier|*
name|frame
parameter_list|,
name|uintptr_t
name|eax
parameter_list|)
block|{
name|dtrace_invop_hdlr_t
modifier|*
name|hdlr
decl_stmt|;
name|int
name|rval
decl_stmt|;
for|for
control|(
name|hdlr
operator|=
name|dtrace_invop_hdlr
init|;
name|hdlr
operator|!=
name|NULL
condition|;
name|hdlr
operator|=
name|hdlr
operator|->
name|dtih_next
control|)
if|if
condition|(
operator|(
name|rval
operator|=
name|hdlr
operator|->
name|dtih_func
argument_list|(
name|addr
argument_list|,
name|frame
argument_list|,
name|eax
argument_list|)
operator|)
operator|!=
literal|0
condition|)
return|return
operator|(
name|rval
operator|)
return|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_function
name|void
name|dtrace_invop_add
parameter_list|(
name|int
function_decl|(
modifier|*
name|func
function_decl|)
parameter_list|(
name|uintptr_t
parameter_list|,
name|struct
name|trapframe
modifier|*
parameter_list|,
name|uintptr_t
parameter_list|)
parameter_list|)
block|{
name|dtrace_invop_hdlr_t
modifier|*
name|hdlr
decl_stmt|;
name|hdlr
operator|=
name|kmem_alloc
argument_list|(
sizeof|sizeof
argument_list|(
name|dtrace_invop_hdlr_t
argument_list|)
argument_list|,
name|KM_SLEEP
argument_list|)
expr_stmt|;
name|hdlr
operator|->
name|dtih_func
operator|=
name|func
expr_stmt|;
name|hdlr
operator|->
name|dtih_next
operator|=
name|dtrace_invop_hdlr
expr_stmt|;
name|dtrace_invop_hdlr
operator|=
name|hdlr
expr_stmt|;
block|}
end_function

begin_function
name|void
name|dtrace_invop_remove
parameter_list|(
name|int
function_decl|(
modifier|*
name|func
function_decl|)
parameter_list|(
name|uintptr_t
parameter_list|,
name|struct
name|trapframe
modifier|*
parameter_list|,
name|uintptr_t
parameter_list|)
parameter_list|)
block|{
name|dtrace_invop_hdlr_t
modifier|*
name|hdlr
decl_stmt|,
modifier|*
name|prev
decl_stmt|;
name|hdlr
operator|=
name|dtrace_invop_hdlr
expr_stmt|;
name|prev
operator|=
name|NULL
expr_stmt|;
for|for
control|(
init|;
condition|;
control|)
block|{
if|if
condition|(
name|hdlr
operator|==
name|NULL
condition|)
name|panic
argument_list|(
literal|"attempt to remove non-existent invop handler"
argument_list|)
expr_stmt|;
if|if
condition|(
name|hdlr
operator|->
name|dtih_func
operator|==
name|func
condition|)
break|break;
name|prev
operator|=
name|hdlr
expr_stmt|;
name|hdlr
operator|=
name|hdlr
operator|->
name|dtih_next
expr_stmt|;
block|}
if|if
condition|(
name|prev
operator|==
name|NULL
condition|)
block|{
name|ASSERT
argument_list|(
name|dtrace_invop_hdlr
operator|==
name|hdlr
argument_list|)
expr_stmt|;
name|dtrace_invop_hdlr
operator|=
name|hdlr
operator|->
name|dtih_next
expr_stmt|;
block|}
else|else
block|{
name|ASSERT
argument_list|(
name|dtrace_invop_hdlr
operator|!=
name|hdlr
argument_list|)
expr_stmt|;
name|prev
operator|->
name|dtih_next
operator|=
name|hdlr
operator|->
name|dtih_next
expr_stmt|;
block|}
name|kmem_free
argument_list|(
name|hdlr
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*ARGSUSED*/
end_comment

begin_function
name|void
name|dtrace_toxic_ranges
parameter_list|(
name|void
function_decl|(
modifier|*
name|func
function_decl|)
parameter_list|(
name|uintptr_t
name|base
parameter_list|,
name|uintptr_t
name|limit
parameter_list|)
parameter_list|)
block|{
call|(
modifier|*
name|func
call|)
argument_list|(
literal|0
argument_list|,
operator|(
name|uintptr_t
operator|)
name|VM_MIN_KERNEL_ADDRESS
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|void
name|dtrace_xcall
parameter_list|(
name|processorid_t
name|cpu
parameter_list|,
name|dtrace_xcall_t
name|func
parameter_list|,
name|void
modifier|*
name|arg
parameter_list|)
block|{
name|cpuset_t
name|cpus
decl_stmt|;
if|if
condition|(
name|cpu
operator|==
name|DTRACE_CPUALL
condition|)
name|cpus
operator|=
name|all_cpus
expr_stmt|;
else|else
name|CPU_SETOF
argument_list|(
name|cpu
argument_list|,
operator|&
name|cpus
argument_list|)
expr_stmt|;
name|smp_rendezvous_cpus
argument_list|(
name|cpus
argument_list|,
name|smp_no_rendevous_barrier
argument_list|,
name|func
argument_list|,
name|smp_no_rendevous_barrier
argument_list|,
name|arg
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
name|dtrace_sync_func
parameter_list|(
name|void
parameter_list|)
block|{  }
end_function

begin_function
name|void
name|dtrace_sync
parameter_list|(
name|void
parameter_list|)
block|{
name|dtrace_xcall
argument_list|(
name|DTRACE_CPUALL
argument_list|,
operator|(
name|dtrace_xcall_t
operator|)
name|dtrace_sync_func
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*  * DTrace needs a high resolution time function which can  * be called from a probe context and guaranteed not to have  * instrumented with probes itself.  *  * Returns nanoseconds since boot.  */
end_comment

begin_function
name|uint64_t
name|dtrace_gethrtime
parameter_list|()
block|{
name|struct
name|timespec
name|curtime
decl_stmt|;
name|nanouptime
argument_list|(
operator|&
name|curtime
argument_list|)
expr_stmt|;
return|return
operator|(
name|curtime
operator|.
name|tv_sec
operator|*
literal|1000000000UL
operator|+
name|curtime
operator|.
name|tv_nsec
operator|)
return|;
block|}
end_function

begin_function
name|uint64_t
name|dtrace_gethrestime
parameter_list|(
name|void
parameter_list|)
block|{
name|struct
name|timespec
name|current_time
decl_stmt|;
name|dtrace_getnanotime
argument_list|(
operator|&
name|current_time
argument_list|)
expr_stmt|;
return|return
operator|(
name|current_time
operator|.
name|tv_sec
operator|*
literal|1000000000UL
operator|+
name|current_time
operator|.
name|tv_nsec
operator|)
return|;
block|}
end_function

begin_comment
comment|/* Function to handle DTrace traps during probes. See arm64/arm64/trap.c */
end_comment

begin_function
name|int
name|dtrace_trap
parameter_list|(
name|struct
name|trapframe
modifier|*
name|frame
parameter_list|,
name|u_int
name|type
parameter_list|)
block|{
comment|/* 	 * A trap can occur while DTrace executes a probe. Before 	 * executing the probe, DTrace blocks re-scheduling and sets 	 * a flag in it's per-cpu flags to indicate that it doesn't 	 * want to fault. On returning from the probe, the no-fault 	 * flag is cleared and finally re-scheduling is enabled. 	 * 	 * Check if DTrace has enabled 'no-fault' mode: 	 * 	 */
if|if
condition|(
operator|(
name|cpu_core
index|[
name|curcpu
index|]
operator|.
name|cpuc_dtrace_flags
operator|&
name|CPU_DTRACE_NOFAULT
operator|)
operator|!=
literal|0
condition|)
block|{
comment|/* 		 * There are only a couple of trap types that are expected. 		 * All the rest will be handled in the usual way. 		 */
switch|switch
condition|(
name|type
condition|)
block|{
case|case
name|EXCP_DATA_ABORT
case|:
comment|/* Flag a bad address. */
name|cpu_core
index|[
name|curcpu
index|]
operator|.
name|cpuc_dtrace_flags
operator||=
name|CPU_DTRACE_BADADDR
expr_stmt|;
name|cpu_core
index|[
name|curcpu
index|]
operator|.
name|cpuc_dtrace_illval
operator|=
literal|0
expr_stmt|;
comment|/* 			 * Offset the instruction pointer to the instruction 			 * following the one causing the fault. 			 */
name|frame
operator|->
name|tf_elr
operator|+=
literal|4
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
default|default:
comment|/* Handle all other traps in the usual way. */
break|break;
block|}
block|}
comment|/* Handle the trap in the usual way. */
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_function
name|void
name|dtrace_probe_error
parameter_list|(
name|dtrace_state_t
modifier|*
name|state
parameter_list|,
name|dtrace_epid_t
name|epid
parameter_list|,
name|int
name|which
parameter_list|,
name|int
name|fault
parameter_list|,
name|int
name|fltoffs
parameter_list|,
name|uintptr_t
name|illval
parameter_list|)
block|{
name|dtrace_probe
argument_list|(
name|dtrace_probeid_error
argument_list|,
operator|(
name|uint64_t
operator|)
operator|(
name|uintptr_t
operator|)
name|state
argument_list|,
operator|(
name|uintptr_t
operator|)
name|epid
argument_list|,
operator|(
name|uintptr_t
operator|)
name|which
argument_list|,
operator|(
name|uintptr_t
operator|)
name|fault
argument_list|,
operator|(
name|uintptr_t
operator|)
name|fltoffs
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|int
name|dtrace_invop_start
parameter_list|(
name|struct
name|trapframe
modifier|*
name|frame
parameter_list|)
block|{
name|int
name|data
decl_stmt|,
name|invop
decl_stmt|,
name|reg
decl_stmt|,
name|update_sp
decl_stmt|;
name|register_t
name|arg1
decl_stmt|,
name|arg2
decl_stmt|;
name|register_t
modifier|*
name|sp
decl_stmt|;
name|int
name|offs
decl_stmt|;
name|int
name|tmp
decl_stmt|;
name|int
name|i
decl_stmt|;
name|invop
operator|=
name|dtrace_invop
argument_list|(
name|frame
operator|->
name|tf_elr
argument_list|,
name|frame
argument_list|,
name|frame
operator|->
name|tf_elr
argument_list|)
expr_stmt|;
name|tmp
operator|=
operator|(
name|invop
operator|&
name|LDP_STP_MASK
operator|)
expr_stmt|;
if|if
condition|(
name|tmp
operator|==
name|STP_64
operator|||
name|tmp
operator|==
name|LDP_64
condition|)
block|{
name|sp
operator|=
operator|(
name|register_t
operator|*
operator|)
name|frame
operator|->
name|tf_sp
expr_stmt|;
name|data
operator|=
name|invop
expr_stmt|;
name|arg1
operator|=
operator|(
name|data
operator|>>
name|ARG1_SHIFT
operator|)
operator|&
name|ARG1_MASK
expr_stmt|;
name|arg2
operator|=
operator|(
name|data
operator|>>
name|ARG2_SHIFT
operator|)
operator|&
name|ARG2_MASK
expr_stmt|;
name|offs
operator|=
operator|(
name|data
operator|>>
name|OFFSET_SHIFT
operator|)
operator|&
name|OFFSET_MASK
expr_stmt|;
switch|switch
condition|(
name|tmp
condition|)
block|{
case|case
name|STP_64
case|:
if|if
condition|(
name|offs
operator|>>
operator|(
name|OFFSET_SIZE
operator|-
literal|1
operator|)
condition|)
name|sp
operator|-=
operator|(
operator|~
name|offs
operator|&
name|OFFSET_MASK
operator|)
operator|+
literal|1
expr_stmt|;
else|else
name|sp
operator|+=
operator|(
name|offs
operator|)
expr_stmt|;
operator|*
operator|(
name|sp
operator|+
literal|0
operator|)
operator|=
name|frame
operator|->
name|tf_x
index|[
name|arg1
index|]
expr_stmt|;
operator|*
operator|(
name|sp
operator|+
literal|1
operator|)
operator|=
name|frame
operator|->
name|tf_x
index|[
name|arg2
index|]
expr_stmt|;
break|break;
case|case
name|LDP_64
case|:
name|frame
operator|->
name|tf_x
index|[
name|arg1
index|]
operator|=
operator|*
operator|(
name|sp
operator|+
literal|0
operator|)
expr_stmt|;
name|frame
operator|->
name|tf_x
index|[
name|arg2
index|]
operator|=
operator|*
operator|(
name|sp
operator|+
literal|1
operator|)
expr_stmt|;
if|if
condition|(
name|offs
operator|>>
operator|(
name|OFFSET_SIZE
operator|-
literal|1
operator|)
condition|)
name|sp
operator|-=
operator|(
operator|~
name|offs
operator|&
name|OFFSET_MASK
operator|)
operator|+
literal|1
expr_stmt|;
else|else
name|sp
operator|+=
operator|(
name|offs
operator|)
expr_stmt|;
break|break;
default|default:
break|break;
block|}
comment|/* Update the stack pointer and program counter to continue */
name|frame
operator|->
name|tf_sp
operator|=
operator|(
name|register_t
operator|)
name|sp
expr_stmt|;
name|frame
operator|->
name|tf_elr
operator|+=
name|INSN_SIZE
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
if|if
condition|(
operator|(
name|invop
operator|&
name|B_MASK
operator|)
operator|==
name|B_INSTR
condition|)
block|{
name|data
operator|=
operator|(
name|invop
operator|&
name|B_DATA_MASK
operator|)
expr_stmt|;
comment|/* The data is the number of 4-byte words to change the pc */
name|data
operator|*=
literal|4
expr_stmt|;
name|frame
operator|->
name|tf_elr
operator|+=
name|data
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
if|if
condition|(
name|invop
operator|==
name|RET_INSTR
condition|)
block|{
name|frame
operator|->
name|tf_elr
operator|=
name|frame
operator|->
name|tf_lr
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
return|return
operator|(
operator|-
literal|1
operator|)
return|;
block|}
end_function

begin_function
name|void
name|dtrace_invop_init
parameter_list|(
name|void
parameter_list|)
block|{
name|dtrace_invop_jump_addr
operator|=
name|dtrace_invop_start
expr_stmt|;
block|}
end_function

begin_function
name|void
name|dtrace_invop_uninit
parameter_list|(
name|void
parameter_list|)
block|{
name|dtrace_invop_jump_addr
operator|=
literal|0
expr_stmt|;
block|}
end_function

end_unit

