begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/****************************************************************************  * Copyright (c) 1998 Free Software Foundation, Inc.                        *  *                                                                          *  * Permission is hereby granted, free of charge, to any person obtaining a  *  * copy of this software and associated documentation files (the            *  * "Software"), to deal in the Software without restriction, including      *  * without limitation the rights to use, copy, modify, merge, publish,      *  * distribute, distribute with modifications, sublicense, and/or sell       *  * copies of the Software, and to permit persons to whom the Software is    *  * furnished to do so, subject to the following conditions:                 *  *                                                                          *  * The above copyright notice and this permission notice shall be included  *  * in all copies or substantial portions of the Software.                   *  *                                                                          *  * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS  *  * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF               *  * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.   *  * IN NO EVENT SHALL THE ABOVE COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,   *  * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR    *  * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR    *  * THE USE OR OTHER DEALINGS IN THE SOFTWARE.                               *  *                                                                          *  * Except as contained in this notice, the name(s) of the above copyright   *  * holders shall not be used in advertising or otherwise to promote the     *  * sale, use or other dealings in this Software without prior written       *  * authorization.                                                           *  ****************************************************************************/
end_comment

begin_comment
comment|/****************************************************************************  *  Author: Zeyd M. Ben-Halim<zmbenhal@netcom.com> 1992,1995               *  *     and: Eric S. Raymond<esr@snark.thyrsus.com>                         *  ****************************************************************************/
end_comment

begin_comment
comment|/*  *	vidputs(newmode, outc)  *  *	newmode is taken to be the logical 'or' of the symbols in curses.h  *	representing graphic renditions.  The terminal is set to be in all of  *	the given modes, if possible.  *  *	if the new attribute is normal  *		if exit-alt-char-set exists  *			emit it  *		emit exit-attribute-mode  *	else if set-attributes exists  *		use it to set exactly what you want  *	else  *		if exit-attribute-mode exists  *			turn off everything  *		else  *			turn off those which can be turned off and aren't in  *			newmode.  *		turn on each mode which should be on and isn't, one by one  *  *	NOTE that this algorithm won't achieve the desired mix of attributes  *	in some cases, but those are probably just those cases in which it is  *	actually impossible, anyway, so...  *  * 	NOTE that we cannot assume that there's no interaction between color  *	and other attribute resets.  So each time we reset color (or other  *	attributes) we'll have to be prepared to restore the other.  */
end_comment

begin_include
include|#
directive|include
file|<curses.priv.h>
end_include

begin_include
include|#
directive|include
file|<term.h>
end_include

begin_macro
name|MODULE_ID
argument_list|(
literal|"$Id: lib_vidattr.c,v 1.23 1999/06/12 21:20:41 tom Exp $"
argument_list|)
end_macro

begin_define
define|#
directive|define
name|doPut
parameter_list|(
name|mode
parameter_list|)
value|TPUTS_TRACE(#mode); tputs(mode, 1, outc)
end_define

begin_define
define|#
directive|define
name|TurnOn
parameter_list|(
name|mask
parameter_list|,
name|mode
parameter_list|)
define|\
value|if ((turn_on& mask)&& mode) { doPut(mode); }
end_define

begin_define
define|#
directive|define
name|TurnOff
parameter_list|(
name|mask
parameter_list|,
name|mode
parameter_list|)
define|\
value|if ((turn_off& mask)&& mode) { doPut(mode); turn_off&= ~mask; }
end_define

begin_comment
comment|/* if there is no current screen, assume we *can* do color */
end_comment

begin_define
define|#
directive|define
name|SetColorsIf
parameter_list|(
name|why
parameter_list|,
name|old_attr
parameter_list|)
define|\
value|if ((!SP || SP->_coloron)&& (why)) { \ 		int old_pair = PAIR_NUMBER(old_attr); \ 		T(("old pair = %d -- new pair = %d", old_pair, pair)); \ 		if ((pair != old_pair) \ 		 || (reverse ^ ((old_attr& A_REVERSE) != 0))) { \ 			_nc_do_color(pair, reverse, outc); \ 		} \ 	}
end_define

begin_function
name|int
name|vidputs
parameter_list|(
name|attr_t
name|newmode
parameter_list|,
name|int
function_decl|(
modifier|*
name|outc
function_decl|)
parameter_list|(
name|int
parameter_list|)
parameter_list|)
block|{
specifier|static
name|attr_t
name|previous_attr
init|=
name|A_NORMAL
decl_stmt|;
name|attr_t
name|turn_on
decl_stmt|,
name|turn_off
decl_stmt|;
name|int
name|pair
decl_stmt|;
name|bool
name|reverse
init|=
name|FALSE
decl_stmt|;
name|bool
name|used_ncv
init|=
name|FALSE
decl_stmt|;
name|T
argument_list|(
operator|(
name|T_CALLED
argument_list|(
literal|"vidputs(%s)"
argument_list|)
operator|,
name|_traceattr
argument_list|(
name|newmode
argument_list|)
operator|)
argument_list|)
expr_stmt|;
comment|/* this allows us to go on whether or not newterm() has been called */
if|if
condition|(
name|SP
condition|)
name|previous_attr
operator|=
name|SP
operator|->
name|_current_attr
expr_stmt|;
name|T
argument_list|(
operator|(
literal|"previous attribute was %s"
operator|,
name|_traceattr
argument_list|(
name|previous_attr
argument_list|)
operator|)
argument_list|)
expr_stmt|;
if|#
directive|if
operator|!
name|USE_XMC_SUPPORT
if|if
condition|(
operator|(
name|SP
operator|!=
literal|0
operator|)
operator|&&
operator|(
name|magic_cookie_glitch
operator|>
literal|0
operator|)
condition|)
name|newmode
operator|&=
operator|~
operator|(
name|SP
operator|->
name|_xmc_suppress
operator|)
expr_stmt|;
endif|#
directive|endif
comment|/* 	 * If we have a terminal that cannot combine color with video 	 * attributes, use the colors in preference. 	 */
if|if
condition|(
operator|(
name|newmode
operator|&
name|A_COLOR
operator|)
operator|&&
operator|(
name|no_color_video
operator|>
literal|0
operator|)
condition|)
block|{
specifier|static
specifier|const
struct|struct
block|{
name|attr_t
name|video
decl_stmt|;
name|unsigned
name|bit
decl_stmt|;
block|}
name|table
index|[]
init|=
block|{
block|{
name|A_STANDOUT
block|,
literal|1
block|}
block|,
block|{
name|A_UNDERLINE
block|,
literal|2
block|}
block|,
block|{
name|A_REVERSE
block|,
literal|4
block|}
block|,
block|{
name|A_BLINK
block|,
literal|8
block|}
block|,
block|{
name|A_DIM
block|,
literal|16
block|}
block|,
block|{
name|A_BOLD
block|,
literal|32
block|}
block|,
block|{
name|A_INVIS
block|,
literal|64
block|}
block|,
block|{
name|A_PROTECT
block|,
literal|128
block|}
block|,
block|{
name|A_ALTCHARSET
block|,
literal|256
block|}
block|, 		}
struct|;
name|size_t
name|n
decl_stmt|;
for|for
control|(
name|n
operator|=
literal|0
init|;
name|n
operator|<
name|SIZEOF
argument_list|(
name|table
argument_list|)
condition|;
name|n
operator|++
control|)
block|{
if|if
condition|(
operator|(
name|table
index|[
name|n
index|]
operator|.
name|bit
operator|&
name|no_color_video
operator|)
operator|&&
operator|(
name|table
index|[
name|n
index|]
operator|.
name|video
operator|&
name|newmode
operator|)
condition|)
block|{
name|used_ncv
operator|=
name|TRUE
expr_stmt|;
if|if
condition|(
name|table
index|[
name|n
index|]
operator|.
name|video
operator|==
name|A_REVERSE
condition|)
name|reverse
operator|=
name|TRUE
expr_stmt|;
else|else
name|newmode
operator|&=
operator|~
name|table
index|[
name|n
index|]
operator|.
name|video
expr_stmt|;
block|}
block|}
block|}
if|if
condition|(
name|newmode
operator|==
name|previous_attr
condition|)
name|returnCode
argument_list|(
name|OK
argument_list|)
expr_stmt|;
name|pair
operator|=
name|PAIR_NUMBER
argument_list|(
name|newmode
argument_list|)
expr_stmt|;
if|if
condition|(
name|reverse
condition|)
block|{
name|newmode
operator|&=
operator|~
name|A_REVERSE
expr_stmt|;
block|}
name|turn_off
operator|=
operator|(
operator|~
name|newmode
operator|&
name|previous_attr
operator|)
operator|&
name|ALL_BUT_COLOR
expr_stmt|;
name|turn_on
operator|=
operator|(
name|newmode
operator|&
operator|~
name|previous_attr
operator|)
operator|&
name|ALL_BUT_COLOR
expr_stmt|;
name|SetColorsIf
argument_list|(
name|pair
operator|==
literal|0
argument_list|,
name|previous_attr
argument_list|)
expr_stmt|;
if|if
condition|(
name|newmode
operator|==
name|A_NORMAL
condition|)
block|{
if|if
condition|(
operator|(
name|previous_attr
operator|&
name|A_ALTCHARSET
operator|)
operator|&&
name|exit_alt_charset_mode
condition|)
block|{
name|doPut
argument_list|(
name|exit_alt_charset_mode
argument_list|)
expr_stmt|;
name|previous_attr
operator|&=
operator|~
name|A_ALTCHARSET
expr_stmt|;
block|}
if|if
condition|(
name|previous_attr
condition|)
block|{
name|doPut
argument_list|(
name|exit_attribute_mode
argument_list|)
expr_stmt|;
name|previous_attr
operator|&=
operator|~
name|A_COLOR
expr_stmt|;
block|}
name|SetColorsIf
argument_list|(
name|pair
operator|!=
literal|0
argument_list|,
name|previous_attr
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|set_attributes
operator|&&
operator|!
name|used_ncv
condition|)
block|{
if|if
condition|(
name|turn_on
operator|||
name|turn_off
condition|)
block|{
name|TPUTS_TRACE
argument_list|(
literal|"set_attributes"
argument_list|)
expr_stmt|;
name|tputs
argument_list|(
name|tparm
argument_list|(
name|set_attributes
argument_list|,
operator|(
name|newmode
operator|&
name|A_STANDOUT
operator|)
operator|!=
literal|0
argument_list|,
operator|(
name|newmode
operator|&
name|A_UNDERLINE
operator|)
operator|!=
literal|0
argument_list|,
operator|(
name|newmode
operator|&
name|A_REVERSE
operator|)
operator|!=
literal|0
argument_list|,
operator|(
name|newmode
operator|&
name|A_BLINK
operator|)
operator|!=
literal|0
argument_list|,
operator|(
name|newmode
operator|&
name|A_DIM
operator|)
operator|!=
literal|0
argument_list|,
operator|(
name|newmode
operator|&
name|A_BOLD
operator|)
operator|!=
literal|0
argument_list|,
operator|(
name|newmode
operator|&
name|A_INVIS
operator|)
operator|!=
literal|0
argument_list|,
operator|(
name|newmode
operator|&
name|A_PROTECT
operator|)
operator|!=
literal|0
argument_list|,
operator|(
name|newmode
operator|&
name|A_ALTCHARSET
operator|)
operator|!=
literal|0
argument_list|)
argument_list|,
literal|1
argument_list|,
name|outc
argument_list|)
expr_stmt|;
name|previous_attr
operator|&=
operator|~
name|A_COLOR
expr_stmt|;
block|}
name|SetColorsIf
argument_list|(
name|pair
operator|!=
literal|0
argument_list|,
name|previous_attr
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|T
argument_list|(
operator|(
literal|"turning %s off"
operator|,
name|_traceattr
argument_list|(
name|turn_off
argument_list|)
operator|)
argument_list|)
expr_stmt|;
name|TurnOff
argument_list|(
name|A_ALTCHARSET
argument_list|,
name|exit_alt_charset_mode
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|SP
operator|||
name|SP
operator|->
name|_use_rmul
condition|)
block|{
name|TurnOff
argument_list|(
name|A_UNDERLINE
argument_list|,
name|exit_underline_mode
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
operator|!
name|SP
operator|||
name|SP
operator|->
name|_use_rmso
condition|)
block|{
name|TurnOff
argument_list|(
name|A_STANDOUT
argument_list|,
name|exit_standout_mode
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|turn_off
operator|&&
name|exit_attribute_mode
condition|)
block|{
name|doPut
argument_list|(
name|exit_attribute_mode
argument_list|)
expr_stmt|;
name|turn_on
operator||=
operator|(
name|newmode
operator|&
call|(
name|chtype
call|)
argument_list|(
operator|~
name|A_COLOR
argument_list|)
operator|)
expr_stmt|;
name|previous_attr
operator|&=
operator|~
name|A_COLOR
expr_stmt|;
block|}
name|SetColorsIf
argument_list|(
name|pair
operator|!=
literal|0
argument_list|,
name|previous_attr
argument_list|)
expr_stmt|;
name|T
argument_list|(
operator|(
literal|"turning %s on"
operator|,
name|_traceattr
argument_list|(
name|turn_on
argument_list|)
operator|)
argument_list|)
expr_stmt|;
name|TurnOn
argument_list|(
name|A_ALTCHARSET
argument_list|,
name|enter_alt_charset_mode
argument_list|)
expr_stmt|;
name|TurnOn
argument_list|(
name|A_BLINK
argument_list|,
name|enter_blink_mode
argument_list|)
expr_stmt|;
name|TurnOn
argument_list|(
name|A_BOLD
argument_list|,
name|enter_bold_mode
argument_list|)
expr_stmt|;
name|TurnOn
argument_list|(
name|A_DIM
argument_list|,
name|enter_dim_mode
argument_list|)
expr_stmt|;
name|TurnOn
argument_list|(
name|A_REVERSE
argument_list|,
name|enter_reverse_mode
argument_list|)
expr_stmt|;
name|TurnOn
argument_list|(
name|A_STANDOUT
argument_list|,
name|enter_standout_mode
argument_list|)
expr_stmt|;
name|TurnOn
argument_list|(
name|A_PROTECT
argument_list|,
name|enter_protected_mode
argument_list|)
expr_stmt|;
name|TurnOn
argument_list|(
name|A_INVIS
argument_list|,
name|enter_secure_mode
argument_list|)
expr_stmt|;
name|TurnOn
argument_list|(
name|A_UNDERLINE
argument_list|,
name|enter_underline_mode
argument_list|)
expr_stmt|;
name|TurnOn
argument_list|(
name|A_HORIZONTAL
argument_list|,
name|enter_horizontal_hl_mode
argument_list|)
expr_stmt|;
name|TurnOn
argument_list|(
name|A_LEFT
argument_list|,
name|enter_left_hl_mode
argument_list|)
expr_stmt|;
name|TurnOn
argument_list|(
name|A_LOW
argument_list|,
name|enter_low_hl_mode
argument_list|)
expr_stmt|;
name|TurnOn
argument_list|(
name|A_RIGHT
argument_list|,
name|enter_right_hl_mode
argument_list|)
expr_stmt|;
name|TurnOn
argument_list|(
name|A_TOP
argument_list|,
name|enter_top_hl_mode
argument_list|)
expr_stmt|;
name|TurnOn
argument_list|(
name|A_VERTICAL
argument_list|,
name|enter_vertical_hl_mode
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|reverse
condition|)
name|newmode
operator||=
name|A_REVERSE
expr_stmt|;
if|if
condition|(
name|SP
condition|)
name|SP
operator|->
name|_current_attr
operator|=
name|newmode
expr_stmt|;
else|else
name|previous_attr
operator|=
name|newmode
expr_stmt|;
name|returnCode
argument_list|(
name|OK
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|int
name|vidattr
parameter_list|(
name|attr_t
name|newmode
parameter_list|)
block|{
name|T
argument_list|(
operator|(
name|T_CALLED
argument_list|(
literal|"vidattr(%s)"
argument_list|)
operator|,
name|_traceattr
argument_list|(
name|newmode
argument_list|)
operator|)
argument_list|)
expr_stmt|;
name|returnCode
argument_list|(
name|vidputs
argument_list|(
name|newmode
argument_list|,
name|_nc_outch
argument_list|)
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|chtype
name|termattrs
parameter_list|(
name|void
parameter_list|)
block|{
name|chtype
name|attrs
init|=
name|A_NORMAL
decl_stmt|;
if|if
condition|(
name|enter_alt_charset_mode
condition|)
name|attrs
operator||=
name|A_ALTCHARSET
expr_stmt|;
if|if
condition|(
name|enter_blink_mode
condition|)
name|attrs
operator||=
name|A_BLINK
expr_stmt|;
if|if
condition|(
name|enter_bold_mode
condition|)
name|attrs
operator||=
name|A_BOLD
expr_stmt|;
if|if
condition|(
name|enter_dim_mode
condition|)
name|attrs
operator||=
name|A_DIM
expr_stmt|;
if|if
condition|(
name|enter_reverse_mode
condition|)
name|attrs
operator||=
name|A_REVERSE
expr_stmt|;
if|if
condition|(
name|enter_standout_mode
condition|)
name|attrs
operator||=
name|A_STANDOUT
expr_stmt|;
if|if
condition|(
name|enter_protected_mode
condition|)
name|attrs
operator||=
name|A_PROTECT
expr_stmt|;
if|if
condition|(
name|enter_secure_mode
condition|)
name|attrs
operator||=
name|A_INVIS
expr_stmt|;
if|if
condition|(
name|enter_underline_mode
condition|)
name|attrs
operator||=
name|A_UNDERLINE
expr_stmt|;
if|if
condition|(
name|SP
operator|->
name|_coloron
condition|)
name|attrs
operator||=
name|A_COLOR
expr_stmt|;
return|return
operator|(
name|attrs
operator|)
return|;
block|}
end_function

end_unit

