begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (c) 2000-2002 Sendmail, Inc. and its suppliers.  *      All rights reserved.  * Copyright (c) 1990, 1993  *	The Regents of the University of California.  All rights reserved.  *  * This code is derived from software contributed to Berkeley by  * Chris Torek.  *  * By using this file, you agree to the terms and conditions set  * forth in the LICENSE file which can be found at the top level of  * the sendmail distribution.  */
end_comment

begin_include
include|#
directive|include
file|<sm/gen.h>
end_include

begin_macro
name|SM_RCSID
argument_list|(
literal|"@(#)$Id: fclose.c,v 1.42 2002/02/01 02:28:00 ca Exp $"
argument_list|)
end_macro

begin_include
include|#
directive|include
file|<errno.h>
end_include

begin_include
include|#
directive|include
file|<stdlib.h>
end_include

begin_include
include|#
directive|include
file|<sys/time.h>
end_include

begin_include
include|#
directive|include
file|<setjmp.h>
end_include

begin_include
include|#
directive|include
file|<sm/io.h>
end_include

begin_include
include|#
directive|include
file|<sm/assert.h>
end_include

begin_include
include|#
directive|include
file|<sm/heap.h>
end_include

begin_include
include|#
directive|include
file|<sm/signal.h>
end_include

begin_include
include|#
directive|include
file|<sm/conf.h>
end_include

begin_include
include|#
directive|include
file|<sm/clock.h>
end_include

begin_include
include|#
directive|include
file|"local.h"
end_include

begin_decl_stmt
specifier|static
name|jmp_buf
name|CloseTimeOut
decl_stmt|;
end_decl_stmt

begin_comment
comment|/* **  CLOSEALRM -- handler when timeout activated for sm_io_close() ** **	Returns flow of control to where setjmp(CloseTimeOut) was set. ** **	Parameters: **		sig -- unused ** **	Returns: **		does not return ** **	Side Effects: **		returns flow of control to setjmp(CloseTimeOut). ** **	NOTE:	THIS CAN BE CALLED FROM A SIGNAL HANDLER.  DO NOT ADD **		ANYTHING TO THIS ROUTINE UNLESS YOU KNOW WHAT YOU ARE **		DOING. */
end_comment

begin_comment
comment|/* ARGSUSED0 */
end_comment

begin_function
specifier|static
name|void
name|closealrm
parameter_list|(
name|sig
parameter_list|)
name|int
name|sig
decl_stmt|;
block|{
name|longjmp
argument_list|(
name|CloseTimeOut
argument_list|,
literal|1
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/* **  SM_IO_CLOSE -- close a file handle/pointer ** **	Parameters: **		fp -- file pointer to be closed **		timeout -- maximum time allowed to perform the close (millisecs) ** **	Returns: **		0 on success **		-1 on failure and sets errno ** **	Side Effects: **		file pointer 'fp' will no longer be valid. */
end_comment

begin_function
name|int
name|sm_io_close
parameter_list|(
name|fp
parameter_list|,
name|timeout
parameter_list|)
specifier|register
name|SM_FILE_T
modifier|*
name|fp
decl_stmt|;
name|int
name|SM_NONVOLATILE
name|timeout
decl_stmt|;
block|{
specifier|register
name|int
name|SM_NONVOLATILE
name|r
decl_stmt|;
name|SM_EVENT
modifier|*
name|evt
init|=
name|NULL
decl_stmt|;
if|if
condition|(
name|fp
operator|==
name|NULL
condition|)
block|{
name|errno
operator|=
name|EBADF
expr_stmt|;
return|return
name|SM_IO_EOF
return|;
block|}
name|SM_REQUIRE_ISA
argument_list|(
name|fp
argument_list|,
name|SmFileMagic
argument_list|)
expr_stmt|;
comment|/* XXX this won't be reached if above macro is active */
if|if
condition|(
name|fp
operator|->
name|sm_magic
operator|==
name|NULL
condition|)
block|{
comment|/* not open! */
name|errno
operator|=
name|EBADF
expr_stmt|;
return|return
name|SM_IO_EOF
return|;
block|}
if|if
condition|(
name|fp
operator|->
name|f_close
operator|==
name|NULL
condition|)
block|{
comment|/* no close function! */
name|errno
operator|=
name|ENODEV
expr_stmt|;
return|return
name|SM_IO_EOF
return|;
block|}
if|if
condition|(
name|fp
operator|->
name|f_dup_cnt
operator|>
literal|0
condition|)
block|{
comment|/* decrement file pointer open count */
name|fp
operator|->
name|f_dup_cnt
operator|--
expr_stmt|;
return|return
literal|0
return|;
block|}
comment|/*  Okay, this is where we set the timeout.  */
if|if
condition|(
name|timeout
operator|==
name|SM_TIME_DEFAULT
condition|)
name|timeout
operator|=
name|fp
operator|->
name|f_timeout
expr_stmt|;
if|if
condition|(
name|timeout
operator|==
name|SM_TIME_IMMEDIATE
condition|)
block|{
name|errno
operator|=
name|EAGAIN
expr_stmt|;
return|return
operator|-
literal|1
return|;
block|}
comment|/* No more duplicates of file pointer. Flush buffer and close */
name|r
operator|=
name|fp
operator|->
name|f_flags
operator|&
name|SMWR
condition|?
name|sm_flush
argument_list|(
name|fp
argument_list|,
operator|(
name|int
operator|*
operator|)
operator|&
name|timeout
argument_list|)
else|:
literal|0
expr_stmt|;
comment|/* sm_flush() has updated to.it_value for the time it's used */
if|if
condition|(
name|timeout
operator|!=
name|SM_TIME_FOREVER
condition|)
block|{
if|if
condition|(
name|setjmp
argument_list|(
name|CloseTimeOut
argument_list|)
operator|!=
literal|0
condition|)
block|{
name|errno
operator|=
name|EAGAIN
expr_stmt|;
return|return
name|SM_IO_EOF
return|;
block|}
name|evt
operator|=
name|sm_seteventm
argument_list|(
name|timeout
argument_list|,
name|closealrm
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
call|(
modifier|*
name|fp
operator|->
name|f_close
call|)
argument_list|(
name|fp
argument_list|)
operator|<
literal|0
condition|)
name|r
operator|=
name|SM_IO_EOF
expr_stmt|;
comment|/*  We're back. So undo our timeout and handler */
if|if
condition|(
name|evt
operator|!=
name|NULL
condition|)
name|sm_clrevent
argument_list|(
name|evt
argument_list|)
expr_stmt|;
if|if
condition|(
name|fp
operator|->
name|f_flags
operator|&
name|SMMBF
condition|)
block|{
name|sm_free
argument_list|(
operator|(
name|char
operator|*
operator|)
name|fp
operator|->
name|f_bf
operator|.
name|smb_base
argument_list|)
expr_stmt|;
name|fp
operator|->
name|f_bf
operator|.
name|smb_base
operator|=
name|NULL
expr_stmt|;
block|}
if|if
condition|(
name|HASUB
argument_list|(
name|fp
argument_list|)
condition|)
name|FREEUB
argument_list|(
name|fp
argument_list|)
expr_stmt|;
name|fp
operator|->
name|f_flags
operator|=
literal|0
expr_stmt|;
comment|/* clear flags */
name|fp
operator|->
name|sm_magic
operator|=
name|NULL
expr_stmt|;
comment|/* Release this SM_FILE_T for reuse. */
name|fp
operator|->
name|f_r
operator|=
name|fp
operator|->
name|f_w
operator|=
literal|0
expr_stmt|;
comment|/* Mess up if reaccessed. */
return|return
name|r
return|;
block|}
end_function

end_unit

