begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * System call names.  *  * DO NOT EDIT-- this file is automatically generated.  * $FreeBSD$  * created from FreeBSD: src/sys/kern/syscalls.master,v 1.101 2001/12/29 07:13:45 alfred Exp   */
end_comment

begin_decl_stmt
name|char
modifier|*
name|syscallnames
index|[]
init|=
block|{
literal|"syscall"
block|,
comment|/* 0 = syscall */
literal|"exit"
block|,
comment|/* 1 = exit */
literal|"fork"
block|,
comment|/* 2 = fork */
literal|"read"
block|,
comment|/* 3 = read */
literal|"write"
block|,
comment|/* 4 = write */
literal|"open"
block|,
comment|/* 5 = open */
literal|"close"
block|,
comment|/* 6 = close */
literal|"wait4"
block|,
comment|/* 7 = wait4 */
literal|"old.creat"
block|,
comment|/* 8 = old creat */
literal|"link"
block|,
comment|/* 9 = link */
literal|"unlink"
block|,
comment|/* 10 = unlink */
literal|"obs_execv"
block|,
comment|/* 11 = obsolete execv */
literal|"chdir"
block|,
comment|/* 12 = chdir */
literal|"fchdir"
block|,
comment|/* 13 = fchdir */
literal|"mknod"
block|,
comment|/* 14 = mknod */
literal|"chmod"
block|,
comment|/* 15 = chmod */
literal|"chown"
block|,
comment|/* 16 = chown */
literal|"break"
block|,
comment|/* 17 = break */
literal|"getfsstat"
block|,
comment|/* 18 = getfsstat */
literal|"old.lseek"
block|,
comment|/* 19 = old lseek */
literal|"getpid"
block|,
comment|/* 20 = getpid */
literal|"mount"
block|,
comment|/* 21 = mount */
literal|"unmount"
block|,
comment|/* 22 = unmount */
literal|"setuid"
block|,
comment|/* 23 = setuid */
literal|"getuid"
block|,
comment|/* 24 = getuid */
literal|"geteuid"
block|,
comment|/* 25 = geteuid */
literal|"ptrace"
block|,
comment|/* 26 = ptrace */
literal|"recvmsg"
block|,
comment|/* 27 = recvmsg */
literal|"sendmsg"
block|,
comment|/* 28 = sendmsg */
literal|"recvfrom"
block|,
comment|/* 29 = recvfrom */
literal|"accept"
block|,
comment|/* 30 = accept */
literal|"getpeername"
block|,
comment|/* 31 = getpeername */
literal|"getsockname"
block|,
comment|/* 32 = getsockname */
literal|"access"
block|,
comment|/* 33 = access */
literal|"chflags"
block|,
comment|/* 34 = chflags */
literal|"fchflags"
block|,
comment|/* 35 = fchflags */
literal|"sync"
block|,
comment|/* 36 = sync */
literal|"kill"
block|,
comment|/* 37 = kill */
literal|"old.stat"
block|,
comment|/* 38 = old stat */
literal|"getppid"
block|,
comment|/* 39 = getppid */
literal|"old.lstat"
block|,
comment|/* 40 = old lstat */
literal|"dup"
block|,
comment|/* 41 = dup */
literal|"pipe"
block|,
comment|/* 42 = pipe */
literal|"getegid"
block|,
comment|/* 43 = getegid */
literal|"profil"
block|,
comment|/* 44 = profil */
literal|"ktrace"
block|,
comment|/* 45 = ktrace */
literal|"old.sigaction"
block|,
comment|/* 46 = old sigaction */
literal|"getgid"
block|,
comment|/* 47 = getgid */
literal|"old.sigprocmask"
block|,
comment|/* 48 = old sigprocmask */
literal|"getlogin"
block|,
comment|/* 49 = getlogin */
literal|"setlogin"
block|,
comment|/* 50 = setlogin */
literal|"acct"
block|,
comment|/* 51 = acct */
literal|"old.sigpending"
block|,
comment|/* 52 = old sigpending */
literal|"sigaltstack"
block|,
comment|/* 53 = sigaltstack */
literal|"ioctl"
block|,
comment|/* 54 = ioctl */
literal|"reboot"
block|,
comment|/* 55 = reboot */
literal|"revoke"
block|,
comment|/* 56 = revoke */
literal|"symlink"
block|,
comment|/* 57 = symlink */
literal|"readlink"
block|,
comment|/* 58 = readlink */
literal|"execve"
block|,
comment|/* 59 = execve */
literal|"umask"
block|,
comment|/* 60 = umask */
literal|"chroot"
block|,
comment|/* 61 = chroot */
literal|"old.fstat"
block|,
comment|/* 62 = old fstat */
literal|"old.getkerninfo"
block|,
comment|/* 63 = old getkerninfo */
literal|"old.getpagesize"
block|,
comment|/* 64 = old getpagesize */
literal|"msync"
block|,
comment|/* 65 = msync */
literal|"vfork"
block|,
comment|/* 66 = vfork */
literal|"obs_vread"
block|,
comment|/* 67 = obsolete vread */
literal|"obs_vwrite"
block|,
comment|/* 68 = obsolete vwrite */
literal|"sbrk"
block|,
comment|/* 69 = sbrk */
literal|"sstk"
block|,
comment|/* 70 = sstk */
literal|"old.mmap"
block|,
comment|/* 71 = old mmap */
literal|"vadvise"
block|,
comment|/* 72 = vadvise */
literal|"munmap"
block|,
comment|/* 73 = munmap */
literal|"mprotect"
block|,
comment|/* 74 = mprotect */
literal|"madvise"
block|,
comment|/* 75 = madvise */
literal|"obs_vhangup"
block|,
comment|/* 76 = obsolete vhangup */
literal|"obs_vlimit"
block|,
comment|/* 77 = obsolete vlimit */
literal|"mincore"
block|,
comment|/* 78 = mincore */
literal|"getgroups"
block|,
comment|/* 79 = getgroups */
literal|"setgroups"
block|,
comment|/* 80 = setgroups */
literal|"getpgrp"
block|,
comment|/* 81 = getpgrp */
literal|"setpgid"
block|,
comment|/* 82 = setpgid */
literal|"setitimer"
block|,
comment|/* 83 = setitimer */
literal|"old.wait"
block|,
comment|/* 84 = old wait */
literal|"swapon"
block|,
comment|/* 85 = swapon */
literal|"getitimer"
block|,
comment|/* 86 = getitimer */
literal|"old.gethostname"
block|,
comment|/* 87 = old gethostname */
literal|"old.sethostname"
block|,
comment|/* 88 = old sethostname */
literal|"getdtablesize"
block|,
comment|/* 89 = getdtablesize */
literal|"dup2"
block|,
comment|/* 90 = dup2 */
literal|"#91"
block|,
comment|/* 91 = getdopt */
literal|"fcntl"
block|,
comment|/* 92 = fcntl */
literal|"select"
block|,
comment|/* 93 = select */
literal|"#94"
block|,
comment|/* 94 = setdopt */
literal|"fsync"
block|,
comment|/* 95 = fsync */
literal|"setpriority"
block|,
comment|/* 96 = setpriority */
literal|"socket"
block|,
comment|/* 97 = socket */
literal|"connect"
block|,
comment|/* 98 = connect */
literal|"old.accept"
block|,
comment|/* 99 = old accept */
literal|"getpriority"
block|,
comment|/* 100 = getpriority */
literal|"old.send"
block|,
comment|/* 101 = old send */
literal|"old.recv"
block|,
comment|/* 102 = old recv */
literal|"old.sigreturn"
block|,
comment|/* 103 = old sigreturn */
literal|"bind"
block|,
comment|/* 104 = bind */
literal|"setsockopt"
block|,
comment|/* 105 = setsockopt */
literal|"listen"
block|,
comment|/* 106 = listen */
literal|"obs_vtimes"
block|,
comment|/* 107 = obsolete vtimes */
literal|"old.sigvec"
block|,
comment|/* 108 = old sigvec */
literal|"old.sigblock"
block|,
comment|/* 109 = old sigblock */
literal|"old.sigsetmask"
block|,
comment|/* 110 = old sigsetmask */
literal|"old.sigsuspend"
block|,
comment|/* 111 = old sigsuspend */
literal|"old.sigstack"
block|,
comment|/* 112 = old sigstack */
literal|"old.recvmsg"
block|,
comment|/* 113 = old recvmsg */
literal|"old.sendmsg"
block|,
comment|/* 114 = old sendmsg */
literal|"obs_vtrace"
block|,
comment|/* 115 = obsolete vtrace */
literal|"gettimeofday"
block|,
comment|/* 116 = gettimeofday */
literal|"getrusage"
block|,
comment|/* 117 = getrusage */
literal|"getsockopt"
block|,
comment|/* 118 = getsockopt */
literal|"#119"
block|,
comment|/* 119 = resuba */
literal|"readv"
block|,
comment|/* 120 = readv */
literal|"writev"
block|,
comment|/* 121 = writev */
literal|"settimeofday"
block|,
comment|/* 122 = settimeofday */
literal|"fchown"
block|,
comment|/* 123 = fchown */
literal|"fchmod"
block|,
comment|/* 124 = fchmod */
literal|"old.recvfrom"
block|,
comment|/* 125 = old recvfrom */
literal|"setreuid"
block|,
comment|/* 126 = setreuid */
literal|"setregid"
block|,
comment|/* 127 = setregid */
literal|"rename"
block|,
comment|/* 128 = rename */
literal|"old.truncate"
block|,
comment|/* 129 = old truncate */
literal|"old.ftruncate"
block|,
comment|/* 130 = old ftruncate */
literal|"flock"
block|,
comment|/* 131 = flock */
literal|"mkfifo"
block|,
comment|/* 132 = mkfifo */
literal|"sendto"
block|,
comment|/* 133 = sendto */
literal|"shutdown"
block|,
comment|/* 134 = shutdown */
literal|"socketpair"
block|,
comment|/* 135 = socketpair */
literal|"mkdir"
block|,
comment|/* 136 = mkdir */
literal|"rmdir"
block|,
comment|/* 137 = rmdir */
literal|"utimes"
block|,
comment|/* 138 = utimes */
literal|"obs_4.2"
block|,
comment|/* 139 = obsolete 4.2 sigreturn */
literal|"adjtime"
block|,
comment|/* 140 = adjtime */
literal|"old.getpeername"
block|,
comment|/* 141 = old getpeername */
literal|"old.gethostid"
block|,
comment|/* 142 = old gethostid */
literal|"old.sethostid"
block|,
comment|/* 143 = old sethostid */
literal|"old.getrlimit"
block|,
comment|/* 144 = old getrlimit */
literal|"old.setrlimit"
block|,
comment|/* 145 = old setrlimit */
literal|"old.killpg"
block|,
comment|/* 146 = old killpg */
literal|"setsid"
block|,
comment|/* 147 = setsid */
literal|"quotactl"
block|,
comment|/* 148 = quotactl */
literal|"old.quota"
block|,
comment|/* 149 = old quota */
literal|"old.getsockname"
block|,
comment|/* 150 = old getsockname */
literal|"#151"
block|,
comment|/* 151 = sem_lock */
literal|"#152"
block|,
comment|/* 152 = sem_wakeup */
literal|"#153"
block|,
comment|/* 153 = asyncdaemon */
literal|"#154"
block|,
comment|/* 154 = nosys */
literal|"nfssvc"
block|,
comment|/* 155 = nfssvc */
literal|"old.getdirentries"
block|,
comment|/* 156 = old getdirentries */
literal|"statfs"
block|,
comment|/* 157 = statfs */
literal|"fstatfs"
block|,
comment|/* 158 = fstatfs */
literal|"#159"
block|,
comment|/* 159 = nosys */
literal|"#160"
block|,
comment|/* 160 = nosys */
literal|"getfh"
block|,
comment|/* 161 = getfh */
literal|"getdomainname"
block|,
comment|/* 162 = getdomainname */
literal|"setdomainname"
block|,
comment|/* 163 = setdomainname */
literal|"uname"
block|,
comment|/* 164 = uname */
literal|"sysarch"
block|,
comment|/* 165 = sysarch */
literal|"rtprio"
block|,
comment|/* 166 = rtprio */
literal|"#167"
block|,
comment|/* 167 = nosys */
literal|"#168"
block|,
comment|/* 168 = nosys */
literal|"semsys"
block|,
comment|/* 169 = semsys */
literal|"msgsys"
block|,
comment|/* 170 = msgsys */
literal|"shmsys"
block|,
comment|/* 171 = shmsys */
literal|"#172"
block|,
comment|/* 172 = nosys */
literal|"pread"
block|,
comment|/* 173 = pread */
literal|"pwrite"
block|,
comment|/* 174 = pwrite */
literal|"#175"
block|,
comment|/* 175 = nosys */
literal|"ntp_adjtime"
block|,
comment|/* 176 = ntp_adjtime */
literal|"#177"
block|,
comment|/* 177 = sfork */
literal|"#178"
block|,
comment|/* 178 = getdescriptor */
literal|"#179"
block|,
comment|/* 179 = setdescriptor */
literal|"#180"
block|,
comment|/* 180 = nosys */
literal|"setgid"
block|,
comment|/* 181 = setgid */
literal|"setegid"
block|,
comment|/* 182 = setegid */
literal|"seteuid"
block|,
comment|/* 183 = seteuid */
literal|"#184"
block|,
comment|/* 184 = lfs_bmapv */
literal|"#185"
block|,
comment|/* 185 = lfs_markv */
literal|"#186"
block|,
comment|/* 186 = lfs_segclean */
literal|"#187"
block|,
comment|/* 187 = lfs_segwait */
literal|"stat"
block|,
comment|/* 188 = stat */
literal|"fstat"
block|,
comment|/* 189 = fstat */
literal|"lstat"
block|,
comment|/* 190 = lstat */
literal|"pathconf"
block|,
comment|/* 191 = pathconf */
literal|"fpathconf"
block|,
comment|/* 192 = fpathconf */
literal|"#193"
block|,
comment|/* 193 = nosys */
literal|"getrlimit"
block|,
comment|/* 194 = getrlimit */
literal|"setrlimit"
block|,
comment|/* 195 = setrlimit */
literal|"getdirentries"
block|,
comment|/* 196 = getdirentries */
literal|"mmap"
block|,
comment|/* 197 = mmap */
literal|"__syscall"
block|,
comment|/* 198 = __syscall */
literal|"lseek"
block|,
comment|/* 199 = lseek */
literal|"truncate"
block|,
comment|/* 200 = truncate */
literal|"ftruncate"
block|,
comment|/* 201 = ftruncate */
literal|"__sysctl"
block|,
comment|/* 202 = __sysctl */
literal|"mlock"
block|,
comment|/* 203 = mlock */
literal|"munlock"
block|,
comment|/* 204 = munlock */
literal|"undelete"
block|,
comment|/* 205 = undelete */
literal|"futimes"
block|,
comment|/* 206 = futimes */
literal|"getpgid"
block|,
comment|/* 207 = getpgid */
literal|"#208"
block|,
comment|/* 208 = newreboot */
literal|"poll"
block|,
comment|/* 209 = poll */
literal|"lkmnosys"
block|,
comment|/* 210 = lkmnosys */
literal|"lkmnosys"
block|,
comment|/* 211 = lkmnosys */
literal|"lkmnosys"
block|,
comment|/* 212 = lkmnosys */
literal|"lkmnosys"
block|,
comment|/* 213 = lkmnosys */
literal|"lkmnosys"
block|,
comment|/* 214 = lkmnosys */
literal|"lkmnosys"
block|,
comment|/* 215 = lkmnosys */
literal|"lkmnosys"
block|,
comment|/* 216 = lkmnosys */
literal|"lkmnosys"
block|,
comment|/* 217 = lkmnosys */
literal|"lkmnosys"
block|,
comment|/* 218 = lkmnosys */
literal|"lkmnosys"
block|,
comment|/* 219 = lkmnosys */
literal|"__semctl"
block|,
comment|/* 220 = __semctl */
literal|"semget"
block|,
comment|/* 221 = semget */
literal|"semop"
block|,
comment|/* 222 = semop */
literal|"#223"
block|,
comment|/* 223 = semconfig */
literal|"msgctl"
block|,
comment|/* 224 = msgctl */
literal|"msgget"
block|,
comment|/* 225 = msgget */
literal|"msgsnd"
block|,
comment|/* 226 = msgsnd */
literal|"msgrcv"
block|,
comment|/* 227 = msgrcv */
literal|"shmat"
block|,
comment|/* 228 = shmat */
literal|"shmctl"
block|,
comment|/* 229 = shmctl */
literal|"shmdt"
block|,
comment|/* 230 = shmdt */
literal|"shmget"
block|,
comment|/* 231 = shmget */
literal|"clock_gettime"
block|,
comment|/* 232 = clock_gettime */
literal|"clock_settime"
block|,
comment|/* 233 = clock_settime */
literal|"clock_getres"
block|,
comment|/* 234 = clock_getres */
literal|"#235"
block|,
comment|/* 235 = timer_create */
literal|"#236"
block|,
comment|/* 236 = timer_delete */
literal|"#237"
block|,
comment|/* 237 = timer_settime */
literal|"#238"
block|,
comment|/* 238 = timer_gettime */
literal|"#239"
block|,
comment|/* 239 = timer_getoverrun */
literal|"nanosleep"
block|,
comment|/* 240 = nanosleep */
literal|"#241"
block|,
comment|/* 241 = nosys */
literal|"#242"
block|,
comment|/* 242 = nosys */
literal|"#243"
block|,
comment|/* 243 = nosys */
literal|"#244"
block|,
comment|/* 244 = nosys */
literal|"#245"
block|,
comment|/* 245 = nosys */
literal|"#246"
block|,
comment|/* 246 = nosys */
literal|"#247"
block|,
comment|/* 247 = nosys */
literal|"#248"
block|,
comment|/* 248 = nosys */
literal|"#249"
block|,
comment|/* 249 = nosys */
literal|"minherit"
block|,
comment|/* 250 = minherit */
literal|"rfork"
block|,
comment|/* 251 = rfork */
literal|"openbsd_poll"
block|,
comment|/* 252 = openbsd_poll */
literal|"issetugid"
block|,
comment|/* 253 = issetugid */
literal|"lchown"
block|,
comment|/* 254 = lchown */
literal|"#255"
block|,
comment|/* 255 = nosys */
literal|"#256"
block|,
comment|/* 256 = nosys */
literal|"#257"
block|,
comment|/* 257 = nosys */
literal|"#258"
block|,
comment|/* 258 = nosys */
literal|"#259"
block|,
comment|/* 259 = nosys */
literal|"#260"
block|,
comment|/* 260 = nosys */
literal|"#261"
block|,
comment|/* 261 = nosys */
literal|"#262"
block|,
comment|/* 262 = nosys */
literal|"#263"
block|,
comment|/* 263 = nosys */
literal|"#264"
block|,
comment|/* 264 = nosys */
literal|"#265"
block|,
comment|/* 265 = nosys */
literal|"#266"
block|,
comment|/* 266 = nosys */
literal|"#267"
block|,
comment|/* 267 = nosys */
literal|"#268"
block|,
comment|/* 268 = nosys */
literal|"#269"
block|,
comment|/* 269 = nosys */
literal|"#270"
block|,
comment|/* 270 = nosys */
literal|"#271"
block|,
comment|/* 271 = nosys */
literal|"getdents"
block|,
comment|/* 272 = getdents */
literal|"#273"
block|,
comment|/* 273 = nosys */
literal|"lchmod"
block|,
comment|/* 274 = lchmod */
literal|"netbsd_lchown"
block|,
comment|/* 275 = netbsd_lchown */
literal|"lutimes"
block|,
comment|/* 276 = lutimes */
literal|"netbsd_msync"
block|,
comment|/* 277 = netbsd_msync */
literal|"nstat"
block|,
comment|/* 278 = nstat */
literal|"nfstat"
block|,
comment|/* 279 = nfstat */
literal|"nlstat"
block|,
comment|/* 280 = nlstat */
literal|"#281"
block|,
comment|/* 281 = nosys */
literal|"#282"
block|,
comment|/* 282 = nosys */
literal|"#283"
block|,
comment|/* 283 = nosys */
literal|"#284"
block|,
comment|/* 284 = nosys */
literal|"#285"
block|,
comment|/* 285 = nosys */
literal|"#286"
block|,
comment|/* 286 = nosys */
literal|"#287"
block|,
comment|/* 287 = nosys */
literal|"#288"
block|,
comment|/* 288 = nosys */
literal|"#289"
block|,
comment|/* 289 = nosys */
literal|"#290"
block|,
comment|/* 290 = nosys */
literal|"#291"
block|,
comment|/* 291 = nosys */
literal|"#292"
block|,
comment|/* 292 = nosys */
literal|"#293"
block|,
comment|/* 293 = nosys */
literal|"#294"
block|,
comment|/* 294 = nosys */
literal|"#295"
block|,
comment|/* 295 = nosys */
literal|"#296"
block|,
comment|/* 296 = nosys */
literal|"fhstatfs"
block|,
comment|/* 297 = fhstatfs */
literal|"fhopen"
block|,
comment|/* 298 = fhopen */
literal|"fhstat"
block|,
comment|/* 299 = fhstat */
literal|"modnext"
block|,
comment|/* 300 = modnext */
literal|"modstat"
block|,
comment|/* 301 = modstat */
literal|"modfnext"
block|,
comment|/* 302 = modfnext */
literal|"modfind"
block|,
comment|/* 303 = modfind */
literal|"kldload"
block|,
comment|/* 304 = kldload */
literal|"kldunload"
block|,
comment|/* 305 = kldunload */
literal|"kldfind"
block|,
comment|/* 306 = kldfind */
literal|"kldnext"
block|,
comment|/* 307 = kldnext */
literal|"kldstat"
block|,
comment|/* 308 = kldstat */
literal|"kldfirstmod"
block|,
comment|/* 309 = kldfirstmod */
literal|"getsid"
block|,
comment|/* 310 = getsid */
literal|"setresuid"
block|,
comment|/* 311 = setresuid */
literal|"setresgid"
block|,
comment|/* 312 = setresgid */
literal|"obs_signanosleep"
block|,
comment|/* 313 = obsolete signanosleep */
literal|"aio_return"
block|,
comment|/* 314 = aio_return */
literal|"aio_suspend"
block|,
comment|/* 315 = aio_suspend */
literal|"aio_cancel"
block|,
comment|/* 316 = aio_cancel */
literal|"aio_error"
block|,
comment|/* 317 = aio_error */
literal|"aio_read"
block|,
comment|/* 318 = aio_read */
literal|"aio_write"
block|,
comment|/* 319 = aio_write */
literal|"lio_listio"
block|,
comment|/* 320 = lio_listio */
literal|"yield"
block|,
comment|/* 321 = yield */
literal|"obs_thr_sleep"
block|,
comment|/* 322 = obsolete thr_sleep */
literal|"obs_thr_wakeup"
block|,
comment|/* 323 = obsolete thr_wakeup */
literal|"mlockall"
block|,
comment|/* 324 = mlockall */
literal|"munlockall"
block|,
comment|/* 325 = munlockall */
literal|"__getcwd"
block|,
comment|/* 326 = __getcwd */
literal|"sched_setparam"
block|,
comment|/* 327 = sched_setparam */
literal|"sched_getparam"
block|,
comment|/* 328 = sched_getparam */
literal|"sched_setscheduler"
block|,
comment|/* 329 = sched_setscheduler */
literal|"sched_getscheduler"
block|,
comment|/* 330 = sched_getscheduler */
literal|"sched_yield"
block|,
comment|/* 331 = sched_yield */
literal|"sched_get_priority_max"
block|,
comment|/* 332 = sched_get_priority_max */
literal|"sched_get_priority_min"
block|,
comment|/* 333 = sched_get_priority_min */
literal|"sched_rr_get_interval"
block|,
comment|/* 334 = sched_rr_get_interval */
literal|"utrace"
block|,
comment|/* 335 = utrace */
literal|"sendfile"
block|,
comment|/* 336 = sendfile */
literal|"kldsym"
block|,
comment|/* 337 = kldsym */
literal|"jail"
block|,
comment|/* 338 = jail */
literal|"#339"
block|,
comment|/* 339 = pioctl */
literal|"sigprocmask"
block|,
comment|/* 340 = sigprocmask */
literal|"sigsuspend"
block|,
comment|/* 341 = sigsuspend */
literal|"sigaction"
block|,
comment|/* 342 = sigaction */
literal|"sigpending"
block|,
comment|/* 343 = sigpending */
literal|"sigreturn"
block|,
comment|/* 344 = sigreturn */
literal|"#345"
block|,
comment|/* 345 = sigtimedwait */
literal|"#346"
block|,
comment|/* 346 = sigwaitinfo */
literal|"__acl_get_file"
block|,
comment|/* 347 = __acl_get_file */
literal|"__acl_set_file"
block|,
comment|/* 348 = __acl_set_file */
literal|"__acl_get_fd"
block|,
comment|/* 349 = __acl_get_fd */
literal|"__acl_set_fd"
block|,
comment|/* 350 = __acl_set_fd */
literal|"__acl_delete_file"
block|,
comment|/* 351 = __acl_delete_file */
literal|"__acl_delete_fd"
block|,
comment|/* 352 = __acl_delete_fd */
literal|"__acl_aclcheck_file"
block|,
comment|/* 353 = __acl_aclcheck_file */
literal|"__acl_aclcheck_fd"
block|,
comment|/* 354 = __acl_aclcheck_fd */
literal|"extattrctl"
block|,
comment|/* 355 = extattrctl */
literal|"extattr_set_file"
block|,
comment|/* 356 = extattr_set_file */
literal|"extattr_get_file"
block|,
comment|/* 357 = extattr_get_file */
literal|"extattr_delete_file"
block|,
comment|/* 358 = extattr_delete_file */
literal|"aio_waitcomplete"
block|,
comment|/* 359 = aio_waitcomplete */
literal|"getresuid"
block|,
comment|/* 360 = getresuid */
literal|"getresgid"
block|,
comment|/* 361 = getresgid */
literal|"kqueue"
block|,
comment|/* 362 = kqueue */
literal|"kevent"
block|,
comment|/* 363 = kevent */
literal|"__cap_get_proc"
block|,
comment|/* 364 = __cap_get_proc */
literal|"__cap_set_proc"
block|,
comment|/* 365 = __cap_set_proc */
literal|"__cap_get_fd"
block|,
comment|/* 366 = __cap_get_fd */
literal|"__cap_get_file"
block|,
comment|/* 367 = __cap_get_file */
literal|"__cap_set_fd"
block|,
comment|/* 368 = __cap_set_fd */
literal|"__cap_set_file"
block|,
comment|/* 369 = __cap_set_file */
literal|"lkmressys"
block|,
comment|/* 370 = lkmressys */
literal|"extattr_set_fd"
block|,
comment|/* 371 = extattr_set_fd */
literal|"extattr_get_fd"
block|,
comment|/* 372 = extattr_get_fd */
literal|"extattr_delete_fd"
block|,
comment|/* 373 = extattr_delete_fd */
literal|"__setugid"
block|,
comment|/* 374 = __setugid */
literal|"nfsclnt"
block|,
comment|/* 375 = nfsclnt */
literal|"eaccess"
block|,
comment|/* 376 = eaccess */
literal|"#377"
block|,
comment|/* 377 = afs_syscall */
literal|"nmount"
block|,
comment|/* 378 = nmount */
block|}
decl_stmt|;
end_decl_stmt

end_unit

