begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_include
include|#
directive|include
file|<tommath.h>
end_include

begin_ifdef
ifdef|#
directive|ifdef
name|BN_MP_RAND_C
end_ifdef

begin_comment
comment|/* LibTomMath, multiple-precision integer library -- Tom St Denis  *  * LibTomMath is a library that provides multiple-precision  * integer arithmetic as well as number theoretic functionality.  *  * The library was designed directly after the MPI library by  * Michael Fromberger but has been written from scratch with  * additional optimizations in place.  *  * The library is free for all purposes without any express  * guarantee it works.  *  * Tom St Denis, tomstdenis@gmail.com, http://libtom.org  */
end_comment

begin_comment
comment|/* makes a pseudo-random int of a given size */
end_comment

begin_function
name|int
name|mp_rand
parameter_list|(
name|mp_int
modifier|*
name|a
parameter_list|,
name|int
name|digits
parameter_list|)
block|{
name|int
name|res
decl_stmt|;
name|mp_digit
name|d
decl_stmt|;
name|mp_zero
argument_list|(
name|a
argument_list|)
expr_stmt|;
if|if
condition|(
name|digits
operator|<=
literal|0
condition|)
block|{
return|return
name|MP_OKAY
return|;
block|}
comment|/* first place a random non-zero digit */
do|do
block|{
name|d
operator|=
operator|(
operator|(
name|mp_digit
operator|)
name|abs
argument_list|(
name|rand
argument_list|()
argument_list|)
operator|)
operator|&
name|MP_MASK
expr_stmt|;
block|}
do|while
condition|(
name|d
operator|==
literal|0
condition|)
do|;
if|if
condition|(
operator|(
name|res
operator|=
name|mp_add_d
argument_list|(
name|a
argument_list|,
name|d
argument_list|,
name|a
argument_list|)
operator|)
operator|!=
name|MP_OKAY
condition|)
block|{
return|return
name|res
return|;
block|}
while|while
condition|(
operator|--
name|digits
operator|>
literal|0
condition|)
block|{
if|if
condition|(
operator|(
name|res
operator|=
name|mp_lshd
argument_list|(
name|a
argument_list|,
literal|1
argument_list|)
operator|)
operator|!=
name|MP_OKAY
condition|)
block|{
return|return
name|res
return|;
block|}
if|if
condition|(
operator|(
name|res
operator|=
name|mp_add_d
argument_list|(
name|a
argument_list|,
operator|(
operator|(
name|mp_digit
operator|)
name|abs
argument_list|(
name|rand
argument_list|()
argument_list|)
operator|)
argument_list|,
name|a
argument_list|)
operator|)
operator|!=
name|MP_OKAY
condition|)
block|{
return|return
name|res
return|;
block|}
block|}
return|return
name|MP_OKAY
return|;
block|}
end_function

begin_endif
endif|#
directive|endif
end_endif

begin_comment
comment|/* $Source: /cvs/libtom/libtommath/bn_mp_rand.c,v $ */
end_comment

begin_comment
comment|/* $Revision: 1.4 $ */
end_comment

begin_comment
comment|/* $Date: 2006/12/28 01:25:13 $ */
end_comment

end_unit

