begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*-  * Copyright (c) 2016 Martin Matuska  * All rights reserved.  *  * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions  * are met:  * 1. Redistributions of source code must retain the above copyright  *    notice, this list of conditions and the following disclaimer.  * 2. Redistributions in binary form must reproduce the above copyright  *    notice, this list of conditions and the following disclaimer in the  *    documentation and/or other materials provided with the distribution.  *  * THIS SOFTWARE IS PROVIDED BY THE AUTHOR(S) ``AS IS'' AND ANY EXPRESS OR  * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES  * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  * IN NO EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY DIRECT, INDIRECT,  * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT  * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,  * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY  * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT  * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF  * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.  */
end_comment

begin_include
include|#
directive|include
file|"test.h"
end_include

begin_expr_stmt
name|__FBSDID
argument_list|(
literal|"$FreeBSD$"
argument_list|)
expr_stmt|;
end_expr_stmt

begin_comment
comment|/*  * Test converting ACLs to text, both wide and non-wide  *  * This should work on all systems, regardless of whether local  * filesystems support ACLs or not.  */
end_comment

begin_decl_stmt
specifier|static
name|struct
name|archive_test_acl_t
name|acls0
index|[]
init|=
block|{
block|{
name|ARCHIVE_ENTRY_ACL_TYPE_ACCESS
block|,
name|ARCHIVE_ENTRY_ACL_EXECUTE
operator||
name|ARCHIVE_ENTRY_ACL_READ
operator||
name|ARCHIVE_ENTRY_ACL_WRITE
block|,
name|ARCHIVE_ENTRY_ACL_USER_OBJ
block|,
operator|-
literal|1
block|,
literal|""
block|}
block|,
block|{
name|ARCHIVE_ENTRY_ACL_TYPE_ACCESS
block|,
name|ARCHIVE_ENTRY_ACL_EXECUTE
operator||
name|ARCHIVE_ENTRY_ACL_READ
block|,
name|ARCHIVE_ENTRY_ACL_USER
block|,
literal|100
block|,
literal|"user100"
block|}
block|,
block|{
name|ARCHIVE_ENTRY_ACL_TYPE_ACCESS
block|,
literal|0
block|,
name|ARCHIVE_ENTRY_ACL_USER
block|,
literal|1000
block|,
literal|"user1000"
block|}
block|,
block|{
name|ARCHIVE_ENTRY_ACL_TYPE_ACCESS
block|,
name|ARCHIVE_ENTRY_ACL_EXECUTE
operator||
name|ARCHIVE_ENTRY_ACL_READ
block|,
name|ARCHIVE_ENTRY_ACL_GROUP_OBJ
block|,
operator|-
literal|1
block|,
literal|""
block|}
block|,
block|{
name|ARCHIVE_ENTRY_ACL_TYPE_ACCESS
block|,
name|ARCHIVE_ENTRY_ACL_EXECUTE
operator||
name|ARCHIVE_ENTRY_ACL_READ
operator||
name|ARCHIVE_ENTRY_ACL_WRITE
block|,
name|ARCHIVE_ENTRY_ACL_GROUP
block|,
literal|78
block|,
literal|"group78"
block|}
block|,
block|{
name|ARCHIVE_ENTRY_ACL_TYPE_ACCESS
block|,
name|ARCHIVE_ENTRY_ACL_READ
operator||
name|ARCHIVE_ENTRY_ACL_EXECUTE
block|,
name|ARCHIVE_ENTRY_ACL_OTHER
block|,
operator|-
literal|1
block|,
literal|""
block|}
block|,
block|{
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
block|,
name|ARCHIVE_ENTRY_ACL_EXECUTE
operator||
name|ARCHIVE_ENTRY_ACL_READ
block|,
name|ARCHIVE_ENTRY_ACL_USER_OBJ
block|,
operator|-
literal|1
block|,
literal|""
block|}
block|,
block|{
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
block|,
name|ARCHIVE_ENTRY_ACL_EXECUTE
operator||
name|ARCHIVE_ENTRY_ACL_READ
block|,
name|ARCHIVE_ENTRY_ACL_GROUP_OBJ
block|,
operator|-
literal|1
block|,
literal|""
block|}
block|,
block|{
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
block|,
literal|0
block|,
name|ARCHIVE_ENTRY_ACL_OTHER
block|,
operator|-
literal|1
block|,
literal|""
block|}
block|,
block|{
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
block|,
name|ARCHIVE_ENTRY_ACL_EXECUTE
operator||
name|ARCHIVE_ENTRY_ACL_READ
block|,
name|ARCHIVE_ENTRY_ACL_USER
block|,
literal|101
block|,
literal|"user101"
block|}
block|,
block|{
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
block|,
name|ARCHIVE_ENTRY_ACL_EXECUTE
block|,
name|ARCHIVE_ENTRY_ACL_GROUP
block|,
literal|79
block|,
literal|"group79"
block|}
block|, }
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|struct
name|archive_test_acl_t
name|acls1
index|[]
init|=
block|{
block|{
name|ARCHIVE_ENTRY_ACL_TYPE_ALLOW
block|,
name|ARCHIVE_ENTRY_ACL_READ_DATA
operator||
name|ARCHIVE_ENTRY_ACL_WRITE_DATA
operator||
name|ARCHIVE_ENTRY_ACL_APPEND_DATA
operator||
name|ARCHIVE_ENTRY_ACL_READ_ATTRIBUTES
operator||
name|ARCHIVE_ENTRY_ACL_READ_NAMED_ATTRS
operator||
name|ARCHIVE_ENTRY_ACL_READ_ACL
operator||
name|ARCHIVE_ENTRY_ACL_WRITE_OWNER
block|,
name|ARCHIVE_ENTRY_ACL_USER
block|,
literal|77
block|,
literal|"user77"
block|}
block|,
block|{
name|ARCHIVE_ENTRY_ACL_TYPE_DENY
block|,
name|ARCHIVE_ENTRY_ACL_WRITE_DATA
operator||
name|ARCHIVE_ENTRY_ACL_APPEND_DATA
operator||
name|ARCHIVE_ENTRY_ACL_DELETE_CHILD
operator||
name|ARCHIVE_ENTRY_ACL_DELETE
operator||
name|ARCHIVE_ENTRY_ACL_ENTRY_FILE_INHERIT
operator||
name|ARCHIVE_ENTRY_ACL_ENTRY_DIRECTORY_INHERIT
operator||
name|ARCHIVE_ENTRY_ACL_ENTRY_INHERIT_ONLY
operator||
name|ARCHIVE_ENTRY_ACL_ENTRY_NO_PROPAGATE_INHERIT
block|,
name|ARCHIVE_ENTRY_ACL_USER
block|,
literal|101
block|,
literal|"user101"
block|}
block|,
block|{
name|ARCHIVE_ENTRY_ACL_TYPE_ALLOW
block|,
name|ARCHIVE_ENTRY_ACL_READ_DATA
operator||
name|ARCHIVE_ENTRY_ACL_READ_ATTRIBUTES
operator||
name|ARCHIVE_ENTRY_ACL_READ_NAMED_ATTRS
operator||
name|ARCHIVE_ENTRY_ACL_READ_ACL
operator||
name|ARCHIVE_ENTRY_ACL_ENTRY_INHERITED
block|,
name|ARCHIVE_ENTRY_ACL_GROUP
block|,
literal|78
block|,
literal|"group78"
block|}
block|,
block|{
name|ARCHIVE_ENTRY_ACL_TYPE_ALLOW
block|,
name|ARCHIVE_ENTRY_ACL_READ_DATA
operator||
name|ARCHIVE_ENTRY_ACL_WRITE_DATA
operator||
name|ARCHIVE_ENTRY_ACL_EXECUTE
operator||
name|ARCHIVE_ENTRY_ACL_APPEND_DATA
operator||
name|ARCHIVE_ENTRY_ACL_READ_ATTRIBUTES
operator||
name|ARCHIVE_ENTRY_ACL_WRITE_ATTRIBUTES
operator||
name|ARCHIVE_ENTRY_ACL_READ_NAMED_ATTRS
operator||
name|ARCHIVE_ENTRY_ACL_WRITE_NAMED_ATTRS
operator||
name|ARCHIVE_ENTRY_ACL_READ_ACL
operator||
name|ARCHIVE_ENTRY_ACL_WRITE_ACL
operator||
name|ARCHIVE_ENTRY_ACL_WRITE_OWNER
block|,
name|ARCHIVE_ENTRY_ACL_USER_OBJ
block|,
literal|0
block|,
literal|""
block|}
block|,
block|{
name|ARCHIVE_ENTRY_ACL_TYPE_ALLOW
block|,
name|ARCHIVE_ENTRY_ACL_READ_DATA
operator||
name|ARCHIVE_ENTRY_ACL_WRITE_DATA
operator||
name|ARCHIVE_ENTRY_ACL_APPEND_DATA
operator||
name|ARCHIVE_ENTRY_ACL_READ_ATTRIBUTES
operator||
name|ARCHIVE_ENTRY_ACL_READ_NAMED_ATTRS
operator||
name|ARCHIVE_ENTRY_ACL_READ_ACL
block|,
name|ARCHIVE_ENTRY_ACL_GROUP_OBJ
block|,
literal|0
block|,
literal|""
block|}
block|,
block|{
name|ARCHIVE_ENTRY_ACL_TYPE_ALLOW
block|,
name|ARCHIVE_ENTRY_ACL_READ_DATA
operator||
name|ARCHIVE_ENTRY_ACL_READ_ATTRIBUTES
operator||
name|ARCHIVE_ENTRY_ACL_READ_NAMED_ATTRS
operator||
name|ARCHIVE_ENTRY_ACL_READ_ACL
operator||
name|ARCHIVE_ENTRY_ACL_SYNCHRONIZE
block|,
name|ARCHIVE_ENTRY_ACL_EVERYONE
block|,
literal|0
block|,
literal|""
block|}
block|, }
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|const
name|char
modifier|*
name|acltext
index|[]
init|=
block|{
literal|"user::rwx\n"
literal|"group::r-x\n"
literal|"other::r-x\n"
literal|"user:user100:r-x\n"
literal|"user:user1000:---\n"
literal|"group:group78:rwx\n"
literal|"default:user::r-x\n"
literal|"default:group::r-x\n"
literal|"default:other::---\n"
literal|"default:user:user101:r-x\n"
literal|"default:group:group79:--x"
block|,
literal|"user::rwx\n"
literal|"group::r-x\n"
literal|"other::r-x\n"
literal|"user:user100:r-x:100\n"
literal|"user:user1000:---:1000\n"
literal|"group:group78:rwx:78\n"
literal|"default:user::r-x\n"
literal|"default:group::r-x\n"
literal|"default:other::---\n"
literal|"default:user:user101:r-x:101\n"
literal|"default:group:group79:--x:79"
block|,
literal|"u::rwx\n"
literal|"g::r-x\n"
literal|"o::r-x\n"
literal|"u:user100:r-x:100\n"
literal|"u:user1000:---:1000\n"
literal|"g:group78:rwx:78\n"
literal|"d:user::r-x\n"
literal|"d:group::r-x\n"
literal|"d:other::---\n"
literal|"d:user:user101:r-x:101\n"
literal|"d:group:group79:--x:79"
block|,
literal|"user::rwx\n"
literal|"group::r-x\n"
literal|"other::r-x\n"
literal|"user:user100:r-x\n"
literal|"user:user1000:---\n"
literal|"group:group78:rwx"
block|,
literal|"user::rwx,"
literal|"group::r-x,"
literal|"other::r-x,"
literal|"user:user100:r-x,"
literal|"user:user1000:---,"
literal|"group:group78:rwx"
block|,
literal|"user::rwx\n"
literal|"group::r-x\n"
literal|"other::r-x\n"
literal|"user:user100:r-x:100\n"
literal|"user:user1000:---:1000\n"
literal|"group:group78:rwx:78"
block|,
literal|"user::r-x\n"
literal|"group::r-x\n"
literal|"other::---\n"
literal|"user:user101:r-x\n"
literal|"group:group79:--x"
block|,
literal|"user::r-x\n"
literal|"group::r-x\n"
literal|"other::---\n"
literal|"user:user101:r-x:101\n"
literal|"group:group79:--x:79"
block|,
literal|"default:user::r-x\n"
literal|"default:group::r-x\n"
literal|"default:other::---\n"
literal|"default:user:user101:r-x\n"
literal|"default:group:group79:--x"
block|,
literal|"user:user77:rw-p--a-R-c-o-:-------:allow\n"
literal|"user:user101:-w-pdD--------:fdin---:deny\n"
literal|"group:group78:r-----a-R-c---:------I:allow\n"
literal|"owner@:rwxp--aARWcCo-:-------:allow\n"
literal|"group@:rw-p--a-R-c---:-------:allow\n"
literal|"everyone@:r-----a-R-c--s:-------:allow"
block|,
literal|"user:user77:rw-p--a-R-c-o-:-------:allow:77\n"
literal|"user:user101:-w-pdD--------:fdin---:deny:101\n"
literal|"group:group78:r-----a-R-c---:------I:allow:78\n"
literal|"owner@:rwxp--aARWcCo-:-------:allow\n"
literal|"group@:rw-p--a-R-c---:-------:allow\n"
literal|"everyone@:r-----a-R-c--s:-------:allow"
block|,
literal|"user:user77:rwpaRco::allow:77\n"
literal|"user:user101:wpdD:fdin:deny:101\n"
literal|"group:group78:raRc:I:allow:78\n"
literal|"owner@:rwxpaARWcCo::allow\n"
literal|"group@:rwpaRc::allow\n"
literal|"everyone@:raRcs::allow"
block|}
decl_stmt|;
end_decl_stmt

begin_function
specifier|static
name|wchar_t
modifier|*
name|convert_s_to_ws
parameter_list|(
specifier|const
name|char
modifier|*
name|s
parameter_list|)
block|{
name|size_t
name|len
decl_stmt|;
name|wchar_t
modifier|*
name|ws
init|=
name|NULL
decl_stmt|;
if|if
condition|(
name|s
operator|!=
name|NULL
condition|)
block|{
name|len
operator|=
name|strlen
argument_list|(
name|s
argument_list|)
operator|+
literal|1
expr_stmt|;
name|ws
operator|=
name|malloc
argument_list|(
name|len
operator|*
sizeof|sizeof
argument_list|(
name|wchar_t
argument_list|)
argument_list|)
expr_stmt|;
name|assert
argument_list|(
name|mbstowcs
argument_list|(
name|ws
argument_list|,
name|s
argument_list|,
name|len
argument_list|)
operator|!=
operator|(
name|size_t
operator|)
operator|-
literal|1
argument_list|)
expr_stmt|;
block|}
return|return
operator|(
name|ws
operator|)
return|;
block|}
end_function

begin_function
specifier|static
name|void
name|compare_acl_text
parameter_list|(
name|struct
name|archive_entry
modifier|*
name|ae
parameter_list|,
name|int
name|flags
parameter_list|,
specifier|const
name|char
modifier|*
name|s
parameter_list|)
block|{
name|char
modifier|*
name|text
decl_stmt|;
name|wchar_t
modifier|*
name|wtext
decl_stmt|;
name|wchar_t
modifier|*
name|ws
decl_stmt|;
name|ssize_t
name|slen
decl_stmt|;
name|ws
operator|=
name|convert_s_to_ws
argument_list|(
name|s
argument_list|)
expr_stmt|;
name|text
operator|=
name|archive_entry_acl_to_text
argument_list|(
name|ae
argument_list|,
operator|&
name|slen
argument_list|,
name|flags
argument_list|)
expr_stmt|;
name|assertEqualString
argument_list|(
name|text
argument_list|,
name|s
argument_list|)
expr_stmt|;
if|if
condition|(
name|text
operator|!=
name|NULL
condition|)
name|assertEqualInt
argument_list|(
name|strlen
argument_list|(
name|text
argument_list|)
argument_list|,
name|slen
argument_list|)
expr_stmt|;
name|wtext
operator|=
name|archive_entry_acl_to_text_w
argument_list|(
name|ae
argument_list|,
operator|&
name|slen
argument_list|,
name|flags
argument_list|)
expr_stmt|;
name|assertEqualWString
argument_list|(
name|wtext
argument_list|,
name|ws
argument_list|)
expr_stmt|;
if|if
condition|(
name|wtext
operator|!=
name|NULL
condition|)
block|{
name|assertEqualInt
argument_list|(
name|wcslen
argument_list|(
name|wtext
argument_list|)
argument_list|,
name|slen
argument_list|)
expr_stmt|;
block|}
name|free
argument_list|(
name|text
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|wtext
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|ws
argument_list|)
expr_stmt|;
block|}
end_function

begin_macro
name|DEFINE_TEST
argument_list|(
argument|test_acl_from_text
argument_list|)
end_macro

begin_block
block|{
name|struct
name|archive_entry
modifier|*
name|ae
decl_stmt|;
name|wchar_t
modifier|*
name|ws
init|=
name|NULL
decl_stmt|;
comment|/* Create an empty archive_entry. */
name|assert
argument_list|(
operator|(
name|ae
operator|=
name|archive_entry_new
argument_list|()
operator|)
operator|!=
name|NULL
argument_list|)
expr_stmt|;
comment|/* 1a. Read POSIX.1e access ACLs from text */
name|assertEqualInt
argument_list|(
name|ARCHIVE_OK
argument_list|,
name|archive_entry_acl_from_text
argument_list|(
name|ae
argument_list|,
name|acltext
index|[
literal|5
index|]
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_ACCESS
argument_list|)
argument_list|)
expr_stmt|;
name|assertEntryCompareAcls
argument_list|(
name|ae
argument_list|,
name|acls0
argument_list|,
sizeof|sizeof
argument_list|(
name|acls0
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|acls0
index|[
literal|0
index|]
argument_list|)
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_ACCESS
argument_list|,
literal|0755
argument_list|)
expr_stmt|;
name|assertEqualInt
argument_list|(
literal|6
argument_list|,
name|archive_entry_acl_reset
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_ACCESS
argument_list|)
argument_list|)
expr_stmt|;
comment|/* 1b. Now read POSIX.1e default ACLs and append them */
name|assertEqualInt
argument_list|(
name|ARCHIVE_OK
argument_list|,
name|archive_entry_acl_from_text
argument_list|(
name|ae
argument_list|,
name|acltext
index|[
literal|7
index|]
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
argument_list|)
argument_list|)
expr_stmt|;
name|assertEntryCompareAcls
argument_list|(
name|ae
argument_list|,
name|acls0
argument_list|,
sizeof|sizeof
argument_list|(
name|acls0
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|acls0
index|[
literal|0
index|]
argument_list|)
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_POSIX1E
argument_list|,
literal|0755
argument_list|)
expr_stmt|;
name|assertEqualInt
argument_list|(
literal|11
argument_list|,
name|archive_entry_acl_reset
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_POSIX1E
argument_list|)
argument_list|)
expr_stmt|;
name|archive_entry_acl_clear
argument_list|(
name|ae
argument_list|)
expr_stmt|;
comment|/* 1a and 1b with wide strings */
name|ws
operator|=
name|convert_s_to_ws
argument_list|(
name|acltext
index|[
literal|5
index|]
argument_list|)
expr_stmt|;
name|assertEqualInt
argument_list|(
name|ARCHIVE_OK
argument_list|,
name|archive_entry_acl_from_text_w
argument_list|(
name|ae
argument_list|,
name|ws
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_ACCESS
argument_list|)
argument_list|)
expr_stmt|;
name|assertEntryCompareAcls
argument_list|(
name|ae
argument_list|,
name|acls0
argument_list|,
sizeof|sizeof
argument_list|(
name|acls0
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|acls0
index|[
literal|0
index|]
argument_list|)
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_ACCESS
argument_list|,
literal|0755
argument_list|)
expr_stmt|;
name|assertEqualInt
argument_list|(
literal|6
argument_list|,
name|archive_entry_acl_reset
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_ACCESS
argument_list|)
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|ws
argument_list|)
expr_stmt|;
name|ws
operator|=
name|convert_s_to_ws
argument_list|(
name|acltext
index|[
literal|7
index|]
argument_list|)
expr_stmt|;
name|assertEqualInt
argument_list|(
name|ARCHIVE_OK
argument_list|,
name|archive_entry_acl_from_text_w
argument_list|(
name|ae
argument_list|,
name|ws
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
argument_list|)
argument_list|)
expr_stmt|;
name|assertEntryCompareAcls
argument_list|(
name|ae
argument_list|,
name|acls0
argument_list|,
sizeof|sizeof
argument_list|(
name|acls0
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|acls0
index|[
literal|0
index|]
argument_list|)
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_POSIX1E
argument_list|,
literal|0755
argument_list|)
expr_stmt|;
name|assertEqualInt
argument_list|(
literal|11
argument_list|,
name|archive_entry_acl_reset
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_POSIX1E
argument_list|)
argument_list|)
expr_stmt|;
name|archive_entry_acl_clear
argument_list|(
name|ae
argument_list|)
expr_stmt|;
comment|/* 2. Read POSIX.1e default ACLs from text */
name|assertEqualInt
argument_list|(
name|ARCHIVE_OK
argument_list|,
name|archive_entry_acl_from_text
argument_list|(
name|ae
argument_list|,
name|acltext
index|[
literal|7
index|]
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
argument_list|)
argument_list|)
expr_stmt|;
name|assertEntryCompareAcls
argument_list|(
name|ae
argument_list|,
name|acls0
argument_list|,
sizeof|sizeof
argument_list|(
name|acls0
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|acls0
index|[
literal|0
index|]
argument_list|)
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|assertEqualInt
argument_list|(
literal|5
argument_list|,
name|archive_entry_acl_reset
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
argument_list|)
argument_list|)
expr_stmt|;
name|archive_entry_acl_clear
argument_list|(
name|ae
argument_list|)
expr_stmt|;
comment|/* ws is still acltext[7] */
name|assertEqualInt
argument_list|(
name|ARCHIVE_OK
argument_list|,
name|archive_entry_acl_from_text_w
argument_list|(
name|ae
argument_list|,
name|ws
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
argument_list|)
argument_list|)
expr_stmt|;
name|assertEntryCompareAcls
argument_list|(
name|ae
argument_list|,
name|acls0
argument_list|,
sizeof|sizeof
argument_list|(
name|acls0
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|acls0
index|[
literal|0
index|]
argument_list|)
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|assertEqualInt
argument_list|(
literal|5
argument_list|,
name|archive_entry_acl_reset
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
argument_list|)
argument_list|)
expr_stmt|;
name|archive_entry_acl_clear
argument_list|(
name|ae
argument_list|)
expr_stmt|;
comment|/* 3. Read POSIX.1e access and default ACLs from text */
name|assertEqualInt
argument_list|(
name|ARCHIVE_OK
argument_list|,
name|archive_entry_acl_from_text
argument_list|(
name|ae
argument_list|,
name|acltext
index|[
literal|1
index|]
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_POSIX1E
argument_list|)
argument_list|)
expr_stmt|;
name|assertEntryCompareAcls
argument_list|(
name|ae
argument_list|,
name|acls0
argument_list|,
sizeof|sizeof
argument_list|(
name|acls0
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|acls0
index|[
literal|0
index|]
argument_list|)
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_POSIX1E
argument_list|,
literal|0755
argument_list|)
expr_stmt|;
name|assertEqualInt
argument_list|(
literal|11
argument_list|,
name|archive_entry_acl_reset
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_POSIX1E
argument_list|)
argument_list|)
expr_stmt|;
name|archive_entry_acl_clear
argument_list|(
name|ae
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|ws
argument_list|)
expr_stmt|;
name|ws
operator|=
name|convert_s_to_ws
argument_list|(
name|acltext
index|[
literal|1
index|]
argument_list|)
expr_stmt|;
name|assertEqualInt
argument_list|(
name|ARCHIVE_OK
argument_list|,
name|archive_entry_acl_from_text_w
argument_list|(
name|ae
argument_list|,
name|ws
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_POSIX1E
argument_list|)
argument_list|)
expr_stmt|;
name|assertEntryCompareAcls
argument_list|(
name|ae
argument_list|,
name|acls0
argument_list|,
sizeof|sizeof
argument_list|(
name|acls0
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|acls0
index|[
literal|0
index|]
argument_list|)
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_POSIX1E
argument_list|,
literal|0755
argument_list|)
expr_stmt|;
name|assertEqualInt
argument_list|(
literal|11
argument_list|,
name|archive_entry_acl_reset
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_POSIX1E
argument_list|)
argument_list|)
expr_stmt|;
name|archive_entry_acl_clear
argument_list|(
name|ae
argument_list|)
expr_stmt|;
comment|/* 4. Read POSIX.1e access and default ACLs from text (short form) */
name|assertEqualInt
argument_list|(
name|ARCHIVE_OK
argument_list|,
name|archive_entry_acl_from_text
argument_list|(
name|ae
argument_list|,
name|acltext
index|[
literal|2
index|]
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_POSIX1E
argument_list|)
argument_list|)
expr_stmt|;
name|assertEntryCompareAcls
argument_list|(
name|ae
argument_list|,
name|acls0
argument_list|,
sizeof|sizeof
argument_list|(
name|acls0
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|acls0
index|[
literal|0
index|]
argument_list|)
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_POSIX1E
argument_list|,
literal|0755
argument_list|)
expr_stmt|;
name|assertEqualInt
argument_list|(
literal|11
argument_list|,
name|archive_entry_acl_reset
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_POSIX1E
argument_list|)
argument_list|)
expr_stmt|;
name|archive_entry_acl_clear
argument_list|(
name|ae
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|ws
argument_list|)
expr_stmt|;
name|ws
operator|=
name|convert_s_to_ws
argument_list|(
name|acltext
index|[
literal|2
index|]
argument_list|)
expr_stmt|;
name|assertEqualInt
argument_list|(
name|ARCHIVE_OK
argument_list|,
name|archive_entry_acl_from_text_w
argument_list|(
name|ae
argument_list|,
name|ws
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_POSIX1E
argument_list|)
argument_list|)
expr_stmt|;
name|assertEntryCompareAcls
argument_list|(
name|ae
argument_list|,
name|acls0
argument_list|,
sizeof|sizeof
argument_list|(
name|acls0
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|acls0
index|[
literal|0
index|]
argument_list|)
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_POSIX1E
argument_list|,
literal|0755
argument_list|)
expr_stmt|;
name|assertEqualInt
argument_list|(
literal|11
argument_list|,
name|archive_entry_acl_reset
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_POSIX1E
argument_list|)
argument_list|)
expr_stmt|;
name|archive_entry_acl_clear
argument_list|(
name|ae
argument_list|)
expr_stmt|;
comment|/* 5. Read NFSv4 ACLs from text */
name|assertEqualInt
argument_list|(
name|ARCHIVE_OK
argument_list|,
name|archive_entry_acl_from_text
argument_list|(
name|ae
argument_list|,
name|acltext
index|[
literal|10
index|]
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_NFS4
argument_list|)
argument_list|)
expr_stmt|;
name|assertEntryCompareAcls
argument_list|(
name|ae
argument_list|,
name|acls1
argument_list|,
sizeof|sizeof
argument_list|(
name|acls1
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|acls1
index|[
literal|0
index|]
argument_list|)
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_NFS4
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|assertEqualInt
argument_list|(
literal|6
argument_list|,
name|archive_entry_acl_reset
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_NFS4
argument_list|)
argument_list|)
expr_stmt|;
name|archive_entry_acl_clear
argument_list|(
name|ae
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|ws
argument_list|)
expr_stmt|;
name|ws
operator|=
name|convert_s_to_ws
argument_list|(
name|acltext
index|[
literal|10
index|]
argument_list|)
expr_stmt|;
name|assertEqualInt
argument_list|(
name|ARCHIVE_OK
argument_list|,
name|archive_entry_acl_from_text_w
argument_list|(
name|ae
argument_list|,
name|ws
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_NFS4
argument_list|)
argument_list|)
expr_stmt|;
name|assertEntryCompareAcls
argument_list|(
name|ae
argument_list|,
name|acls1
argument_list|,
sizeof|sizeof
argument_list|(
name|acls1
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|acls1
index|[
literal|0
index|]
argument_list|)
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_NFS4
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|assertEqualInt
argument_list|(
literal|6
argument_list|,
name|archive_entry_acl_reset
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_NFS4
argument_list|)
argument_list|)
expr_stmt|;
name|archive_entry_acl_clear
argument_list|(
name|ae
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|ws
argument_list|)
expr_stmt|;
name|archive_entry_free
argument_list|(
name|ae
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|DEFINE_TEST
argument_list|(
argument|test_acl_to_text
argument_list|)
end_macro

begin_block
block|{
name|struct
name|archive_entry
modifier|*
name|ae
decl_stmt|;
comment|/* Create an empty archive_entry. */
name|assert
argument_list|(
operator|(
name|ae
operator|=
name|archive_entry_new
argument_list|()
operator|)
operator|!=
name|NULL
argument_list|)
expr_stmt|;
comment|/* Write POSIX.1e ACLs  */
name|assertEntrySetAcls
argument_list|(
name|ae
argument_list|,
name|acls0
argument_list|,
sizeof|sizeof
argument_list|(
name|acls0
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|acls0
index|[
literal|0
index|]
argument_list|)
argument_list|)
expr_stmt|;
comment|/* No flags should give output like getfacl(1) on linux */
name|compare_acl_text
argument_list|(
name|ae
argument_list|,
literal|0
argument_list|,
name|acltext
index|[
literal|0
index|]
argument_list|)
expr_stmt|;
comment|/* This should give the same output as previous test */
name|compare_acl_text
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_ACCESS
operator||
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
argument_list|,
name|acltext
index|[
literal|0
index|]
argument_list|)
expr_stmt|;
comment|/* This should give the same output as previous two tests */
name|compare_acl_text
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_ACCESS
operator||
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
operator||
name|ARCHIVE_ENTRY_ACL_STYLE_MARK_DEFAULT
argument_list|,
name|acltext
index|[
literal|0
index|]
argument_list|)
expr_stmt|;
comment|/* POSIX.1e access and default ACLs with appended ID */
name|compare_acl_text
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_STYLE_EXTRA_ID
argument_list|,
name|acltext
index|[
literal|1
index|]
argument_list|)
expr_stmt|;
comment|/* POSIX.1e access acls only, like getfacl(1) on FreeBSD */
name|compare_acl_text
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_ACCESS
argument_list|,
name|acltext
index|[
literal|3
index|]
argument_list|)
expr_stmt|;
comment|/* POSIX.1e access acls separated with comma */
name|compare_acl_text
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_ACCESS
operator||
name|ARCHIVE_ENTRY_ACL_STYLE_SEPARATOR_COMMA
argument_list|,
name|acltext
index|[
literal|4
index|]
argument_list|)
expr_stmt|;
comment|/* POSIX.1e access acls with appended user or group ID */
name|compare_acl_text
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_ACCESS
operator||
name|ARCHIVE_ENTRY_ACL_STYLE_EXTRA_ID
argument_list|,
name|acltext
index|[
literal|5
index|]
argument_list|)
expr_stmt|;
comment|/* POSIX.1e default acls */
name|compare_acl_text
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
argument_list|,
name|acltext
index|[
literal|6
index|]
argument_list|)
expr_stmt|;
comment|/* POSIX.1e default acls with appended user or group ID */
name|compare_acl_text
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
operator||
name|ARCHIVE_ENTRY_ACL_STYLE_EXTRA_ID
argument_list|,
name|acltext
index|[
literal|7
index|]
argument_list|)
expr_stmt|;
comment|/* POSIX.1e default acls prefixed with default: */
name|compare_acl_text
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_TYPE_DEFAULT
operator||
name|ARCHIVE_ENTRY_ACL_STYLE_MARK_DEFAULT
argument_list|,
name|acltext
index|[
literal|8
index|]
argument_list|)
expr_stmt|;
comment|/* Write NFSv4 ACLs */
name|assertEntrySetAcls
argument_list|(
name|ae
argument_list|,
name|acls1
argument_list|,
sizeof|sizeof
argument_list|(
name|acls1
argument_list|)
operator|/
sizeof|sizeof
argument_list|(
name|acls1
index|[
literal|0
index|]
argument_list|)
argument_list|)
expr_stmt|;
comment|/* NFSv4 ACLs like getfacl(1) on FreeBSD */
name|compare_acl_text
argument_list|(
name|ae
argument_list|,
literal|0
argument_list|,
name|acltext
index|[
literal|9
index|]
argument_list|)
expr_stmt|;
comment|/* NFSv4 ACLs like "getfacl -i" on FreeBSD */
name|compare_acl_text
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_STYLE_EXTRA_ID
argument_list|,
name|acltext
index|[
literal|10
index|]
argument_list|)
expr_stmt|;
comment|/* NFSv4 ACLs like "getfacl -i" on FreeBSD with stripped minus chars */
name|compare_acl_text
argument_list|(
name|ae
argument_list|,
name|ARCHIVE_ENTRY_ACL_STYLE_EXTRA_ID
operator||
name|ARCHIVE_ENTRY_ACL_STYLE_COMPACT
argument_list|,
name|acltext
index|[
literal|11
index|]
argument_list|)
expr_stmt|;
name|archive_entry_free
argument_list|(
name|ae
argument_list|)
expr_stmt|;
block|}
end_block

end_unit

