begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*-  * Copyright (c) 1999, 2000 Andrew J. Korty  * All rights reserved.  * Copyright (c) 2001 Networks Associates Technologies, Inc.  * All rights reserved.  *  * Portions of this software were developed for the FreeBSD Project by  * ThinkSec AS and NAI Labs, the Security Research Division of Network  * Associates, Inc.  under DARPA/SPAWAR contract N66001-01-C-8035  * ("CBOSS"), as part of the DARPA CHATS research program.  *  * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions  * are met:  * 1. Redistributions of source code must retain the above copyright  *    notice, this list of conditions and the following disclaimer.  * 2. Redistributions in binary form must reproduce the above copyright  *    notice, this list of conditions and the following disclaimer in the  *    documentation and/or other materials provided with the distribution.  * 3. The name of the author may not be used to endorse or promote  *    products derived from this software without specific prior written  *    permission.  *  * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND  * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE  * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS  * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)  * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT  * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY  * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF  * SUCH DAMAGE.  */
end_comment

begin_include
include|#
directive|include
file|<sys/cdefs.h>
end_include

begin_expr_stmt
name|__FBSDID
argument_list|(
literal|"$FreeBSD$"
argument_list|)
expr_stmt|;
end_expr_stmt

begin_include
include|#
directive|include
file|<sys/param.h>
end_include

begin_include
include|#
directive|include
file|<sys/socket.h>
end_include

begin_include
include|#
directive|include
file|<sys/stat.h>
end_include

begin_include
include|#
directive|include
file|<sys/wait.h>
end_include

begin_include
include|#
directive|include
file|<dirent.h>
end_include

begin_include
include|#
directive|include
file|<pwd.h>
end_include

begin_include
include|#
directive|include
file|<signal.h>
end_include

begin_include
include|#
directive|include
file|<ssh.h>
end_include

begin_include
include|#
directive|include
file|<stdio.h>
end_include

begin_include
include|#
directive|include
file|<stdlib.h>
end_include

begin_include
include|#
directive|include
file|<string.h>
end_include

begin_include
include|#
directive|include
file|<unistd.h>
end_include

begin_define
define|#
directive|define
name|PAM_SM_AUTH
end_define

begin_define
define|#
directive|define
name|PAM_SM_ACCOUNT
end_define

begin_define
define|#
directive|define
name|PAM_SM_SESSION
end_define

begin_define
define|#
directive|define
name|PAM_SM_PASSWORD
end_define

begin_include
include|#
directive|include
file|<security/pam_appl.h>
end_include

begin_include
include|#
directive|include
file|<security/pam_modules.h>
end_include

begin_include
include|#
directive|include
file|<security/pam_mod_misc.h>
end_include

begin_include
include|#
directive|include
file|<openssl/dsa.h>
end_include

begin_include
include|#
directive|include
file|<openssl/evp.h>
end_include

begin_include
include|#
directive|include
file|"key.h"
end_include

begin_include
include|#
directive|include
file|"authfd.h"
end_include

begin_include
include|#
directive|include
file|"authfile.h"
end_include

begin_include
include|#
directive|include
file|"log.h"
end_include

begin_include
include|#
directive|include
file|"pam_ssh.h"
end_include

begin_function_decl
specifier|static
name|int
name|auth_via_key
parameter_list|(
name|pam_handle_t
modifier|*
parameter_list|,
name|int
parameter_list|,
specifier|const
name|char
modifier|*
parameter_list|,
specifier|const
name|char
modifier|*
parameter_list|,
specifier|const
name|struct
name|passwd
modifier|*
parameter_list|,
specifier|const
name|char
modifier|*
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|key_cleanup
parameter_list|(
name|pam_handle_t
modifier|*
parameter_list|,
name|void
modifier|*
parameter_list|,
name|int
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|ssh_cleanup
parameter_list|(
name|pam_handle_t
modifier|*
parameter_list|,
name|void
modifier|*
parameter_list|,
name|int
parameter_list|)
function_decl|;
end_function_decl

begin_comment
comment|/*  * Generic cleanup function for SSH "Key" type.  */
end_comment

begin_function
specifier|static
name|void
name|key_cleanup
parameter_list|(
name|pam_handle_t
modifier|*
name|pamh
name|__unused
parameter_list|,
name|void
modifier|*
name|data
parameter_list|,
name|int
name|error_status
name|__unused
parameter_list|)
block|{
if|if
condition|(
name|data
condition|)
name|key_free
argument_list|(
name|data
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*  * Generic PAM cleanup function for this module.  */
end_comment

begin_function
specifier|static
name|void
name|ssh_cleanup
parameter_list|(
name|pam_handle_t
modifier|*
name|pamh
name|__unused
parameter_list|,
name|void
modifier|*
name|data
parameter_list|,
name|int
name|error_status
name|__unused
parameter_list|)
block|{
if|if
condition|(
name|data
condition|)
name|free
argument_list|(
name|data
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*  * Authenticate a user's key by trying to decrypt it with the password  * provided.  The key and its comment are then stored for later  * retrieval by the session phase.  An increasing index is embedded in  * the PAM variable names so this function may be called multiple times  * for multiple keys.  */
end_comment

begin_function
specifier|static
name|int
name|auth_via_key
parameter_list|(
name|pam_handle_t
modifier|*
name|pamh
parameter_list|,
name|int
name|type
parameter_list|,
specifier|const
name|char
modifier|*
name|file
parameter_list|,
specifier|const
name|char
modifier|*
name|dir
parameter_list|,
specifier|const
name|struct
name|passwd
modifier|*
name|user
parameter_list|,
specifier|const
name|char
modifier|*
name|pass
parameter_list|)
block|{
name|char
modifier|*
name|comment
decl_stmt|;
comment|/* private key comment */
name|char
modifier|*
name|data_name
decl_stmt|;
comment|/* PAM state */
specifier|static
name|int
name|indx
init|=
literal|0
decl_stmt|;
comment|/* for saved keys */
name|Key
modifier|*
name|key
decl_stmt|;
comment|/* user's key */
name|char
modifier|*
name|path
decl_stmt|;
comment|/* to key files */
name|int
name|retval
decl_stmt|;
comment|/* from calls */
name|uid_t
name|saved_uid
decl_stmt|;
comment|/* caller's uid */
comment|/* locate the user's private key file */
if|if
condition|(
operator|!
name|asprintf
argument_list|(
operator|&
name|path
argument_list|,
literal|"%s/%s"
argument_list|,
name|dir
argument_list|,
name|file
argument_list|)
condition|)
block|{
name|syslog
argument_list|(
name|LOG_CRIT
argument_list|,
literal|"%s: %m"
argument_list|,
name|MODULE_NAME
argument_list|)
expr_stmt|;
return|return
name|PAM_SERVICE_ERR
return|;
block|}
name|saved_uid
operator|=
name|geteuid
argument_list|()
expr_stmt|;
comment|/* 	 * Try to decrypt the private key with the passphrase provided. 	 * If success, the user is authenticated. 	 */
name|seteuid
argument_list|(
name|user
operator|->
name|pw_uid
argument_list|)
expr_stmt|;
name|key
operator|=
name|key_load_private_type
argument_list|(
name|type
argument_list|,
name|path
argument_list|,
name|pass
argument_list|,
operator|&
name|comment
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|path
argument_list|)
expr_stmt|;
name|seteuid
argument_list|(
name|saved_uid
argument_list|)
expr_stmt|;
if|if
condition|(
name|key
operator|==
name|NULL
condition|)
return|return
name|PAM_AUTH_ERR
return|;
comment|/* 	 * Save the key and comment to pass to ssh-agent in the session 	 * phase. 	 */
if|if
condition|(
operator|!
name|asprintf
argument_list|(
operator|&
name|data_name
argument_list|,
literal|"ssh_private_key_%d"
argument_list|,
name|indx
argument_list|)
condition|)
block|{
name|syslog
argument_list|(
name|LOG_CRIT
argument_list|,
literal|"%s: %m"
argument_list|,
name|MODULE_NAME
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|comment
argument_list|)
expr_stmt|;
return|return
name|PAM_SERVICE_ERR
return|;
block|}
name|retval
operator|=
name|pam_set_data
argument_list|(
name|pamh
argument_list|,
name|data_name
argument_list|,
name|key
argument_list|,
name|key_cleanup
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|data_name
argument_list|)
expr_stmt|;
if|if
condition|(
name|retval
operator|!=
name|PAM_SUCCESS
condition|)
block|{
name|key_free
argument_list|(
name|key
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|comment
argument_list|)
expr_stmt|;
return|return
name|retval
return|;
block|}
if|if
condition|(
operator|!
name|asprintf
argument_list|(
operator|&
name|data_name
argument_list|,
literal|"ssh_key_comment_%d"
argument_list|,
name|indx
argument_list|)
condition|)
block|{
name|syslog
argument_list|(
name|LOG_CRIT
argument_list|,
literal|"%s: %m"
argument_list|,
name|MODULE_NAME
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|comment
argument_list|)
expr_stmt|;
return|return
name|PAM_SERVICE_ERR
return|;
block|}
name|retval
operator|=
name|pam_set_data
argument_list|(
name|pamh
argument_list|,
name|data_name
argument_list|,
name|comment
argument_list|,
name|ssh_cleanup
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|data_name
argument_list|)
expr_stmt|;
if|if
condition|(
name|retval
operator|!=
name|PAM_SUCCESS
condition|)
block|{
name|free
argument_list|(
name|comment
argument_list|)
expr_stmt|;
return|return
name|retval
return|;
block|}
operator|++
name|indx
expr_stmt|;
return|return
name|PAM_SUCCESS
return|;
block|}
end_function

begin_function
name|PAM_EXTERN
name|int
name|pam_sm_authenticate
parameter_list|(
name|pam_handle_t
modifier|*
name|pamh
parameter_list|,
name|int
name|flags
name|__unused
parameter_list|,
name|int
name|argc
parameter_list|,
specifier|const
name|char
modifier|*
modifier|*
name|argv
parameter_list|)
block|{
name|int
name|options
decl_stmt|;
comment|/* module options */
name|int
name|authenticated
decl_stmt|;
comment|/* user authenticated? */
name|char
modifier|*
name|dotdir
decl_stmt|;
comment|/* .ssh2 dir name */
name|struct
name|dirent
modifier|*
name|dotdir_ent
decl_stmt|;
comment|/* .ssh2 dir entry */
name|DIR
modifier|*
name|dotdir_p
decl_stmt|;
comment|/* .ssh2 dir pointer */
specifier|const
name|char
modifier|*
name|pass
decl_stmt|;
comment|/* passphrase */
name|struct
name|passwd
modifier|*
name|pwd
decl_stmt|;
comment|/* user's passwd entry */
name|struct
name|passwd
modifier|*
name|pwd_keep
decl_stmt|;
comment|/* our own copy */
name|int
name|retval
decl_stmt|;
comment|/* from calls */
name|int
name|pam_auth_dsa
decl_stmt|;
comment|/* Authorised via DSA */
name|int
name|pam_auth_rsa
decl_stmt|;
comment|/* Authorised via RSA */
specifier|const
name|char
modifier|*
name|user
decl_stmt|;
comment|/* username */
while|while
condition|(
name|argc
operator|--
condition|)
name|pam_std_option
argument_list|(
operator|&
name|options
argument_list|,
operator|*
name|argv
operator|++
argument_list|)
expr_stmt|;
name|retval
operator|=
name|pam_get_user
argument_list|(
name|pamh
argument_list|,
operator|&
name|user
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|retval
operator|!=
name|PAM_SUCCESS
condition|)
name|PAM_RETURN
argument_list|(
name|retval
argument_list|)
expr_stmt|;
name|pwd
operator|=
name|getpwnam
argument_list|(
name|user
argument_list|)
expr_stmt|;
if|if
condition|(
name|pwd
operator|==
name|NULL
operator|||
name|pwd
operator|->
name|pw_dir
operator|==
name|NULL
condition|)
comment|/* delay? */
name|PAM_RETURN
argument_list|(
name|PAM_AUTH_ERR
argument_list|)
expr_stmt|;
comment|/* 	 * Pass prompt message to application and receive 	 * passphrase. 	 */
name|retval
operator|=
name|pam_get_pass
argument_list|(
name|pamh
argument_list|,
operator|&
name|pass
argument_list|,
name|NEED_PASSPHRASE
argument_list|,
name|options
argument_list|)
expr_stmt|;
if|if
condition|(
name|retval
operator|!=
name|PAM_SUCCESS
condition|)
name|PAM_RETURN
argument_list|(
name|retval
argument_list|)
expr_stmt|;
name|OpenSSL_add_all_algorithms
argument_list|()
expr_stmt|;
comment|/* required for DSA */
comment|/* 	 * Either the DSA or the RSA key will authenticate us, but if 	 * we can decrypt both, we'll do so here so we can cache them in 	 * the session phase. 	 */
if|if
condition|(
operator|!
name|asprintf
argument_list|(
operator|&
name|dotdir
argument_list|,
literal|"%s/%s"
argument_list|,
name|pwd
operator|->
name|pw_dir
argument_list|,
name|SSH_CLIENT_DIR
argument_list|)
condition|)
block|{
name|syslog
argument_list|(
name|LOG_CRIT
argument_list|,
literal|"%s: %m"
argument_list|,
name|MODULE_NAME
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_SERVICE_ERR
argument_list|)
expr_stmt|;
block|}
name|pam_auth_dsa
operator|=
name|auth_via_key
argument_list|(
name|pamh
argument_list|,
name|KEY_DSA
argument_list|,
name|SSH_CLIENT_ID_DSA
argument_list|,
name|dotdir
argument_list|,
name|pwd
argument_list|,
name|pass
argument_list|)
expr_stmt|;
name|pam_auth_rsa
operator|=
name|auth_via_key
argument_list|(
name|pamh
argument_list|,
name|KEY_RSA1
argument_list|,
name|SSH_CLIENT_IDENTITY
argument_list|,
name|dotdir
argument_list|,
name|pwd
argument_list|,
name|pass
argument_list|)
expr_stmt|;
name|authenticated
operator|=
literal|0
expr_stmt|;
if|if
condition|(
name|pam_auth_dsa
operator|==
name|PAM_SUCCESS
condition|)
name|authenticated
operator|++
expr_stmt|;
if|if
condition|(
name|pam_auth_rsa
operator|==
name|PAM_SUCCESS
condition|)
name|authenticated
operator|++
expr_stmt|;
comment|/* 	 * Compatibility with SSH2 from SSH Communications Security. 	 */
if|if
condition|(
operator|!
name|asprintf
argument_list|(
operator|&
name|dotdir
argument_list|,
literal|"%s/%s"
argument_list|,
name|pwd
operator|->
name|pw_dir
argument_list|,
name|SSH2_CLIENT_DIR
argument_list|)
condition|)
block|{
name|syslog
argument_list|(
name|LOG_CRIT
argument_list|,
literal|"%s: %m"
argument_list|,
name|MODULE_NAME
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_SERVICE_ERR
argument_list|)
expr_stmt|;
block|}
comment|/* 	 * Try to load anything that looks like a private key.  For 	 * now, we only support DSA and RSA keys. 	 */
name|dotdir_p
operator|=
name|opendir
argument_list|(
name|dotdir
argument_list|)
expr_stmt|;
while|while
condition|(
name|dotdir_p
operator|&&
operator|(
name|dotdir_ent
operator|=
name|readdir
argument_list|(
name|dotdir_p
argument_list|)
operator|)
condition|)
block|{
comment|/* skip public keys */
if|if
condition|(
name|strcmp
argument_list|(
operator|&
name|dotdir_ent
operator|->
name|d_name
index|[
name|dotdir_ent
operator|->
name|d_namlen
operator|-
name|strlen
argument_list|(
name|SSH2_PUB_SUFFIX
argument_list|)
index|]
argument_list|,
name|SSH2_PUB_SUFFIX
argument_list|)
operator|==
literal|0
condition|)
continue|continue;
comment|/* DSA keys */
if|if
condition|(
name|strncmp
argument_list|(
name|dotdir_ent
operator|->
name|d_name
argument_list|,
name|SSH2_DSA_PREFIX
argument_list|,
name|strlen
argument_list|(
name|SSH2_DSA_PREFIX
argument_list|)
argument_list|)
operator|==
literal|0
condition|)
name|retval
operator|=
name|auth_via_key
argument_list|(
name|pamh
argument_list|,
name|KEY_DSA
argument_list|,
name|dotdir_ent
operator|->
name|d_name
argument_list|,
name|dotdir
argument_list|,
name|pwd
argument_list|,
name|pass
argument_list|)
expr_stmt|;
comment|/* RSA keys */
elseif|else
if|if
condition|(
name|strncmp
argument_list|(
name|dotdir_ent
operator|->
name|d_name
argument_list|,
name|SSH2_RSA_PREFIX
argument_list|,
name|strlen
argument_list|(
name|SSH2_RSA_PREFIX
argument_list|)
argument_list|)
operator|==
literal|0
condition|)
name|retval
operator|=
name|auth_via_key
argument_list|(
name|pamh
argument_list|,
name|KEY_RSA
argument_list|,
name|dotdir_ent
operator|->
name|d_name
argument_list|,
name|dotdir
argument_list|,
name|pwd
argument_list|,
name|pass
argument_list|)
expr_stmt|;
comment|/* skip other files */
else|else
continue|continue;
name|authenticated
operator|+=
operator|(
name|retval
operator|==
name|PAM_SUCCESS
operator|)
expr_stmt|;
block|}
if|if
condition|(
operator|!
name|authenticated
condition|)
block|{
name|PAM_VERBOSE_ERROR
argument_list|(
literal|"SSH authentication refused"
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_AUTH_ERR
argument_list|)
expr_stmt|;
block|}
comment|/* 	 * Copy the passwd entry (in case successive calls are made) 	 * and save it for the session phase. 	 */
name|pwd_keep
operator|=
name|malloc
argument_list|(
sizeof|sizeof
expr|*
name|pwd
argument_list|)
expr_stmt|;
if|if
condition|(
name|pwd_keep
operator|==
name|NULL
condition|)
block|{
name|syslog
argument_list|(
name|LOG_CRIT
argument_list|,
literal|"%m"
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_SERVICE_ERR
argument_list|)
expr_stmt|;
block|}
name|memcpy
argument_list|(
name|pwd_keep
argument_list|,
name|pwd
argument_list|,
sizeof|sizeof
expr|*
name|pwd_keep
argument_list|)
expr_stmt|;
name|retval
operator|=
name|pam_set_data
argument_list|(
name|pamh
argument_list|,
literal|"ssh_passwd_entry"
argument_list|,
name|pwd_keep
argument_list|,
name|ssh_cleanup
argument_list|)
expr_stmt|;
if|if
condition|(
name|retval
operator|!=
name|PAM_SUCCESS
condition|)
block|{
name|free
argument_list|(
name|pwd_keep
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|retval
argument_list|)
expr_stmt|;
block|}
name|PAM_RETURN
argument_list|(
name|PAM_SUCCESS
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|PAM_EXTERN
name|int
name|pam_sm_setcred
parameter_list|(
name|pam_handle_t
modifier|*
name|pamh
name|__unused
parameter_list|,
name|int
name|flags
name|__unused
parameter_list|,
name|int
name|argc
parameter_list|,
specifier|const
name|char
modifier|*
modifier|*
name|argv
parameter_list|)
block|{
name|int
name|options
decl_stmt|;
while|while
condition|(
name|argc
operator|--
condition|)
name|pam_std_option
argument_list|(
operator|&
name|options
argument_list|,
operator|*
name|argv
operator|++
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_SUCCESS
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|PAM_EXTERN
name|int
name|pam_sm_acct_mgmt
parameter_list|(
name|pam_handle_t
modifier|*
name|pamh
name|__unused
parameter_list|,
name|int
name|flags
name|__unused
parameter_list|,
name|int
name|argc
parameter_list|,
specifier|const
name|char
modifier|*
modifier|*
name|argv
parameter_list|)
block|{
name|int
name|options
decl_stmt|;
while|while
condition|(
name|argc
operator|--
condition|)
name|pam_std_option
argument_list|(
operator|&
name|options
argument_list|,
operator|*
name|argv
operator|++
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_IGNORE
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|PAM_EXTERN
name|int
name|pam_sm_chauthtok
parameter_list|(
name|pam_handle_t
modifier|*
name|pamh
name|__unused
parameter_list|,
name|int
name|flags
name|__unused
parameter_list|,
name|int
name|argc
parameter_list|,
specifier|const
name|char
modifier|*
modifier|*
name|argv
parameter_list|)
block|{
name|int
name|options
decl_stmt|;
while|while
condition|(
name|argc
operator|--
condition|)
name|pam_std_option
argument_list|(
operator|&
name|options
argument_list|,
operator|*
name|argv
operator|++
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_IGNORE
argument_list|)
expr_stmt|;
block|}
end_function

begin_typedef
typedef|typedef
name|AuthenticationConnection
name|AC
typedef|;
end_typedef

begin_function
name|PAM_EXTERN
name|int
name|pam_sm_open_session
parameter_list|(
name|pam_handle_t
modifier|*
name|pamh
parameter_list|,
name|int
name|flags
name|__unused
parameter_list|,
name|int
name|argc
parameter_list|,
specifier|const
name|char
modifier|*
modifier|*
name|argv
parameter_list|)
block|{
name|int
name|options
decl_stmt|;
comment|/* module options */
name|AC
modifier|*
name|ac
decl_stmt|;
comment|/* to ssh-agent */
name|char
modifier|*
name|agent_socket
decl_stmt|;
comment|/* agent socket */
name|char
modifier|*
name|comment
decl_stmt|;
comment|/* on private key */
name|char
modifier|*
name|env_end
decl_stmt|;
comment|/* end of env */
name|char
modifier|*
name|env_file
decl_stmt|;
comment|/* to store env */
name|FILE
modifier|*
name|env_fp
decl_stmt|;
comment|/* env_file handle */
name|char
modifier|*
name|env_value
decl_stmt|;
comment|/* envariable value */
name|char
modifier|*
name|data_name
decl_stmt|;
comment|/* PAM state */
name|int
name|final
decl_stmt|;
comment|/* final return value */
name|int
name|indx
decl_stmt|;
comment|/* for saved keys */
name|Key
modifier|*
name|key
decl_stmt|;
comment|/* user's private key */
name|FILE
modifier|*
name|lpipe
decl_stmt|;
comment|/* ssh-agent handle */
name|struct
name|passwd
modifier|*
name|pwd
decl_stmt|;
comment|/* user's passwd entry */
name|int
name|retval
decl_stmt|;
comment|/* from calls */
name|uid_t
name|saved_uid
decl_stmt|;
comment|/* caller's uid */
specifier|const
name|char
modifier|*
name|tty
decl_stmt|;
comment|/* tty or display name */
name|char
name|hname
index|[
name|MAXHOSTNAMELEN
index|]
decl_stmt|;
comment|/* local hostname */
name|char
name|env_string
index|[
name|BUFSIZ
index|]
decl_stmt|;
comment|/* environment string */
while|while
condition|(
name|argc
operator|--
condition|)
name|pam_std_option
argument_list|(
operator|&
name|options
argument_list|,
operator|*
name|argv
operator|++
argument_list|)
expr_stmt|;
comment|/* dump output of ssh-agent in ~/.ssh */
name|retval
operator|=
name|pam_get_data
argument_list|(
name|pamh
argument_list|,
literal|"ssh_passwd_entry"
argument_list|,
operator|(
specifier|const
name|void
operator|*
operator|*
operator|)
operator|&
name|pwd
argument_list|)
expr_stmt|;
if|if
condition|(
name|retval
operator|!=
name|PAM_SUCCESS
condition|)
name|PAM_RETURN
argument_list|(
name|retval
argument_list|)
expr_stmt|;
comment|/* use the tty or X display name in the filename */
name|retval
operator|=
name|pam_get_item
argument_list|(
name|pamh
argument_list|,
name|PAM_TTY
argument_list|,
operator|(
specifier|const
name|void
operator|*
operator|*
operator|)
operator|&
name|tty
argument_list|)
expr_stmt|;
if|if
condition|(
name|retval
operator|!=
name|PAM_SUCCESS
condition|)
name|PAM_RETURN
argument_list|(
name|retval
argument_list|)
expr_stmt|;
if|if
condition|(
name|gethostname
argument_list|(
name|hname
argument_list|,
sizeof|sizeof
name|hname
argument_list|)
operator|==
literal|0
condition|)
block|{
if|if
condition|(
name|asprintf
argument_list|(
operator|&
name|env_file
argument_list|,
literal|"%s/.ssh/agent-%s%s%s"
argument_list|,
name|pwd
operator|->
name|pw_dir
argument_list|,
name|hname
argument_list|,
operator|*
name|tty
operator|==
literal|':'
condition|?
literal|""
else|:
literal|":"
argument_list|,
name|tty
argument_list|)
operator|==
operator|-
literal|1
condition|)
block|{
name|syslog
argument_list|(
name|LOG_CRIT
argument_list|,
literal|"%s: %m"
argument_list|,
name|MODULE_NAME
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_SERVICE_ERR
argument_list|)
expr_stmt|;
block|}
block|}
elseif|else
if|if
condition|(
name|asprintf
argument_list|(
operator|&
name|env_file
argument_list|,
literal|"%s/.ssh/agent-%s"
argument_list|,
name|pwd
operator|->
name|pw_dir
argument_list|,
name|tty
argument_list|)
operator|==
operator|-
literal|1
condition|)
block|{
name|syslog
argument_list|(
name|LOG_CRIT
argument_list|,
literal|"%s: %m"
argument_list|,
name|MODULE_NAME
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_SERVICE_ERR
argument_list|)
expr_stmt|;
block|}
comment|/* save the filename so we can delete the file on session close */
name|retval
operator|=
name|pam_set_data
argument_list|(
name|pamh
argument_list|,
literal|"ssh_agent_env"
argument_list|,
name|env_file
argument_list|,
name|ssh_cleanup
argument_list|)
expr_stmt|;
if|if
condition|(
name|retval
operator|!=
name|PAM_SUCCESS
condition|)
block|{
name|free
argument_list|(
name|env_file
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|retval
argument_list|)
expr_stmt|;
block|}
comment|/* start the agent as the user */
name|saved_uid
operator|=
name|geteuid
argument_list|()
expr_stmt|;
name|seteuid
argument_list|(
name|pwd
operator|->
name|pw_uid
argument_list|)
expr_stmt|;
name|env_fp
operator|=
name|fopen
argument_list|(
name|env_file
argument_list|,
literal|"w"
argument_list|)
expr_stmt|;
if|if
condition|(
name|env_fp
operator|!=
name|NULL
condition|)
name|chmod
argument_list|(
name|env_file
argument_list|,
name|S_IRUSR
argument_list|)
expr_stmt|;
name|lpipe
operator|=
name|popen
argument_list|(
name|SSH_AGENT
argument_list|,
literal|"r"
argument_list|)
expr_stmt|;
name|seteuid
argument_list|(
name|saved_uid
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|lpipe
condition|)
block|{
name|syslog
argument_list|(
name|LOG_ERR
argument_list|,
literal|"%s: %s: %m"
argument_list|,
name|MODULE_NAME
argument_list|,
name|SSH_AGENT
argument_list|)
expr_stmt|;
if|if
condition|(
name|env_fp
condition|)
name|fclose
argument_list|(
name|env_fp
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_SESSION_ERR
argument_list|)
expr_stmt|;
block|}
comment|/* 	 * Save environment for application with pam_putenv(). 	 */
name|agent_socket
operator|=
name|NULL
expr_stmt|;
while|while
condition|(
name|fgets
argument_list|(
name|env_string
argument_list|,
sizeof|sizeof
name|env_string
argument_list|,
name|lpipe
argument_list|)
condition|)
block|{
if|if
condition|(
name|env_fp
condition|)
name|fputs
argument_list|(
name|env_string
argument_list|,
name|env_fp
argument_list|)
expr_stmt|;
name|env_value
operator|=
name|strchr
argument_list|(
name|env_string
argument_list|,
literal|'='
argument_list|)
expr_stmt|;
if|if
condition|(
name|env_value
operator|==
name|NULL
condition|)
continue|continue;
name|env_end
operator|=
name|strchr
argument_list|(
name|env_value
argument_list|,
literal|';'
argument_list|)
expr_stmt|;
if|if
condition|(
name|env_end
operator|==
name|NULL
condition|)
continue|continue;
operator|*
name|env_end
operator|=
literal|'\0'
expr_stmt|;
comment|/* pass to the application ... */
name|retval
operator|=
name|pam_putenv
argument_list|(
name|pamh
argument_list|,
name|env_string
argument_list|)
expr_stmt|;
if|if
condition|(
name|retval
operator|!=
name|PAM_SUCCESS
condition|)
block|{
name|pclose
argument_list|(
name|lpipe
argument_list|)
expr_stmt|;
if|if
condition|(
name|env_fp
condition|)
name|fclose
argument_list|(
name|env_fp
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_SERVICE_ERR
argument_list|)
expr_stmt|;
block|}
operator|*
name|env_value
operator|++
operator|=
literal|'\0'
expr_stmt|;
if|if
condition|(
name|strcmp
argument_list|(
operator|&
name|env_string
index|[
name|strlen
argument_list|(
name|env_string
argument_list|)
operator|-
name|strlen
argument_list|(
name|ENV_SOCKET_SUFFIX
argument_list|)
index|]
argument_list|,
name|ENV_SOCKET_SUFFIX
argument_list|)
operator|==
literal|0
condition|)
block|{
name|agent_socket
operator|=
name|strdup
argument_list|(
name|env_value
argument_list|)
expr_stmt|;
if|if
condition|(
name|agent_socket
operator|==
name|NULL
condition|)
block|{
name|syslog
argument_list|(
name|LOG_CRIT
argument_list|,
literal|"%s: %m"
argument_list|,
name|MODULE_NAME
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_SERVICE_ERR
argument_list|)
expr_stmt|;
block|}
block|}
elseif|else
if|if
condition|(
name|strcmp
argument_list|(
operator|&
name|env_string
index|[
name|strlen
argument_list|(
name|env_string
argument_list|)
operator|-
name|strlen
argument_list|(
name|ENV_PID_SUFFIX
argument_list|)
index|]
argument_list|,
name|ENV_PID_SUFFIX
argument_list|)
operator|==
literal|0
condition|)
block|{
name|env_value
operator|=
name|strdup
argument_list|(
name|env_value
argument_list|)
expr_stmt|;
if|if
condition|(
name|env_value
operator|==
name|NULL
condition|)
block|{
name|syslog
argument_list|(
name|LOG_CRIT
argument_list|,
literal|"%s: %m"
argument_list|,
name|MODULE_NAME
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_SERVICE_ERR
argument_list|)
expr_stmt|;
block|}
name|retval
operator|=
name|pam_set_data
argument_list|(
name|pamh
argument_list|,
literal|"ssh_agent_pid"
argument_list|,
name|env_value
argument_list|,
name|ssh_cleanup
argument_list|)
expr_stmt|;
if|if
condition|(
name|retval
operator|!=
name|PAM_SUCCESS
condition|)
name|PAM_RETURN
argument_list|(
name|retval
argument_list|)
expr_stmt|;
block|}
block|}
if|if
condition|(
name|env_fp
condition|)
name|fclose
argument_list|(
name|env_fp
argument_list|)
expr_stmt|;
name|retval
operator|=
name|pclose
argument_list|(
name|lpipe
argument_list|)
expr_stmt|;
switch|switch
condition|(
name|retval
condition|)
block|{
case|case
operator|-
literal|1
case|:
name|syslog
argument_list|(
name|LOG_ERR
argument_list|,
literal|"%s: %s: %m"
argument_list|,
name|MODULE_NAME
argument_list|,
name|SSH_AGENT
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_SESSION_ERR
argument_list|)
expr_stmt|;
case|case
literal|0
case|:
break|break;
case|case
literal|127
case|:
name|syslog
argument_list|(
name|LOG_ERR
argument_list|,
literal|"%s: cannot execute %s"
argument_list|,
name|MODULE_NAME
argument_list|,
name|SSH_AGENT
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_SESSION_ERR
argument_list|)
expr_stmt|;
default|default:
name|syslog
argument_list|(
name|LOG_ERR
argument_list|,
literal|"%s: %s exited %s %d"
argument_list|,
name|MODULE_NAME
argument_list|,
name|SSH_AGENT
argument_list|,
name|WIFSIGNALED
argument_list|(
name|retval
argument_list|)
condition|?
literal|"on signal"
else|:
literal|"with status"
argument_list|,
name|WIFSIGNALED
argument_list|(
name|retval
argument_list|)
condition|?
name|WTERMSIG
argument_list|(
name|retval
argument_list|)
else|:
name|WEXITSTATUS
argument_list|(
name|retval
argument_list|)
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_SESSION_ERR
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|agent_socket
operator|==
name|NULL
condition|)
name|PAM_RETURN
argument_list|(
name|PAM_SESSION_ERR
argument_list|)
expr_stmt|;
comment|/* 	 * Connect to the agent. 	 * 	 * XXX Because ssh_get_authentication_connection() gets the 	 * XXX agent parameters from the environment, we have to 	 * XXX temporarily replace the environment with the PAM 	 * XXX environment list.  This is a hack. 	 */
block|{
specifier|extern
name|char
modifier|*
modifier|*
name|environ
decl_stmt|;
name|char
modifier|*
modifier|*
name|saved
decl_stmt|,
modifier|*
modifier|*
name|evp
decl_stmt|;
name|saved
operator|=
name|environ
expr_stmt|;
if|if
condition|(
operator|(
name|environ
operator|=
name|pam_getenvlist
argument_list|(
name|pamh
argument_list|)
operator|)
operator|==
name|NULL
condition|)
block|{
name|environ
operator|=
name|saved
expr_stmt|;
name|syslog
argument_list|(
name|LOG_ERR
argument_list|,
literal|"%s: %m"
argument_list|,
name|MODULE_NAME
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_BUF_ERR
argument_list|)
expr_stmt|;
block|}
name|ac
operator|=
name|ssh_get_authentication_connection
argument_list|()
expr_stmt|;
for|for
control|(
name|evp
operator|=
name|environ
init|;
operator|*
name|evp
condition|;
name|evp
operator|++
control|)
name|free
argument_list|(
operator|*
name|evp
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|environ
argument_list|)
expr_stmt|;
name|environ
operator|=
name|saved
expr_stmt|;
block|}
if|if
condition|(
operator|!
name|ac
condition|)
block|{
name|syslog
argument_list|(
name|LOG_ERR
argument_list|,
literal|"%s: %s: %m"
argument_list|,
name|MODULE_NAME
argument_list|,
name|agent_socket
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_SESSION_ERR
argument_list|)
expr_stmt|;
block|}
comment|/* hand off each private key to the agent */
name|final
operator|=
literal|0
expr_stmt|;
for|for
control|(
name|indx
operator|=
literal|0
init|;
condition|;
name|indx
operator|++
control|)
block|{
if|if
condition|(
operator|!
name|asprintf
argument_list|(
operator|&
name|data_name
argument_list|,
literal|"ssh_private_key_%d"
argument_list|,
name|indx
argument_list|)
condition|)
block|{
name|syslog
argument_list|(
name|LOG_CRIT
argument_list|,
literal|"%s: %m"
argument_list|,
name|MODULE_NAME
argument_list|)
expr_stmt|;
name|ssh_close_authentication_connection
argument_list|(
name|ac
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_SERVICE_ERR
argument_list|)
expr_stmt|;
block|}
name|retval
operator|=
name|pam_get_data
argument_list|(
name|pamh
argument_list|,
name|data_name
argument_list|,
operator|(
specifier|const
name|void
operator|*
operator|*
operator|)
operator|&
name|key
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|data_name
argument_list|)
expr_stmt|;
if|if
condition|(
name|retval
operator|!=
name|PAM_SUCCESS
condition|)
break|break;
if|if
condition|(
operator|!
name|asprintf
argument_list|(
operator|&
name|data_name
argument_list|,
literal|"ssh_key_comment_%d"
argument_list|,
name|indx
argument_list|)
condition|)
block|{
name|syslog
argument_list|(
name|LOG_CRIT
argument_list|,
literal|"%s: %m"
argument_list|,
name|MODULE_NAME
argument_list|)
expr_stmt|;
name|ssh_close_authentication_connection
argument_list|(
name|ac
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_SERVICE_ERR
argument_list|)
expr_stmt|;
block|}
name|retval
operator|=
name|pam_get_data
argument_list|(
name|pamh
argument_list|,
name|data_name
argument_list|,
operator|(
specifier|const
name|void
operator|*
operator|*
operator|)
operator|&
name|comment
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|data_name
argument_list|)
expr_stmt|;
if|if
condition|(
name|retval
operator|!=
name|PAM_SUCCESS
condition|)
break|break;
name|retval
operator|=
name|ssh_add_identity
argument_list|(
name|ac
argument_list|,
name|key
argument_list|,
name|comment
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|final
condition|)
name|final
operator|=
name|retval
expr_stmt|;
block|}
name|ssh_close_authentication_connection
argument_list|(
name|ac
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|final
condition|?
name|PAM_SUCCESS
else|:
name|PAM_SESSION_ERR
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
name|PAM_EXTERN
name|int
name|pam_sm_close_session
parameter_list|(
name|pam_handle_t
modifier|*
name|pamh
parameter_list|,
name|int
name|flags
name|__unused
parameter_list|,
name|int
name|argc
parameter_list|,
specifier|const
name|char
modifier|*
modifier|*
name|argv
parameter_list|)
block|{
name|int
name|options
decl_stmt|;
comment|/* module options */
specifier|const
name|char
modifier|*
name|env_file
decl_stmt|;
comment|/* ssh-agent environment */
name|pid_t
name|pid
decl_stmt|;
comment|/* ssh-agent process id */
name|int
name|retval
decl_stmt|;
comment|/* from calls */
specifier|const
name|char
modifier|*
name|ssh_agent_pid
decl_stmt|;
comment|/* ssh-agent pid string */
while|while
condition|(
name|argc
operator|--
condition|)
name|pam_std_option
argument_list|(
operator|&
name|options
argument_list|,
operator|*
name|argv
operator|++
argument_list|)
expr_stmt|;
comment|/* retrieve environment filename, then remove the file */
name|retval
operator|=
name|pam_get_data
argument_list|(
name|pamh
argument_list|,
literal|"ssh_agent_env"
argument_list|,
operator|(
specifier|const
name|void
operator|*
operator|*
operator|)
operator|&
name|env_file
argument_list|)
expr_stmt|;
if|if
condition|(
name|retval
operator|!=
name|PAM_SUCCESS
condition|)
name|PAM_RETURN
argument_list|(
name|retval
argument_list|)
expr_stmt|;
name|unlink
argument_list|(
name|env_file
argument_list|)
expr_stmt|;
comment|/* retrieve the agent's process id */
name|retval
operator|=
name|pam_get_data
argument_list|(
name|pamh
argument_list|,
literal|"ssh_agent_pid"
argument_list|,
operator|(
specifier|const
name|void
operator|*
operator|*
operator|)
operator|&
name|ssh_agent_pid
argument_list|)
expr_stmt|;
if|if
condition|(
name|retval
operator|!=
name|PAM_SUCCESS
condition|)
name|PAM_RETURN
argument_list|(
name|retval
argument_list|)
expr_stmt|;
comment|/* 	 * Kill the agent.  SSH2 from SSH Communications Security does 	 * not have a -k option, so we just call kill(). 	 */
name|pid
operator|=
name|atoi
argument_list|(
name|ssh_agent_pid
argument_list|)
expr_stmt|;
if|if
condition|(
name|pid
operator|<=
literal|0
condition|)
name|PAM_RETURN
argument_list|(
name|PAM_SESSION_ERR
argument_list|)
expr_stmt|;
if|if
condition|(
name|kill
argument_list|(
name|pid
argument_list|,
name|SIGTERM
argument_list|)
operator|!=
literal|0
condition|)
block|{
name|syslog
argument_list|(
name|LOG_ERR
argument_list|,
literal|"%s: %s: %m"
argument_list|,
name|MODULE_NAME
argument_list|,
name|ssh_agent_pid
argument_list|)
expr_stmt|;
name|PAM_RETURN
argument_list|(
name|PAM_SESSION_ERR
argument_list|)
expr_stmt|;
block|}
name|PAM_RETURN
argument_list|(
name|PAM_SUCCESS
argument_list|)
expr_stmt|;
block|}
end_function

begin_expr_stmt
name|PAM_MODULE_ENTRY
argument_list|(
literal|"pam_ssh"
argument_list|)
expr_stmt|;
end_expr_stmt

end_unit

