begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * System call names.  *  * DO NOT EDIT-- this file is automatically generated.  * created from	@(#)syscalls.master	8.2 (Berkeley) 4/3/95  */
end_comment

begin_decl_stmt
name|char
modifier|*
name|syscallnames
index|[]
init|=
block|{
literal|"#0"
block|,
comment|/* 0 = nosys syscall */
literal|"exit"
block|,
comment|/* 1 = exit */
literal|"fork"
block|,
comment|/* 2 = fork */
literal|"read"
block|,
comment|/* 3 = read */
literal|"write"
block|,
comment|/* 4 = write */
literal|"open"
block|,
comment|/* 5 = open */
literal|"close"
block|,
comment|/* 6 = close */
literal|"sun_wait4"
block|,
comment|/* 7 = sun_wait4 */
literal|"sun_creat"
block|,
comment|/* 8 = sun_creat */
literal|"link"
block|,
comment|/* 9 = link */
literal|"unlink"
block|,
comment|/* 10 = unlink */
literal|"sun_execv"
block|,
comment|/* 11 = sun_execv */
literal|"chdir"
block|,
comment|/* 12 = chdir */
literal|"old.sun_time"
block|,
comment|/* 13 = old sun_time */
literal|"mknod"
block|,
comment|/* 14 = mknod */
literal|"chmod"
block|,
comment|/* 15 = chmod */
literal|"chown"
block|,
comment|/* 16 = chown */
literal|"break"
block|,
comment|/* 17 = break */
literal|"old.sun_stat"
block|,
comment|/* 18 = old sun_stat */
literal|"compat_43_lseek"
block|,
comment|/* 19 = compat_43_lseek */
literal|"getpid"
block|,
comment|/* 20 = getpid */
literal|"obs_sun_old_mount"
block|,
comment|/* 21 = obsolete sun_old_mount */
literal|"#22"
block|,
comment|/* 22 = System V umount */
literal|"old.setuid"
block|,
comment|/* 23 = old setuid */
literal|"getuid"
block|,
comment|/* 24 = getuid */
literal|"old.sun_stime"
block|,
comment|/* 25 = old sun_stime */
literal|"#26"
block|,
comment|/* 26 = sun_ptrace */
literal|"old.sun_alarm"
block|,
comment|/* 27 = old sun_alarm */
literal|"old.sun_fstat"
block|,
comment|/* 28 = old sun_fstat */
literal|"old.sun_pause"
block|,
comment|/* 29 = old sun_pause */
literal|"old.sun_utime"
block|,
comment|/* 30 = old sun_utime */
literal|"#31"
block|,
comment|/* 31 = was stty */
literal|"#32"
block|,
comment|/* 32 = was gtty */
literal|"access"
block|,
comment|/* 33 = access */
literal|"old.sun_nice"
block|,
comment|/* 34 = old sun_nice */
literal|"old.sun_ftime"
block|,
comment|/* 35 = old sun_ftime */
literal|"sync"
block|,
comment|/* 36 = sync */
literal|"kill"
block|,
comment|/* 37 = kill */
literal|"compat_43_stat"
block|,
comment|/* 38 = compat_43_stat */
literal|"old.sun_setpgrp"
block|,
comment|/* 39 = old sun_setpgrp */
literal|"compat_43_lstat"
block|,
comment|/* 40 = compat_43_lstat */
literal|"dup"
block|,
comment|/* 41 = dup */
literal|"pipe"
block|,
comment|/* 42 = pipe */
literal|"old.sun_times"
block|,
comment|/* 43 = old sun_times */
literal|"profil"
block|,
comment|/* 44 = profil */
literal|"#45"
block|,
comment|/* 45 = nosys */
literal|"old.sun_setgid"
block|,
comment|/* 46 = old sun_setgid */
literal|"getgid"
block|,
comment|/* 47 = getgid */
literal|"old.sun_ssig"
block|,
comment|/* 48 = old sun_ssig */
literal|"#49"
block|,
comment|/* 49 = reserved for USG */
literal|"#50"
block|,
comment|/* 50 = reserved for USG */
literal|"acct"
block|,
comment|/* 51 = acct */
literal|"#52"
block|,
comment|/* 52 = nosys */
literal|"sun_mctl"
block|,
comment|/* 53 = sun_mctl */
literal|"sun_ioctl"
block|,
comment|/* 54 = sun_ioctl */
literal|"reboot"
block|,
comment|/* 55 = reboot */
literal|"obs_sun_owait3"
block|,
comment|/* 56 = obsolete sun_owait3 */
literal|"symlink"
block|,
comment|/* 57 = symlink */
literal|"readlink"
block|,
comment|/* 58 = readlink */
literal|"execve"
block|,
comment|/* 59 = execve */
literal|"umask"
block|,
comment|/* 60 = umask */
literal|"chroot"
block|,
comment|/* 61 = chroot */
literal|"compat_43_fstat"
block|,
comment|/* 62 = compat_43_fstat */
literal|"#63"
block|,
comment|/* 63 = nosys */
literal|"compat_43_getpagesize"
block|,
comment|/* 64 = compat_43_getpagesize */
literal|"sun_omsync"
block|,
comment|/* 65 = sun_omsync */
literal|"vfork"
block|,
comment|/* 66 = vfork */
literal|"obs_vread"
block|,
comment|/* 67 = obsolete vread */
literal|"obs_vwrite"
block|,
comment|/* 68 = obsolete vwrite */
literal|"sbrk"
block|,
comment|/* 69 = sbrk */
literal|"sstk"
block|,
comment|/* 70 = sstk */
literal|"mmap"
block|,
comment|/* 71 = mmap */
literal|"vadvise"
block|,
comment|/* 72 = vadvise */
literal|"munmap"
block|,
comment|/* 73 = munmap */
literal|"mprotect"
block|,
comment|/* 74 = mprotect */
literal|"madvise"
block|,
comment|/* 75 = madvise */
literal|"old.vhangup"
block|,
comment|/* 76 = old vhangup */
literal|"old.vlimit"
block|,
comment|/* 77 = old vlimit */
literal|"mincore"
block|,
comment|/* 78 = mincore */
literal|"getgroups"
block|,
comment|/* 79 = getgroups */
literal|"setgroups"
block|,
comment|/* 80 = setgroups */
literal|"getpgrp"
block|,
comment|/* 81 = getpgrp */
literal|"setpgid"
block|,
comment|/* 82 = setpgid */
literal|"setitimer"
block|,
comment|/* 83 = setitimer */
literal|"old.wait"
block|,
comment|/* 84 = old wait */
literal|"swapon"
block|,
comment|/* 85 = swapon */
literal|"getitimer"
block|,
comment|/* 86 = getitimer */
literal|"compat_43_gethostname"
block|,
comment|/* 87 = compat_43_gethostname */
literal|"compat_43_sethostname"
block|,
comment|/* 88 = compat_43_sethostname */
literal|"getdtablesize"
block|,
comment|/* 89 = getdtablesize */
literal|"dup2"
block|,
comment|/* 90 = dup2 */
literal|"#91"
block|,
comment|/* 91 = getdopt */
literal|"fcntl"
block|,
comment|/* 92 = fcntl */
literal|"select"
block|,
comment|/* 93 = select */
literal|"#94"
block|,
comment|/* 94 = setdopt */
literal|"fsync"
block|,
comment|/* 95 = fsync */
literal|"setpriority"
block|,
comment|/* 96 = setpriority */
literal|"socket"
block|,
comment|/* 97 = socket */
literal|"connect"
block|,
comment|/* 98 = connect */
literal|"compat_43_accept"
block|,
comment|/* 99 = compat_43_accept */
literal|"getpriority"
block|,
comment|/* 100 = getpriority */
literal|"compat_43_send"
block|,
comment|/* 101 = compat_43_send */
literal|"compat_43_recv"
block|,
comment|/* 102 = compat_43_recv */
literal|"#103"
block|,
comment|/* 103 = old socketaddr */
literal|"bind"
block|,
comment|/* 104 = bind */
literal|"sun_setsockopt"
block|,
comment|/* 105 = sun_setsockopt */
literal|"listen"
block|,
comment|/* 106 = listen */
literal|"old.vtimes"
block|,
comment|/* 107 = old vtimes */
literal|"compat_43_sigvec"
block|,
comment|/* 108 = compat_43_sigvec */
literal|"compat_43_sigblock"
block|,
comment|/* 109 = compat_43_sigblock */
literal|"compat_43_sigsetmask"
block|,
comment|/* 110 = compat_43_sigsetmask */
literal|"sigsuspend"
block|,
comment|/* 111 = sigsuspend */
literal|"compat_43_sigstack"
block|,
comment|/* 112 = compat_43_sigstack */
literal|"compat_43_recvmsg"
block|,
comment|/* 113 = compat_43_recvmsg */
literal|"compat_43_sendmsg"
block|,
comment|/* 114 = compat_43_sendmsg */
literal|"obs_vtrace"
block|,
comment|/* 115 = obsolete vtrace */
literal|"gettimeofday"
block|,
comment|/* 116 = gettimeofday */
literal|"getrusage"
block|,
comment|/* 117 = getrusage */
literal|"getsockopt"
block|,
comment|/* 118 = getsockopt */
literal|"#119"
block|,
comment|/* 119 = nosys */
literal|"readv"
block|,
comment|/* 120 = readv */
literal|"writev"
block|,
comment|/* 121 = writev */
literal|"settimeofday"
block|,
comment|/* 122 = settimeofday */
literal|"fchown"
block|,
comment|/* 123 = fchown */
literal|"fchmod"
block|,
comment|/* 124 = fchmod */
literal|"compat_43_recvfrom"
block|,
comment|/* 125 = compat_43_recvfrom */
literal|"compat_43_setreuid"
block|,
comment|/* 126 = compat_43_setreuid */
literal|"compat_43_setregid"
block|,
comment|/* 127 = compat_43_setregid */
literal|"rename"
block|,
comment|/* 128 = rename */
literal|"compat_43_truncate"
block|,
comment|/* 129 = compat_43_truncate */
literal|"compat_43_ftruncate"
block|,
comment|/* 130 = compat_43_ftruncate */
literal|"flock"
block|,
comment|/* 131 = flock */
literal|"#132"
block|,
comment|/* 132 = nosys */
literal|"sendto"
block|,
comment|/* 133 = sendto */
literal|"shutdown"
block|,
comment|/* 134 = shutdown */
literal|"socketpair"
block|,
comment|/* 135 = socketpair */
literal|"mkdir"
block|,
comment|/* 136 = mkdir */
literal|"rmdir"
block|,
comment|/* 137 = rmdir */
literal|"utimes"
block|,
comment|/* 138 = utimes */
literal|"sigreturn"
block|,
comment|/* 139 = sigreturn */
literal|"adjtime"
block|,
comment|/* 140 = adjtime */
literal|"compat_43_getpeername"
block|,
comment|/* 141 = compat_43_getpeername */
literal|"compat_43_gethostid"
block|,
comment|/* 142 = compat_43_gethostid */
literal|"#143"
block|,
comment|/* 143 = old sethostid */
literal|"compat_43_getrlimit"
block|,
comment|/* 144 = compat_43_getrlimit */
literal|"compat_43_setrlimit"
block|,
comment|/* 145 = compat_43_setrlimit */
literal|"compat_43_killpg"
block|,
comment|/* 146 = compat_43_killpg */
literal|"#147"
block|,
comment|/* 147 = nosys */
literal|"#148"
block|,
comment|/* 148 = nosys */
literal|"#149"
block|,
comment|/* 149 = nosys */
literal|"compat_43_getsockname"
block|,
comment|/* 150 = compat_43_getsockname */
literal|"#151"
block|,
comment|/* 151 = getmsg */
literal|"#152"
block|,
comment|/* 152 = putmsg */
literal|"#153"
block|,
comment|/* 153 = poll */
literal|"#154"
block|,
comment|/* 154 = nosys */
literal|"#155"
block|,
comment|/* 155 = nosys */
literal|"getdirentries"
block|,
comment|/* 156 = getdirentries */
literal|"statfs"
block|,
comment|/* 157 = statfs */
literal|"fstatfs"
block|,
comment|/* 158 = fstatfs */
literal|"sun_unmount"
block|,
comment|/* 159 = sun_unmount */
literal|"#160"
block|,
comment|/* 160 = nosys */
literal|"#161"
block|,
comment|/* 161 = nosys */
literal|"sun_getdomainname"
block|,
comment|/* 162 = sun_getdomainname */
literal|"sun_setdomainname"
block|,
comment|/* 163 = sun_setdomainname */
literal|"#164"
block|,
comment|/* 164 = rtschedule */
literal|"#165"
block|,
comment|/* 165 = quotactl */
literal|"#166"
block|,
comment|/* 166 = exportfs */
literal|"sun_mount"
block|,
comment|/* 167 = sun_mount */
literal|"#168"
block|,
comment|/* 168 = ustat */
literal|"#169"
block|,
comment|/* 169 = semsys */
literal|"#170"
block|,
comment|/* 170 = msgsys */
ifdef|#
directive|ifdef
name|SYSVSHM
literal|"shmsys"
block|,
comment|/* 171 = shmsys */
else|#
directive|else
literal|"#171"
block|,
comment|/* 171 = nosys */
endif|#
directive|endif
literal|"#172"
block|,
comment|/* 172 = auditsys */
literal|"#173"
block|,
comment|/* 173 = rfssys */
literal|"sun_getdents"
block|,
comment|/* 174 = sun_getdents */
literal|"setsid"
block|,
comment|/* 175 = setsid */
literal|"fchdir"
block|,
comment|/* 176 = fchdir */
literal|"sun_fchroot"
block|,
comment|/* 177 = sun_fchroot */
literal|"#178"
block|,
comment|/* 178 = nosys */
literal|"#179"
block|,
comment|/* 179 = nosys */
literal|"#180"
block|,
comment|/* 180 = nosys */
literal|"#181"
block|,
comment|/* 181 = nosys */
literal|"#182"
block|,
comment|/* 182 = nosys */
literal|"sun_sigpending"
block|,
comment|/* 183 = sun_sigpending */
literal|"#184"
block|,
comment|/* 184 = nosys */
literal|"setpgid"
block|,
comment|/* 185 = setpgid */
literal|"#186"
block|,
comment|/* 186 = pathconf */
literal|"#187"
block|,
comment|/* 187 = fpathconf */
literal|"#188"
block|,
comment|/* 188 = sysconf */
literal|"#189"
block|,
comment|/* 189 = uname */
block|}
decl_stmt|;
end_decl_stmt

end_unit

