begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/****************************************************************************  * Copyright (c) 1998 Free Software Foundation, Inc.                        *  *                                                                          *  * Permission is hereby granted, free of charge, to any person obtaining a  *  * copy of this software and associated documentation files (the            *  * "Software"), to deal in the Software without restriction, including      *  * without limitation the rights to use, copy, modify, merge, publish,      *  * distribute, distribute with modifications, sublicense, and/or sell       *  * copies of the Software, and to permit persons to whom the Software is    *  * furnished to do so, subject to the following conditions:                 *  *                                                                          *  * The above copyright notice and this permission notice shall be included  *  * in all copies or substantial portions of the Software.                   *  *                                                                          *  * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS  *  * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF               *  * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.   *  * IN NO EVENT SHALL THE ABOVE COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,   *  * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR    *  * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR    *  * THE USE OR OTHER DEALINGS IN THE SOFTWARE.                               *  *                                                                          *  * Except as contained in this notice, the name(s) of the above copyright   *  * holders shall not be used in advertising or otherwise to promote the     *  * sale, use or other dealings in this Software without prior written       *  * authorization.                                                           *  ****************************************************************************/
end_comment

begin_comment
comment|/****************************************************************************  *   Author: Juergen Pfeifer<juergen.pfeifer@gmx.net> 1995,1997            *  ****************************************************************************/
end_comment

begin_include
include|#
directive|include
file|"form.priv.h"
end_include

begin_macro
name|MODULE_ID
argument_list|(
literal|"$Id: fld_def.c,v 1.12 1999/05/16 17:37:48 juergen Exp $"
argument_list|)
end_macro

begin_comment
comment|/* this can't be readonly */
end_comment

begin_decl_stmt
specifier|static
name|FIELD
name|default_field
init|=
block|{
literal|0
block|,
comment|/* status */
literal|0
block|,
comment|/* rows   */
literal|0
block|,
comment|/* cols   */
literal|0
block|,
comment|/* frow   */
literal|0
block|,
comment|/* fcol   */
literal|0
block|,
comment|/* drows  */
literal|0
block|,
comment|/* dcols  */
literal|0
block|,
comment|/* maxgrow*/
literal|0
block|,
comment|/* nrow   */
literal|0
block|,
comment|/* nbuf   */
name|NO_JUSTIFICATION
block|,
comment|/* just   */
literal|0
block|,
comment|/* page   */
literal|0
block|,
comment|/* index  */
operator|(
name|int
operator|)
literal|' '
block|,
comment|/* pad    */
name|A_NORMAL
block|,
comment|/* fore   */
name|A_NORMAL
block|,
comment|/* back   */
name|ALL_FIELD_OPTS
block|,
comment|/* opts   */
operator|(
name|FIELD
operator|*
operator|)
literal|0
block|,
comment|/* snext  */
operator|(
name|FIELD
operator|*
operator|)
literal|0
block|,
comment|/* sprev  */
operator|(
name|FIELD
operator|*
operator|)
literal|0
block|,
comment|/* link   */
operator|(
name|FORM
operator|*
operator|)
literal|0
block|,
comment|/* form   */
operator|(
name|FIELDTYPE
operator|*
operator|)
literal|0
block|,
comment|/* type   */
operator|(
name|char
operator|*
operator|)
literal|0
block|,
comment|/* arg    */
operator|(
name|char
operator|*
operator|)
literal|0
block|,
comment|/* buf    */
operator|(
name|char
operator|*
operator|)
literal|0
comment|/* usrptr */
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
name|FIELD
modifier|*
name|_nc_Default_Field
init|=
operator|&
name|default_field
decl_stmt|;
end_decl_stmt

begin_escape
end_escape

begin_comment
comment|/*--------------------------------------------------------------------------- |   Facility      :  libnform   |   Function      :  TypeArgument *_nc_Make_Argument( |                              const FIELDTYPE *typ, |                              va_list *ap, |                              int *err ) |    |   Description   :  Create an argument structure for the specified type. |                    Use the type-dependant argument list to construct |                    it. | |   Return Values :  Pointer to argument structure. Maybe NULL. |                    In case of an error in *err an errorcounter is increased.  +--------------------------------------------------------------------------*/
end_comment

begin_function
name|TypeArgument
modifier|*
name|_nc_Make_Argument
parameter_list|(
specifier|const
name|FIELDTYPE
modifier|*
name|typ
parameter_list|,
name|va_list
modifier|*
name|ap
parameter_list|,
name|int
modifier|*
name|err
parameter_list|)
block|{
name|TypeArgument
modifier|*
name|res
init|=
operator|(
name|TypeArgument
operator|*
operator|)
literal|0
decl_stmt|;
name|TypeArgument
modifier|*
name|p
decl_stmt|;
if|if
condition|(
name|typ
operator|&&
operator|(
name|typ
operator|->
name|status
operator|&
name|_HAS_ARGS
operator|)
condition|)
block|{
name|assert
argument_list|(
name|err
operator|&&
name|ap
argument_list|)
expr_stmt|;
if|if
condition|(
name|typ
operator|->
name|status
operator|&
name|_LINKED_TYPE
condition|)
block|{
name|p
operator|=
operator|(
name|TypeArgument
operator|*
operator|)
name|malloc
argument_list|(
sizeof|sizeof
argument_list|(
name|TypeArgument
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|p
condition|)
block|{
name|p
operator|->
name|left
operator|=
name|_nc_Make_Argument
argument_list|(
name|typ
operator|->
name|left
argument_list|,
name|ap
argument_list|,
name|err
argument_list|)
expr_stmt|;
name|p
operator|->
name|right
operator|=
name|_nc_Make_Argument
argument_list|(
name|typ
operator|->
name|right
argument_list|,
name|ap
argument_list|,
name|err
argument_list|)
expr_stmt|;
return|return
name|p
return|;
block|}
else|else
operator|*
name|err
operator|+=
literal|1
expr_stmt|;
block|}
else|else
block|{
name|assert
argument_list|(
name|typ
operator|->
name|makearg
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
operator|(
name|res
operator|=
operator|(
name|TypeArgument
operator|*
operator|)
name|typ
operator|->
name|makearg
argument_list|(
name|ap
argument_list|)
operator|)
condition|)
operator|*
name|err
operator|+=
literal|1
expr_stmt|;
block|}
block|}
return|return
name|res
return|;
block|}
end_function

begin_comment
comment|/*--------------------------------------------------------------------------- |   Facility      :  libnform   |   Function      :  TypeArgument *_nc_Copy_Argument(const FIELDTYPE *typ, |                                                    const TypeArgument *argp, |                                                    int *err ) |    |   Description   :  Create a copy of an argument structure for the specified  |                    type. | |   Return Values :  Pointer to argument structure. Maybe NULL. |                    In case of an error in *err an errorcounter is increased.  +--------------------------------------------------------------------------*/
end_comment

begin_function
name|TypeArgument
modifier|*
name|_nc_Copy_Argument
parameter_list|(
specifier|const
name|FIELDTYPE
modifier|*
name|typ
parameter_list|,
specifier|const
name|TypeArgument
modifier|*
name|argp
parameter_list|,
name|int
modifier|*
name|err
parameter_list|)
block|{
name|TypeArgument
modifier|*
name|res
init|=
operator|(
name|TypeArgument
operator|*
operator|)
literal|0
decl_stmt|;
name|TypeArgument
modifier|*
name|p
decl_stmt|;
if|if
condition|(
name|typ
operator|&&
operator|(
name|typ
operator|->
name|status
operator|&
name|_HAS_ARGS
operator|)
condition|)
block|{
name|assert
argument_list|(
name|err
operator|&&
name|argp
argument_list|)
expr_stmt|;
if|if
condition|(
name|typ
operator|->
name|status
operator|&
name|_LINKED_TYPE
condition|)
block|{
name|p
operator|=
operator|(
name|TypeArgument
operator|*
operator|)
name|malloc
argument_list|(
sizeof|sizeof
argument_list|(
name|TypeArgument
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|p
condition|)
block|{
name|p
operator|->
name|left
operator|=
name|_nc_Copy_Argument
argument_list|(
name|typ
argument_list|,
name|argp
operator|->
name|left
argument_list|,
name|err
argument_list|)
expr_stmt|;
name|p
operator|->
name|right
operator|=
name|_nc_Copy_Argument
argument_list|(
name|typ
argument_list|,
name|argp
operator|->
name|right
argument_list|,
name|err
argument_list|)
expr_stmt|;
return|return
name|p
return|;
block|}
operator|*
name|err
operator|+=
literal|1
expr_stmt|;
block|}
else|else
block|{
if|if
condition|(
name|typ
operator|->
name|copyarg
condition|)
block|{
if|if
condition|(
operator|!
operator|(
name|res
operator|=
operator|(
name|TypeArgument
operator|*
operator|)
operator|(
name|typ
operator|->
name|copyarg
argument_list|(
operator|(
specifier|const
name|void
operator|*
operator|)
name|argp
argument_list|)
operator|)
operator|)
condition|)
operator|*
name|err
operator|+=
literal|1
expr_stmt|;
block|}
else|else
name|res
operator|=
operator|(
name|TypeArgument
operator|*
operator|)
name|argp
expr_stmt|;
block|}
block|}
return|return
name|res
return|;
block|}
end_function

begin_comment
comment|/*--------------------------------------------------------------------------- |   Facility      :  libnform   |   Function      :  void _nc_Free_Argument(const FIELDTYPE *typ, |                                           TypeArgument * argp ) |    |   Description   :  Release memory associated with the argument structure |                    for the given fieldtype. | |   Return Values :  - +--------------------------------------------------------------------------*/
end_comment

begin_function
name|void
name|_nc_Free_Argument
parameter_list|(
specifier|const
name|FIELDTYPE
modifier|*
name|typ
parameter_list|,
name|TypeArgument
modifier|*
name|argp
parameter_list|)
block|{
if|if
condition|(
operator|!
name|typ
operator|||
operator|!
operator|(
name|typ
operator|->
name|status
operator|&
name|_HAS_ARGS
operator|)
condition|)
return|return;
if|if
condition|(
name|typ
operator|->
name|status
operator|&
name|_LINKED_TYPE
condition|)
block|{
name|assert
argument_list|(
name|argp
argument_list|)
expr_stmt|;
name|_nc_Free_Argument
argument_list|(
name|typ
operator|->
name|left
argument_list|,
name|argp
operator|->
name|left
argument_list|)
expr_stmt|;
name|_nc_Free_Argument
argument_list|(
name|typ
operator|->
name|right
argument_list|,
name|argp
operator|->
name|right
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|argp
argument_list|)
expr_stmt|;
block|}
else|else
block|{
if|if
condition|(
name|typ
operator|->
name|freearg
condition|)
name|typ
operator|->
name|freearg
argument_list|(
operator|(
name|void
operator|*
operator|)
name|argp
argument_list|)
expr_stmt|;
block|}
block|}
end_function

begin_comment
comment|/*--------------------------------------------------------------------------- |   Facility      :  libnform   |   Function      :  bool _nc_Copy_Type( FIELD *dst, FIELD const *src ) |    |   Description   :  Copy argument structure of field src to field dst | |   Return Values :  TRUE       - copy worked |                    FALSE      - error occured +--------------------------------------------------------------------------*/
end_comment

begin_function
name|bool
name|_nc_Copy_Type
parameter_list|(
name|FIELD
modifier|*
name|dst
parameter_list|,
name|FIELD
specifier|const
modifier|*
name|src
parameter_list|)
block|{
name|int
name|err
init|=
literal|0
decl_stmt|;
name|assert
argument_list|(
name|dst
operator|&&
name|src
argument_list|)
expr_stmt|;
name|dst
operator|->
name|type
operator|=
name|src
operator|->
name|type
expr_stmt|;
name|dst
operator|->
name|arg
operator|=
operator|(
name|void
operator|*
operator|)
name|_nc_Copy_Argument
argument_list|(
name|src
operator|->
name|type
argument_list|,
operator|(
name|TypeArgument
operator|*
operator|)
operator|(
name|src
operator|->
name|arg
operator|)
argument_list|,
operator|&
name|err
argument_list|)
expr_stmt|;
if|if
condition|(
name|err
condition|)
block|{
name|_nc_Free_Argument
argument_list|(
name|dst
operator|->
name|type
argument_list|,
operator|(
name|TypeArgument
operator|*
operator|)
operator|(
name|dst
operator|->
name|arg
operator|)
argument_list|)
expr_stmt|;
name|dst
operator|->
name|type
operator|=
operator|(
name|FIELDTYPE
operator|*
operator|)
literal|0
expr_stmt|;
name|dst
operator|->
name|arg
operator|=
operator|(
name|void
operator|*
operator|)
literal|0
expr_stmt|;
return|return
name|FALSE
return|;
block|}
else|else
block|{
if|if
condition|(
name|dst
operator|->
name|type
condition|)
name|dst
operator|->
name|type
operator|->
name|ref
operator|++
expr_stmt|;
return|return
name|TRUE
return|;
block|}
block|}
end_function

begin_comment
comment|/*--------------------------------------------------------------------------- |   Facility      :  libnform   |   Function      :  void _nc_Free_Type( FIELD *field ) |    |   Description   :  Release Argument structure for this field | |   Return Values :  - +--------------------------------------------------------------------------*/
end_comment

begin_function
name|void
name|_nc_Free_Type
parameter_list|(
name|FIELD
modifier|*
name|field
parameter_list|)
block|{
name|assert
argument_list|(
name|field
argument_list|)
expr_stmt|;
if|if
condition|(
name|field
operator|->
name|type
condition|)
name|field
operator|->
name|type
operator|->
name|ref
operator|--
expr_stmt|;
name|_nc_Free_Argument
argument_list|(
name|field
operator|->
name|type
argument_list|,
operator|(
name|TypeArgument
operator|*
operator|)
operator|(
name|field
operator|->
name|arg
operator|)
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*--------------------------------------------------------------------------- |   Facility      :  libnform   |   Function      :  FIELD *new_field( int rows, int cols,  |                                      int frow, int fcol, |                                      int nrow, int nbuf ) |    |   Description   :  Create a new field with this many 'rows' and 'cols', |                    starting at 'frow/fcol' in the subwindow of the form. |                    Allocate 'nrow' off-screen rows and 'nbuf' additional |                    buffers. If an error occurs, errno is set to |                     |                    E_BAD_ARGUMENT - invalid argument |                    E_SYSTEM_ERROR - system error | |   Return Values :  Pointer to the new field or NULL if failure. +--------------------------------------------------------------------------*/
end_comment

begin_function
name|FIELD
modifier|*
name|new_field
parameter_list|(
name|int
name|rows
parameter_list|,
name|int
name|cols
parameter_list|,
name|int
name|frow
parameter_list|,
name|int
name|fcol
parameter_list|,
name|int
name|nrow
parameter_list|,
name|int
name|nbuf
parameter_list|)
block|{
name|FIELD
modifier|*
name|New_Field
init|=
operator|(
name|FIELD
operator|*
operator|)
literal|0
decl_stmt|;
name|int
name|err
init|=
name|E_BAD_ARGUMENT
decl_stmt|;
if|if
condition|(
name|rows
operator|>
literal|0
operator|&&
name|cols
operator|>
literal|0
operator|&&
name|frow
operator|>=
literal|0
operator|&&
name|fcol
operator|>=
literal|0
operator|&&
name|nrow
operator|>=
literal|0
operator|&&
name|nbuf
operator|>=
literal|0
operator|&&
operator|(
operator|(
name|err
operator|=
name|E_SYSTEM_ERROR
operator|)
operator|!=
literal|0
operator|)
operator|&&
comment|/* trick: this resets the default error */
operator|(
name|New_Field
operator|=
operator|(
name|FIELD
operator|*
operator|)
name|malloc
argument_list|(
sizeof|sizeof
argument_list|(
name|FIELD
argument_list|)
argument_list|)
operator|)
condition|)
block|{
operator|*
name|New_Field
operator|=
name|default_field
expr_stmt|;
name|New_Field
operator|->
name|rows
operator|=
name|rows
expr_stmt|;
name|New_Field
operator|->
name|cols
operator|=
name|cols
expr_stmt|;
name|New_Field
operator|->
name|drows
operator|=
name|rows
operator|+
name|nrow
expr_stmt|;
name|New_Field
operator|->
name|dcols
operator|=
name|cols
expr_stmt|;
name|New_Field
operator|->
name|frow
operator|=
name|frow
expr_stmt|;
name|New_Field
operator|->
name|fcol
operator|=
name|fcol
expr_stmt|;
name|New_Field
operator|->
name|nrow
operator|=
name|nrow
expr_stmt|;
name|New_Field
operator|->
name|nbuf
operator|=
name|nbuf
expr_stmt|;
name|New_Field
operator|->
name|link
operator|=
name|New_Field
expr_stmt|;
if|if
condition|(
name|_nc_Copy_Type
argument_list|(
name|New_Field
argument_list|,
operator|&
name|default_field
argument_list|)
condition|)
block|{
name|size_t
name|len
decl_stmt|;
name|len
operator|=
name|Total_Buffer_Size
argument_list|(
name|New_Field
argument_list|)
expr_stmt|;
if|if
condition|(
operator|(
name|New_Field
operator|->
name|buf
operator|=
operator|(
name|char
operator|*
operator|)
name|malloc
argument_list|(
name|len
argument_list|)
operator|)
condition|)
block|{
comment|/* Prefill buffers with blanks and insert terminating zeroes 		 between buffers */
name|int
name|i
decl_stmt|;
name|memset
argument_list|(
name|New_Field
operator|->
name|buf
argument_list|,
literal|' '
argument_list|,
name|len
argument_list|)
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<=
name|New_Field
operator|->
name|nbuf
condition|;
name|i
operator|++
control|)
block|{
name|New_Field
operator|->
name|buf
index|[
operator|(
name|New_Field
operator|->
name|drows
operator|*
name|New_Field
operator|->
name|cols
operator|+
literal|1
operator|)
operator|*
operator|(
name|i
operator|+
literal|1
operator|)
operator|-
literal|1
index|]
operator|=
literal|'\0'
expr_stmt|;
block|}
return|return
name|New_Field
return|;
block|}
block|}
block|}
if|if
condition|(
name|New_Field
condition|)
name|free_field
argument_list|(
name|New_Field
argument_list|)
expr_stmt|;
name|SET_ERROR
argument_list|(
name|err
argument_list|)
expr_stmt|;
return|return
operator|(
name|FIELD
operator|*
operator|)
literal|0
return|;
block|}
end_function

begin_comment
comment|/*--------------------------------------------------------------------------- |   Facility      :  libnform   |   Function      :  int free_field( FIELD *field ) |    |   Description   :  Frees the storage allocated for the field. | |   Return Values :  E_OK           - success |                    E_BAD_ARGUMENT - invalid field pointer |                    E_CONNECTED    - field is connected +--------------------------------------------------------------------------*/
end_comment

begin_function
name|int
name|free_field
parameter_list|(
name|FIELD
modifier|*
name|field
parameter_list|)
block|{
if|if
condition|(
operator|!
name|field
condition|)
name|RETURN
argument_list|(
name|E_BAD_ARGUMENT
argument_list|)
expr_stmt|;
if|if
condition|(
name|field
operator|->
name|form
condition|)
name|RETURN
argument_list|(
name|E_CONNECTED
argument_list|)
expr_stmt|;
if|if
condition|(
name|field
operator|==
name|field
operator|->
name|link
condition|)
block|{
if|if
condition|(
name|field
operator|->
name|buf
condition|)
name|free
argument_list|(
name|field
operator|->
name|buf
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|FIELD
modifier|*
name|f
decl_stmt|;
for|for
control|(
name|f
operator|=
name|field
init|;
name|f
operator|->
name|link
operator|!=
name|field
condition|;
name|f
operator|=
name|f
operator|->
name|link
control|)
block|{}
name|f
operator|->
name|link
operator|=
name|field
operator|->
name|link
expr_stmt|;
block|}
name|_nc_Free_Type
argument_list|(
name|field
argument_list|)
expr_stmt|;
name|free
argument_list|(
name|field
argument_list|)
expr_stmt|;
name|RETURN
argument_list|(
name|E_OK
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/* fld_def.c ends here */
end_comment

end_unit

