begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*	$NetBSD: t_timer_create.c,v 1.4 2012/03/18 07:00:52 jruoho Exp $ */
end_comment

begin_comment
comment|/*-  * Copyright (c) 2010 The NetBSD Foundation, Inc.  * All rights reserved.  *  * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions  * are met:  * 1. Redistributions of source code must retain the above copyright  *    notice, this list of conditions and the following disclaimer.  * 2. Redistributions in binary form must reproduce the above copyright  *    notice, this list of conditions and the following disclaimer in the  *    documentation and/or other materials provided with the distribution.  *  * THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS  * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED  * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR  * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS  * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR  * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF  * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS  * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN  * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)  * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE  * POSSIBILITY OF SUCH DAMAGE.  */
end_comment

begin_include
include|#
directive|include
file|<atf-c.h>
end_include

begin_include
include|#
directive|include
file|<errno.h>
end_include

begin_include
include|#
directive|include
file|<stdio.h>
end_include

begin_include
include|#
directive|include
file|<signal.h>
end_include

begin_include
include|#
directive|include
file|<string.h>
end_include

begin_include
include|#
directive|include
file|<time.h>
end_include

begin_include
include|#
directive|include
file|<unistd.h>
end_include

begin_decl_stmt
specifier|static
name|timer_t
name|t
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|bool
name|fail
init|=
name|true
decl_stmt|;
end_decl_stmt

begin_function
specifier|static
name|void
if|#
directive|if
name|defined
argument_list|(
name|__FreeBSD__
argument_list|)
name|timer_signal_handler
parameter_list|(
name|int
name|signo
parameter_list|,
name|siginfo_t
modifier|*
name|si
parameter_list|,
name|void
modifier|*
name|osi
name|__unused
parameter_list|)
else|#
directive|else
function|timer_signal_handler
parameter_list|(
name|int
name|signo
parameter_list|,
name|siginfo_t
modifier|*
name|si
parameter_list|,
name|void
modifier|*
name|osi
parameter_list|)
endif|#
directive|endif
block|{
name|timer_t
modifier|*
name|tp
decl_stmt|;
name|tp
operator|=
name|si
operator|->
name|si_value
operator|.
name|sival_ptr
expr_stmt|;
if|if
condition|(
operator|*
name|tp
operator|==
name|t
operator|&&
name|signo
operator|==
name|SIGALRM
condition|)
name|fail
operator|=
name|false
expr_stmt|;
operator|(
name|void
operator|)
name|fprintf
argument_list|(
name|stderr
argument_list|,
literal|"%s: %s\n"
argument_list|,
name|__func__
argument_list|,
name|strsignal
argument_list|(
name|signo
argument_list|)
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
name|timer_signal_create
parameter_list|(
name|clockid_t
name|cid
parameter_list|,
name|bool
name|expire
parameter_list|)
block|{
name|struct
name|itimerspec
name|tim
decl_stmt|;
name|struct
name|sigaction
name|act
decl_stmt|;
name|struct
name|sigevent
name|evt
decl_stmt|;
name|sigset_t
name|set
decl_stmt|;
name|t
operator|=
literal|0
expr_stmt|;
name|fail
operator|=
name|true
expr_stmt|;
operator|(
name|void
operator|)
name|memset
argument_list|(
operator|&
name|evt
argument_list|,
literal|0
argument_list|,
sizeof|sizeof
argument_list|(
expr|struct
name|sigevent
argument_list|)
argument_list|)
expr_stmt|;
operator|(
name|void
operator|)
name|memset
argument_list|(
operator|&
name|act
argument_list|,
literal|0
argument_list|,
sizeof|sizeof
argument_list|(
expr|struct
name|sigaction
argument_list|)
argument_list|)
expr_stmt|;
operator|(
name|void
operator|)
name|memset
argument_list|(
operator|&
name|tim
argument_list|,
literal|0
argument_list|,
sizeof|sizeof
argument_list|(
expr|struct
name|itimerspec
argument_list|)
argument_list|)
expr_stmt|;
comment|/* 	 * Set handler. 	 */
name|act
operator|.
name|sa_flags
operator|=
name|SA_SIGINFO
expr_stmt|;
name|act
operator|.
name|sa_sigaction
operator|=
name|timer_signal_handler
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|sigemptyset
argument_list|(
operator|&
name|set
argument_list|)
operator|==
literal|0
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|sigemptyset
argument_list|(
operator|&
name|act
operator|.
name|sa_mask
argument_list|)
operator|==
literal|0
argument_list|)
expr_stmt|;
comment|/* 	 * Block SIGALRM while configuring the timer. 	 */
name|ATF_REQUIRE
argument_list|(
name|sigaction
argument_list|(
name|SIGALRM
argument_list|,
operator|&
name|act
argument_list|,
name|NULL
argument_list|)
operator|==
literal|0
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|sigaddset
argument_list|(
operator|&
name|set
argument_list|,
name|SIGALRM
argument_list|)
operator|==
literal|0
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|sigprocmask
argument_list|(
name|SIG_SETMASK
argument_list|,
operator|&
name|set
argument_list|,
name|NULL
argument_list|)
operator|==
literal|0
argument_list|)
expr_stmt|;
comment|/* 	 * Create the timer (SIGEV_SIGNAL). 	 */
name|evt
operator|.
name|sigev_signo
operator|=
name|SIGALRM
expr_stmt|;
name|evt
operator|.
name|sigev_value
operator|.
name|sival_ptr
operator|=
operator|&
name|t
expr_stmt|;
name|evt
operator|.
name|sigev_notify
operator|=
name|SIGEV_SIGNAL
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|timer_create
argument_list|(
name|cid
argument_list|,
operator|&
name|evt
argument_list|,
operator|&
name|t
argument_list|)
operator|==
literal|0
argument_list|)
expr_stmt|;
comment|/* 	 * Start the timer. After this, unblock the signal. 	 */
name|tim
operator|.
name|it_value
operator|.
name|tv_sec
operator|=
name|expire
condition|?
literal|5
else|:
literal|1
expr_stmt|;
name|tim
operator|.
name|it_value
operator|.
name|tv_nsec
operator|=
literal|0
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|timer_settime
argument_list|(
name|t
argument_list|,
literal|0
argument_list|,
operator|&
name|tim
argument_list|,
name|NULL
argument_list|)
operator|==
literal|0
argument_list|)
expr_stmt|;
operator|(
name|void
operator|)
name|sigprocmask
argument_list|(
name|SIG_UNBLOCK
argument_list|,
operator|&
name|set
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
operator|(
name|void
operator|)
name|sleep
argument_list|(
literal|2
argument_list|)
expr_stmt|;
if|if
condition|(
name|expire
condition|)
block|{
if|if
condition|(
operator|!
name|fail
condition|)
name|atf_tc_fail
argument_list|(
literal|"timer fired too soon"
argument_list|)
expr_stmt|;
block|}
else|else
block|{
if|if
condition|(
name|fail
condition|)
name|atf_tc_fail
argument_list|(
literal|"timer failed to fire"
argument_list|)
expr_stmt|;
block|}
name|ATF_REQUIRE
argument_list|(
name|timer_delete
argument_list|(
name|t
argument_list|)
operator|==
literal|0
argument_list|)
expr_stmt|;
block|}
end_function

begin_expr_stmt
name|ATF_TC
argument_list|(
name|timer_create_err
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|timer_create_err
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Check errors from timer_create(2) (PR lib/42434"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|timer_create_err
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|struct
name|sigevent
name|ev
decl_stmt|;
operator|(
name|void
operator|)
name|memset
argument_list|(
operator|&
name|ev
argument_list|,
literal|0
argument_list|,
sizeof|sizeof
argument_list|(
expr|struct
name|sigevent
argument_list|)
argument_list|)
expr_stmt|;
name|errno
operator|=
literal|0
expr_stmt|;
name|ev
operator|.
name|sigev_signo
operator|=
operator|-
literal|1
expr_stmt|;
name|ev
operator|.
name|sigev_notify
operator|=
name|SIGEV_SIGNAL
expr_stmt|;
name|ATF_REQUIRE_ERRNO
argument_list|(
name|EINVAL
argument_list|,
name|timer_create
argument_list|(
name|CLOCK_REALTIME
argument_list|,
operator|&
name|ev
argument_list|,
operator|&
name|t
argument_list|)
operator|==
operator|-
literal|1
argument_list|)
expr_stmt|;
name|errno
operator|=
literal|0
expr_stmt|;
name|ev
operator|.
name|sigev_signo
operator|=
name|SIGUSR1
expr_stmt|;
name|ev
operator|.
name|sigev_notify
operator|=
name|SIGEV_THREAD
operator|+
literal|100
expr_stmt|;
name|ATF_REQUIRE_ERRNO
argument_list|(
name|EINVAL
argument_list|,
name|timer_create
argument_list|(
name|CLOCK_REALTIME
argument_list|,
operator|&
name|ev
argument_list|,
operator|&
name|t
argument_list|)
operator|==
operator|-
literal|1
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|timer_create_real
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|timer_create_real
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Checks timer_create(2) with CLOCK_REALTIME and sigevent(3), "
literal|"SIGEV_SIGNAL"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|timer_create_real
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|timer_signal_create
argument_list|(
name|CLOCK_REALTIME
argument_list|,
name|false
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|timer_create_mono
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|timer_create_mono
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Checks timer_create(2) with CLOCK_MONOTONIC and sigevent(3), "
literal|"SIGEV_SIGNAL"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|timer_create_mono
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|timer_signal_create
argument_list|(
name|CLOCK_MONOTONIC
argument_list|,
name|false
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|timer_create_real_expire
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|timer_create_real_expire
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Checks timer_create(2) with CLOCK_REALTIME and sigevent(3), "
literal|"SIGEV_SIGNAL, with expiration"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|timer_create_real_expire
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|timer_signal_create
argument_list|(
name|CLOCK_REALTIME
argument_list|,
name|true
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|timer_create_mono_expire
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|timer_create_mono_expire
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Checks timer_create(2) with CLOCK_MONOTONIC and sigevent(3), "
literal|"SIGEV_SIGNAL, with expiration"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|timer_create_mono_expire
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|timer_signal_create
argument_list|(
name|CLOCK_MONOTONIC
argument_list|,
name|true
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TP_ADD_TCS
argument_list|(
argument|tp
argument_list|)
end_macro

begin_block
block|{
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|timer_create_err
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|timer_create_real
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|timer_create_mono
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|timer_create_real_expire
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|timer_create_mono_expire
argument_list|)
expr_stmt|;
return|return
name|atf_no_error
argument_list|()
return|;
block|}
end_block

end_unit

