begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* $NetBSD: t_unlink.c,v 1.2 2014/04/21 18:05:17 martin Exp $ */
end_comment

begin_comment
comment|/*-  * Copyright (c) 2011 The NetBSD Foundation, Inc.  * All rights reserved.  *  * This code is derived from software contributed to The NetBSD Foundation  * by Jukka Ruohonen.  *  * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions  * are met:  * 1. Redistributions of source code must retain the above copyright  *    notice, this list of conditions and the following disclaimer.  * 2. Redistributions in binary form must reproduce the above copyright  *    notice, this list of conditions and the following disclaimer in the  *    documentation and/or other materials provided with the distribution.  *  * THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS  * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED  * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR  * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS  * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR  * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF  * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS  * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN  * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)  * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE  * POSSIBILITY OF SUCH DAMAGE.  */
end_comment

begin_include
include|#
directive|include
file|<sys/cdefs.h>
end_include

begin_expr_stmt
name|__RCSID
argument_list|(
literal|"$NetBSD: t_unlink.c,v 1.2 2014/04/21 18:05:17 martin Exp $"
argument_list|)
expr_stmt|;
end_expr_stmt

begin_include
include|#
directive|include
file|<sys/stat.h>
end_include

begin_include
include|#
directive|include
file|<atf-c.h>
end_include

begin_include
include|#
directive|include
file|<errno.h>
end_include

begin_include
include|#
directive|include
file|<fcntl.h>
end_include

begin_include
include|#
directive|include
file|<limits.h>
end_include

begin_include
include|#
directive|include
file|<string.h>
end_include

begin_include
include|#
directive|include
file|<unistd.h>
end_include

begin_decl_stmt
specifier|static
name|char
name|path
index|[]
init|=
literal|"unlink"
decl_stmt|;
end_decl_stmt

begin_expr_stmt
name|ATF_TC_WITH_CLEANUP
argument_list|(
name|unlink_basic
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|unlink_basic
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"A basic test of unlink(2)"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|unlink_basic
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
specifier|const
name|size_t
name|n
init|=
literal|512
decl_stmt|;
name|size_t
name|i
decl_stmt|;
name|int
name|fd
decl_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
name|n
condition|;
name|i
operator|++
control|)
block|{
name|fd
operator|=
name|open
argument_list|(
name|path
argument_list|,
name|O_RDWR
operator||
name|O_CREAT
argument_list|,
literal|0666
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|fd
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|close
argument_list|(
name|fd
argument_list|)
operator|==
literal|0
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|unlink
argument_list|(
name|path
argument_list|)
operator|==
literal|0
argument_list|)
expr_stmt|;
name|errno
operator|=
literal|0
expr_stmt|;
name|ATF_REQUIRE_ERRNO
argument_list|(
name|ENOENT
argument_list|,
name|open
argument_list|(
name|path
argument_list|,
name|O_RDONLY
argument_list|)
operator|==
operator|-
literal|1
argument_list|)
expr_stmt|;
block|}
block|}
end_block

begin_macro
name|ATF_TC_CLEANUP
argument_list|(
argument|unlink_basic
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
operator|(
name|void
operator|)
name|unlink
argument_list|(
name|path
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC_WITH_CLEANUP
argument_list|(
name|unlink_err
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|unlink_err
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Test error conditions of unlink(2)"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|unlink_err
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|char
name|buf
index|[
name|PATH_MAX
operator|+
literal|1
index|]
decl_stmt|;
operator|(
name|void
operator|)
name|memset
argument_list|(
name|buf
argument_list|,
literal|'x'
argument_list|,
sizeof|sizeof
argument_list|(
name|buf
argument_list|)
argument_list|)
expr_stmt|;
name|errno
operator|=
literal|0
expr_stmt|;
if|#
directive|if
name|defined
argument_list|(
name|__FreeBSD__
argument_list|)
name|ATF_REQUIRE_ERRNO
argument_list|(
name|EISDIR
argument_list|,
name|unlink
argument_list|(
literal|"/"
argument_list|)
operator|==
operator|-
literal|1
argument_list|)
expr_stmt|;
else|#
directive|else
name|ATF_REQUIRE_ERRNO
argument_list|(
name|EBUSY
argument_list|,
name|unlink
argument_list|(
literal|"/"
argument_list|)
operator|==
operator|-
literal|1
argument_list|)
expr_stmt|;
endif|#
directive|endif
name|errno
operator|=
literal|0
expr_stmt|;
name|ATF_REQUIRE_ERRNO
argument_list|(
name|ENAMETOOLONG
argument_list|,
name|unlink
argument_list|(
name|buf
argument_list|)
operator|==
operator|-
literal|1
argument_list|)
expr_stmt|;
name|errno
operator|=
literal|0
expr_stmt|;
name|ATF_REQUIRE_ERRNO
argument_list|(
name|ENOENT
argument_list|,
name|unlink
argument_list|(
literal|"/a/b/c/d/e/f/g/h/i/j/k/l/m"
argument_list|)
operator|==
operator|-
literal|1
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_CLEANUP
argument_list|(
argument|unlink_err
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
operator|(
name|void
operator|)
name|unlink
argument_list|(
name|path
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC_WITH_CLEANUP
argument_list|(
name|unlink_fifo
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|unlink_fifo
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Test unlink(2) for a FIFO"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|unlink_fifo
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|ATF_REQUIRE
argument_list|(
name|mkfifo
argument_list|(
name|path
argument_list|,
literal|0666
argument_list|)
operator|==
literal|0
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|unlink
argument_list|(
name|path
argument_list|)
operator|==
literal|0
argument_list|)
expr_stmt|;
name|errno
operator|=
literal|0
expr_stmt|;
name|ATF_REQUIRE_ERRNO
argument_list|(
name|ENOENT
argument_list|,
name|open
argument_list|(
name|path
argument_list|,
name|O_RDONLY
argument_list|)
operator|==
operator|-
literal|1
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_CLEANUP
argument_list|(
argument|unlink_fifo
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
operator|(
name|void
operator|)
name|unlink
argument_list|(
name|path
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC_WITH_CLEANUP
argument_list|(
name|unlink_perm
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|unlink_perm
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Test permissions with unlink(2)"
argument_list|)
expr_stmt|;
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"require.user"
argument_list|,
literal|"unprivileged"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|unlink_perm
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|int
name|rv
decl_stmt|;
name|errno
operator|=
literal|0
expr_stmt|;
name|rv
operator|=
name|unlink
argument_list|(
literal|"/etc"
argument_list|)
expr_stmt|;
name|ATF_REQUIRE_MSG
argument_list|(
name|rv
operator|==
operator|-
literal|1
operator|&&
operator|(
name|errno
operator|==
name|EACCES
operator|||
name|errno
operator|==
name|EPERM
operator|)
argument_list|,
literal|"unlinking a directory did not fail with EPERM or EACCESS; "
literal|"unlink() returned %d, errno %d"
argument_list|,
name|rv
argument_list|,
name|errno
argument_list|)
expr_stmt|;
name|errno
operator|=
literal|0
expr_stmt|;
name|ATF_REQUIRE_ERRNO
argument_list|(
name|EACCES
argument_list|,
name|unlink
argument_list|(
literal|"/root/.profile"
argument_list|)
operator|==
operator|-
literal|1
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_CLEANUP
argument_list|(
argument|unlink_perm
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
operator|(
name|void
operator|)
name|unlink
argument_list|(
name|path
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TP_ADD_TCS
argument_list|(
argument|tp
argument_list|)
end_macro

begin_block
block|{
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|unlink_basic
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|unlink_err
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|unlink_fifo
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|unlink_perm
argument_list|)
expr_stmt|;
return|return
name|atf_no_error
argument_list|()
return|;
block|}
end_block

end_unit

