begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/******************************************************************************  *  * Module Name: aslanalyze.c - Support functions for parse tree walks  *  *****************************************************************************/
end_comment

begin_comment
comment|/******************************************************************************  *  * 1. Copyright Notice  *  * Some or all of this work - Copyright (c) 1999 - 2017, Intel Corp.  * All rights reserved.  *  * 2. License  *  * 2.1. This is your license from Intel Corp. under its intellectual property  * rights. You may have additional license terms from the party that provided  * you this software, covering your right to use that party's intellectual  * property rights.  *  * 2.2. Intel grants, free of charge, to any person ("Licensee") obtaining a  * copy of the source code appearing in this file ("Covered Code") an  * irrevocable, perpetual, worldwide license under Intel's copyrights in the  * base code distributed originally by Intel ("Original Intel Code") to copy,  * make derivatives, distribute, use and display any portion of the Covered  * Code in any form, with the right to sublicense such rights; and  *  * 2.3. Intel grants Licensee a non-exclusive and non-transferable patent  * license (with the right to sublicense), under only those claims of Intel  * patents that are infringed by the Original Intel Code, to make, use, sell,  * offer to sell, and import the Covered Code and derivative works thereof  * solely to the minimum extent necessary to exercise the above copyright  * license, and in no event shall the patent license extend to any additions  * to or modifications of the Original Intel Code. No other license or right  * is granted directly or by implication, estoppel or otherwise;  *  * The above copyright and patent license is granted only if the following  * conditions are met:  *  * 3. Conditions  *  * 3.1. Redistribution of Source with Rights to Further Distribute Source.  * Redistribution of source code of any substantial portion of the Covered  * Code or modification with rights to further distribute source must include  * the above Copyright Notice, the above License, this list of Conditions,  * and the following Disclaimer and Export Compliance provision. In addition,  * Licensee must cause all Covered Code to which Licensee contributes to  * contain a file documenting the changes Licensee made to create that Covered  * Code and the date of any change. Licensee must include in that file the  * documentation of any changes made by any predecessor Licensee. Licensee  * must include a prominent statement that the modification is derived,  * directly or indirectly, from Original Intel Code.  *  * 3.2. Redistribution of Source with no Rights to Further Distribute Source.  * Redistribution of source code of any substantial portion of the Covered  * Code or modification without rights to further distribute source must  * include the following Disclaimer and Export Compliance provision in the  * documentation and/or other materials provided with distribution. In  * addition, Licensee may not authorize further sublicense of source of any  * portion of the Covered Code, and must include terms to the effect that the  * license from Licensee to its licensee is limited to the intellectual  * property embodied in the software Licensee provides to its licensee, and  * not to intellectual property embodied in modifications its licensee may  * make.  *  * 3.3. Redistribution of Executable. Redistribution in executable form of any  * substantial portion of the Covered Code or modification must reproduce the  * above Copyright Notice, and the following Disclaimer and Export Compliance  * provision in the documentation and/or other materials provided with the  * distribution.  *  * 3.4. Intel retains all right, title, and interest in and to the Original  * Intel Code.  *  * 3.5. Neither the name Intel nor any other trademark owned or controlled by  * Intel shall be used in advertising or otherwise to promote the sale, use or  * other dealings in products derived from or relating to the Covered Code  * without prior written authorization from Intel.  *  * 4. Disclaimer and Export Compliance  *  * 4.1. INTEL MAKES NO WARRANTY OF ANY KIND REGARDING ANY SOFTWARE PROVIDED  * HERE. ANY SOFTWARE ORIGINATING FROM INTEL OR DERIVED FROM INTEL SOFTWARE  * IS PROVIDED "AS IS," AND INTEL WILL NOT PROVIDE ANY SUPPORT, ASSISTANCE,  * INSTALLATION, TRAINING OR OTHER SERVICES. INTEL WILL NOT PROVIDE ANY  * UPDATES, ENHANCEMENTS OR EXTENSIONS. INTEL SPECIFICALLY DISCLAIMS ANY  * IMPLIED WARRANTIES OF MERCHANTABILITY, NONINFRINGEMENT AND FITNESS FOR A  * PARTICULAR PURPOSE.  *  * 4.2. IN NO EVENT SHALL INTEL HAVE ANY LIABILITY TO LICENSEE, ITS LICENSEES  * OR ANY OTHER THIRD PARTY, FOR ANY LOST PROFITS, LOST DATA, LOSS OF USE OR  * COSTS OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, OR FOR ANY INDIRECT,  * SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THIS AGREEMENT, UNDER ANY  * CAUSE OF ACTION OR THEORY OF LIABILITY, AND IRRESPECTIVE OF WHETHER INTEL  * HAS ADVANCE NOTICE OF THE POSSIBILITY OF SUCH DAMAGES. THESE LIMITATIONS  * SHALL APPLY NOTWITHSTANDING THE FAILURE OF THE ESSENTIAL PURPOSE OF ANY  * LIMITED REMEDY.  *  * 4.3. Licensee shall not export, either directly or indirectly, any of this  * software or system incorporating such software without first obtaining any  * required license or other approval from the U. S. Department of Commerce or  * any other agency or department of the United States Government. In the  * event Licensee exports any such software from the United States or  * re-exports any such software from a foreign destination, Licensee shall  * ensure that the distribution and export/re-export of the software is in  * compliance with all laws, regulations, orders, or other restrictions of the  * U.S. Export Administration Regulations. Licensee agrees that neither it nor  * any of its subsidiaries will export/re-export any technical data, process,  * software, or service, directly or indirectly, to any country for which the  * United States government or any agency thereof requires an export license,  * other governmental approval, or letter of assurance, without first obtaining  * such license, approval or letter.  *  *****************************************************************************  *  * Alternatively, you may choose to be licensed under the terms of the  * following license:  *  * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions  * are met:  * 1. Redistributions of source code must retain the above copyright  *    notice, this list of conditions, and the following disclaimer,  *    without modification.  * 2. Redistributions in binary form must reproduce at minimum a disclaimer  *    substantially similar to the "NO WARRANTY" disclaimer below  *    ("Disclaimer") and any redistribution must be conditioned upon  *    including a substantially similar Disclaimer requirement for further  *    binary redistribution.  * 3. Neither the names of the above-listed copyright holders nor the names  *    of any contributors may be used to endorse or promote products derived  *    from this software without specific prior written permission.  *  * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS  * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT  * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR  * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT  * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,  * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT  * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,  * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY  * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT  * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE  * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.  *  * Alternatively, you may choose to be licensed under the terms of the  * GNU General Public License ("GPL") version 2 as published by the Free  * Software Foundation.  *  *****************************************************************************/
end_comment

begin_include
include|#
directive|include
file|<contrib/dev/acpica/compiler/aslcompiler.h>
end_include

begin_include
include|#
directive|include
file|"aslcompiler.y.h"
end_include

begin_include
include|#
directive|include
file|<string.h>
end_include

begin_define
define|#
directive|define
name|_COMPONENT
value|ACPI_COMPILER
end_define

begin_macro
name|ACPI_MODULE_NAME
argument_list|(
literal|"aslanalyze"
argument_list|)
end_macro

begin_comment
comment|/* Local Prototypes */
end_comment

begin_function_decl
specifier|static
name|ACPI_STATUS
name|ApDeviceSubtreeWalk
parameter_list|(
name|ACPI_PARSE_OBJECT
modifier|*
name|Op
parameter_list|,
name|UINT32
name|Level
parameter_list|,
name|void
modifier|*
name|Context
parameter_list|)
function_decl|;
end_function_decl

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    AnIsInternalMethod  *  * PARAMETERS:  Op                  - Current op  *  * RETURN:      Boolean  *  * DESCRIPTION: Check for an internal control method.  *  ******************************************************************************/
end_comment

begin_function
name|BOOLEAN
name|AnIsInternalMethod
parameter_list|(
name|ACPI_PARSE_OBJECT
modifier|*
name|Op
parameter_list|)
block|{
if|if
condition|(
operator|(
operator|!
name|strcmp
argument_list|(
name|Op
operator|->
name|Asl
operator|.
name|ExternalName
argument_list|,
literal|"\\_OSI"
argument_list|)
operator|)
operator|||
operator|(
operator|!
name|strcmp
argument_list|(
name|Op
operator|->
name|Asl
operator|.
name|ExternalName
argument_list|,
literal|"_OSI"
argument_list|)
operator|)
condition|)
block|{
return|return
operator|(
name|TRUE
operator|)
return|;
block|}
return|return
operator|(
name|FALSE
operator|)
return|;
block|}
end_function

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    AnGetInternalMethodReturnType  *  * PARAMETERS:  Op                  - Current op  *  * RETURN:      Btype  *  * DESCRIPTION: Get the return type of an internal method  *  ******************************************************************************/
end_comment

begin_function
name|UINT32
name|AnGetInternalMethodReturnType
parameter_list|(
name|ACPI_PARSE_OBJECT
modifier|*
name|Op
parameter_list|)
block|{
if|if
condition|(
operator|(
operator|!
name|strcmp
argument_list|(
name|Op
operator|->
name|Asl
operator|.
name|ExternalName
argument_list|,
literal|"\\_OSI"
argument_list|)
operator|)
operator|||
operator|(
operator|!
name|strcmp
argument_list|(
name|Op
operator|->
name|Asl
operator|.
name|ExternalName
argument_list|,
literal|"_OSI"
argument_list|)
operator|)
condition|)
block|{
return|return
operator|(
name|ACPI_BTYPE_STRING
operator|)
return|;
block|}
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    AnCheckId  *  * PARAMETERS:  Op                  - Current parse op  *              Type                - HID or CID  *  * RETURN:      None  *  * DESCRIPTION: Perform various checks on _HID and _CID strings. Only limited  *              checks can be performed on _CID strings.  *  ******************************************************************************/
end_comment

begin_function
name|void
name|AnCheckId
parameter_list|(
name|ACPI_PARSE_OBJECT
modifier|*
name|Op
parameter_list|,
name|ACPI_NAME
name|Type
parameter_list|)
block|{
name|UINT32
name|i
decl_stmt|;
name|ACPI_SIZE
name|Length
decl_stmt|;
comment|/* Only care about string versions of _HID/_CID (integers are legal) */
if|if
condition|(
name|Op
operator|->
name|Asl
operator|.
name|ParseOpcode
operator|!=
name|PARSEOP_STRING_LITERAL
condition|)
block|{
return|return;
block|}
comment|/* For both _HID and _CID, the string must be non-null */
name|Length
operator|=
name|strlen
argument_list|(
name|Op
operator|->
name|Asl
operator|.
name|Value
operator|.
name|String
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|Length
condition|)
block|{
name|AslError
argument_list|(
name|ASL_ERROR
argument_list|,
name|ASL_MSG_NULL_STRING
argument_list|,
name|Op
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
return|return;
block|}
comment|/*      * One of the things we want to catch here is the use of a leading      * asterisk in the string -- an odd construct that certain platform      * manufacturers are fond of. Technically, a leading asterisk is OK      * for _CID, but a valid use of this has not been seen.      */
if|if
condition|(
operator|*
name|Op
operator|->
name|Asl
operator|.
name|Value
operator|.
name|String
operator|==
literal|'*'
condition|)
block|{
name|AslError
argument_list|(
name|ASL_ERROR
argument_list|,
name|ASL_MSG_LEADING_ASTERISK
argument_list|,
name|Op
argument_list|,
name|Op
operator|->
name|Asl
operator|.
name|Value
operator|.
name|String
argument_list|)
expr_stmt|;
return|return;
block|}
comment|/* _CID strings are bus-specific, no more checks can be performed */
if|if
condition|(
name|Type
operator|==
name|ASL_TYPE_CID
condition|)
block|{
return|return;
block|}
comment|/* For _HID, all characters must be alphanumeric */
for|for
control|(
name|i
operator|=
literal|0
init|;
name|Op
operator|->
name|Asl
operator|.
name|Value
operator|.
name|String
index|[
name|i
index|]
condition|;
name|i
operator|++
control|)
block|{
if|if
condition|(
operator|!
name|isalnum
argument_list|(
operator|(
name|int
operator|)
name|Op
operator|->
name|Asl
operator|.
name|Value
operator|.
name|String
index|[
name|i
index|]
argument_list|)
condition|)
block|{
name|AslError
argument_list|(
name|ASL_ERROR
argument_list|,
name|ASL_MSG_ALPHANUMERIC_STRING
argument_list|,
name|Op
argument_list|,
name|Op
operator|->
name|Asl
operator|.
name|Value
operator|.
name|String
argument_list|)
expr_stmt|;
return|return;
block|}
block|}
comment|/*      * _HID String must be one of these forms:      *      * "AAA####"    A is an uppercase letter and # is a hex digit      * "ACPI####"   # is a hex digit      * "NNNN####"   N is an uppercase letter or decimal digit (0-9)      *              # is a hex digit (ACPI 5.0)      */
if|if
condition|(
operator|(
name|Length
operator|<
literal|7
operator|)
operator|||
operator|(
name|Length
operator|>
literal|8
operator|)
condition|)
block|{
name|AslError
argument_list|(
name|ASL_ERROR
argument_list|,
name|ASL_MSG_HID_LENGTH
argument_list|,
name|Op
argument_list|,
name|Op
operator|->
name|Asl
operator|.
name|Value
operator|.
name|String
argument_list|)
expr_stmt|;
return|return;
block|}
comment|/* _HID Length is valid (7 or 8), now check prefix (first 3 or 4 chars) */
if|if
condition|(
name|Length
operator|==
literal|7
condition|)
block|{
comment|/* AAA####: Ensure the alphabetic prefix is all uppercase */
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
literal|3
condition|;
name|i
operator|++
control|)
block|{
if|if
condition|(
operator|!
name|isupper
argument_list|(
operator|(
name|int
operator|)
name|Op
operator|->
name|Asl
operator|.
name|Value
operator|.
name|String
index|[
name|i
index|]
argument_list|)
condition|)
block|{
name|AslError
argument_list|(
name|ASL_ERROR
argument_list|,
name|ASL_MSG_UPPER_CASE
argument_list|,
name|Op
argument_list|,
operator|&
name|Op
operator|->
name|Asl
operator|.
name|Value
operator|.
name|String
index|[
name|i
index|]
argument_list|)
expr_stmt|;
return|return;
block|}
block|}
block|}
else|else
comment|/* Length == 8 */
block|{
comment|/*          * ACPI#### or NNNN####:          * Ensure the prefix contains only uppercase alpha or decimal digits          */
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
literal|4
condition|;
name|i
operator|++
control|)
block|{
if|if
condition|(
operator|!
name|isupper
argument_list|(
operator|(
name|int
operator|)
name|Op
operator|->
name|Asl
operator|.
name|Value
operator|.
name|String
index|[
name|i
index|]
argument_list|)
operator|&&
operator|!
name|isdigit
argument_list|(
operator|(
name|int
operator|)
name|Op
operator|->
name|Asl
operator|.
name|Value
operator|.
name|String
index|[
name|i
index|]
argument_list|)
condition|)
block|{
name|AslError
argument_list|(
name|ASL_ERROR
argument_list|,
name|ASL_MSG_HID_PREFIX
argument_list|,
name|Op
argument_list|,
operator|&
name|Op
operator|->
name|Asl
operator|.
name|Value
operator|.
name|String
index|[
name|i
index|]
argument_list|)
expr_stmt|;
return|return;
block|}
block|}
block|}
comment|/* Remaining characters (suffix) must be hex digits */
for|for
control|(
init|;
name|i
operator|<
name|Length
condition|;
name|i
operator|++
control|)
block|{
if|if
condition|(
operator|!
name|isxdigit
argument_list|(
operator|(
name|int
operator|)
name|Op
operator|->
name|Asl
operator|.
name|Value
operator|.
name|String
index|[
name|i
index|]
argument_list|)
condition|)
block|{
name|AslError
argument_list|(
name|ASL_ERROR
argument_list|,
name|ASL_MSG_HID_SUFFIX
argument_list|,
name|Op
argument_list|,
operator|&
name|Op
operator|->
name|Asl
operator|.
name|Value
operator|.
name|String
index|[
name|i
index|]
argument_list|)
expr_stmt|;
break|break;
block|}
block|}
block|}
end_function

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    AnLastStatementIsReturn  *  * PARAMETERS:  Op                  - A method parse node  *  * RETURN:      TRUE if last statement is an ASL RETURN. False otherwise  *  * DESCRIPTION: Walk down the list of top level statements within a method  *              to find the last one. Check if that last statement is in  *              fact a RETURN statement.  *  ******************************************************************************/
end_comment

begin_function
name|BOOLEAN
name|AnLastStatementIsReturn
parameter_list|(
name|ACPI_PARSE_OBJECT
modifier|*
name|Op
parameter_list|)
block|{
name|ACPI_PARSE_OBJECT
modifier|*
name|Next
decl_stmt|;
comment|/* Check if last statement is a return */
name|Next
operator|=
name|ASL_GET_CHILD_NODE
argument_list|(
name|Op
argument_list|)
expr_stmt|;
while|while
condition|(
name|Next
condition|)
block|{
if|if
condition|(
operator|(
operator|!
name|Next
operator|->
name|Asl
operator|.
name|Next
operator|)
operator|&&
operator|(
name|Next
operator|->
name|Asl
operator|.
name|ParseOpcode
operator|==
name|PARSEOP_RETURN
operator|)
condition|)
block|{
return|return
operator|(
name|TRUE
operator|)
return|;
block|}
name|Next
operator|=
name|ASL_GET_PEER_NODE
argument_list|(
name|Next
argument_list|)
expr_stmt|;
block|}
return|return
operator|(
name|FALSE
operator|)
return|;
block|}
end_function

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    AnCheckMethodReturnValue  *  * PARAMETERS:  Op                  - Parent  *              OpInfo              - Parent info  *              ArgOp               - Method invocation op  *              RequiredBtypes      - What caller requires  *              ThisNodeBtype       - What this node returns (if anything)  *  * RETURN:      None  *  * DESCRIPTION: Check a method invocation for 1) A return value and if it does  *              in fact return a value, 2) check the type of the return value.  *  ******************************************************************************/
end_comment

begin_function
name|void
name|AnCheckMethodReturnValue
parameter_list|(
name|ACPI_PARSE_OBJECT
modifier|*
name|Op
parameter_list|,
specifier|const
name|ACPI_OPCODE_INFO
modifier|*
name|OpInfo
parameter_list|,
name|ACPI_PARSE_OBJECT
modifier|*
name|ArgOp
parameter_list|,
name|UINT32
name|RequiredBtypes
parameter_list|,
name|UINT32
name|ThisNodeBtype
parameter_list|)
block|{
name|ACPI_PARSE_OBJECT
modifier|*
name|OwningOp
decl_stmt|;
name|ACPI_NAMESPACE_NODE
modifier|*
name|Node
decl_stmt|;
name|Node
operator|=
name|ArgOp
operator|->
name|Asl
operator|.
name|Node
expr_stmt|;
if|if
condition|(
operator|!
name|Node
condition|)
block|{
comment|/* No error message, this can happen and is OK */
return|return;
block|}
comment|/* Examine the parent op of this method */
name|OwningOp
operator|=
name|Node
operator|->
name|Op
expr_stmt|;
if|if
condition|(
name|OwningOp
operator|->
name|Asl
operator|.
name|CompileFlags
operator|&
name|OP_METHOD_NO_RETVAL
condition|)
block|{
comment|/* Method NEVER returns a value */
name|AslError
argument_list|(
name|ASL_ERROR
argument_list|,
name|ASL_MSG_NO_RETVAL
argument_list|,
name|Op
argument_list|,
name|Op
operator|->
name|Asl
operator|.
name|ExternalName
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|OwningOp
operator|->
name|Asl
operator|.
name|CompileFlags
operator|&
name|OP_METHOD_SOME_NO_RETVAL
condition|)
block|{
comment|/* Method SOMETIMES returns a value, SOMETIMES not */
name|AslError
argument_list|(
name|ASL_WARNING
argument_list|,
name|ASL_MSG_SOME_NO_RETVAL
argument_list|,
name|Op
argument_list|,
name|Op
operator|->
name|Asl
operator|.
name|ExternalName
argument_list|)
expr_stmt|;
block|}
elseif|else
if|if
condition|(
operator|!
operator|(
name|ThisNodeBtype
operator|&
name|RequiredBtypes
operator|)
condition|)
block|{
comment|/* Method returns a value, but the type is wrong */
name|AnFormatBtype
argument_list|(
name|StringBuffer
argument_list|,
name|ThisNodeBtype
argument_list|)
expr_stmt|;
name|AnFormatBtype
argument_list|(
name|StringBuffer2
argument_list|,
name|RequiredBtypes
argument_list|)
expr_stmt|;
comment|/*          * The case where the method does not return any value at all          * was already handled in the namespace cross reference          * -- Only issue an error if the method in fact returns a value,          * but it is of the wrong type          */
if|if
condition|(
name|ThisNodeBtype
operator|!=
literal|0
condition|)
block|{
name|sprintf
argument_list|(
name|MsgBuffer
argument_list|,
literal|"Method returns [%s], %s operator requires [%s]"
argument_list|,
name|StringBuffer
argument_list|,
name|OpInfo
operator|->
name|Name
argument_list|,
name|StringBuffer2
argument_list|)
expr_stmt|;
name|AslError
argument_list|(
name|ASL_ERROR
argument_list|,
name|ASL_MSG_INVALID_TYPE
argument_list|,
name|ArgOp
argument_list|,
name|MsgBuffer
argument_list|)
expr_stmt|;
block|}
block|}
block|}
end_function

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    AnIsResultUsed  *  * PARAMETERS:  Op                  - Parent op for the operator  *  * RETURN:      TRUE if result from this operation is actually consumed  *  * DESCRIPTION: Determine if the function result value from an operator is  *              used.  *  ******************************************************************************/
end_comment

begin_function
name|BOOLEAN
name|AnIsResultUsed
parameter_list|(
name|ACPI_PARSE_OBJECT
modifier|*
name|Op
parameter_list|)
block|{
name|ACPI_PARSE_OBJECT
modifier|*
name|Parent
decl_stmt|;
switch|switch
condition|(
name|Op
operator|->
name|Asl
operator|.
name|ParseOpcode
condition|)
block|{
case|case
name|PARSEOP_INCREMENT
case|:
case|case
name|PARSEOP_DECREMENT
case|:
comment|/* These are standalone operators, no return value */
return|return
operator|(
name|TRUE
operator|)
return|;
default|default:
break|break;
block|}
comment|/* Examine parent to determine if the return value is used */
name|Parent
operator|=
name|Op
operator|->
name|Asl
operator|.
name|Parent
expr_stmt|;
switch|switch
condition|(
name|Parent
operator|->
name|Asl
operator|.
name|ParseOpcode
condition|)
block|{
comment|/* If/While - check if the operator is the predicate */
case|case
name|PARSEOP_IF
case|:
case|case
name|PARSEOP_WHILE
case|:
comment|/* First child is the predicate */
if|if
condition|(
name|Parent
operator|->
name|Asl
operator|.
name|Child
operator|==
name|Op
condition|)
block|{
return|return
operator|(
name|TRUE
operator|)
return|;
block|}
return|return
operator|(
name|FALSE
operator|)
return|;
comment|/* Not used if one of these is the parent */
case|case
name|PARSEOP_METHOD
case|:
case|case
name|PARSEOP_DEFINITION_BLOCK
case|:
case|case
name|PARSEOP_ELSE
case|:
return|return
operator|(
name|FALSE
operator|)
return|;
default|default:
comment|/* Any other type of parent means that the result is used */
return|return
operator|(
name|TRUE
operator|)
return|;
block|}
block|}
end_function

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    ApCheckForGpeNameConflict  *  * PARAMETERS:  Op                  - Current parse op  *  * RETURN:      None  *  * DESCRIPTION: Check for a conflict between GPE names within this scope.  *              Conflict means two GPE names with the same GPE number, but  *              different types -- such as _L1C and _E1C.  *  ******************************************************************************/
end_comment

begin_function
name|void
name|ApCheckForGpeNameConflict
parameter_list|(
name|ACPI_PARSE_OBJECT
modifier|*
name|Op
parameter_list|)
block|{
name|ACPI_PARSE_OBJECT
modifier|*
name|NextOp
decl_stmt|;
name|UINT32
name|GpeNumber
decl_stmt|;
name|char
name|Name
index|[
name|ACPI_NAME_SIZE
operator|+
literal|1
index|]
decl_stmt|;
name|char
name|Target
index|[
name|ACPI_NAME_SIZE
index|]
decl_stmt|;
comment|/* Need a null-terminated string version of NameSeg */
name|ACPI_MOVE_32_TO_32
argument_list|(
name|Name
argument_list|,
operator|&
name|Op
operator|->
name|Asl
operator|.
name|NameSeg
argument_list|)
expr_stmt|;
name|Name
index|[
name|ACPI_NAME_SIZE
index|]
operator|=
literal|0
expr_stmt|;
comment|/*      * For a GPE method:      * 1st char must be underscore      * 2nd char must be L or E      * 3rd/4th chars must be a hex number      */
if|if
condition|(
operator|(
name|Name
index|[
literal|0
index|]
operator|!=
literal|'_'
operator|)
operator|||
operator|(
operator|(
name|Name
index|[
literal|1
index|]
operator|!=
literal|'L'
operator|)
operator|&&
operator|(
name|Name
index|[
literal|1
index|]
operator|!=
literal|'E'
operator|)
operator|)
condition|)
block|{
return|return;
block|}
comment|/* Verify 3rd/4th chars are a valid hex value */
name|GpeNumber
operator|=
name|strtoul
argument_list|(
operator|&
name|Name
index|[
literal|2
index|]
argument_list|,
name|NULL
argument_list|,
literal|16
argument_list|)
expr_stmt|;
if|if
condition|(
name|GpeNumber
operator|==
name|ACPI_UINT32_MAX
condition|)
block|{
return|return;
block|}
comment|/*      * We are now sure we have an _Lxx or _Exx.      * Create the target name that would cause collision (Flip E/L)      */
name|ACPI_MOVE_32_TO_32
argument_list|(
name|Target
argument_list|,
name|Name
argument_list|)
expr_stmt|;
comment|/* Inject opposite letter ("L" versus "E") */
if|if
condition|(
name|Name
index|[
literal|1
index|]
operator|==
literal|'L'
condition|)
block|{
name|Target
index|[
literal|1
index|]
operator|=
literal|'E'
expr_stmt|;
block|}
else|else
comment|/* Name[1] == 'E' */
block|{
name|Target
index|[
literal|1
index|]
operator|=
literal|'L'
expr_stmt|;
block|}
comment|/* Search all peers (objects within this scope) for target match */
name|NextOp
operator|=
name|Op
operator|->
name|Asl
operator|.
name|Next
expr_stmt|;
while|while
condition|(
name|NextOp
condition|)
block|{
comment|/*          * We mostly care about methods, but check Name() constructs also,          * even though they will get another error for not being a method.          * All GPE names must be defined as control methods.          */
if|if
condition|(
operator|(
name|NextOp
operator|->
name|Asl
operator|.
name|ParseOpcode
operator|==
name|PARSEOP_METHOD
operator|)
operator|||
operator|(
name|NextOp
operator|->
name|Asl
operator|.
name|ParseOpcode
operator|==
name|PARSEOP_NAME
operator|)
condition|)
block|{
if|if
condition|(
name|ACPI_COMPARE_NAME
argument_list|(
name|Target
argument_list|,
name|NextOp
operator|->
name|Asl
operator|.
name|NameSeg
argument_list|)
condition|)
block|{
comment|/* Found both _Exy and _Lxy in the same scope, error */
name|AslError
argument_list|(
name|ASL_ERROR
argument_list|,
name|ASL_MSG_GPE_NAME_CONFLICT
argument_list|,
name|NextOp
argument_list|,
name|Name
argument_list|)
expr_stmt|;
return|return;
block|}
block|}
name|NextOp
operator|=
name|NextOp
operator|->
name|Asl
operator|.
name|Next
expr_stmt|;
block|}
comment|/* OK, no conflict found */
return|return;
block|}
end_function

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    ApCheckRegMethod  *  * PARAMETERS:  Op                  - Current parse op  *  * RETURN:      None  *  * DESCRIPTION: Ensure that a _REG method has a corresponding Operation  *              Region declaration within the same scope. Note: _REG is defined  *              to have two arguments and must therefore be defined as a  *              control method.  *  ******************************************************************************/
end_comment

begin_function
name|void
name|ApCheckRegMethod
parameter_list|(
name|ACPI_PARSE_OBJECT
modifier|*
name|Op
parameter_list|)
block|{
name|ACPI_PARSE_OBJECT
modifier|*
name|Next
decl_stmt|;
name|ACPI_PARSE_OBJECT
modifier|*
name|Parent
decl_stmt|;
comment|/* We are only interested in _REG methods */
if|if
condition|(
operator|!
name|ACPI_COMPARE_NAME
argument_list|(
name|METHOD_NAME__REG
argument_list|,
operator|&
name|Op
operator|->
name|Asl
operator|.
name|NameSeg
argument_list|)
condition|)
block|{
return|return;
block|}
comment|/* Get the start of the current scope */
name|Parent
operator|=
name|Op
operator|->
name|Asl
operator|.
name|Parent
expr_stmt|;
name|Next
operator|=
name|Parent
operator|->
name|Asl
operator|.
name|Child
expr_stmt|;
comment|/* Search entire scope for an operation region declaration */
while|while
condition|(
name|Next
condition|)
block|{
if|if
condition|(
name|Next
operator|->
name|Asl
operator|.
name|ParseOpcode
operator|==
name|PARSEOP_OPERATIONREGION
condition|)
block|{
return|return;
comment|/* Found region, OK */
block|}
name|Next
operator|=
name|Next
operator|->
name|Asl
operator|.
name|Next
expr_stmt|;
block|}
comment|/* No region found, issue warning */
name|AslError
argument_list|(
name|ASL_WARNING
argument_list|,
name|ASL_MSG_NO_REGION
argument_list|,
name|Op
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
block|}
end_function

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    ApFindNameInDeviceTree  *  * PARAMETERS:  Name                - Name to search for  *              Op                  - Current parse op  *  * RETURN:      TRUE if name found in the same scope as Op.  *  * DESCRIPTION: Determine if a name appears in the same scope as Op, as either  *              a Method() or a Name(). "Same scope" can mean under an If or  *              Else statement.  *  * NOTE: Detects _HID/_ADR in this type of construct (legal in ACPI 6.1+)  *  * Scope (\_SB.PCI0)  * {  *     Device (I2C0)  *     {  *         If (SMD0 != 4) {  *             Name (_HID, "INT3442")  *         } Else {  *             Name (_ADR, 0x400)  *         }  *     }  * }  ******************************************************************************/
end_comment

begin_function
name|BOOLEAN
name|ApFindNameInDeviceTree
parameter_list|(
name|char
modifier|*
name|Name
parameter_list|,
name|ACPI_PARSE_OBJECT
modifier|*
name|Op
parameter_list|)
block|{
name|ACPI_STATUS
name|Status
decl_stmt|;
name|Status
operator|=
name|TrWalkParseTree
argument_list|(
name|Op
argument_list|,
name|ASL_WALK_VISIT_DOWNWARD
argument_list|,
name|ApDeviceSubtreeWalk
argument_list|,
name|NULL
argument_list|,
name|Name
argument_list|)
expr_stmt|;
if|if
condition|(
name|Status
operator|==
name|AE_CTRL_TRUE
condition|)
block|{
return|return
operator|(
name|TRUE
operator|)
return|;
comment|/* Found a match */
block|}
return|return
operator|(
name|FALSE
operator|)
return|;
block|}
end_function

begin_comment
comment|/* Callback function for interface above */
end_comment

begin_function
specifier|static
name|ACPI_STATUS
name|ApDeviceSubtreeWalk
parameter_list|(
name|ACPI_PARSE_OBJECT
modifier|*
name|Op
parameter_list|,
name|UINT32
name|Level
parameter_list|,
name|void
modifier|*
name|Context
parameter_list|)
block|{
name|char
modifier|*
name|Name
init|=
name|ACPI_CAST_PTR
argument_list|(
name|char
argument_list|,
name|Context
argument_list|)
decl_stmt|;
switch|switch
condition|(
name|Op
operator|->
name|Asl
operator|.
name|ParseOpcode
condition|)
block|{
case|case
name|PARSEOP_DEVICE
case|:
comment|/* Level 0 is the starting device, ignore it */
if|if
condition|(
name|Level
operator|>
literal|0
condition|)
block|{
comment|/* Ignore sub-devices */
return|return
operator|(
name|AE_CTRL_DEPTH
operator|)
return|;
block|}
break|break;
case|case
name|PARSEOP_NAME
case|:
case|case
name|PARSEOP_METHOD
case|:
comment|/* These are what we are looking for */
if|if
condition|(
name|ACPI_COMPARE_NAME
argument_list|(
name|Name
argument_list|,
name|Op
operator|->
name|Asl
operator|.
name|NameSeg
argument_list|)
condition|)
block|{
return|return
operator|(
name|AE_CTRL_TRUE
operator|)
return|;
block|}
return|return
operator|(
name|AE_CTRL_DEPTH
operator|)
return|;
case|case
name|PARSEOP_SCOPE
case|:
case|case
name|PARSEOP_FIELD
case|:
case|case
name|PARSEOP_OPERATIONREGION
case|:
comment|/*          * We want to ignore these, because either they can be large          * subtrees or open a scope to somewhere else.          */
return|return
operator|(
name|AE_CTRL_DEPTH
operator|)
return|;
default|default:
break|break;
block|}
return|return
operator|(
name|AE_OK
operator|)
return|;
block|}
end_function

begin_comment
comment|/*******************************************************************************  *  * FUNCTION:    ApFindNameInScope  *  * PARAMETERS:  Name                - Name to search for  *              Op                  - Current parse op  *  * RETURN:      TRUE if name found in the same scope as Op.  *  * DESCRIPTION: Determine if a name appears in the same scope as Op, as either  *              a Method() or a Name().  *  ******************************************************************************/
end_comment

begin_function
name|BOOLEAN
name|ApFindNameInScope
parameter_list|(
name|char
modifier|*
name|Name
parameter_list|,
name|ACPI_PARSE_OBJECT
modifier|*
name|Op
parameter_list|)
block|{
name|ACPI_PARSE_OBJECT
modifier|*
name|Next
decl_stmt|;
name|ACPI_PARSE_OBJECT
modifier|*
name|Parent
decl_stmt|;
comment|/* Get the start of the current scope */
name|Parent
operator|=
name|Op
operator|->
name|Asl
operator|.
name|Parent
expr_stmt|;
name|Next
operator|=
name|Parent
operator|->
name|Asl
operator|.
name|Child
expr_stmt|;
comment|/* Search entire scope for a match to the name */
while|while
condition|(
name|Next
condition|)
block|{
if|if
condition|(
operator|(
name|Next
operator|->
name|Asl
operator|.
name|ParseOpcode
operator|==
name|PARSEOP_METHOD
operator|)
operator|||
operator|(
name|Next
operator|->
name|Asl
operator|.
name|ParseOpcode
operator|==
name|PARSEOP_NAME
operator|)
condition|)
block|{
if|if
condition|(
name|ACPI_COMPARE_NAME
argument_list|(
name|Name
argument_list|,
name|Next
operator|->
name|Asl
operator|.
name|NameSeg
argument_list|)
condition|)
block|{
return|return
operator|(
name|TRUE
operator|)
return|;
block|}
block|}
name|Next
operator|=
name|Next
operator|->
name|Asl
operator|.
name|Next
expr_stmt|;
block|}
return|return
operator|(
name|FALSE
operator|)
return|;
block|}
end_function

end_unit

