begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* Copyright (c) 2007 The NetBSD Foundation, Inc.  * All rights reserved.  *  * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions  * are met:  * 1. Redistributions of source code must retain the above copyright  *    notice, this list of conditions and the following disclaimer.  * 2. Redistributions in binary form must reproduce the above copyright  *    notice, this list of conditions and the following disclaimer in the  *    documentation and/or other materials provided with the distribution.  *  * THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND  * CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,  * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF  * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  * IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS BE LIABLE FOR ANY  * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE  * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS  * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER  * IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR  * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN  * IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.  */
end_comment

begin_include
include|#
directive|include
file|"atf-c/detail/fs.h"
end_include

begin_include
include|#
directive|include
file|<sys/types.h>
end_include

begin_include
include|#
directive|include
file|<sys/stat.h>
end_include

begin_include
include|#
directive|include
file|<errno.h>
end_include

begin_include
include|#
directive|include
file|<fcntl.h>
end_include

begin_include
include|#
directive|include
file|<stdio.h>
end_include

begin_include
include|#
directive|include
file|<stdlib.h>
end_include

begin_include
include|#
directive|include
file|<string.h>
end_include

begin_include
include|#
directive|include
file|<unistd.h>
end_include

begin_include
include|#
directive|include
file|<atf-c.h>
end_include

begin_include
include|#
directive|include
file|"atf-c/detail/test_helpers.h"
end_include

begin_include
include|#
directive|include
file|"atf-c/detail/user.h"
end_include

begin_comment
comment|/* ---------------------------------------------------------------------  * Auxiliary functions.  * --------------------------------------------------------------------- */
end_comment

begin_function
specifier|static
name|void
name|create_dir
parameter_list|(
specifier|const
name|char
modifier|*
name|p
parameter_list|,
name|int
name|mode
parameter_list|)
block|{
name|int
name|ret
decl_stmt|;
name|ret
operator|=
name|mkdir
argument_list|(
name|p
argument_list|,
name|mode
argument_list|)
expr_stmt|;
if|if
condition|(
name|ret
operator|==
operator|-
literal|1
condition|)
name|atf_tc_fail
argument_list|(
literal|"Could not create helper directory %s"
argument_list|,
name|p
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
name|create_file
parameter_list|(
specifier|const
name|char
modifier|*
name|p
parameter_list|,
name|int
name|mode
parameter_list|)
block|{
name|int
name|fd
decl_stmt|;
name|fd
operator|=
name|open
argument_list|(
name|p
argument_list|,
name|O_CREAT
operator||
name|O_WRONLY
operator||
name|O_TRUNC
argument_list|,
name|mode
argument_list|)
expr_stmt|;
if|if
condition|(
name|fd
operator|==
operator|-
literal|1
condition|)
name|atf_tc_fail
argument_list|(
literal|"Could not create helper file %s"
argument_list|,
name|p
argument_list|)
expr_stmt|;
name|close
argument_list|(
name|fd
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|bool
name|exists
parameter_list|(
specifier|const
name|atf_fs_path_t
modifier|*
name|p
parameter_list|)
block|{
return|return
name|access
argument_list|(
name|atf_fs_path_cstring
argument_list|(
name|p
argument_list|)
argument_list|,
name|F_OK
argument_list|)
operator|==
literal|0
return|;
block|}
end_function

begin_function
specifier|static
name|atf_error_t
name|mkstemp_discard_fd
parameter_list|(
name|atf_fs_path_t
modifier|*
name|p
parameter_list|)
block|{
name|int
name|fd
decl_stmt|;
name|atf_error_t
name|err
init|=
name|atf_fs_mkstemp
argument_list|(
name|p
argument_list|,
operator|&
name|fd
argument_list|)
decl_stmt|;
if|if
condition|(
operator|!
name|atf_is_error
argument_list|(
name|err
argument_list|)
condition|)
name|close
argument_list|(
name|fd
argument_list|)
expr_stmt|;
return|return
name|err
return|;
block|}
end_function

begin_comment
comment|/* ---------------------------------------------------------------------  * Test cases for the "atf_fs_path" type.  * --------------------------------------------------------------------- */
end_comment

begin_expr_stmt
name|ATF_TC
argument_list|(
name|path_normalize
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|path_normalize
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the path's normalization"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|path_normalize
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
struct|struct
name|test
block|{
specifier|const
name|char
modifier|*
name|in
decl_stmt|;
specifier|const
name|char
modifier|*
name|out
decl_stmt|;
block|}
name|tests
index|[]
init|=
block|{
block|{
literal|"."
block|,
literal|"."
block|, }
block|,
block|{
literal|".."
block|,
literal|".."
block|, }
block|,
block|{
literal|"/"
block|,
literal|"/"
block|, }
block|,
block|{
literal|"//"
block|,
literal|"/"
block|, }
block|,
comment|/* NO_CHECK_STYLE */
block|{
literal|"///"
block|,
literal|"/"
block|, }
block|,
comment|/* NO_CHECK_STYLE */
block|{
literal|"foo"
block|,
literal|"foo"
block|, }
block|,
block|{
literal|"foo/"
block|,
literal|"foo"
block|, }
block|,
block|{
literal|"foo/bar"
block|,
literal|"foo/bar"
block|, }
block|,
block|{
literal|"foo/bar/"
block|,
literal|"foo/bar"
block|, }
block|,
block|{
literal|"/foo"
block|,
literal|"/foo"
block|, }
block|,
block|{
literal|"/foo/bar"
block|,
literal|"/foo/bar"
block|, }
block|,
block|{
literal|"/foo/bar/"
block|,
literal|"/foo/bar"
block|, }
block|,
block|{
literal|"///foo"
block|,
literal|"/foo"
block|, }
block|,
comment|/* NO_CHECK_STYLE */
block|{
literal|"///foo///bar"
block|,
literal|"/foo/bar"
block|, }
block|,
comment|/* NO_CHECK_STYLE */
block|{
literal|"///foo///bar///"
block|,
literal|"/foo/bar"
block|, }
block|,
comment|/* NO_CHECK_STYLE */
block|{
name|NULL
block|,
name|NULL
block|}
block|}
struct|;
name|struct
name|test
modifier|*
name|t
decl_stmt|;
for|for
control|(
name|t
operator|=
operator|&
name|tests
index|[
literal|0
index|]
init|;
name|t
operator|->
name|in
operator|!=
name|NULL
condition|;
name|t
operator|++
control|)
block|{
name|atf_fs_path_t
name|p
decl_stmt|;
name|printf
argument_list|(
literal|"Input          :>%s<\n"
argument_list|,
name|t
operator|->
name|in
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Expected output:>%s<\n"
argument_list|,
name|t
operator|->
name|out
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"%s"
argument_list|,
name|t
operator|->
name|in
argument_list|)
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Output         :>%s<\n"
argument_list|,
name|atf_fs_path_cstring
argument_list|(
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|strcmp
argument_list|(
name|atf_fs_path_cstring
argument_list|(
operator|&
name|p
argument_list|)
argument_list|,
name|t
operator|->
name|out
argument_list|)
operator|==
literal|0
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"\n"
argument_list|)
expr_stmt|;
block|}
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|path_copy
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|path_copy
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_path_copy constructor"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|path_copy
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_fs_path_t
name|str
decl_stmt|,
name|str2
decl_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|str
argument_list|,
literal|"foo"
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_copy
argument_list|(
operator|&
name|str2
argument_list|,
operator|&
name|str
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_equal_fs_path_fs_path
argument_list|(
operator|&
name|str
argument_list|,
operator|&
name|str2
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_append_fmt
argument_list|(
operator|&
name|str2
argument_list|,
literal|"bar"
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_equal_fs_path_fs_path
argument_list|(
operator|&
name|str
argument_list|,
operator|&
name|str2
argument_list|)
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|str2
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|str
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|path_is_absolute
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|path_is_absolute
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the path::is_absolute function"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|path_is_absolute
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
struct|struct
name|test
block|{
specifier|const
name|char
modifier|*
name|in
decl_stmt|;
name|bool
name|abs
decl_stmt|;
block|}
name|tests
index|[]
init|=
block|{
block|{
literal|"/"
block|,
name|true
block|}
block|,
block|{
literal|"////"
block|,
name|true
block|}
block|,
comment|/* NO_CHECK_STYLE */
block|{
literal|"////a"
block|,
name|true
block|}
block|,
comment|/* NO_CHECK_STYLE */
block|{
literal|"//a//"
block|,
name|true
block|}
block|,
comment|/* NO_CHECK_STYLE */
block|{
literal|"a////"
block|,
name|false
block|}
block|,
comment|/* NO_CHECK_STYLE */
block|{
literal|"../foo"
block|,
name|false
block|}
block|,
block|{
name|NULL
block|,
name|false
block|}
block|,     }
struct|;
name|struct
name|test
modifier|*
name|t
decl_stmt|;
for|for
control|(
name|t
operator|=
operator|&
name|tests
index|[
literal|0
index|]
init|;
name|t
operator|->
name|in
operator|!=
name|NULL
condition|;
name|t
operator|++
control|)
block|{
name|atf_fs_path_t
name|p
decl_stmt|;
name|printf
argument_list|(
literal|"Input          : %s\n"
argument_list|,
name|t
operator|->
name|in
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Expected result: %s\n"
argument_list|,
name|t
operator|->
name|abs
condition|?
literal|"true"
else|:
literal|"false"
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"%s"
argument_list|,
name|t
operator|->
name|in
argument_list|)
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Result         : %s\n"
argument_list|,
name|atf_fs_path_is_absolute
argument_list|(
operator|&
name|p
argument_list|)
condition|?
literal|"true"
else|:
literal|"false"
argument_list|)
expr_stmt|;
if|if
condition|(
name|t
operator|->
name|abs
condition|)
name|ATF_REQUIRE
argument_list|(
name|atf_fs_path_is_absolute
argument_list|(
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
else|else
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_fs_path_is_absolute
argument_list|(
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"\n"
argument_list|)
expr_stmt|;
block|}
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|path_is_root
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|path_is_root
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the path::is_root function"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|path_is_root
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
struct|struct
name|test
block|{
specifier|const
name|char
modifier|*
name|in
decl_stmt|;
name|bool
name|root
decl_stmt|;
block|}
name|tests
index|[]
init|=
block|{
block|{
literal|"/"
block|,
name|true
block|}
block|,
block|{
literal|"////"
block|,
name|true
block|}
block|,
comment|/* NO_CHECK_STYLE */
block|{
literal|"////a"
block|,
name|false
block|}
block|,
comment|/* NO_CHECK_STYLE */
block|{
literal|"//a//"
block|,
name|false
block|}
block|,
comment|/* NO_CHECK_STYLE */
block|{
literal|"a////"
block|,
name|false
block|}
block|,
comment|/* NO_CHECK_STYLE */
block|{
literal|"../foo"
block|,
name|false
block|}
block|,
block|{
name|NULL
block|,
name|false
block|}
block|,     }
struct|;
name|struct
name|test
modifier|*
name|t
decl_stmt|;
for|for
control|(
name|t
operator|=
operator|&
name|tests
index|[
literal|0
index|]
init|;
name|t
operator|->
name|in
operator|!=
name|NULL
condition|;
name|t
operator|++
control|)
block|{
name|atf_fs_path_t
name|p
decl_stmt|;
name|printf
argument_list|(
literal|"Input          : %s\n"
argument_list|,
name|t
operator|->
name|in
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Expected result: %s\n"
argument_list|,
name|t
operator|->
name|root
condition|?
literal|"true"
else|:
literal|"false"
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"%s"
argument_list|,
name|t
operator|->
name|in
argument_list|)
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Result         : %s\n"
argument_list|,
name|atf_fs_path_is_root
argument_list|(
operator|&
name|p
argument_list|)
condition|?
literal|"true"
else|:
literal|"false"
argument_list|)
expr_stmt|;
if|if
condition|(
name|t
operator|->
name|root
condition|)
name|ATF_REQUIRE
argument_list|(
name|atf_fs_path_is_root
argument_list|(
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
else|else
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_fs_path_is_root
argument_list|(
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"\n"
argument_list|)
expr_stmt|;
block|}
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|path_branch_path
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|path_branch_path
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_path_branch_path "
literal|"function"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|path_branch_path
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
struct|struct
name|test
block|{
specifier|const
name|char
modifier|*
name|in
decl_stmt|;
specifier|const
name|char
modifier|*
name|branch
decl_stmt|;
block|}
name|tests
index|[]
init|=
block|{
block|{
literal|"."
block|,
literal|"."
block|}
block|,
block|{
literal|"foo"
block|,
literal|"."
block|}
block|,
block|{
literal|"foo/bar"
block|,
literal|"foo"
block|}
block|,
block|{
literal|"/foo"
block|,
literal|"/"
block|}
block|,
block|{
literal|"/foo/bar"
block|,
literal|"/foo"
block|}
block|,
block|{
name|NULL
block|,
name|NULL
block|}
block|,     }
struct|;
name|struct
name|test
modifier|*
name|t
decl_stmt|;
for|for
control|(
name|t
operator|=
operator|&
name|tests
index|[
literal|0
index|]
init|;
name|t
operator|->
name|in
operator|!=
name|NULL
condition|;
name|t
operator|++
control|)
block|{
name|atf_fs_path_t
name|p
decl_stmt|,
name|bp
decl_stmt|;
name|printf
argument_list|(
literal|"Input          : %s\n"
argument_list|,
name|t
operator|->
name|in
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Expected output: %s\n"
argument_list|,
name|t
operator|->
name|branch
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"%s"
argument_list|,
name|t
operator|->
name|in
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_branch_path
argument_list|(
operator|&
name|p
argument_list|,
operator|&
name|bp
argument_list|)
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Output         : %s\n"
argument_list|,
name|atf_fs_path_cstring
argument_list|(
operator|&
name|bp
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|strcmp
argument_list|(
name|atf_fs_path_cstring
argument_list|(
operator|&
name|bp
argument_list|)
argument_list|,
name|t
operator|->
name|branch
argument_list|)
operator|==
literal|0
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|bp
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"\n"
argument_list|)
expr_stmt|;
block|}
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|path_leaf_name
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|path_leaf_name
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_path_leaf_name "
literal|"function"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|path_leaf_name
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
struct|struct
name|test
block|{
specifier|const
name|char
modifier|*
name|in
decl_stmt|;
specifier|const
name|char
modifier|*
name|leaf
decl_stmt|;
block|}
name|tests
index|[]
init|=
block|{
block|{
literal|"."
block|,
literal|"."
block|}
block|,
block|{
literal|"foo"
block|,
literal|"foo"
block|}
block|,
block|{
literal|"foo/bar"
block|,
literal|"bar"
block|}
block|,
block|{
literal|"/foo"
block|,
literal|"foo"
block|}
block|,
block|{
literal|"/foo/bar"
block|,
literal|"bar"
block|}
block|,
block|{
name|NULL
block|,
name|NULL
block|}
block|,     }
struct|;
name|struct
name|test
modifier|*
name|t
decl_stmt|;
for|for
control|(
name|t
operator|=
operator|&
name|tests
index|[
literal|0
index|]
init|;
name|t
operator|->
name|in
operator|!=
name|NULL
condition|;
name|t
operator|++
control|)
block|{
name|atf_fs_path_t
name|p
decl_stmt|;
name|atf_dynstr_t
name|ln
decl_stmt|;
name|printf
argument_list|(
literal|"Input          : %s\n"
argument_list|,
name|t
operator|->
name|in
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Expected output: %s\n"
argument_list|,
name|t
operator|->
name|leaf
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"%s"
argument_list|,
name|t
operator|->
name|in
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_leaf_name
argument_list|(
operator|&
name|p
argument_list|,
operator|&
name|ln
argument_list|)
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Output         : %s\n"
argument_list|,
name|atf_dynstr_cstring
argument_list|(
operator|&
name|ln
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_equal_dynstr_cstring
argument_list|(
operator|&
name|ln
argument_list|,
name|t
operator|->
name|leaf
argument_list|)
argument_list|)
expr_stmt|;
name|atf_dynstr_fini
argument_list|(
operator|&
name|ln
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"\n"
argument_list|)
expr_stmt|;
block|}
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|path_append
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|path_append
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the concatenation of multiple "
literal|"paths"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|path_append
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
struct|struct
name|test
block|{
specifier|const
name|char
modifier|*
name|in
decl_stmt|;
specifier|const
name|char
modifier|*
name|ap
decl_stmt|;
specifier|const
name|char
modifier|*
name|out
decl_stmt|;
block|}
name|tests
index|[]
init|=
block|{
block|{
literal|"foo"
block|,
literal|"bar"
block|,
literal|"foo/bar"
block|}
block|,
block|{
literal|"foo/"
block|,
literal|"/bar"
block|,
literal|"foo/bar"
block|}
block|,
block|{
literal|"foo/"
block|,
literal|"/bar/baz"
block|,
literal|"foo/bar/baz"
block|}
block|,
block|{
literal|"foo/"
block|,
literal|"///bar///baz"
block|,
literal|"foo/bar/baz"
block|}
block|,
comment|/* NO_CHECK_STYLE */
block|{
name|NULL
block|,
name|NULL
block|,
name|NULL
block|}
block|}
struct|;
name|struct
name|test
modifier|*
name|t
decl_stmt|;
for|for
control|(
name|t
operator|=
operator|&
name|tests
index|[
literal|0
index|]
init|;
name|t
operator|->
name|in
operator|!=
name|NULL
condition|;
name|t
operator|++
control|)
block|{
name|atf_fs_path_t
name|p
decl_stmt|;
name|printf
argument_list|(
literal|"Input          :>%s<\n"
argument_list|,
name|t
operator|->
name|in
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Append         :>%s<\n"
argument_list|,
name|t
operator|->
name|ap
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Expected output:>%s<\n"
argument_list|,
name|t
operator|->
name|out
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"%s"
argument_list|,
name|t
operator|->
name|in
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_append_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"%s"
argument_list|,
name|t
operator|->
name|ap
argument_list|)
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Output         :>%s<\n"
argument_list|,
name|atf_fs_path_cstring
argument_list|(
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|strcmp
argument_list|(
name|atf_fs_path_cstring
argument_list|(
operator|&
name|p
argument_list|)
argument_list|,
name|t
operator|->
name|out
argument_list|)
operator|==
literal|0
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"\n"
argument_list|)
expr_stmt|;
block|}
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|path_to_absolute
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|path_to_absolute
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_path_to_absolute "
literal|"function"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|path_to_absolute
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
specifier|const
name|char
modifier|*
name|names
index|[]
init|=
block|{
literal|"."
block|,
literal|"dir"
block|,
name|NULL
block|}
decl_stmt|;
specifier|const
name|char
modifier|*
modifier|*
name|n
decl_stmt|;
name|ATF_REQUIRE
argument_list|(
name|mkdir
argument_list|(
literal|"dir"
argument_list|,
literal|0755
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
for|for
control|(
name|n
operator|=
name|names
init|;
operator|*
name|n
operator|!=
name|NULL
condition|;
name|n
operator|++
control|)
block|{
name|atf_fs_path_t
name|p
decl_stmt|,
name|p2
decl_stmt|;
name|atf_fs_stat_t
name|st1
decl_stmt|,
name|st2
decl_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"%s"
argument_list|,
operator|*
name|n
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_stat_init
argument_list|(
operator|&
name|st1
argument_list|,
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Relative path: %s\n"
argument_list|,
name|atf_fs_path_cstring
argument_list|(
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_to_absolute
argument_list|(
operator|&
name|p
argument_list|,
operator|&
name|p2
argument_list|)
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Absolute path: %s\n"
argument_list|,
name|atf_fs_path_cstring
argument_list|(
operator|&
name|p2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_fs_path_is_absolute
argument_list|(
operator|&
name|p2
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_stat_init
argument_list|(
operator|&
name|st2
argument_list|,
operator|&
name|p2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE_EQ
argument_list|(
name|atf_fs_stat_get_device
argument_list|(
operator|&
name|st1
argument_list|)
argument_list|,
name|atf_fs_stat_get_device
argument_list|(
operator|&
name|st2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE_EQ
argument_list|(
name|atf_fs_stat_get_inode
argument_list|(
operator|&
name|st1
argument_list|)
argument_list|,
name|atf_fs_stat_get_inode
argument_list|(
operator|&
name|st2
argument_list|)
argument_list|)
expr_stmt|;
name|atf_fs_stat_fini
argument_list|(
operator|&
name|st2
argument_list|)
expr_stmt|;
name|atf_fs_stat_fini
argument_list|(
operator|&
name|st1
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p2
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"\n"
argument_list|)
expr_stmt|;
block|}
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|path_equal
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|path_equal
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the equality operators for paths"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|path_equal
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_fs_path_t
name|p1
decl_stmt|,
name|p2
decl_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p1
argument_list|,
literal|"foo"
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p2
argument_list|,
literal|"foo"
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_equal_fs_path_fs_path
argument_list|(
operator|&
name|p1
argument_list|,
operator|&
name|p2
argument_list|)
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p2
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p2
argument_list|,
literal|"bar"
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_equal_fs_path_fs_path
argument_list|(
operator|&
name|p1
argument_list|,
operator|&
name|p2
argument_list|)
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p2
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p1
argument_list|)
expr_stmt|;
block|}
end_block

begin_comment
comment|/* ---------------------------------------------------------------------  * Test cases for the "atf_fs_stat" type.  * --------------------------------------------------------------------- */
end_comment

begin_expr_stmt
name|ATF_TC
argument_list|(
name|stat_mode
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|stat_mode
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_stat_get_mode function "
literal|"and, indirectly, the constructor"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|stat_mode
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_fs_path_t
name|p
decl_stmt|;
name|atf_fs_stat_t
name|st
decl_stmt|;
name|create_file
argument_list|(
literal|"f1"
argument_list|,
literal|0400
argument_list|)
expr_stmt|;
name|create_file
argument_list|(
literal|"f2"
argument_list|,
literal|0644
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"f1"
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_stat_init
argument_list|(
operator|&
name|st
argument_list|,
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK_EQ
argument_list|(
literal|0400
argument_list|,
name|atf_fs_stat_get_mode
argument_list|(
operator|&
name|st
argument_list|)
argument_list|)
expr_stmt|;
name|atf_fs_stat_fini
argument_list|(
operator|&
name|st
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"f2"
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_stat_init
argument_list|(
operator|&
name|st
argument_list|,
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK_EQ
argument_list|(
literal|0644
argument_list|,
name|atf_fs_stat_get_mode
argument_list|(
operator|&
name|st
argument_list|)
argument_list|)
expr_stmt|;
name|atf_fs_stat_fini
argument_list|(
operator|&
name|st
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|stat_type
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|stat_type
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_stat_get_type function "
literal|"and, indirectly, the constructor"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|stat_type
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_fs_path_t
name|p
decl_stmt|;
name|atf_fs_stat_t
name|st
decl_stmt|;
name|create_dir
argument_list|(
literal|"dir"
argument_list|,
literal|0755
argument_list|)
expr_stmt|;
name|create_file
argument_list|(
literal|"reg"
argument_list|,
literal|0644
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"dir"
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_stat_init
argument_list|(
operator|&
name|st
argument_list|,
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE_EQ
argument_list|(
name|atf_fs_stat_get_type
argument_list|(
operator|&
name|st
argument_list|)
argument_list|,
name|atf_fs_stat_dir_type
argument_list|)
expr_stmt|;
name|atf_fs_stat_fini
argument_list|(
operator|&
name|st
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"reg"
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_stat_init
argument_list|(
operator|&
name|st
argument_list|,
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE_EQ
argument_list|(
name|atf_fs_stat_get_type
argument_list|(
operator|&
name|st
argument_list|)
argument_list|,
name|atf_fs_stat_reg_type
argument_list|)
expr_stmt|;
name|atf_fs_stat_fini
argument_list|(
operator|&
name|st
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|stat_perms
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|stat_perms
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_stat_is_* functions"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|stat_perms
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_fs_path_t
name|p
decl_stmt|;
name|atf_fs_stat_t
name|st
decl_stmt|;
name|create_file
argument_list|(
literal|"reg"
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"reg"
argument_list|)
argument_list|)
expr_stmt|;
define|#
directive|define
name|perms
parameter_list|(
name|ur
parameter_list|,
name|uw
parameter_list|,
name|ux
parameter_list|,
name|gr
parameter_list|,
name|gw
parameter_list|,
name|gx
parameter_list|,
name|othr
parameter_list|,
name|othw
parameter_list|,
name|othx
parameter_list|)
define|\
value|{ \         RE(atf_fs_stat_init(&st,&p)); \         ATF_REQUIRE(atf_fs_stat_is_owner_readable(&st) == ur); \         ATF_REQUIRE(atf_fs_stat_is_owner_writable(&st) == uw); \         ATF_REQUIRE(atf_fs_stat_is_owner_executable(&st) == ux); \         ATF_REQUIRE(atf_fs_stat_is_group_readable(&st) == gr); \         ATF_REQUIRE(atf_fs_stat_is_group_writable(&st) == gw); \         ATF_REQUIRE(atf_fs_stat_is_group_executable(&st) == gx); \         ATF_REQUIRE(atf_fs_stat_is_other_readable(&st) == othr); \         ATF_REQUIRE(atf_fs_stat_is_other_writable(&st) == othw); \         ATF_REQUIRE(atf_fs_stat_is_other_executable(&st) == othx); \         atf_fs_stat_fini(&st); \     }
name|chmod
argument_list|(
literal|"reg"
argument_list|,
literal|0000
argument_list|)
expr_stmt|;
name|perms
argument_list|(
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|)
expr_stmt|;
name|chmod
argument_list|(
literal|"reg"
argument_list|,
literal|0001
argument_list|)
expr_stmt|;
name|perms
argument_list|(
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|true
argument_list|)
expr_stmt|;
name|chmod
argument_list|(
literal|"reg"
argument_list|,
literal|0010
argument_list|)
expr_stmt|;
name|perms
argument_list|(
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|true
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|)
expr_stmt|;
name|chmod
argument_list|(
literal|"reg"
argument_list|,
literal|0100
argument_list|)
expr_stmt|;
name|perms
argument_list|(
name|false
argument_list|,
name|false
argument_list|,
name|true
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|)
expr_stmt|;
name|chmod
argument_list|(
literal|"reg"
argument_list|,
literal|0002
argument_list|)
expr_stmt|;
name|perms
argument_list|(
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|true
argument_list|,
name|false
argument_list|)
expr_stmt|;
name|chmod
argument_list|(
literal|"reg"
argument_list|,
literal|0020
argument_list|)
expr_stmt|;
name|perms
argument_list|(
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|true
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|)
expr_stmt|;
name|chmod
argument_list|(
literal|"reg"
argument_list|,
literal|0200
argument_list|)
expr_stmt|;
name|perms
argument_list|(
name|false
argument_list|,
name|true
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|)
expr_stmt|;
name|chmod
argument_list|(
literal|"reg"
argument_list|,
literal|0004
argument_list|)
expr_stmt|;
name|perms
argument_list|(
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|true
argument_list|,
name|false
argument_list|,
name|false
argument_list|)
expr_stmt|;
name|chmod
argument_list|(
literal|"reg"
argument_list|,
literal|0040
argument_list|)
expr_stmt|;
name|perms
argument_list|(
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|true
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|)
expr_stmt|;
name|chmod
argument_list|(
literal|"reg"
argument_list|,
literal|0400
argument_list|)
expr_stmt|;
name|perms
argument_list|(
name|true
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|false
argument_list|)
expr_stmt|;
name|chmod
argument_list|(
literal|"reg"
argument_list|,
literal|0644
argument_list|)
expr_stmt|;
name|perms
argument_list|(
name|true
argument_list|,
name|true
argument_list|,
name|false
argument_list|,
name|true
argument_list|,
name|false
argument_list|,
name|false
argument_list|,
name|true
argument_list|,
name|false
argument_list|,
name|false
argument_list|)
expr_stmt|;
name|chmod
argument_list|(
literal|"reg"
argument_list|,
literal|0755
argument_list|)
expr_stmt|;
name|perms
argument_list|(
name|true
argument_list|,
name|true
argument_list|,
name|true
argument_list|,
name|true
argument_list|,
name|false
argument_list|,
name|true
argument_list|,
name|true
argument_list|,
name|false
argument_list|,
name|true
argument_list|)
expr_stmt|;
name|chmod
argument_list|(
literal|"reg"
argument_list|,
literal|0777
argument_list|)
expr_stmt|;
name|perms
argument_list|(
name|true
argument_list|,
name|true
argument_list|,
name|true
argument_list|,
name|true
argument_list|,
name|true
argument_list|,
name|true
argument_list|,
name|true
argument_list|,
name|true
argument_list|,
name|true
argument_list|)
expr_stmt|;
undef|#
directive|undef
name|perms
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
block|}
end_block

begin_comment
comment|/* ---------------------------------------------------------------------  * Test cases for the free functions.  * --------------------------------------------------------------------- */
end_comment

begin_expr_stmt
name|ATF_TC
argument_list|(
name|exists
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|exists
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_exists function"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|exists
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_error_t
name|err
decl_stmt|;
name|atf_fs_path_t
name|pdir
decl_stmt|,
name|pfile
decl_stmt|;
name|bool
name|b
decl_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|pdir
argument_list|,
literal|"dir"
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|pfile
argument_list|,
literal|"dir/file"
argument_list|)
argument_list|)
expr_stmt|;
name|create_dir
argument_list|(
name|atf_fs_path_cstring
argument_list|(
operator|&
name|pdir
argument_list|)
argument_list|,
literal|0755
argument_list|)
expr_stmt|;
name|create_file
argument_list|(
name|atf_fs_path_cstring
argument_list|(
operator|&
name|pfile
argument_list|)
argument_list|,
literal|0644
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Checking existence of a directory\n"
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_exists
argument_list|(
operator|&
name|pdir
argument_list|,
operator|&
name|b
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|b
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Checking existence of a file\n"
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_exists
argument_list|(
operator|&
name|pfile
argument_list|,
operator|&
name|b
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|b
argument_list|)
expr_stmt|;
comment|/* XXX: This should probably be a separate test case to let the user      * be aware that some tests were skipped because privileges were not      * correct. */
if|if
condition|(
operator|!
name|atf_user_is_root
argument_list|()
condition|)
block|{
name|printf
argument_list|(
literal|"Checking existence of a file inside a directory without "
literal|"permissions\n"
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|chmod
argument_list|(
name|atf_fs_path_cstring
argument_list|(
operator|&
name|pdir
argument_list|)
argument_list|,
literal|0000
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
name|err
operator|=
name|atf_fs_exists
argument_list|(
operator|&
name|pfile
argument_list|,
operator|&
name|b
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_is_error
argument_list|(
name|err
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_error_is
argument_list|(
name|err
argument_list|,
literal|"libc"
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|chmod
argument_list|(
name|atf_fs_path_cstring
argument_list|(
operator|&
name|pdir
argument_list|)
argument_list|,
literal|0755
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
name|atf_error_free
argument_list|(
name|err
argument_list|)
expr_stmt|;
block|}
name|printf
argument_list|(
literal|"Checking existence of a non-existent file\n"
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|unlink
argument_list|(
name|atf_fs_path_cstring
argument_list|(
operator|&
name|pfile
argument_list|)
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_exists
argument_list|(
operator|&
name|pfile
argument_list|,
operator|&
name|b
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|b
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|pfile
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|pdir
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|eaccess
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|eaccess
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_eaccess function"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|eaccess
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
specifier|const
name|int
name|modes
index|[]
init|=
block|{
name|atf_fs_access_f
block|,
name|atf_fs_access_r
block|,
name|atf_fs_access_w
block|,
name|atf_fs_access_x
block|,
literal|0
block|}
decl_stmt|;
specifier|const
name|int
modifier|*
name|m
decl_stmt|;
struct|struct
name|tests
block|{
name|mode_t
name|fmode
decl_stmt|;
name|int
name|amode
decl_stmt|;
name|int
name|uerror
decl_stmt|;
name|int
name|rerror
decl_stmt|;
block|}
name|tests
index|[]
init|=
block|{
block|{
literal|0000
block|,
name|atf_fs_access_r
block|,
name|EACCES
block|,
literal|0
block|}
block|,
block|{
literal|0000
block|,
name|atf_fs_access_w
block|,
name|EACCES
block|,
literal|0
block|}
block|,
block|{
literal|0000
block|,
name|atf_fs_access_x
block|,
name|EACCES
block|,
name|EACCES
block|}
block|,
block|{
literal|0001
block|,
name|atf_fs_access_r
block|,
name|EACCES
block|,
literal|0
block|}
block|,
block|{
literal|0001
block|,
name|atf_fs_access_w
block|,
name|EACCES
block|,
literal|0
block|}
block|,
block|{
literal|0001
block|,
name|atf_fs_access_x
block|,
name|EACCES
block|,
literal|0
block|}
block|,
block|{
literal|0002
block|,
name|atf_fs_access_r
block|,
name|EACCES
block|,
literal|0
block|}
block|,
block|{
literal|0002
block|,
name|atf_fs_access_w
block|,
name|EACCES
block|,
literal|0
block|}
block|,
block|{
literal|0002
block|,
name|atf_fs_access_x
block|,
name|EACCES
block|,
name|EACCES
block|}
block|,
block|{
literal|0004
block|,
name|atf_fs_access_r
block|,
name|EACCES
block|,
literal|0
block|}
block|,
block|{
literal|0004
block|,
name|atf_fs_access_w
block|,
name|EACCES
block|,
literal|0
block|}
block|,
block|{
literal|0004
block|,
name|atf_fs_access_x
block|,
name|EACCES
block|,
name|EACCES
block|}
block|,
block|{
literal|0010
block|,
name|atf_fs_access_r
block|,
name|EACCES
block|,
literal|0
block|}
block|,
block|{
literal|0010
block|,
name|atf_fs_access_w
block|,
name|EACCES
block|,
literal|0
block|}
block|,
block|{
literal|0010
block|,
name|atf_fs_access_x
block|,
literal|0
block|,
literal|0
block|}
block|,
block|{
literal|0020
block|,
name|atf_fs_access_r
block|,
name|EACCES
block|,
literal|0
block|}
block|,
block|{
literal|0020
block|,
name|atf_fs_access_w
block|,
literal|0
block|,
literal|0
block|}
block|,
block|{
literal|0020
block|,
name|atf_fs_access_x
block|,
name|EACCES
block|,
name|EACCES
block|}
block|,
block|{
literal|0040
block|,
name|atf_fs_access_r
block|,
literal|0
block|,
literal|0
block|}
block|,
block|{
literal|0040
block|,
name|atf_fs_access_w
block|,
name|EACCES
block|,
literal|0
block|}
block|,
block|{
literal|0040
block|,
name|atf_fs_access_x
block|,
name|EACCES
block|,
name|EACCES
block|}
block|,
block|{
literal|0100
block|,
name|atf_fs_access_r
block|,
name|EACCES
block|,
literal|0
block|}
block|,
block|{
literal|0100
block|,
name|atf_fs_access_w
block|,
name|EACCES
block|,
literal|0
block|}
block|,
block|{
literal|0100
block|,
name|atf_fs_access_x
block|,
literal|0
block|,
literal|0
block|}
block|,
block|{
literal|0200
block|,
name|atf_fs_access_r
block|,
name|EACCES
block|,
literal|0
block|}
block|,
block|{
literal|0200
block|,
name|atf_fs_access_w
block|,
literal|0
block|,
literal|0
block|}
block|,
block|{
literal|0200
block|,
name|atf_fs_access_x
block|,
name|EACCES
block|,
name|EACCES
block|}
block|,
block|{
literal|0400
block|,
name|atf_fs_access_r
block|,
literal|0
block|,
literal|0
block|}
block|,
block|{
literal|0400
block|,
name|atf_fs_access_w
block|,
name|EACCES
block|,
literal|0
block|}
block|,
block|{
literal|0400
block|,
name|atf_fs_access_x
block|,
name|EACCES
block|,
name|EACCES
block|}
block|,
block|{
literal|0
block|,
literal|0
block|,
literal|0
block|,
literal|0
block|}
block|}
struct|;
name|struct
name|tests
modifier|*
name|t
decl_stmt|;
name|atf_fs_path_t
name|p
decl_stmt|;
name|atf_error_t
name|err
decl_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"the-file"
argument_list|)
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Non-existent file checks\n"
argument_list|)
expr_stmt|;
for|for
control|(
name|m
operator|=
operator|&
name|modes
index|[
literal|0
index|]
init|;
operator|*
name|m
operator|!=
literal|0
condition|;
name|m
operator|++
control|)
block|{
name|err
operator|=
name|atf_fs_eaccess
argument_list|(
operator|&
name|p
argument_list|,
operator|*
name|m
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_is_error
argument_list|(
name|err
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_error_is
argument_list|(
name|err
argument_list|,
literal|"libc"
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE_EQ
argument_list|(
name|atf_libc_error_code
argument_list|(
name|err
argument_list|)
argument_list|,
name|ENOENT
argument_list|)
expr_stmt|;
name|atf_error_free
argument_list|(
name|err
argument_list|)
expr_stmt|;
block|}
name|create_file
argument_list|(
name|atf_fs_path_cstring
argument_list|(
operator|&
name|p
argument_list|)
argument_list|,
literal|0000
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|chown
argument_list|(
name|atf_fs_path_cstring
argument_list|(
operator|&
name|p
argument_list|)
argument_list|,
name|geteuid
argument_list|()
argument_list|,
name|getegid
argument_list|()
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
for|for
control|(
name|t
operator|=
operator|&
name|tests
index|[
literal|0
index|]
init|;
name|t
operator|->
name|amode
operator|!=
literal|0
condition|;
name|t
operator|++
control|)
block|{
specifier|const
name|int
name|experr
init|=
name|atf_user_is_root
argument_list|()
condition|?
name|t
operator|->
name|rerror
else|:
name|t
operator|->
name|uerror
decl_stmt|;
name|printf
argument_list|(
literal|"\n"
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"File mode     : %04o\n"
argument_list|,
operator|(
name|unsigned
name|int
operator|)
name|t
operator|->
name|fmode
argument_list|)
expr_stmt|;
name|printf
argument_list|(
literal|"Access mode   : 0x%02x\n"
argument_list|,
name|t
operator|->
name|amode
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|chmod
argument_list|(
name|atf_fs_path_cstring
argument_list|(
operator|&
name|p
argument_list|)
argument_list|,
name|t
operator|->
name|fmode
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
comment|/* First, existence check. */
name|err
operator|=
name|atf_fs_eaccess
argument_list|(
operator|&
name|p
argument_list|,
name|atf_fs_access_f
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_is_error
argument_list|(
name|err
argument_list|)
argument_list|)
expr_stmt|;
comment|/* Now do the specific test case. */
name|printf
argument_list|(
literal|"Expected error: %d\n"
argument_list|,
name|experr
argument_list|)
expr_stmt|;
name|err
operator|=
name|atf_fs_eaccess
argument_list|(
operator|&
name|p
argument_list|,
name|t
operator|->
name|amode
argument_list|)
expr_stmt|;
if|if
condition|(
name|atf_is_error
argument_list|(
name|err
argument_list|)
condition|)
block|{
if|if
condition|(
name|atf_error_is
argument_list|(
name|err
argument_list|,
literal|"libc"
argument_list|)
condition|)
name|printf
argument_list|(
literal|"Error         : %d\n"
argument_list|,
name|atf_libc_error_code
argument_list|(
name|err
argument_list|)
argument_list|)
expr_stmt|;
else|else
name|printf
argument_list|(
literal|"Error         : Non-libc error\n"
argument_list|)
expr_stmt|;
block|}
else|else
name|printf
argument_list|(
literal|"Error         : None\n"
argument_list|)
expr_stmt|;
if|if
condition|(
name|experr
operator|==
literal|0
condition|)
block|{
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_is_error
argument_list|(
name|err
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|ATF_REQUIRE
argument_list|(
name|atf_is_error
argument_list|(
name|err
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_error_is
argument_list|(
name|err
argument_list|,
literal|"libc"
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE_EQ
argument_list|(
name|atf_libc_error_code
argument_list|(
name|err
argument_list|)
argument_list|,
name|experr
argument_list|)
expr_stmt|;
name|atf_error_free
argument_list|(
name|err
argument_list|)
expr_stmt|;
block|}
block|}
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|getcwd
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|getcwd
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_getcwd function"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|getcwd
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_fs_path_t
name|cwd1
decl_stmt|,
name|cwd2
decl_stmt|;
name|create_dir
argument_list|(
literal|"root"
argument_list|,
literal|0755
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_getcwd
argument_list|(
operator|&
name|cwd1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|chdir
argument_list|(
literal|"root"
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_getcwd
argument_list|(
operator|&
name|cwd2
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_append_fmt
argument_list|(
operator|&
name|cwd1
argument_list|,
literal|"root"
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_equal_fs_path_fs_path
argument_list|(
operator|&
name|cwd1
argument_list|,
operator|&
name|cwd2
argument_list|)
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|cwd2
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|cwd1
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|rmdir_empty
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|rmdir_empty
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_rmdir function"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|rmdir_empty
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_fs_path_t
name|p
decl_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"test-dir"
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|mkdir
argument_list|(
literal|"test-dir"
argument_list|,
literal|0755
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|exists
argument_list|(
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_rmdir
argument_list|(
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|exists
argument_list|(
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|rmdir_enotempty
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|rmdir_enotempty
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_rmdir function"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|rmdir_enotempty
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_fs_path_t
name|p
decl_stmt|;
name|atf_error_t
name|err
decl_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"test-dir"
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|mkdir
argument_list|(
literal|"test-dir"
argument_list|,
literal|0755
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|exists
argument_list|(
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
name|create_file
argument_list|(
literal|"test-dir/foo"
argument_list|,
literal|0644
argument_list|)
expr_stmt|;
name|err
operator|=
name|atf_fs_rmdir
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_is_error
argument_list|(
name|err
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_error_is
argument_list|(
name|err
argument_list|,
literal|"libc"
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE_EQ
argument_list|(
name|atf_libc_error_code
argument_list|(
name|err
argument_list|)
argument_list|,
name|ENOTEMPTY
argument_list|)
expr_stmt|;
name|atf_error_free
argument_list|(
name|err
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|rmdir_eperm
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|rmdir_eperm
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_rmdir function"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|rmdir_eperm
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_fs_path_t
name|p
decl_stmt|;
name|atf_error_t
name|err
decl_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"test-dir/foo"
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|mkdir
argument_list|(
literal|"test-dir"
argument_list|,
literal|0755
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|mkdir
argument_list|(
literal|"test-dir/foo"
argument_list|,
literal|0755
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|chmod
argument_list|(
literal|"test-dir"
argument_list|,
literal|0555
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|exists
argument_list|(
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
name|err
operator|=
name|atf_fs_rmdir
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
if|if
condition|(
name|atf_user_is_root
argument_list|()
condition|)
block|{
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_is_error
argument_list|(
name|err
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|ATF_REQUIRE
argument_list|(
name|atf_is_error
argument_list|(
name|err
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_error_is
argument_list|(
name|err
argument_list|,
literal|"libc"
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE_EQ
argument_list|(
name|atf_libc_error_code
argument_list|(
name|err
argument_list|)
argument_list|,
name|EACCES
argument_list|)
expr_stmt|;
name|atf_error_free
argument_list|(
name|err
argument_list|)
expr_stmt|;
block|}
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|mkdtemp_ok
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|mkdtemp_ok
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_mkdtemp function, "
literal|"successful execution"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|mkdtemp_ok
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_fs_path_t
name|p1
decl_stmt|,
name|p2
decl_stmt|;
name|atf_fs_stat_t
name|s1
decl_stmt|,
name|s2
decl_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p1
argument_list|,
literal|"testdir.XXXXXX"
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p2
argument_list|,
literal|"testdir.XXXXXX"
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_mkdtemp
argument_list|(
operator|&
name|p1
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_mkdtemp
argument_list|(
operator|&
name|p2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_equal_fs_path_fs_path
argument_list|(
operator|&
name|p1
argument_list|,
operator|&
name|p2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|exists
argument_list|(
operator|&
name|p1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|exists
argument_list|(
operator|&
name|p2
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_stat_init
argument_list|(
operator|&
name|s1
argument_list|,
operator|&
name|p1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE_EQ
argument_list|(
name|atf_fs_stat_get_type
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|,
name|atf_fs_stat_dir_type
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_fs_stat_is_owner_readable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_fs_stat_is_owner_writable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_fs_stat_is_owner_executable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_fs_stat_is_group_readable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_fs_stat_is_group_writable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_fs_stat_is_group_executable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_fs_stat_is_other_readable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_fs_stat_is_other_writable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_fs_stat_is_other_executable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_stat_init
argument_list|(
operator|&
name|s2
argument_list|,
operator|&
name|p2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE_EQ
argument_list|(
name|atf_fs_stat_get_type
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|,
name|atf_fs_stat_dir_type
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_fs_stat_is_owner_readable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_fs_stat_is_owner_writable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_fs_stat_is_owner_executable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_fs_stat_is_group_readable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_fs_stat_is_group_writable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_fs_stat_is_group_executable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_fs_stat_is_other_readable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_fs_stat_is_other_writable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_fs_stat_is_other_executable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|atf_fs_stat_fini
argument_list|(
operator|&
name|s2
argument_list|)
expr_stmt|;
name|atf_fs_stat_fini
argument_list|(
operator|&
name|s1
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p2
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p1
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|mkdtemp_err
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|mkdtemp_err
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_mkdtemp function, "
literal|"error conditions"
argument_list|)
expr_stmt|;
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"require.user"
argument_list|,
literal|"unprivileged"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|mkdtemp_err
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_error_t
name|err
decl_stmt|;
name|atf_fs_path_t
name|p
decl_stmt|;
name|ATF_REQUIRE
argument_list|(
name|mkdir
argument_list|(
literal|"dir"
argument_list|,
literal|0555
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"dir/testdir.XXXXXX"
argument_list|)
argument_list|)
expr_stmt|;
name|err
operator|=
name|atf_fs_mkdtemp
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_is_error
argument_list|(
name|err
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_error_is
argument_list|(
name|err
argument_list|,
literal|"libc"
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK_EQ
argument_list|(
name|atf_libc_error_code
argument_list|(
name|err
argument_list|)
argument_list|,
name|EACCES
argument_list|)
expr_stmt|;
name|atf_error_free
argument_list|(
name|err
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
operator|!
name|exists
argument_list|(
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
name|strcmp
argument_list|(
name|atf_fs_path_cstring
argument_list|(
operator|&
name|p
argument_list|)
argument_list|,
literal|"dir/testdir.XXXXXX"
argument_list|)
operator|==
literal|0
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
block|}
end_block

begin_decl_stmt
specifier|static
name|void
name|do_umask_check
argument_list|(
name|atf_error_t
argument_list|(
operator|*
specifier|const
name|mk_func
argument_list|)
argument_list|(
name|atf_fs_path_t
operator|*
argument_list|)
argument_list|,
name|atf_fs_path_t
operator|*
name|path
argument_list|,
specifier|const
name|mode_t
name|test_mask
argument_list|,
specifier|const
name|char
operator|*
name|str_mask
argument_list|,
specifier|const
name|char
operator|*
name|exp_name
argument_list|)
block|{
name|char
name|buf
index|[
literal|1024
index|]
decl_stmt|;
name|int
name|old_umask
decl_stmt|;
name|atf_error_t
name|err
decl_stmt|;
name|printf
argument_list|(
literal|"Creating temporary %s with umask %s\n"
argument_list|,
name|exp_name
argument_list|,
name|str_mask
argument_list|)
expr_stmt|;
name|old_umask
operator|=
name|umask
argument_list|(
name|test_mask
argument_list|)
expr_stmt|;
name|err
operator|=
name|mk_func
argument_list|(
name|path
argument_list|)
expr_stmt|;
operator|(
name|void
operator|)
name|umask
argument_list|(
name|old_umask
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_is_error
argument_list|(
name|err
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_error_is
argument_list|(
name|err
argument_list|,
literal|"invalid_umask"
argument_list|)
argument_list|)
expr_stmt|;
name|atf_error_format
argument_list|(
name|err
argument_list|,
name|buf
argument_list|,
sizeof|sizeof
argument_list|(
name|buf
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
name|strstr
argument_list|(
name|buf
argument_list|,
name|exp_name
argument_list|)
operator|!=
name|NULL
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
name|strstr
argument_list|(
name|buf
argument_list|,
name|str_mask
argument_list|)
operator|!=
name|NULL
argument_list|)
expr_stmt|;
name|atf_error_free
argument_list|(
name|err
argument_list|)
expr_stmt|;
block|}
end_decl_stmt

begin_expr_stmt
name|ATF_TC
argument_list|(
name|mkdtemp_umask
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|mkdtemp_umask
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_mkdtemp function "
literal|"causing an error due to a too strict umask"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|mkdtemp_umask
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_fs_path_t
name|p
decl_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"testdir.XXXXXX"
argument_list|)
argument_list|)
expr_stmt|;
name|do_umask_check
argument_list|(
name|atf_fs_mkdtemp
argument_list|,
operator|&
name|p
argument_list|,
literal|00100
argument_list|,
literal|"00100"
argument_list|,
literal|"directory"
argument_list|)
expr_stmt|;
name|do_umask_check
argument_list|(
name|atf_fs_mkdtemp
argument_list|,
operator|&
name|p
argument_list|,
literal|00200
argument_list|,
literal|"00200"
argument_list|,
literal|"directory"
argument_list|)
expr_stmt|;
name|do_umask_check
argument_list|(
name|atf_fs_mkdtemp
argument_list|,
operator|&
name|p
argument_list|,
literal|00400
argument_list|,
literal|"00400"
argument_list|,
literal|"directory"
argument_list|)
expr_stmt|;
name|do_umask_check
argument_list|(
name|atf_fs_mkdtemp
argument_list|,
operator|&
name|p
argument_list|,
literal|00500
argument_list|,
literal|"00500"
argument_list|,
literal|"directory"
argument_list|)
expr_stmt|;
name|do_umask_check
argument_list|(
name|atf_fs_mkdtemp
argument_list|,
operator|&
name|p
argument_list|,
literal|00600
argument_list|,
literal|"00600"
argument_list|,
literal|"directory"
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|mkstemp_ok
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|mkstemp_ok
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_mkstemp function, "
literal|"successful execution"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|mkstemp_ok
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|int
name|fd1
decl_stmt|,
name|fd2
decl_stmt|;
name|atf_fs_path_t
name|p1
decl_stmt|,
name|p2
decl_stmt|;
name|atf_fs_stat_t
name|s1
decl_stmt|,
name|s2
decl_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p1
argument_list|,
literal|"testfile.XXXXXX"
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p2
argument_list|,
literal|"testfile.XXXXXX"
argument_list|)
argument_list|)
expr_stmt|;
name|fd1
operator|=
name|fd2
operator|=
operator|-
literal|1
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_mkstemp
argument_list|(
operator|&
name|p1
argument_list|,
operator|&
name|fd1
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_mkstemp
argument_list|(
operator|&
name|p2
argument_list|,
operator|&
name|fd2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
operator|!
name|atf_equal_fs_path_fs_path
argument_list|(
operator|&
name|p1
argument_list|,
operator|&
name|p2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|exists
argument_list|(
operator|&
name|p1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|exists
argument_list|(
operator|&
name|p2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
name|fd1
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
name|fd2
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
name|write
argument_list|(
name|fd1
argument_list|,
literal|"foo"
argument_list|,
literal|3
argument_list|)
operator|==
literal|3
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
name|write
argument_list|(
name|fd2
argument_list|,
literal|"bar"
argument_list|,
literal|3
argument_list|)
operator|==
literal|3
argument_list|)
expr_stmt|;
name|close
argument_list|(
name|fd1
argument_list|)
expr_stmt|;
name|close
argument_list|(
name|fd2
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_stat_init
argument_list|(
operator|&
name|s1
argument_list|,
operator|&
name|p1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK_EQ
argument_list|(
name|atf_fs_stat_get_type
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|,
name|atf_fs_stat_reg_type
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
name|atf_fs_stat_is_owner_readable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
name|atf_fs_stat_is_owner_writable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
operator|!
name|atf_fs_stat_is_owner_executable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
operator|!
name|atf_fs_stat_is_group_readable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
operator|!
name|atf_fs_stat_is_group_writable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
operator|!
name|atf_fs_stat_is_group_executable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
operator|!
name|atf_fs_stat_is_other_readable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
operator|!
name|atf_fs_stat_is_other_writable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
operator|!
name|atf_fs_stat_is_other_executable
argument_list|(
operator|&
name|s1
argument_list|)
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_stat_init
argument_list|(
operator|&
name|s2
argument_list|,
operator|&
name|p2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK_EQ
argument_list|(
name|atf_fs_stat_get_type
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|,
name|atf_fs_stat_reg_type
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
name|atf_fs_stat_is_owner_readable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
name|atf_fs_stat_is_owner_writable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
operator|!
name|atf_fs_stat_is_owner_executable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
operator|!
name|atf_fs_stat_is_group_readable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
operator|!
name|atf_fs_stat_is_group_writable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
operator|!
name|atf_fs_stat_is_group_executable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
operator|!
name|atf_fs_stat_is_other_readable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
operator|!
name|atf_fs_stat_is_other_writable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
operator|!
name|atf_fs_stat_is_other_executable
argument_list|(
operator|&
name|s2
argument_list|)
argument_list|)
expr_stmt|;
name|atf_fs_stat_fini
argument_list|(
operator|&
name|s2
argument_list|)
expr_stmt|;
name|atf_fs_stat_fini
argument_list|(
operator|&
name|s1
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p2
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p1
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|mkstemp_err
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|mkstemp_err
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_mkstemp function, "
literal|"error conditions"
argument_list|)
expr_stmt|;
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"require.user"
argument_list|,
literal|"unprivileged"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|mkstemp_err
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|int
name|fd
decl_stmt|;
name|atf_error_t
name|err
decl_stmt|;
name|atf_fs_path_t
name|p
decl_stmt|;
name|ATF_REQUIRE
argument_list|(
name|mkdir
argument_list|(
literal|"dir"
argument_list|,
literal|0555
argument_list|)
operator|!=
operator|-
literal|1
argument_list|)
expr_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"dir/testfile.XXXXXX"
argument_list|)
argument_list|)
expr_stmt|;
name|fd
operator|=
literal|1234
expr_stmt|;
name|err
operator|=
name|atf_fs_mkstemp
argument_list|(
operator|&
name|p
argument_list|,
operator|&
name|fd
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_is_error
argument_list|(
name|err
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_REQUIRE
argument_list|(
name|atf_error_is
argument_list|(
name|err
argument_list|,
literal|"libc"
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK_EQ
argument_list|(
name|atf_libc_error_code
argument_list|(
name|err
argument_list|)
argument_list|,
name|EACCES
argument_list|)
expr_stmt|;
name|atf_error_free
argument_list|(
name|err
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
operator|!
name|exists
argument_list|(
operator|&
name|p
argument_list|)
argument_list|)
expr_stmt|;
name|ATF_CHECK
argument_list|(
name|strcmp
argument_list|(
name|atf_fs_path_cstring
argument_list|(
operator|&
name|p
argument_list|)
argument_list|,
literal|"dir/testfile.XXXXXX"
argument_list|)
operator|==
literal|0
argument_list|)
expr_stmt|;
name|ATF_CHECK_EQ
argument_list|(
name|fd
argument_list|,
literal|1234
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
block|}
end_block

begin_expr_stmt
name|ATF_TC
argument_list|(
name|mkstemp_umask
argument_list|)
expr_stmt|;
end_expr_stmt

begin_macro
name|ATF_TC_HEAD
argument_list|(
argument|mkstemp_umask
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_tc_set_md_var
argument_list|(
name|tc
argument_list|,
literal|"descr"
argument_list|,
literal|"Tests the atf_fs_mkstemp function "
literal|"causing an error due to a too strict umask"
argument_list|)
expr_stmt|;
block|}
end_block

begin_macro
name|ATF_TC_BODY
argument_list|(
argument|mkstemp_umask
argument_list|,
argument|tc
argument_list|)
end_macro

begin_block
block|{
name|atf_fs_path_t
name|p
decl_stmt|;
name|RE
argument_list|(
name|atf_fs_path_init_fmt
argument_list|(
operator|&
name|p
argument_list|,
literal|"testfile.XXXXXX"
argument_list|)
argument_list|)
expr_stmt|;
name|do_umask_check
argument_list|(
name|mkstemp_discard_fd
argument_list|,
operator|&
name|p
argument_list|,
literal|00100
argument_list|,
literal|"00100"
argument_list|,
literal|"regular file"
argument_list|)
expr_stmt|;
name|do_umask_check
argument_list|(
name|mkstemp_discard_fd
argument_list|,
operator|&
name|p
argument_list|,
literal|00200
argument_list|,
literal|"00200"
argument_list|,
literal|"regular file"
argument_list|)
expr_stmt|;
name|do_umask_check
argument_list|(
name|mkstemp_discard_fd
argument_list|,
operator|&
name|p
argument_list|,
literal|00400
argument_list|,
literal|"00400"
argument_list|,
literal|"regular file"
argument_list|)
expr_stmt|;
name|atf_fs_path_fini
argument_list|(
operator|&
name|p
argument_list|)
expr_stmt|;
block|}
end_block

begin_comment
comment|/* ---------------------------------------------------------------------  * Main.  * --------------------------------------------------------------------- */
end_comment

begin_macro
name|ATF_TP_ADD_TCS
argument_list|(
argument|tp
argument_list|)
end_macro

begin_block
block|{
comment|/* Add the tests for the "atf_fs_path" type. */
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|path_normalize
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|path_copy
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|path_is_absolute
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|path_is_root
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|path_branch_path
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|path_leaf_name
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|path_append
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|path_to_absolute
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|path_equal
argument_list|)
expr_stmt|;
comment|/* Add the tests for the "atf_fs_stat" type. */
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|stat_mode
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|stat_type
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|stat_perms
argument_list|)
expr_stmt|;
comment|/* Add the tests for the free functions. */
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|eaccess
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|exists
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|getcwd
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|rmdir_empty
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|rmdir_enotempty
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|rmdir_eperm
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|mkdtemp_ok
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|mkdtemp_err
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|mkdtemp_umask
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|mkstemp_ok
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|mkstemp_err
argument_list|)
expr_stmt|;
name|ATF_TP_ADD_TC
argument_list|(
name|tp
argument_list|,
name|mkstemp_umask
argument_list|)
expr_stmt|;
return|return
name|atf_no_error
argument_list|()
return|;
block|}
end_block

end_unit

