begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/* $NetBSD: all_sync_ops_linkable.c,v 1.4 2014/02/21 10:26:25 martin Exp $ */
end_comment

begin_comment
comment|/*-  * Copyright (c) 2014 The NetBSD Foundation, Inc.  * All rights reserved.  *  * This code is derived from software contributed to The NetBSD Foundation  * by Martin Husemann<martin@NetBSD.org>.  *  * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions  * are met:  * 1. Redistributions of source code must retain the above copyright  *    notice, this list of conditions and the following disclaimer.  * 2. Redistributions in binary form must reproduce the above copyright  *    notice, this list of conditions and the following disclaimer in the  *    documentation and/or other materials provided with the distribution.  *  * THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS  * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED  * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR  * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS  * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR  * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF  * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS  * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN  * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)  * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE  * POSSIBILITY OF SUCH DAMAGE.  */
end_comment

begin_comment
comment|/*  * This is a simple link-time test to verify all builtin atomic sync  * operations are available. Depending on the exact cpu/arch code generator  * options, some of these need support functions (which on NetBSD we  * typically provide in src/common/lib/libc/atomic).  *  * The list of operations has been extracted from sync-builtins.def file  * in the gcc distribution (as of gcc 4.8.2).  */
end_comment

begin_include
include|#
directive|include
file|<machine/types.h>
end_include

begin_include
include|#
directive|include
file|<sys/inttypes.h>
end_include

begin_decl_stmt
specifier|volatile
name|uint8_t
name|u8
init|=
literal|0
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|volatile
name|uint16_t
name|u16
init|=
literal|0
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|volatile
name|uint32_t
name|u32
init|=
literal|0
decl_stmt|;
end_decl_stmt

begin_ifdef
ifdef|#
directive|ifdef
name|__HAVE_ATOMIC64_OPS
end_ifdef

begin_decl_stmt
specifier|volatile
name|uint64_t
name|u64
init|=
literal|0
decl_stmt|;
end_decl_stmt

begin_endif
endif|#
directive|endif
end_endif

begin_function
name|int
name|main
parameter_list|(
name|int
name|argc
parameter_list|,
name|char
modifier|*
modifier|*
name|argv
parameter_list|)
block|{
name|__sync_synchronize
argument_list|()
expr_stmt|;
name|__sync_add_and_fetch
argument_list|(
operator|&
name|u8
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|__sync_add_and_fetch_1
argument_list|(
operator|&
name|u8
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|__sync_add_and_fetch_2
argument_list|(
operator|&
name|u16
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|__sync_add_and_fetch_4
argument_list|(
operator|&
name|u32
argument_list|,
literal|1
argument_list|)
expr_stmt|;
ifdef|#
directive|ifdef
name|__HAVE_ATOMIC64_OPS
name|__sync_add_and_fetch_8
argument_list|(
operator|&
name|u64
argument_list|,
literal|1
argument_list|)
expr_stmt|;
endif|#
directive|endif
name|__sync_bool_compare_and_swap
argument_list|(
operator|&
name|u8
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|__sync_bool_compare_and_swap_1
argument_list|(
operator|&
name|u8
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|__sync_bool_compare_and_swap_2
argument_list|(
operator|&
name|u16
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
expr_stmt|;
name|__sync_bool_compare_and_swap_4
argument_list|(
operator|&
name|u32
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
expr_stmt|;
ifdef|#
directive|ifdef
name|__HAVE_ATOMIC64_OPS
name|__sync_bool_compare_and_swap_8
argument_list|(
operator|&
name|u64
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
expr_stmt|;
endif|#
directive|endif
name|__sync_fetch_and_add
argument_list|(
operator|&
name|u8
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|__sync_fetch_and_add_1
argument_list|(
operator|&
name|u8
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|__sync_fetch_and_add_2
argument_list|(
operator|&
name|u16
argument_list|,
literal|1
argument_list|)
expr_stmt|;
name|__sync_fetch_and_add_4
argument_list|(
operator|&
name|u32
argument_list|,
literal|1
argument_list|)
expr_stmt|;
ifdef|#
directive|ifdef
name|__HAVE_ATOMIC64_OPS
name|__sync_fetch_and_add_8
argument_list|(
operator|&
name|u64
argument_list|,
literal|1
argument_list|)
expr_stmt|;
endif|#
directive|endif
name|__sync_fetch_and_and
argument_list|(
operator|&
name|u8
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
name|__sync_fetch_and_and_1
argument_list|(
operator|&
name|u8
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
name|__sync_fetch_and_and_2
argument_list|(
operator|&
name|u16
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
name|__sync_fetch_and_and_4
argument_list|(
operator|&
name|u32
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
ifdef|#
directive|ifdef
name|__HAVE_ATOMIC64_OPS
name|__sync_fetch_and_and_8
argument_list|(
operator|&
name|u64
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
endif|#
directive|endif
ifndef|#
directive|ifndef
name|__clang__
name|__sync_fetch_and_nand
argument_list|(
operator|&
name|u8
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
name|__sync_fetch_and_nand_1
argument_list|(
operator|&
name|u8
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
name|__sync_fetch_and_nand_2
argument_list|(
operator|&
name|u16
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
name|__sync_fetch_and_nand_4
argument_list|(
operator|&
name|u32
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
ifdef|#
directive|ifdef
name|__HAVE_ATOMIC64_OPS
name|__sync_fetch_and_nand_8
argument_list|(
operator|&
name|u64
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
endif|#
directive|endif
endif|#
directive|endif
name|__sync_fetch_and_or
argument_list|(
operator|&
name|u8
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
name|__sync_fetch_and_or_1
argument_list|(
operator|&
name|u8
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
name|__sync_fetch_and_or_2
argument_list|(
operator|&
name|u16
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
name|__sync_fetch_and_or_4
argument_list|(
operator|&
name|u32
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
ifdef|#
directive|ifdef
name|__HAVE_ATOMIC64_OPS
name|__sync_fetch_and_or_8
argument_list|(
operator|&
name|u64
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
endif|#
directive|endif
name|__sync_fetch_and_sub
argument_list|(
operator|&
name|u8
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
name|__sync_fetch_and_sub_1
argument_list|(
operator|&
name|u8
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
name|__sync_fetch_and_sub_2
argument_list|(
operator|&
name|u16
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
name|__sync_fetch_and_sub_4
argument_list|(
operator|&
name|u32
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
ifdef|#
directive|ifdef
name|__HAVE_ATOMIC64_OPS
name|__sync_fetch_and_sub_8
argument_list|(
operator|&
name|u64
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
endif|#
directive|endif
name|__sync_fetch_and_xor
argument_list|(
operator|&
name|u8
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
name|__sync_fetch_and_xor_1
argument_list|(
operator|&
name|u8
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
name|__sync_fetch_and_xor_2
argument_list|(
operator|&
name|u16
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
name|__sync_fetch_and_xor_4
argument_list|(
operator|&
name|u32
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
ifdef|#
directive|ifdef
name|__HAVE_ATOMIC64_OPS
name|__sync_fetch_and_xor_8
argument_list|(
operator|&
name|u64
argument_list|,
literal|0x80
argument_list|)
expr_stmt|;
endif|#
directive|endif
name|__sync_lock_release
argument_list|(
operator|&
name|u8
argument_list|)
expr_stmt|;
name|__sync_lock_release_1
argument_list|(
operator|&
name|u8
argument_list|)
expr_stmt|;
name|__sync_lock_release_2
argument_list|(
operator|&
name|u16
argument_list|)
expr_stmt|;
name|__sync_lock_release_4
argument_list|(
operator|&
name|u32
argument_list|)
expr_stmt|;
ifdef|#
directive|ifdef
name|__HAVE_ATOMIC64_OPS
name|__sync_lock_release_8
argument_list|(
operator|&
name|u64
argument_list|)
expr_stmt|;
endif|#
directive|endif
name|__sync_lock_test_and_set
argument_list|(
operator|&
name|u8
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|__sync_lock_test_and_set_1
argument_list|(
operator|&
name|u8
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|__sync_lock_test_and_set_2
argument_list|(
operator|&
name|u16
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|__sync_lock_test_and_set_4
argument_list|(
operator|&
name|u32
argument_list|,
literal|5
argument_list|)
expr_stmt|;
ifdef|#
directive|ifdef
name|__HAVE_ATOMIC64_OPS
name|__sync_lock_test_and_set_8
argument_list|(
operator|&
name|u64
argument_list|,
literal|5
argument_list|)
expr_stmt|;
endif|#
directive|endif
ifndef|#
directive|ifndef
name|__clang__
name|__sync_nand_and_fetch
argument_list|(
operator|&
name|u8
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|__sync_nand_and_fetch_1
argument_list|(
operator|&
name|u8
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|__sync_nand_and_fetch_2
argument_list|(
operator|&
name|u16
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|__sync_nand_and_fetch_4
argument_list|(
operator|&
name|u32
argument_list|,
literal|5
argument_list|)
expr_stmt|;
ifdef|#
directive|ifdef
name|__HAVE_ATOMIC64_OPS
name|__sync_nand_and_fetch_8
argument_list|(
operator|&
name|u64
argument_list|,
literal|5
argument_list|)
expr_stmt|;
endif|#
directive|endif
endif|#
directive|endif
name|__sync_or_and_fetch
argument_list|(
operator|&
name|u8
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|__sync_or_and_fetch_1
argument_list|(
operator|&
name|u8
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|__sync_or_and_fetch_2
argument_list|(
operator|&
name|u16
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|__sync_or_and_fetch_4
argument_list|(
operator|&
name|u32
argument_list|,
literal|5
argument_list|)
expr_stmt|;
ifdef|#
directive|ifdef
name|__HAVE_ATOMIC64_OPS
name|__sync_or_and_fetch_8
argument_list|(
operator|&
name|u64
argument_list|,
literal|5
argument_list|)
expr_stmt|;
endif|#
directive|endif
name|__sync_sub_and_fetch
argument_list|(
operator|&
name|u8
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|__sync_sub_and_fetch_1
argument_list|(
operator|&
name|u8
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|__sync_sub_and_fetch_2
argument_list|(
operator|&
name|u16
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|__sync_sub_and_fetch_4
argument_list|(
operator|&
name|u32
argument_list|,
literal|5
argument_list|)
expr_stmt|;
ifdef|#
directive|ifdef
name|__HAVE_ATOMIC64_OPS
name|__sync_sub_and_fetch_8
argument_list|(
operator|&
name|u64
argument_list|,
literal|5
argument_list|)
expr_stmt|;
endif|#
directive|endif
name|__sync_val_compare_and_swap
argument_list|(
operator|&
name|u8
argument_list|,
literal|5
argument_list|,
literal|9
argument_list|)
expr_stmt|;
name|__sync_val_compare_and_swap_1
argument_list|(
operator|&
name|u8
argument_list|,
literal|5
argument_list|,
literal|9
argument_list|)
expr_stmt|;
name|__sync_val_compare_and_swap_2
argument_list|(
operator|&
name|u16
argument_list|,
literal|5
argument_list|,
literal|9
argument_list|)
expr_stmt|;
name|__sync_val_compare_and_swap_4
argument_list|(
operator|&
name|u32
argument_list|,
literal|5
argument_list|,
literal|9
argument_list|)
expr_stmt|;
ifdef|#
directive|ifdef
name|__HAVE_ATOMIC64_OPS
name|__sync_val_compare_and_swap_8
argument_list|(
operator|&
name|u64
argument_list|,
literal|5
argument_list|,
literal|9
argument_list|)
expr_stmt|;
endif|#
directive|endif
name|__sync_xor_and_fetch
argument_list|(
operator|&
name|u8
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|__sync_xor_and_fetch_1
argument_list|(
operator|&
name|u8
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|__sync_xor_and_fetch_2
argument_list|(
operator|&
name|u16
argument_list|,
literal|5
argument_list|)
expr_stmt|;
name|__sync_xor_and_fetch_4
argument_list|(
operator|&
name|u32
argument_list|,
literal|5
argument_list|)
expr_stmt|;
ifdef|#
directive|ifdef
name|__HAVE_ATOMIC64_OPS
name|__sync_xor_and_fetch_8
argument_list|(
operator|&
name|u64
argument_list|,
literal|5
argument_list|)
expr_stmt|;
endif|#
directive|endif
return|return
literal|0
return|;
block|}
end_function

end_unit

