begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * Device probe and attach routines for the following  * Advanced Systems Inc. SCSI controllers:  *  *   Connectivity Products:  *	ABP920   - Bus-Master PCI (16 CDB)  *	ABP930   - Bus-Master PCI (16 CDB) *  *	ABP930U  - Bus-Master PCI Ultra (16 CDB)  *	ABP930UA - Bus-Master PCI Ultra (16 CDB)  *	ABP960   - Bus-Master PCI MAC/PC (16 CDB) **  *	ABP960U  - Bus-Master PCI MAC/PC Ultra (16 CDB)  *  *   Single Channel Products:  *	ABP940 - Bus-Master PCI (240 CDB)  *	ABP940U - Bus-Master PCI Ultra (240 CDB)  *	ABP970 - Bus-Master PCI MAC/PC (240 CDB)  *	ABP970U - Bus-Master PCI MAC/PC Ultra (240 CDB)  *  *   Dual Channel Products:    *	ABP950 - Dual Channel Bus-Master PCI (240 CDB Per Channel)  *  *   Footnotes:  *	 * This board has been sold by SIIG as the Fast SCSI Pro PCI.  *	** This board has been sold by Iomega as a Jaz Jet PCI adapter.   *  * Copyright (c) 1997 Justin Gibbs.  * All rights reserved.  *  * Redistribution and use in source and binary forms, with or without  * modification, are permitted provided that the following conditions  * are met:  * 1. Redistributions of source code must retain the above copyright  *    notice, this list of conditions, and the following disclaimer,  *    without modification, immediately at the beginning of the file.  * 2. The name of the author may not be used to endorse or promote products  *    derived from this software without specific prior written permission.  *  * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND  * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE  * ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR  * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS  * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)  * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT  * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY  * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF  * SUCH DAMAGE.  *  * $FreeBSD$  */
end_comment

begin_include
include|#
directive|include
file|<pci.h>
end_include

begin_if
if|#
directive|if
name|NPCI
operator|>
literal|0
end_if

begin_include
include|#
directive|include
file|<sys/param.h>
end_include

begin_include
include|#
directive|include
file|<sys/systm.h>
end_include

begin_include
include|#
directive|include
file|<sys/kernel.h>
end_include

begin_include
include|#
directive|include
file|<machine/bus_pio.h>
end_include

begin_include
include|#
directive|include
file|<machine/bus.h>
end_include

begin_include
include|#
directive|include
file|<pci/pcireg.h>
end_include

begin_include
include|#
directive|include
file|<pci/pcivar.h>
end_include

begin_include
include|#
directive|include
file|<dev/advansys/advansys.h>
end_include

begin_define
define|#
directive|define
name|PCI_BASEADR0
value|PCI_MAP_REG_START
end_define

begin_comment
comment|/* I/O Address */
end_comment

begin_define
define|#
directive|define
name|PCI_BASEADR1
value|PCI_MAP_REG_START + 4
end_define

begin_comment
comment|/* Mem I/O Address */
end_comment

begin_define
define|#
directive|define
name|PCI_DEVICE_ID_ADVANSYS_1200A
value|0x110010CD
end_define

begin_define
define|#
directive|define
name|PCI_DEVICE_ID_ADVANSYS_1200B
value|0x120010CD
end_define

begin_define
define|#
directive|define
name|PCI_DEVICE_ID_ADVANSYS_ULTRA
value|0x130010CD
end_define

begin_define
define|#
directive|define
name|PCI_DEVICE_REV_ADVANSYS_3150
value|0x02
end_define

begin_define
define|#
directive|define
name|PCI_DEVICE_REV_ADVANSYS_3050
value|0x03
end_define

begin_define
define|#
directive|define
name|ADV_PCI_MAX_DMA_ADDR
value|(0xFFFFFFFFL)
end_define

begin_define
define|#
directive|define
name|ADV_PCI_MAX_DMA_COUNT
value|(0xFFFFFFFFL)
end_define

begin_function_decl
specifier|static
specifier|const
name|char
modifier|*
name|advpciprobe
parameter_list|(
name|pcici_t
name|tag
parameter_list|,
name|pcidi_t
name|type
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|advpciattach
parameter_list|(
name|pcici_t
name|config_id
parameter_list|,
name|int
name|unit
parameter_list|)
function_decl|;
end_function_decl

begin_comment
comment|/*   * The overrun buffer shared amongst all PCI adapters.  */
end_comment

begin_decl_stmt
specifier|static
name|u_int8_t
modifier|*
name|overrun_buf
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|bus_dma_tag_t
name|overrun_dmat
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|bus_dmamap_t
name|overrun_dmamap
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|bus_addr_t
name|overrun_physbase
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|static
name|struct
name|pci_device
name|adv_pci_driver
init|=
block|{
literal|"adv"
block|,
name|advpciprobe
block|,
name|advpciattach
block|,
operator|&
name|adv_unit
block|,
name|NULL
block|}
decl_stmt|;
end_decl_stmt

begin_expr_stmt
name|DATA_SET
argument_list|(
name|pcidevice_set
argument_list|,
name|adv_pci_driver
argument_list|)
expr_stmt|;
end_expr_stmt

begin_function
specifier|static
specifier|const
name|char
modifier|*
name|advpciprobe
parameter_list|(
name|pcici_t
name|tag
parameter_list|,
name|pcidi_t
name|type
parameter_list|)
block|{
name|int
name|rev
init|=
name|pci_conf_read
argument_list|(
name|tag
argument_list|,
name|PCI_CLASS_REG
argument_list|)
operator|&
literal|0xff
decl_stmt|;
switch|switch
condition|(
name|type
condition|)
block|{
case|case
name|PCI_DEVICE_ID_ADVANSYS_1200A
case|:
return|return
operator|(
literal|"AdvanSys ASC1200A SCSI controller"
operator|)
return|;
case|case
name|PCI_DEVICE_ID_ADVANSYS_1200B
case|:
return|return
operator|(
literal|"AdvanSys ASC1200B SCSI controller"
operator|)
return|;
case|case
name|PCI_DEVICE_ID_ADVANSYS_ULTRA
case|:
if|if
condition|(
name|rev
operator|==
name|PCI_DEVICE_REV_ADVANSYS_3150
condition|)
return|return
operator|(
literal|"AdvanSys ASC3150 Ultra SCSI controller"
operator|)
return|;
else|else
return|return
operator|(
literal|"AdvanSys ASC3050 Ultra SCSI controller"
operator|)
return|;
break|break;
default|default:
break|break;
block|}
return|return
operator|(
name|NULL
operator|)
return|;
block|}
end_function

begin_function
specifier|static
name|void
name|advpciattach
parameter_list|(
name|pcici_t
name|config_id
parameter_list|,
name|int
name|unit
parameter_list|)
block|{
name|u_int16_t
name|io_port
decl_stmt|;
name|struct
name|adv_softc
modifier|*
name|adv
decl_stmt|;
name|u_int32_t
name|id
decl_stmt|;
name|u_int32_t
name|command
decl_stmt|;
name|int
name|error
decl_stmt|;
comment|/* 	 * Determine the chip version. 	 */
name|id
operator|=
name|pci_cfgread
argument_list|(
name|config_id
argument_list|,
name|PCI_ID_REG
argument_list|,
comment|/*bytes*/
literal|4
argument_list|)
expr_stmt|;
name|command
operator|=
name|pci_cfgread
argument_list|(
name|config_id
argument_list|,
name|PCIR_COMMAND
argument_list|,
comment|/*bytes*/
literal|1
argument_list|)
expr_stmt|;
comment|/* 	 * These cards do not allow memory mapped accesses, so we must 	 * ensure that I/O accesses are available or we won't be able 	 * to talk to them. 	 */
if|if
condition|(
operator|(
name|command
operator|&
operator|(
name|PCIM_CMD_PORTEN
operator||
name|PCIM_CMD_BUSMASTEREN
operator|)
operator|)
operator|!=
operator|(
name|PCIM_CMD_PORTEN
operator||
name|PCIM_CMD_BUSMASTEREN
operator|)
condition|)
block|{
name|command
operator||=
name|PCIM_CMD_PORTEN
operator||
name|PCIM_CMD_BUSMASTEREN
expr_stmt|;
name|pci_cfgwrite
argument_list|(
name|config_id
argument_list|,
name|PCIR_COMMAND
argument_list|,
name|command
argument_list|,
comment|/*bytes*/
literal|1
argument_list|)
expr_stmt|;
block|}
comment|/* 	 * Early chips can't handle non-zero latency timer settings. 	 */
if|if
condition|(
name|id
operator|==
name|PCI_DEVICE_ID_ADVANSYS_1200A
operator|||
name|id
operator|==
name|PCI_DEVICE_ID_ADVANSYS_1200B
condition|)
block|{
name|pci_cfgwrite
argument_list|(
name|config_id
argument_list|,
name|PCIR_LATTIMER
argument_list|,
comment|/*value*/
literal|0
argument_list|,
comment|/*bytes*/
literal|1
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|pci_map_port
argument_list|(
name|config_id
argument_list|,
name|PCI_BASEADR0
argument_list|,
operator|&
name|io_port
argument_list|)
operator|==
literal|0
condition|)
return|return;
if|if
condition|(
name|adv_find_signature
argument_list|(
name|I386_BUS_SPACE_IO
argument_list|,
name|io_port
argument_list|)
operator|==
literal|0
condition|)
return|return;
name|adv
operator|=
name|adv_alloc
argument_list|(
name|unit
argument_list|,
name|I386_BUS_SPACE_IO
argument_list|,
name|io_port
argument_list|)
expr_stmt|;
if|if
condition|(
name|adv
operator|==
name|NULL
condition|)
return|return;
comment|/* Allocate a dmatag for our transfer DMA maps */
comment|/* XXX Should be a child of the PCI bus dma tag */
name|error
operator|=
name|bus_dma_tag_create
argument_list|(
comment|/*parent*/
name|NULL
argument_list|,
comment|/*alignment*/
literal|1
argument_list|,
comment|/*boundary*/
literal|0
argument_list|,
comment|/*lowaddr*/
name|ADV_PCI_MAX_DMA_ADDR
argument_list|,
comment|/*highaddr*/
name|BUS_SPACE_MAXADDR
argument_list|,
comment|/*filter*/
name|NULL
argument_list|,
comment|/*filterarg*/
name|NULL
argument_list|,
comment|/*maxsize*/
name|BUS_SPACE_MAXSIZE_32BIT
argument_list|,
comment|/*nsegments*/
name|BUS_SPACE_UNRESTRICTED
argument_list|,
comment|/*maxsegsz*/
name|ADV_PCI_MAX_DMA_COUNT
argument_list|,
comment|/*flags*/
literal|0
argument_list|,
operator|&
name|adv
operator|->
name|parent_dmat
argument_list|)
expr_stmt|;
if|if
condition|(
name|error
operator|!=
literal|0
condition|)
block|{
name|printf
argument_list|(
literal|"%s: Could not allocate DMA tag - error %d\n"
argument_list|,
name|adv_name
argument_list|(
name|adv
argument_list|)
argument_list|,
name|error
argument_list|)
expr_stmt|;
name|adv_free
argument_list|(
name|adv
argument_list|)
expr_stmt|;
return|return;
block|}
name|adv
operator|->
name|init_level
operator|++
expr_stmt|;
if|if
condition|(
name|overrun_buf
operator|==
name|NULL
condition|)
block|{
comment|/* Need to allocate our overrun buffer */
if|if
condition|(
name|bus_dma_tag_create
argument_list|(
name|adv
operator|->
name|parent_dmat
argument_list|,
comment|/*alignment*/
literal|8
argument_list|,
comment|/*boundary*/
literal|0
argument_list|,
name|ADV_PCI_MAX_DMA_ADDR
argument_list|,
name|BUS_SPACE_MAXADDR
argument_list|,
comment|/*filter*/
name|NULL
argument_list|,
comment|/*filterarg*/
name|NULL
argument_list|,
name|ADV_OVERRUN_BSIZE
argument_list|,
comment|/*nsegments*/
literal|1
argument_list|,
name|BUS_SPACE_MAXSIZE_32BIT
argument_list|,
comment|/*flags*/
literal|0
argument_list|,
operator|&
name|overrun_dmat
argument_list|)
operator|!=
literal|0
condition|)
block|{
name|bus_dma_tag_destroy
argument_list|(
name|adv
operator|->
name|parent_dmat
argument_list|)
expr_stmt|;
name|adv_free
argument_list|(
name|adv
argument_list|)
expr_stmt|;
return|return;
block|}
if|if
condition|(
name|bus_dmamem_alloc
argument_list|(
name|overrun_dmat
argument_list|,
operator|(
name|void
operator|*
operator|*
operator|)
operator|&
name|overrun_buf
argument_list|,
name|BUS_DMA_NOWAIT
argument_list|,
operator|&
name|overrun_dmamap
argument_list|)
operator|!=
literal|0
condition|)
block|{
name|bus_dma_tag_destroy
argument_list|(
name|overrun_dmat
argument_list|)
expr_stmt|;
name|bus_dma_tag_destroy
argument_list|(
name|adv
operator|->
name|parent_dmat
argument_list|)
expr_stmt|;
name|adv_free
argument_list|(
name|adv
argument_list|)
expr_stmt|;
return|return;
block|}
comment|/* And permanently map it in */
name|bus_dmamap_load
argument_list|(
name|overrun_dmat
argument_list|,
name|overrun_dmamap
argument_list|,
name|overrun_buf
argument_list|,
name|ADV_OVERRUN_BSIZE
argument_list|,
name|adv_map
argument_list|,
operator|&
name|overrun_physbase
argument_list|,
comment|/*flags*/
literal|0
argument_list|)
expr_stmt|;
block|}
name|adv
operator|->
name|overrun_physbase
operator|=
name|overrun_physbase
expr_stmt|;
comment|/* 	 * Stop the chip. 	 */
name|ADV_OUTB
argument_list|(
name|adv
argument_list|,
name|ADV_CHIP_CTRL
argument_list|,
name|ADV_CC_HALT
argument_list|)
expr_stmt|;
name|ADV_OUTW
argument_list|(
name|adv
argument_list|,
name|ADV_CHIP_STATUS
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|adv
operator|->
name|chip_version
operator|=
name|ADV_INB
argument_list|(
name|adv
argument_list|,
name|ADV_NONEISA_CHIP_REVISION
argument_list|)
expr_stmt|;
name|adv
operator|->
name|type
operator|=
name|ADV_PCI
expr_stmt|;
comment|/* 	 * Setup active negation and signal filtering. 	 */
block|{
name|u_int8_t
name|extra_cfg
decl_stmt|;
if|if
condition|(
name|adv
operator|->
name|chip_version
operator|>=
name|ADV_CHIP_VER_PCI_ULTRA_3150
condition|)
name|adv
operator|->
name|type
operator||=
name|ADV_ULTRA
expr_stmt|;
if|if
condition|(
name|adv
operator|->
name|chip_version
operator|==
name|ADV_CHIP_VER_PCI_ULTRA_3150
condition|)
name|extra_cfg
operator|=
name|ADV_IFC_ACT_NEG
operator||
name|ADV_IFC_SLEW_RATE
expr_stmt|;
elseif|else
if|if
condition|(
name|adv
operator|->
name|chip_version
operator|==
name|ADV_CHIP_VER_PCI_ULTRA_3050
condition|)
name|extra_cfg
operator|=
name|ADV_IFC_ACT_NEG
operator||
name|ADV_IFC_WR_EN_FILTER
expr_stmt|;
else|else
name|extra_cfg
operator|=
name|ADV_IFC_ACT_NEG
operator||
name|ADV_IFC_SLEW_RATE
expr_stmt|;
name|ADV_OUTB
argument_list|(
name|adv
argument_list|,
name|ADV_REG_IFC
argument_list|,
name|extra_cfg
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|adv_init
argument_list|(
name|adv
argument_list|)
operator|!=
literal|0
condition|)
block|{
name|adv_free
argument_list|(
name|adv
argument_list|)
expr_stmt|;
return|return;
block|}
name|adv
operator|->
name|max_dma_count
operator|=
name|ADV_PCI_MAX_DMA_COUNT
expr_stmt|;
name|adv
operator|->
name|max_dma_addr
operator|=
name|ADV_PCI_MAX_DMA_ADDR
expr_stmt|;
if|#
directive|if
name|CC_DISABLE_PCI_PARITY_INT
block|{
name|u_int16_t
name|config_msw
decl_stmt|;
name|config_msw
operator|=
name|ADV_INW
argument_list|(
name|adv
argument_list|,
name|ADV_CONFIG_MSW
argument_list|)
expr_stmt|;
name|config_msw
operator|&=
literal|0xFFC0
expr_stmt|;
name|ADV_OUTW
argument_list|(
name|adv
argument_list|,
name|ADV_CONFIG_MSW
argument_list|,
name|config_msw
argument_list|)
expr_stmt|;
block|}
endif|#
directive|endif
if|if
condition|(
name|id
operator|==
name|PCI_DEVICE_ID_ADVANSYS_1200A
operator|||
name|id
operator|==
name|PCI_DEVICE_ID_ADVANSYS_1200B
condition|)
block|{
name|adv
operator|->
name|bug_fix_control
operator||=
name|ADV_BUG_FIX_IF_NOT_DWB
expr_stmt|;
name|adv
operator|->
name|bug_fix_control
operator||=
name|ADV_BUG_FIX_ASYN_USE_SYN
expr_stmt|;
name|adv
operator|->
name|fix_asyn_xfer
operator|=
operator|~
literal|0
expr_stmt|;
block|}
if|if
condition|(
operator|(
name|pci_map_int
argument_list|(
name|config_id
argument_list|,
name|adv_intr
argument_list|,
operator|(
name|void
operator|*
operator|)
name|adv
argument_list|,
operator|&
name|cam_imask
argument_list|)
operator|)
operator|==
literal|0
condition|)
block|{
name|adv_free
argument_list|(
name|adv
argument_list|)
expr_stmt|;
return|return;
block|}
name|adv_attach
argument_list|(
name|adv
argument_list|)
expr_stmt|;
block|}
end_function

begin_endif
endif|#
directive|endif
end_endif

begin_comment
comment|/* NPCI> 0 */
end_comment

end_unit

