begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*  *  * ===================================  * HARP  |  Host ATM Research Platform  * ===================================  *  *  * This Host ATM Research Platform ("HARP") file (the "Software") is  * made available by Network Computing Services, Inc. ("NetworkCS")  * "AS IS".  NetworkCS does not provide maintenance, improvements or  * support of any kind.  *  * NETWORKCS MAKES NO WARRANTIES OR REPRESENTATIONS, EXPRESS OR IMPLIED,  * INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY  * AND FITNESS FOR A PARTICULAR PURPOSE, AS TO ANY ELEMENT OF THE  * SOFTWARE OR ANY SUPPORT PROVIDED IN CONNECTION WITH THIS SOFTWARE.  * In no event shall NetworkCS be responsible for any damages, including  * but not limited to consequential damages, arising from or relating to  * any use of the Software or related support.  *  * Copyright 1994-1998 Network Computing Services, Inc.  *  * Copies of this Software may be made, however, the above copyright  * notice must be reproduced on all copies.  *  *	@(#) $FreeBSD$  *  */
end_comment

begin_comment
comment|/*  * Server Cache Synchronization Protocol (SCSP) Support  * ----------------------------------------------------  *  * Configuration file processing  *  */
end_comment

begin_include
include|#
directive|include
file|<sys/types.h>
end_include

begin_include
include|#
directive|include
file|<sys/param.h>
end_include

begin_include
include|#
directive|include
file|<sys/socket.h>
end_include

begin_include
include|#
directive|include
file|<net/if.h>
end_include

begin_include
include|#
directive|include
file|<netinet/in.h>
end_include

begin_include
include|#
directive|include
file|<netatm/port.h>
end_include

begin_include
include|#
directive|include
file|<netatm/queue.h>
end_include

begin_include
include|#
directive|include
file|<netatm/atm.h>
end_include

begin_include
include|#
directive|include
file|<netatm/atm_if.h>
end_include

begin_include
include|#
directive|include
file|<netatm/atm_sap.h>
end_include

begin_include
include|#
directive|include
file|<netatm/atm_sys.h>
end_include

begin_include
include|#
directive|include
file|<netatm/atm_ioctl.h>
end_include

begin_include
include|#
directive|include
file|<errno.h>
end_include

begin_include
include|#
directive|include
file|<libatm.h>
end_include

begin_include
include|#
directive|include
file|<stdio.h>
end_include

begin_include
include|#
directive|include
file|<stdlib.h>
end_include

begin_include
include|#
directive|include
file|<string.h>
end_include

begin_include
include|#
directive|include
file|<syslog.h>
end_include

begin_include
include|#
directive|include
file|"scsp_msg.h"
end_include

begin_include
include|#
directive|include
file|"scsp_if.h"
end_include

begin_include
include|#
directive|include
file|"scsp_var.h"
end_include

begin_ifndef
ifndef|#
directive|ifndef
name|lint
end_ifndef

begin_expr_stmt
name|__RCSID
argument_list|(
literal|"@(#) $FreeBSD$"
argument_list|)
expr_stmt|;
end_expr_stmt

begin_endif
endif|#
directive|endif
end_endif

begin_decl_stmt
specifier|extern
name|int
name|yyparse
name|__P
argument_list|(
operator|(
name|void
operator|)
argument_list|)
decl_stmt|;
end_decl_stmt

begin_comment
comment|/*  * Global variables  */
end_comment

begin_decl_stmt
name|FILE
modifier|*
name|cfg_file
decl_stmt|;
end_decl_stmt

begin_decl_stmt
name|Scsp_server
modifier|*
name|current_server
decl_stmt|;
end_decl_stmt

begin_decl_stmt
name|Scsp_dcs
modifier|*
name|current_dcs
decl_stmt|;
end_decl_stmt

begin_comment
comment|/*  * Process the configuration file  *  * This routine is called when the daemon starts, and it can also be  * called while it is running, as the result of a SIGHUP signal.  It  * therefore has to be capable of both configuring the daemon from  * scratch and modifying the configuration of a running daemon.  *  * Arguments:  *	cfn	configuration file name  *  * Returns:  *	0	configuration read with no errors  *	else	error found in configuration file  *  */
end_comment

begin_function
name|int
name|scsp_config
parameter_list|(
name|cfn
parameter_list|)
name|char
modifier|*
name|cfn
decl_stmt|;
block|{
name|int
name|rc
decl_stmt|;
name|Scsp_server
modifier|*
name|ssp
decl_stmt|,
modifier|*
name|snext
decl_stmt|;
comment|/* 	 * Open the configuration file 	 */
name|cfg_file
operator|=
name|fopen
argument_list|(
name|cfn
argument_list|,
literal|"r"
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|cfg_file
condition|)
block|{
name|scsp_log
argument_list|(
name|LOG_ERR
argument_list|,
literal|"can't open config file %s"
argument_list|,
operator|(
name|void
operator|*
operator|)
name|cfn
argument_list|)
expr_stmt|;
name|exit
argument_list|(
literal|1
argument_list|)
expr_stmt|;
block|}
comment|/* 	 * Initialize current interface pointer 	 */
name|current_server
operator|=
operator|(
name|Scsp_server
operator|*
operator|)
literal|0
expr_stmt|;
comment|/* 	 * Clear marks on any existing servers 	 */
for|for
control|(
name|ssp
operator|=
name|scsp_server_head
init|;
name|ssp
condition|;
name|ssp
operator|=
name|ssp
operator|->
name|ss_next
control|)
block|{
name|ssp
operator|->
name|ss_mark
operator|=
literal|0
expr_stmt|;
block|}
comment|/* 	 * Scan the configuration file, processing each line as 	 * it is read 	 */
name|rc
operator|=
name|yyparse
argument_list|()
expr_stmt|;
comment|/* 	 * Close the configuration file 	 */
name|fclose
argument_list|(
name|cfg_file
argument_list|)
expr_stmt|;
comment|/* 	 * Delete any server entries that weren't updated 	 */
for|for
control|(
name|ssp
operator|=
name|scsp_server_head
init|;
name|ssp
condition|;
name|ssp
operator|=
name|snext
control|)
block|{
name|snext
operator|=
name|ssp
operator|->
name|ss_next
expr_stmt|;
if|if
condition|(
operator|!
name|ssp
operator|->
name|ss_mark
condition|)
name|scsp_server_delete
argument_list|(
name|ssp
argument_list|)
expr_stmt|;
block|}
return|return
operator|(
name|rc
operator|)
return|;
block|}
end_function

begin_comment
comment|/*  * Prepare for SCSP DCS setup  *  * This routine is called from yyparse() when a DCS command is found.  *  * Arguments:  *	none  *  * Returns:  *	0	success  *	1	error encountered  *  */
end_comment

begin_function
name|int
name|start_dcs
parameter_list|()
block|{
name|Scsp_dcs
modifier|*
name|dcsp
decl_stmt|;
comment|/* 	 * Make sure we have a current server block 	 */
if|if
condition|(
operator|!
name|current_server
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
comment|/* 	 * Allocate a DCS block 	 */
name|dcsp
operator|=
operator|(
name|Scsp_dcs
operator|*
operator|)
name|UM_ALLOC
argument_list|(
sizeof|sizeof
argument_list|(
name|Scsp_dcs
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|dcsp
condition|)
block|{
name|scsp_mem_err
argument_list|(
literal|"start_dcs: sizeof(Scsp_dcs)"
argument_list|)
expr_stmt|;
block|}
name|UM_ZERO
argument_list|(
name|dcsp
argument_list|,
sizeof|sizeof
argument_list|(
name|Scsp_dcs
argument_list|)
argument_list|)
expr_stmt|;
comment|/* 	 * Fill out DCS links and default values 	 */
name|dcsp
operator|->
name|sd_server
operator|=
name|current_server
expr_stmt|;
name|dcsp
operator|->
name|sd_addr
operator|.
name|address_format
operator|=
name|T_ATM_ABSENT
expr_stmt|;
name|dcsp
operator|->
name|sd_subaddr
operator|.
name|address_format
operator|=
name|T_ATM_ABSENT
expr_stmt|;
name|dcsp
operator|->
name|sd_sock
operator|=
operator|-
literal|1
expr_stmt|;
name|dcsp
operator|->
name|sd_ca_rexmt_int
operator|=
name|SCSP_CAReXmitInterval
expr_stmt|;
name|dcsp
operator|->
name|sd_csus_rexmt_int
operator|=
name|SCSP_CSUSReXmitInterval
expr_stmt|;
name|dcsp
operator|->
name|sd_hops
operator|=
name|SCSP_CSA_HOP_CNT
expr_stmt|;
name|dcsp
operator|->
name|sd_csu_rexmt_int
operator|=
name|SCSP_CSUReXmitInterval
expr_stmt|;
name|dcsp
operator|->
name|sd_csu_rexmt_max
operator|=
name|SCSP_CSUReXmitMax
expr_stmt|;
name|LINK2TAIL
argument_list|(
name|dcsp
argument_list|,
name|Scsp_dcs
argument_list|,
name|current_server
operator|->
name|ss_dcs
argument_list|,
name|sd_next
argument_list|)
expr_stmt|;
name|current_dcs
operator|=
name|dcsp
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/*  * Finish up server configuration  *  * This routine is called from yyparse() to at the end of a DCS  * command.  It checks that required fields are set and finishes  * up the DCS block.  *  * Arguments:  *	none  *  * Returns:  *	0	success  *	1	error encountered  *  */
end_comment

begin_function
name|int
name|finish_dcs
parameter_list|()
block|{
name|int
name|rc
init|=
literal|0
decl_stmt|;
name|Scsp_dcs
modifier|*
name|dcsp
decl_stmt|;
name|Scsp_server
modifier|*
name|ssp
decl_stmt|;
comment|/* 	 * Make sure we have a current server block and DCS block 	 */
if|if
condition|(
operator|!
name|current_server
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
if|if
condition|(
operator|!
name|current_dcs
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
name|ssp
operator|=
name|current_server
expr_stmt|;
name|dcsp
operator|=
name|current_dcs
expr_stmt|;
comment|/* 	 * Make sure the DCS ID is set 	 */
if|if
condition|(
name|dcsp
operator|->
name|sd_dcsid
operator|.
name|id_len
operator|==
literal|0
condition|)
block|{
name|parse_error
argument_list|(
literal|"DCS ID not set"
argument_list|)
expr_stmt|;
name|rc
operator|++
expr_stmt|;
block|}
comment|/* 	 * Make sure the ATM address is set 	 */
if|if
condition|(
name|dcsp
operator|->
name|sd_addr
operator|.
name|address_format
operator|==
name|T_ATM_ABSENT
condition|)
block|{
name|parse_error
argument_list|(
literal|"DCS ATM address not set"
argument_list|)
expr_stmt|;
name|rc
operator|++
expr_stmt|;
block|}
name|current_dcs
operator|=
operator|(
name|Scsp_dcs
operator|*
operator|)
literal|0
expr_stmt|;
return|return
operator|(
name|rc
operator|)
return|;
block|}
end_function

begin_comment
comment|/*  * Configure DCS ATM address  *  * This routine is called from yyparse() to process an ATMaddr command.  *  * Arguments:  *	ap	pointer to DCS's ATM address (in ASCII)  *	sap	pointer to DCS's ATM subaddress (in ASCII)  *  * Returns:  *	0	success  *	1	error encountered  *  */
end_comment

begin_function
name|int
name|set_dcs_addr
parameter_list|(
name|ap
parameter_list|,
name|sap
parameter_list|)
name|char
modifier|*
name|ap
decl_stmt|,
decl|*
name|sap
decl_stmt|;
end_function

begin_block
block|{
name|Scsp_dcs
modifier|*
name|dcsp
decl_stmt|;
name|Atm_addr
name|addr
decl_stmt|,
name|subaddr
decl_stmt|;
comment|/* 	 * Make sure we have a current server block and DCS block 	 */
if|if
condition|(
operator|!
name|current_server
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
if|if
condition|(
operator|!
name|current_dcs
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
name|dcsp
operator|=
name|current_dcs
expr_stmt|;
comment|/* 	 * Initialize 	 */
name|UM_ZERO
argument_list|(
operator|&
name|addr
argument_list|,
sizeof|sizeof
argument_list|(
name|addr
argument_list|)
argument_list|)
expr_stmt|;
name|addr
operator|.
name|address_format
operator|=
name|T_ATM_ABSENT
expr_stmt|;
name|UM_ZERO
argument_list|(
operator|&
name|subaddr
argument_list|,
sizeof|sizeof
argument_list|(
name|subaddr
argument_list|)
argument_list|)
expr_stmt|;
name|subaddr
operator|.
name|address_format
operator|=
name|T_ATM_ABSENT
expr_stmt|;
comment|/* 	 * Convert the ATM address from character to internal format 	 */
if|if
condition|(
name|ap
condition|)
block|{
name|addr
operator|.
name|address_length
operator|=
name|get_hex_atm_addr
argument_list|(
name|ap
argument_list|,
operator|(
name|u_char
operator|*
operator|)
name|addr
operator|.
name|address
argument_list|,
name|strlen
argument_list|(
name|ap
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|addr
operator|.
name|address_length
operator|==
literal|0
condition|)
block|{
name|parse_error
argument_list|(
literal|"invalid ATM address"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
if|if
condition|(
name|addr
operator|.
name|address_length
operator|==
sizeof|sizeof
argument_list|(
name|Atm_addr_nsap
argument_list|)
condition|)
block|{
name|addr
operator|.
name|address_format
operator|=
name|T_ATM_ENDSYS_ADDR
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|addr
operator|.
name|address_length
operator|<=
sizeof|sizeof
argument_list|(
name|Atm_addr_e164
argument_list|)
condition|)
block|{
name|addr
operator|.
name|address_format
operator|=
name|T_ATM_E164_ADDR
expr_stmt|;
block|}
else|else
block|{
name|parse_error
argument_list|(
literal|"invalid ATM address"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
block|}
comment|/* 	 * Convert the ATM subaddress from character to internal format 	 */
if|if
condition|(
name|sap
condition|)
block|{
name|subaddr
operator|.
name|address_length
operator|=
name|get_hex_atm_addr
argument_list|(
name|sap
argument_list|,
operator|(
name|u_char
operator|*
operator|)
name|subaddr
operator|.
name|address
argument_list|,
name|strlen
argument_list|(
name|sap
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|subaddr
operator|.
name|address_length
operator|==
literal|0
condition|)
block|{
name|parse_error
argument_list|(
literal|"invalid ATM address"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
if|if
condition|(
name|subaddr
operator|.
name|address_length
operator|==
sizeof|sizeof
argument_list|(
name|Atm_addr_nsap
argument_list|)
condition|)
block|{
name|subaddr
operator|.
name|address_format
operator|=
name|T_ATM_ENDSYS_ADDR
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|subaddr
operator|.
name|address_length
operator|<=
sizeof|sizeof
argument_list|(
name|Atm_addr_e164
argument_list|)
condition|)
block|{
name|subaddr
operator|.
name|address_format
operator|=
name|T_ATM_E164_ADDR
expr_stmt|;
block|}
else|else
block|{
name|parse_error
argument_list|(
literal|"invalid ATM subaddress"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
block|}
comment|/* 	 * Make sure we have a legal ATM address type combination 	 */
if|if
condition|(
operator|(
operator|(
name|addr
operator|.
name|address_format
operator|!=
name|T_ATM_ENDSYS_ADDR
operator|)
operator|||
operator|(
name|subaddr
operator|.
name|address_format
operator|!=
name|T_ATM_ABSENT
operator|)
operator|)
operator|&&
operator|(
operator|(
name|addr
operator|.
name|address_format
operator|!=
name|T_ATM_E164_ADDR
operator|)
operator|||
operator|(
name|subaddr
operator|.
name|address_format
operator|!=
name|T_ATM_ENDSYS_ADDR
operator|)
operator|)
condition|)
block|{
name|parse_error
argument_list|(
literal|"invalid address/subaddress combination"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
comment|/* 	 * Save the address and subaddress 	 */
name|ATM_ADDR_COPY
argument_list|(
operator|&
name|addr
argument_list|,
operator|&
name|dcsp
operator|->
name|sd_addr
argument_list|)
expr_stmt|;
name|ATM_ADDR_COPY
argument_list|(
operator|&
name|subaddr
argument_list|,
operator|&
name|dcsp
operator|->
name|sd_subaddr
argument_list|)
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_block

begin_comment
comment|/*  * Configure CA retransmit interval for DCS  *  * This routine is called from yyparse() to process a CAReXmitInt  * command.  *  * Arguments:  *	val	time interval  *  * Returns:  *	0	success  *	1	error encountered  *  */
end_comment

begin_function
name|int
name|set_dcs_ca_rexmit
parameter_list|(
name|val
parameter_list|)
name|int
name|val
decl_stmt|;
block|{
name|Scsp_dcs
modifier|*
name|dcsp
decl_stmt|;
comment|/* 	 * Make sure we have a current server block and DCS block 	 */
if|if
condition|(
operator|!
name|current_server
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
if|if
condition|(
operator|!
name|current_dcs
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
name|dcsp
operator|=
name|current_dcs
expr_stmt|;
comment|/* 	 * Validate the interval 	 */
if|if
condition|(
name|val
operator|<=
literal|0
operator|||
name|val
operator|>
literal|1024
condition|)
block|{
name|parse_error
argument_list|(
literal|"invalid CA retransmit interval"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
comment|/* 	 * Set CA retransmit interval 	 */
name|dcsp
operator|->
name|sd_ca_rexmt_int
operator|=
name|val
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/*  * Configure CSUS retransmit interval for DCS  *  * This routine is called from yyparse() to process a CSUSReXmitInt  * command.  *  * Arguments:  *	val	time interval  *  * Returns:  *	0	success  *	1	error encountered  *  */
end_comment

begin_function
name|int
name|set_dcs_csus_rexmit
parameter_list|(
name|val
parameter_list|)
name|int
name|val
decl_stmt|;
block|{
name|Scsp_dcs
modifier|*
name|dcsp
decl_stmt|;
comment|/* 	 * Make sure we have a current server block and DCS block 	 */
if|if
condition|(
operator|!
name|current_server
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
if|if
condition|(
operator|!
name|current_dcs
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
name|dcsp
operator|=
name|current_dcs
expr_stmt|;
comment|/* 	 * Validate the interval 	 */
if|if
condition|(
name|val
operator|<=
literal|0
operator|||
name|val
operator|>
literal|1024
condition|)
block|{
name|parse_error
argument_list|(
literal|"invalid CSUS retransmit interval"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
comment|/* 	 * Set CSUS retransmit interval 	 */
name|dcsp
operator|->
name|sd_csus_rexmt_int
operator|=
name|val
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/*  * Configure CSU retransmit interval for DCS  *  * This routine is called from yyparse() to process a CSUReXmitInt  * command.  *  * Arguments:  *	val	time interval  *  * Returns:  *	0	success  *	1	error encountered  *  */
end_comment

begin_function
name|int
name|set_dcs_csu_rexmit
parameter_list|(
name|val
parameter_list|)
name|int
name|val
decl_stmt|;
block|{
name|Scsp_dcs
modifier|*
name|dcsp
decl_stmt|;
comment|/* 	 * Make sure we have a current server block and DCS block 	 */
if|if
condition|(
operator|!
name|current_server
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
if|if
condition|(
operator|!
name|current_dcs
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
name|dcsp
operator|=
name|current_dcs
expr_stmt|;
comment|/* 	 * Validate the interval 	 */
if|if
condition|(
name|val
operator|<=
literal|0
operator|||
name|val
operator|>
literal|1024
condition|)
block|{
name|parse_error
argument_list|(
literal|"invalid CSU retransmit interval"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
comment|/* 	 * Set CSU retransmit interval 	 */
name|dcsp
operator|->
name|sd_csu_rexmt_int
operator|=
name|val
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/*  * Configure CSU retransmit limit for DCS  *  * This routine is called from yyparse() to process a CSUReXmitMax  * command.  *  * Arguments:  *	val	time interval  *  * Returns:  *	0	success  *	1	error encountered  *  */
end_comment

begin_function
name|int
name|set_dcs_csu_rexmit_max
parameter_list|(
name|val
parameter_list|)
name|int
name|val
decl_stmt|;
block|{
name|Scsp_dcs
modifier|*
name|dcsp
decl_stmt|;
comment|/* 	 * Make sure we have a current server block and DCS block 	 */
if|if
condition|(
operator|!
name|current_server
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
if|if
condition|(
operator|!
name|current_dcs
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
name|dcsp
operator|=
name|current_dcs
expr_stmt|;
comment|/* 	 * Validate the interval 	 */
if|if
condition|(
name|val
operator|<=
literal|0
operator|||
name|val
operator|>
literal|1024
condition|)
block|{
name|parse_error
argument_list|(
literal|"invalid CSU retransmit maximum"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
comment|/* 	 * Set CSU retransmit limit 	 */
name|dcsp
operator|->
name|sd_csu_rexmt_max
operator|=
name|val
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/*  * Configure Hello dead factor for DCS  *  * This routine is called from yyparse() to process a HelloDead  * command.  *  * Arguments:  *	val	number of times Hello interval has to expire before  *		a DCS is considered dead  *  * Returns:  *	0	success  *	1	error encountered  *  */
end_comment

begin_function
name|int
name|set_dcs_hello_df
parameter_list|(
name|val
parameter_list|)
name|int
name|val
decl_stmt|;
block|{
name|Scsp_dcs
modifier|*
name|dcsp
decl_stmt|;
comment|/* 	 * Make sure we have a current server block and DCS block 	 */
if|if
condition|(
operator|!
name|current_server
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
if|if
condition|(
operator|!
name|current_dcs
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
name|dcsp
operator|=
name|current_dcs
expr_stmt|;
comment|/* 	 * Validate the limit 	 */
if|if
condition|(
name|val
operator|<=
literal|0
operator|||
name|val
operator|>
literal|1024
condition|)
block|{
name|parse_error
argument_list|(
literal|"invalid Hello dead factor"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
comment|/* 	 * Set Hello dead factor 	 */
name|dcsp
operator|->
name|sd_hello_df
operator|=
name|val
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/*  * Configure Hello interval for DCS  *  * This routine is called from yyparse() to process a HelloInt  * command.  *  * Arguments:  *	val	time interval  *  * Returns:  *	0	success  *	1	error encountered  *  */
end_comment

begin_function
name|int
name|set_dcs_hello_int
parameter_list|(
name|val
parameter_list|)
name|int
name|val
decl_stmt|;
block|{
name|Scsp_dcs
modifier|*
name|dcsp
decl_stmt|;
comment|/* 	 * Make sure we have a current server block and DCS block 	 */
if|if
condition|(
operator|!
name|current_server
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
if|if
condition|(
operator|!
name|current_dcs
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
name|dcsp
operator|=
name|current_dcs
expr_stmt|;
comment|/* 	 * Validate the interval 	 */
if|if
condition|(
name|val
operator|<=
literal|0
operator|||
name|val
operator|>
literal|1024
condition|)
block|{
name|parse_error
argument_list|(
literal|"invalid Hello interval"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
comment|/* 	 * Set Hello interval 	 */
name|dcsp
operator|->
name|sd_hello_int
operator|=
name|val
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/*  * Configure hop count for SCSP server  *  * This routine is called from yyparse() to process a Hops command.  *  * Arguments:  *	hops	number of hops  *  * Returns:  *	0	success  *	1	error encountered  *  */
end_comment

begin_function
name|int
name|set_dcs_hops
parameter_list|(
name|hops
parameter_list|)
name|int
name|hops
decl_stmt|;
block|{
name|Scsp_dcs
modifier|*
name|dcsp
decl_stmt|;
comment|/* 	 * Make sure we have a current server block and DCS block 	 */
if|if
condition|(
operator|!
name|current_server
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
if|if
condition|(
operator|!
name|current_dcs
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
name|dcsp
operator|=
name|current_dcs
expr_stmt|;
comment|/* 	 * Validate the count 	 */
if|if
condition|(
name|hops
operator|<=
literal|0
operator|||
name|hops
operator|>
literal|1024
condition|)
block|{
name|parse_error
argument_list|(
literal|"invalid hop count"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
comment|/* 	 * Set hop count 	 */
name|dcsp
operator|->
name|sd_hops
operator|=
name|hops
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/*  * Configure DCS ID  *  * This routine is called from yyparse() to process an ID command.  *  * Arguments:  *	name	pointer to DCS's DNS name or IP address (in ASCII)  *  * Returns:  *	0	success  *	1	error encountered  *  */
end_comment

begin_function
name|int
name|set_dcs_id
parameter_list|(
name|name
parameter_list|)
name|char
modifier|*
name|name
decl_stmt|;
block|{
name|Scsp_dcs
modifier|*
name|dcsp
decl_stmt|;
name|Scsp_server
modifier|*
name|ssp
decl_stmt|;
name|struct
name|sockaddr_in
modifier|*
name|ip_addr
decl_stmt|;
comment|/* 	 * Make sure we have a current server block and DCS block 	 */
if|if
condition|(
operator|!
name|current_server
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
if|if
condition|(
operator|!
name|current_dcs
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
name|ssp
operator|=
name|current_server
expr_stmt|;
name|dcsp
operator|=
name|current_dcs
expr_stmt|;
comment|/* 	 * Convert the DNS name or IP address 	 */
name|ip_addr
operator|=
name|get_ip_addr
argument_list|(
name|name
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|ip_addr
condition|)
block|{
name|parse_error
argument_list|(
literal|"invalid DCS IP address"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
comment|/* 	 * Verify the address length 	 */
if|if
condition|(
name|ssp
operator|->
name|ss_id_len
operator|!=
sizeof|sizeof
argument_list|(
name|ip_addr
operator|->
name|sin_addr
argument_list|)
condition|)
block|{
name|parse_error
argument_list|(
literal|"invalid DCS ID length"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
comment|/* 	 * Set the ID in the DCS block 	 */
name|dcsp
operator|->
name|sd_dcsid
operator|.
name|id_len
operator|=
name|ssp
operator|->
name|ss_id_len
expr_stmt|;
name|UM_COPY
argument_list|(
operator|&
name|ip_addr
operator|->
name|sin_addr
argument_list|,
name|dcsp
operator|->
name|sd_dcsid
operator|.
name|id
argument_list|,
name|ssp
operator|->
name|ss_id_len
argument_list|)
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/*  * Configure network interface for SCSP server  *  * This routine is called from yyparse() to process a Netif command.  * It verifies the network interface name, gets interface information  * from the kernel, and sets the appropriate fields in the server  * control block.  *  * Arguments:  *	netif	pointer to network interface name  *  * Returns:  *	0	success  *	1	error encountered  *  */
end_comment

begin_function
name|int
name|set_intf
parameter_list|(
name|netif
parameter_list|)
name|char
modifier|*
name|netif
decl_stmt|;
block|{
name|int
name|rc
decl_stmt|;
name|Scsp_server
modifier|*
name|ssp
decl_stmt|;
comment|/* 	 * Get the current network interface address 	 */
name|ssp
operator|=
name|current_server
expr_stmt|;
if|if
condition|(
operator|!
name|ssp
condition|)
block|{
name|parse_error
argument_list|(
literal|"Server not found"
argument_list|)
expr_stmt|;
name|rc
operator|=
literal|1
expr_stmt|;
goto|goto
name|set_intf_done
goto|;
block|}
comment|/* 	 * Make sure we're configuring a valid 	 * network interface 	 */
name|rc
operator|=
name|verify_nif_name
argument_list|(
name|netif
argument_list|)
expr_stmt|;
if|if
condition|(
name|rc
operator|==
literal|0
condition|)
block|{
name|parse_error
argument_list|(
literal|"%s is not a valid network interface"
argument_list|,
operator|(
name|void
operator|*
operator|)
name|netif
argument_list|)
expr_stmt|;
name|rc
operator|=
literal|1
expr_stmt|;
goto|goto
name|set_intf_done
goto|;
block|}
elseif|else
if|if
condition|(
name|rc
operator|<
literal|0
condition|)
block|{
name|scsp_log
argument_list|(
name|LOG_ERR
argument_list|,
literal|"Netif name verify error"
argument_list|)
expr_stmt|;
name|exit
argument_list|(
literal|1
argument_list|)
expr_stmt|;
block|}
comment|/* 	 * Save the server's network interface name 	 */
name|strcpy
argument_list|(
name|ssp
operator|->
name|ss_intf
argument_list|,
name|netif
argument_list|)
expr_stmt|;
name|rc
operator|=
literal|0
expr_stmt|;
name|set_intf_done
label|:
return|return
operator|(
name|rc
operator|)
return|;
block|}
end_function

begin_comment
comment|/*  * Configure protocol for SCSP server  *  * This routine is called from yyparse() to process a Protocol command.  *  * Arguments:  *	proto	SCSP protocol being configured  *  * Returns:  *	0	success  *	1	error encountered  *  */
end_comment

begin_function
name|int
name|set_protocol
parameter_list|(
name|proto
parameter_list|)
name|int
name|proto
decl_stmt|;
block|{
name|Scsp_server
modifier|*
name|ssp
decl_stmt|;
comment|/* 	 * Get address of current server block 	 */
name|ssp
operator|=
name|current_server
expr_stmt|;
if|if
condition|(
operator|!
name|ssp
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
comment|/* 	 * Process based on protocol ID 	 */
switch|switch
condition|(
name|proto
condition|)
block|{
case|case
name|SCSP_PROTO_ATMARP
case|:
name|ssp
operator|->
name|ss_pid
operator|=
name|proto
expr_stmt|;
name|ssp
operator|->
name|ss_id_len
operator|=
name|SCSP_ATMARP_ID_LEN
expr_stmt|;
name|ssp
operator|->
name|ss_ckey_len
operator|=
name|SCSP_ATMARP_KEY_LEN
expr_stmt|;
break|break;
case|case
name|SCSP_PROTO_NHRP
case|:
name|ssp
operator|->
name|ss_pid
operator|=
name|proto
expr_stmt|;
name|ssp
operator|->
name|ss_id_len
operator|=
name|SCSP_NHRP_ID_LEN
expr_stmt|;
name|ssp
operator|->
name|ss_ckey_len
operator|=
name|SCSP_NHRP_KEY_LEN
expr_stmt|;
break|break;
case|case
name|SCSP_PROTO_MARS
case|:
case|case
name|SCSP_PROTO_DHCP
case|:
case|case
name|SCSP_PROTO_LNNI
case|:
default|default:
name|parse_error
argument_list|(
literal|"invalid protocol"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/*  * Configure server group for SCSP server  *  * This routine is called from yyparse() to process a ServerGroupID  * command.  *  * Arguments:  *	sgid	server group id  *  * Returns:  *	0	success  *	1	error encountered  *  */
end_comment

begin_function
name|int
name|set_server_group
parameter_list|(
name|sgid
parameter_list|)
name|int
name|sgid
decl_stmt|;
block|{
name|Scsp_server
modifier|*
name|ssp
decl_stmt|;
comment|/* 	 * Get address of current server block 	 */
name|ssp
operator|=
name|current_server
expr_stmt|;
if|if
condition|(
operator|!
name|ssp
condition|)
block|{
name|parse_error
argument_list|(
literal|"server not found"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
comment|/* 	 * Validate server group ID 	 */
if|if
condition|(
name|sgid
operator|<=
literal|0
condition|)
block|{
name|parse_error
argument_list|(
literal|"invalid server group ID"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
comment|/* 	 * Save the ID 	 */
name|ssp
operator|->
name|ss_sgid
operator|=
name|sgid
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/*  * Prepare for SCSP server setup  *  * This routine is called from yyparse() when a Server statment is  * found.  *  * Arguments:  *	name	pointer to LIS name  *  * Returns:  *	0	success  *	else	error encountered  *  */
end_comment

begin_function
name|int
name|start_server
parameter_list|(
name|name
parameter_list|)
name|char
modifier|*
name|name
decl_stmt|;
block|{
name|int
name|i
decl_stmt|;
name|Scsp_server
modifier|*
name|ssp
decl_stmt|;
name|Scsp_dcs
modifier|*
name|dcsp
decl_stmt|,
modifier|*
name|next_dcs
decl_stmt|;
name|Scsp_cse
modifier|*
name|csep
decl_stmt|,
modifier|*
name|next_cse
decl_stmt|;
comment|/* 	 * See if we already have an entry for this name 	 */
for|for
control|(
name|ssp
operator|=
name|scsp_server_head
init|;
name|ssp
condition|;
name|ssp
operator|=
name|ssp
operator|->
name|ss_next
control|)
block|{
if|if
condition|(
name|strcasecmp
argument_list|(
name|ssp
operator|->
name|ss_name
argument_list|,
name|name
argument_list|)
operator|==
literal|0
condition|)
break|break;
block|}
if|if
condition|(
name|ssp
condition|)
block|{
comment|/* 		 * Log the fact that we're updating the entry 		 */
name|scsp_log
argument_list|(
name|LOG_INFO
argument_list|,
literal|"updating server entry for %s"
argument_list|,
operator|(
name|void
operator|*
operator|)
name|name
argument_list|)
expr_stmt|;
comment|/* 		 * Free the existing cache 		 */
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
name|SCSP_HASHSZ
condition|;
name|i
operator|++
control|)
block|{
for|for
control|(
name|csep
operator|=
name|ssp
operator|->
name|ss_cache
index|[
name|i
index|]
init|;
name|csep
condition|;
name|csep
operator|=
name|next_cse
control|)
block|{
name|next_cse
operator|=
name|csep
operator|->
name|sc_next
expr_stmt|;
name|UNLINK
argument_list|(
name|csep
argument_list|,
name|Scsp_cse
argument_list|,
name|ssp
operator|->
name|ss_cache
index|[
name|i
index|]
argument_list|,
name|sc_next
argument_list|)
expr_stmt|;
name|UM_FREE
argument_list|(
name|csep
argument_list|)
expr_stmt|;
block|}
block|}
comment|/* 		 * Delete existing DCS blocks 		 */
for|for
control|(
name|dcsp
operator|=
name|ssp
operator|->
name|ss_dcs
init|;
name|dcsp
condition|;
name|dcsp
operator|=
name|next_dcs
control|)
block|{
name|next_dcs
operator|=
name|dcsp
operator|->
name|sd_next
expr_stmt|;
name|scsp_dcs_delete
argument_list|(
name|dcsp
argument_list|)
expr_stmt|;
block|}
block|}
else|else
block|{
comment|/* 		 * Get a new server entry 		 */
name|ssp
operator|=
operator|(
name|Scsp_server
operator|*
operator|)
name|UM_ALLOC
argument_list|(
sizeof|sizeof
argument_list|(
name|Scsp_server
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|ssp
condition|)
block|{
name|scsp_log
argument_list|(
name|LOG_ERR
argument_list|,
literal|"unable to allocate server entry"
argument_list|)
expr_stmt|;
name|exit
argument_list|(
literal|1
argument_list|)
expr_stmt|;
block|}
name|UM_ZERO
argument_list|(
name|ssp
argument_list|,
sizeof|sizeof
argument_list|(
name|Scsp_server
argument_list|)
argument_list|)
expr_stmt|;
name|ssp
operator|->
name|ss_sock
operator|=
operator|-
literal|1
expr_stmt|;
name|ssp
operator|->
name|ss_dcs_lsock
operator|=
operator|-
literal|1
expr_stmt|;
comment|/* 		 * Set the name 		 */
name|ssp
operator|->
name|ss_name
operator|=
name|strdup
argument_list|(
name|name
argument_list|)
expr_stmt|;
comment|/* 		 * Link in the new interface entry 		 */
name|LINK2TAIL
argument_list|(
name|ssp
argument_list|,
name|Scsp_server
argument_list|,
name|scsp_server_head
argument_list|,
name|ss_next
argument_list|)
expr_stmt|;
block|}
comment|/* 	 * If the mark is already set, this is a duplicate command 	 */
if|if
condition|(
name|ssp
operator|->
name|ss_mark
condition|)
block|{
name|parse_error
argument_list|(
literal|"duplicate server \"%s\""
argument_list|,
name|name
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
comment|/* 	 * Make this the current interface 	 */
name|current_server
operator|=
name|ssp
expr_stmt|;
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

begin_comment
comment|/*  * Finish up server configuration  *  * This routine is called from yyparse() when the end of a server  * statement is reached.  It checks that required fields are set  * and marks the entry as processed.  *  * Arguments:  *	None  *  * Returns:  *	0	OK  *	1	Error  *  */
end_comment

begin_function
name|int
name|finish_server
parameter_list|()
block|{
name|int
name|rc
init|=
literal|0
decl_stmt|;
name|Scsp_server
modifier|*
name|ssp
decl_stmt|;
comment|/* 	 * Get the current network interface address 	 */
name|ssp
operator|=
name|current_server
expr_stmt|;
if|if
condition|(
operator|!
name|ssp
condition|)
block|{
name|parse_error
argument_list|(
literal|"Server not found"
argument_list|)
expr_stmt|;
name|rc
operator|++
expr_stmt|;
block|}
comment|/* 	 * Mark the interface as processed 	 */
name|ssp
operator|->
name|ss_mark
operator|=
literal|1
expr_stmt|;
comment|/* 	 * Make sure the interface has been configured 	 */
if|if
condition|(
name|ssp
operator|->
name|ss_intf
operator|==
operator|(
name|char
operator|*
operator|)
literal|0
condition|)
block|{
name|parse_error
argument_list|(
literal|"netif missing from server specification"
argument_list|)
expr_stmt|;
name|rc
operator|++
expr_stmt|;
block|}
comment|/* 	 * Make sure the protocol is set 	 */
if|if
condition|(
name|ssp
operator|->
name|ss_pid
operator|==
literal|0
condition|)
block|{
name|parse_error
argument_list|(
literal|"protocol missing from server specification"
argument_list|)
expr_stmt|;
name|rc
operator|++
expr_stmt|;
block|}
comment|/* 	 * Make sure the server group is set 	 */
if|if
condition|(
name|ssp
operator|->
name|ss_sgid
operator|==
literal|0
condition|)
block|{
name|parse_error
argument_list|(
literal|"server group ID missing from server specification"
argument_list|)
expr_stmt|;
name|rc
operator|++
expr_stmt|;
block|}
comment|/* 	 * Make sure at least one DCS is configured 	 */
if|if
condition|(
name|ssp
operator|->
name|ss_dcs
operator|==
operator|(
name|Scsp_dcs
operator|*
operator|)
literal|0
condition|)
block|{
name|parse_error
argument_list|(
literal|"no DCS configured for server"
argument_list|)
expr_stmt|;
name|rc
operator|++
expr_stmt|;
block|}
comment|/* 	 * Mark the end of the server 	 */
name|current_server
operator|=
operator|(
name|Scsp_server
operator|*
operator|)
literal|0
expr_stmt|;
return|return
operator|(
name|rc
operator|)
return|;
block|}
end_function

begin_comment
comment|/*  * Configure log file for SCSP server  *  * This routine is called from yyparse() to process a log File command.  *  * Arguments:  *	file	name of logging file  *  * Returns:  *	0	success  *	1	error encountered  *  */
end_comment

begin_function
name|int
name|set_log_file
parameter_list|(
name|file
parameter_list|)
name|char
modifier|*
name|file
decl_stmt|;
block|{
comment|/* 	 * Make sure we haven't already got a log file 	 */
if|if
condition|(
name|scsp_log_file
condition|)
block|{
name|parse_error
argument_list|(
literal|"multiple log files specified"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
comment|/* 	 * Open the file 	 */
name|scsp_log_file
operator|=
name|fopen
argument_list|(
name|file
argument_list|,
literal|"a"
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|scsp_log_file
condition|)
block|{
name|parse_error
argument_list|(
literal|"can't open log file"
argument_list|)
expr_stmt|;
return|return
operator|(
literal|1
operator|)
return|;
block|}
return|return
operator|(
literal|0
operator|)
return|;
block|}
end_function

end_unit

