begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*	$FreeBSD$	*/
end_comment

begin_comment
comment|/*  * Copyright (C) 2012 by Darren Reed.  *  * See the IPFILTER.LICENCE file for details on licencing.  *  * $Id$  */
end_comment

begin_include
include|#
directive|include
file|"ipf.h"
end_include

begin_include
include|#
directive|include
file|<ctype.h>
end_include

begin_function
name|int
name|getproto
parameter_list|(
name|name
parameter_list|)
name|char
modifier|*
name|name
decl_stmt|;
block|{
name|struct
name|protoent
modifier|*
name|p
decl_stmt|;
name|char
modifier|*
name|s
decl_stmt|;
for|for
control|(
name|s
operator|=
name|name
init|;
operator|*
name|s
operator|!=
literal|'\0'
condition|;
name|s
operator|++
control|)
if|if
condition|(
operator|!
name|ISDIGIT
argument_list|(
operator|*
name|s
argument_list|)
condition|)
break|break;
if|if
condition|(
operator|*
name|s
operator|==
literal|'\0'
condition|)
return|return
name|atoi
argument_list|(
name|name
argument_list|)
return|;
ifdef|#
directive|ifdef
name|_AIX51
comment|/* 	 * For some bogus reason, "ip" is 252 in /etc/protocols on AIX 5 	 * The IANA has doubled up on the definition of 0 - it is now also 	 * used for IPv6 hop-opts, so we can no longer rely on /etc/protocols 	 * providing the correct name->number mapping 	 */
endif|#
directive|endif
if|if
condition|(
operator|!
name|strcasecmp
argument_list|(
name|name
argument_list|,
literal|"ip"
argument_list|)
condition|)
return|return
literal|0
return|;
name|p
operator|=
name|getprotobyname
argument_list|(
name|name
argument_list|)
expr_stmt|;
if|if
condition|(
name|p
operator|!=
name|NULL
condition|)
return|return
name|p
operator|->
name|p_proto
return|;
return|return
operator|-
literal|1
return|;
block|}
end_function

end_unit

